-- Video Anak — the owner's own 45 kids videos from youtube.com/@ulyah-com,
-- provided as a titled list (daftarvideoportalislami2.txt) to appear on
-- /anak immediately: three series (Do'a & Kisah, Syamil & Dodo, Biografi
-- Rasulullah SAW). Rendered as click-to-play privacy-enhanced embeds.

CREATE TABLE video_anak (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  series TEXT NOT NULL CHECK (series IN ('doa-kisah', 'syamil-dodo', 'biografi-rasul')),
  video_order INTEGER NOT NULL,
  title TEXT NOT NULL,
  youtube_id TEXT NOT NULL,
  UNIQUE (series, video_order)
);

INSERT INTO video_anak (series, video_order, title, youtube_id) VALUES
  ('doa-kisah', 1, 'Surga Di Bawah Telapak Kaki Ibu', 'wNd53nYCcXc'),
  ('doa-kisah', 2, 'Kelembutan Hati Sang Khalifah', 'zCwd0Q8wEpA'),
  ('doa-kisah', 3, 'Do''a Untuk Orang Tua', 'fXeEs8fRDF4'),
  ('doa-kisah', 4, 'Do''a Tidur', 'y_YfmZxOW08'),
  ('doa-kisah', 5, 'Do''a Saat Turun Hujan', 'xTLxhpbwnhE'),
  ('doa-kisah', 6, 'Do''a Naik Kendaraan', 'av6gTnzkET4'),
  ('doa-kisah', 7, 'Do''a Memakai Baju', 'YKDRtSGs3qM'),
  ('doa-kisah', 8, 'Do''a Melihat Pemandangan Indah', 't-0Z2L63-S0'),
  ('doa-kisah', 9, 'Do''a Masuk Pasar', 'w-fY3jrzo5g'),
  ('doa-kisah', 10, 'Do''a Mandi', '-KujYKR5Uno'),
  ('doa-kisah', 11, 'Do''a Makan', 'ncfZwUbkxsw'),
  ('doa-kisah', 12, 'Do''a Keluar Rumah', '7mnlhvtruEw'),
  ('doa-kisah', 13, 'Berkelahi Dengan Setan', 'A1FCd049BI8'),
  ('doa-kisah', 14, 'Nabi Daud AS Melawan Jalut', 'IZliz6hp50M'),
  ('syamil-dodo', 1, 'Syamil & Dodo — Shalat 5 Waktu', 'sIWDUfgiYT0'),
  ('syamil-dodo', 2, 'Syamil & Dodo — Rukyat dan Hisab', 'fLLECHFHi-4'),
  ('syamil-dodo', 3, 'Syamil & Dodo — Pengertian Dua Kalimat', 'wYthSkOrpY8'),
  ('syamil-dodo', 4, 'Syamil & Dodo — Nabi & Rasul', 'F1_yQaaXdhg'),
  ('syamil-dodo', 5, 'Syamil & Dodo — Mubah', 'lgY111pJHZU'),
  ('syamil-dodo', 6, 'Syamil & Dodo — Mengapa Waktu Shalat Berbeda', '_o4S3a2V5es'),
  ('syamil-dodo', 7, 'Syamil & Dodo — Makruh', '9RxFSuEZ0wg'),
  ('syamil-dodo', 8, 'Syamil & Dodo — Lailatul Qadar', 'nirDG4wfmpA'),
  ('syamil-dodo', 9, 'Syamil & Dodo — Kitab-Kitab Allah', 'WEppE98y3ao'),
  ('syamil-dodo', 10, 'Syamil & Dodo — Kisah Orang-Orang Terdahulu', 'EvXRl2LKrA0'),
  ('syamil-dodo', 11, 'Syamil & Dodo — Kiamat', 'YCalwBwK6rQ'),
  ('syamil-dodo', 12, 'Syamil & Dodo — Isra'' Mi''raj', 'BY4K_Qhfjjg'),
  ('syamil-dodo', 13, 'Syamil & Dodo — Halal Haram', '7LqVoqTRRTs'),
  ('syamil-dodo', 14, 'Syamil & Dodo — Dodo Disayang Allah', '1oFTrtovq-4'),
  ('syamil-dodo', 15, 'Syamil & Dodo — Tarawih', 'NG1uc2rdhqI'),
  ('syamil-dodo', 16, 'Syamil & Dodo — Wajib', '2pl3bBGkEds'),
  ('syamil-dodo', 17, 'Syamil & Dodo — Syirik dan Bentuk-Bentuknya', 'WDVkRnkO1P0'),
  ('syamil-dodo', 18, 'Syamil & Dodo — Takdir', 'JORB1xz43NY'),
  ('syamil-dodo', 19, 'Syamil & Dodo — Syahadat Risalah', '-hib49ebh-8'),
  ('syamil-dodo', 20, 'Syamil & Dodo — Sunnah', 'dpRxGJ4oxM4'),
  ('syamil-dodo', 21, 'Syamil & Dodo — Siapa Allah', 'eKDaH3Blq_c'),
  ('biografi-rasul', 1, 'Biografi Rasulullah SAW — Eps 01: Tahun Gajah', '0giap6S-Vtc'),
  ('biografi-rasul', 2, 'Biografi Rasulullah SAW — Eps 02', 'Ds4x5ce-gUQ'),
  ('biografi-rasul', 3, 'Biografi Rasulullah SAW — Eps 03: Hijrahnya', 'eA2AzaoAbL4'),
  ('biografi-rasul', 4, 'Biografi Rasulullah SAW — Eps 04', 'wQGAwhaNO9g'),
  ('biografi-rasul', 5, 'Biografi Rasulullah SAW — Eps 05: Pesan', 'twCa-YLTCfU'),
  ('biografi-rasul', 6, 'Biografi Rasulullah SAW — Eps 06: Jawaban', 'H_gzwBfiz0o'),
  ('biografi-rasul', 7, 'Biografi Rasulullah SAW — Eps 07: Jujur', 'ZUA-lIOuD8U'),
  ('biografi-rasul', 8, 'Biografi Rasulullah SAW — Eps 08: Kejayaan', '70Dz8afd0L8'),
  ('biografi-rasul', 9, 'Biografi Rasulullah SAW — Eps 09: Ibadah', 'KcogCQgAzfw'),
  ('biografi-rasul', 10, 'Biografi Rasulullah SAW — Eps 10: Ibadah', '3K-JaCxkxUw');
