-- Auto-generated by scripts/generate-hadith-dehlawi-seed.mjs — DO NOT hand-edit.
-- Source: fawazahmed0/hadith-api (github.com/fawazahmed0/hadith-api), Unlicense / public domain.
-- 40 Hadith of Shah Waliullah Ad-Dehlawi — Arabic + English (Indonesian translated on demand).
-- Bulk-imported rows leave narrator NULL — the translated text already includes the full isnad.

INSERT OR REPLACE INTO hadits_collection (slug, name_id, name_ar, author, sort_order, id_start, id_end, has_native_id) VALUES
  ('dehlawi', 'Arba''in Ad-Dehlawi (40 Hadits Syah Waliullah)', 'الأربعون للشاه ولي الله الدهلوي', 'Syah Waliullah Ad-Dehlawi', 10, 80001, 80999, 0);

INSERT OR IGNORE INTO hadits (id, text_ar, text_id, text_en, narrator, grade, source, collection, hadith_number) VALUES
  (80001, 'لَیْسَ الْخَبَرُ کَالْمُعَایَنَةِ', 'The report is not like witnessing', 'The report is not like witnessing', NULL, NULL, 'Arba''in Ad-Dehlawi no. 1', 'dehlawi', 1),
  (80002, 'الْحَرْبُ خُدَعَةٌ', 'War is deception', 'War is deception', NULL, NULL, 'Arba''in Ad-Dehlawi no. 2', 'dehlawi', 2),
  (80003, 'الْمُسْلِمُ مِرْآةُ الْمُسْلِمِ', 'A Muslim is a mirror of the Muslim', 'A Muslim is a mirror of the Muslim', NULL, NULL, 'Arba''in Ad-Dehlawi no. 3', 'dehlawi', 3),
  (80004, 'الْمُسْتَشَارُ مُؤتَمَنٌ', 'Someone whose advice is sought is in a position of trust', 'Someone whose advice is sought is in a position of trust', NULL, NULL, 'Arba''in Ad-Dehlawi no. 4', 'dehlawi', 4),
  (80005, 'الدَّالُّ عَلَی الْخَیْرِ کَفَاعِلِهِ', 'The person guiding (someone) to do a good deed, is like the one performing the good deed', 'The person guiding (someone) to do a good deed, is like the one performing the good deed', NULL, NULL, 'Arba''in Ad-Dehlawi no. 5', 'dehlawi', 5),
  (80006, 'إِسْتَعِیْنُوْا عَلَی الْحَوَائِجِ بِالْکِتْمَانِ', 'Seek help for any needs discreetly', 'Seek help for any needs discreetly', NULL, NULL, 'Arba''in Ad-Dehlawi no. 6', 'dehlawi', 6),
  (80007, 'إِتَّقُوْا النَّارَ وَلَوْ بِشِقِّ تَمْرَةٍ', 'Protect yourself from the fire even with a part of a date', 'Protect yourself from the fire even with a part of a date', NULL, NULL, 'Arba''in Ad-Dehlawi no. 7', 'dehlawi', 7),
  (80008, 'الدُّنْیَا سِجْنُ الْمُؤمِنِ وَ جَنَّةُ الْکَافِرِ', 'The world is the believer’s prison and the disbeliever’s paradise', 'The world is the believer’s prison and the disbeliever’s paradise', NULL, NULL, 'Arba''in Ad-Dehlawi no. 8', 'dehlawi', 8),
  (80009, 'الْحَیَاءُ خَیْرٌ کُلُّهُ', 'Modesty is entirely good', 'Modesty is entirely good', NULL, NULL, 'Arba''in Ad-Dehlawi no. 9', 'dehlawi', 9),
  (80010, 'عِدَةُ الْمُؤمِنِ کَاَخْذِ الْکَفِّ', 'The word of the believer is like seizing of the hand', 'The word of the believer is like seizing of the hand', NULL, NULL, 'Arba''in Ad-Dehlawi no. 10', 'dehlawi', 10),
  (80011, 'لَا یَحِلُّ لِمُؤمِنٍ اَنْ یَّجُهْرَ أخَاهُ فَوقَ ثَلَاثَةِ أیَّامٍ', 'It is unlawful for a believer to sever relations with his brother for more than three days', 'It is unlawful for a believer to sever relations with his brother for more than three days', NULL, NULL, 'Arba''in Ad-Dehlawi no. 11', 'dehlawi', 11),
  (80012, 'لَیْسَ مِنَّا مَنْ غَشَّنَا', 'He is not one of us who cheats us', 'He is not one of us who cheats us', NULL, NULL, 'Arba''in Ad-Dehlawi no. 12', 'dehlawi', 12),
  (80013, 'مَا قَلَّ وَكَفَى خَيْرٌ مِمَّا كَثُرَ وَأَلْهَى', 'A little that suffices is better than an abundance that distracts', 'A little that suffices is better than an abundance that distracts', NULL, NULL, 'Arba''in Ad-Dehlawi no. 13', 'dehlawi', 13),
  (80014, 'الرَّاجِعُ فِيْ هِبَتِهِ کَالرَّاجِعِ فِيْ قَیْئِهِ', 'Someone who takes back his gift is like someone who eats his vomit', 'Someone who takes back his gift is like someone who eats his vomit', NULL, NULL, 'Arba''in Ad-Dehlawi no. 14', 'dehlawi', 14),
  (80015, 'الْبَلَاءُ مُوَکِّلٌ بِالْمَنْطِقِ', 'Affliction comes from (loose) talk', 'Affliction comes from (loose) talk', NULL, NULL, 'Arba''in Ad-Dehlawi no. 15', 'dehlawi', 15),
  (80016, 'النَّاسُ کَأسْنَانِ الْمُشْطِ', 'People are like the teeth of a comb', 'People are like the teeth of a comb', NULL, NULL, 'Arba''in Ad-Dehlawi no. 16', 'dehlawi', 16),
  (80017, 'الْغِنَى غِنَى النَّفْسِ', 'Richness lies in the richness of the soul', 'Richness lies in the richness of the soul', NULL, NULL, 'Arba''in Ad-Dehlawi no. 17', 'dehlawi', 17),
  (80018, 'الْسَّعِیْدُ مَنْ وُّعِظَ بِغَیْرِهِ', 'The felicitous person takes lessons from (the actions of) others', 'The felicitous person takes lessons from (the actions of) others', NULL, NULL, 'Arba''in Ad-Dehlawi no. 18', 'dehlawi', 18),
  (80019, 'وَ إِنَّ مِنَ الشِّعْرِ لَحِکْمَةً وَاِنَّ مِنَ الْبَیَانِ لَسِحْرًا', 'Indeed, in poetry there is wisdom and in eloquence there is magic', 'Indeed, in poetry there is wisdom and in eloquence there is magic', NULL, NULL, 'Arba''in Ad-Dehlawi no. 19', 'dehlawi', 19),
  (80020, 'عَفْوُ الْمُلُوْكِ إِبْقَاءٌ لِلْمُلْكِ', 'The king’s pardon preserves the kingdom', 'The king’s pardon preserves the kingdom', NULL, NULL, 'Arba''in Ad-Dehlawi no. 20', 'dehlawi', 20),
  (80021, 'اَلْمَرْءُ مَعَ مَنْ أَحَبَّ', 'A man will be with whom he loves', 'A man will be with whom he loves', NULL, NULL, 'Arba''in Ad-Dehlawi no. 21', 'dehlawi', 21),
  (80022, 'مَا هَلَكَ إمْرُؤٌ عَرَفَ قَدْرَهُ', 'A man who knows his worth will not be ruined', 'A man who knows his worth will not be ruined', NULL, NULL, 'Arba''in Ad-Dehlawi no. 22', 'dehlawi', 22),
  (80023, 'اَلْوَلَدُ لِلْفِرَاشِ وَ لِلْعَاهِرِ الْحَجَرُ', 'The child belongs to the bed and stoning is for the adulterer', 'The child belongs to the bed and stoning is for the adulterer', NULL, NULL, 'Arba''in Ad-Dehlawi no. 23', 'dehlawi', 23),
  (80024, 'الْیَدُ الْعُلْیَا خَیْرٌ مِّنَ الْیَدِ السُّفْلَی', 'The upper hand is superior to the lower hand', 'The upper hand is superior to the lower hand', NULL, NULL, 'Arba''in Ad-Dehlawi no. 24', 'dehlawi', 24),
  (80025, 'لَا شَکَرَ اللهَ مَنْ لَّا یَشْکُرُ النَّاسَ', 'He does not thank Allah who does not thank people', 'He does not thank Allah who does not thank people', NULL, NULL, 'Arba''in Ad-Dehlawi no. 25', 'dehlawi', 25),
  (80026, 'حُبُّكَ الشَّيْءَ یُعْمِيْ وَ یُصِمُّ', 'Your love of something can blind and deafen (you)', 'Your love of something can blind and deafen (you)', NULL, NULL, 'Arba''in Ad-Dehlawi no. 26', 'dehlawi', 26),
  (80027, 'جُبِلَتِ الْقُلُوبُ عَلی حُبَّ مَنْ اَحْسَنَ اِلَیْهَا وَ بُغْضِ مَنْ اَسَاءَ اِلَیْهَا', 'Hearts are predisposed to love someone who does them good and detest someone who does them harm', 'Hearts are predisposed to love someone who does them good and detest someone who does them harm', NULL, NULL, 'Arba''in Ad-Dehlawi no. 27', 'dehlawi', 27),
  (80028, 'الْتَّائِبُ مِنَ الذَّنْبِ کَمَنْ لَا ذَنْبَ لَهُ', 'One who repents from sin is like someone without sin', 'One who repents from sin is like someone without sin', NULL, NULL, 'Arba''in Ad-Dehlawi no. 28', 'dehlawi', 28),
  (80029, 'الشَّاهِدُ یَرَی مَا لَا یَرَاهُ الْغَائِبُ', 'The person who actually witnesses an (event) sees that which one who is absent does not', 'The person who actually witnesses an (event) sees that which one who is absent does not', NULL, NULL, 'Arba''in Ad-Dehlawi no. 29', 'dehlawi', 29),
  (80030, 'اِذا جَاءَکُمْ کَرِیْمُ قَوْمٍ فَاَکْرِمُوهُ', 'If the nobleman of a people comes to you, honour him', 'If the nobleman of a people comes to you, honour him', NULL, NULL, 'Arba''in Ad-Dehlawi no. 30', 'dehlawi', 30),
  (80031, 'الْیَمِینُ الْفَاجِرَةُ تَدَعُ الدِّیَارَ الْبَلَاقِعَ', 'False oaths lay waste to home (lands)', 'False oaths lay waste to home (lands)', NULL, NULL, 'Arba''in Ad-Dehlawi no. 31', 'dehlawi', 31),
  (80032, 'مَنْ قُتِلَ دُونَ مَالِهِ فَهُوَ شَهِیْدٌ', 'Whoever is killed attempting to save his property is a martyr', 'Whoever is killed attempting to save his property is a martyr', NULL, NULL, 'Arba''in Ad-Dehlawi no. 32', 'dehlawi', 32),
  (80033, 'الْاَعْمَالُ بِالنِّیَّةِ', 'Actions are through intentions', 'Actions are through intentions', NULL, NULL, 'Arba''in Ad-Dehlawi no. 33', 'dehlawi', 33),
  (80034, 'سَیِّدُ الْقَوْمِ خَادِمُهُمْ', 'The leader of a people is their servant', 'The leader of a people is their servant', NULL, NULL, 'Arba''in Ad-Dehlawi no. 34', 'dehlawi', 34),
  (80035, 'خَیْرُ الْأُمُوْرِ أَوْسَطُهَا', 'The best of affairs is that which is balanced', 'The best of affairs is that which is balanced', NULL, NULL, 'Arba''in Ad-Dehlawi no. 35', 'dehlawi', 35),
  (80036, 'اَللَّهُمَّ بَارِكْ فِیْ أُمَّتِیْ فِی بُکُوْرِهَا یَوْمَ الْخَمِیْسِ', 'O Allah, bless my nation in its early rising on Thursdays', 'O Allah, bless my nation in its early rising on Thursdays', NULL, NULL, 'Arba''in Ad-Dehlawi no. 36', 'dehlawi', 36),
  (80037, 'کَادَ الْفَقْرُ أَنْ یَکُوْنَ کُفْرًا', 'Poverty can almost turn into disbelief', 'Poverty can almost turn into disbelief', NULL, NULL, 'Arba''in Ad-Dehlawi no. 37', 'dehlawi', 37),
  (80038, 'الْسَّفَرُ قِطْعَةٌ مِّنَ الْعَذَابِ', 'Travelling is a portion of punishment', 'Travelling is a portion of punishment', NULL, NULL, 'Arba''in Ad-Dehlawi no. 38', 'dehlawi', 38),
  (80039, 'خَیْرُ زَّادِ الْتَّقْوَی', 'The best of provision is God-Consciousness (taqwa)', 'The best of provision is God-Consciousness (taqwa)', NULL, NULL, 'Arba''in Ad-Dehlawi no. 39', 'dehlawi', 39),
  (80040, 'الْمَجَالِسُ بِالْاَمَانَةِ', 'Meetings are under trust', 'Meetings are under trust', NULL, NULL, 'Arba''in Ad-Dehlawi no. 40', 'dehlawi', 40);

