-- AUTO-GENERATED by scripts/generate-hadith-ahmad-darimi-seed.ts — do not edit by hand.
-- Source: gadingnst/hadith-api (github.com/gadingnst/hadith-api), MIT license.
-- Musnad Ahmad + Sunan ad-Darimi — Arabic + native Indonesian, matched by hadith number.
-- Self-contained catalogue rows (INSERT OR IGNORE) so no separate migration is needed,
-- same pattern as the 'Kisah Islami' category added in kisah_dzulqarnain.sql.

INSERT OR IGNORE INTO hadits_collection (slug, name_id, name_ar, author, sort_order, id_start, id_end, has_native_id) VALUES ('ahmad', 'Musnad Ahmad', 'مسند أحمد', 'Imam Ahmad bin Hanbal', 10, 80001, 89999, 1);
INSERT OR IGNORE INTO hadits_collection (slug, name_id, name_ar, author, sort_order, id_start, id_end, has_native_id) VALUES ('darimi', 'Sunan Ad-Darimi', 'سنن الدارمي', 'Imam Ad-Darimi', 11, 90001, 99999, 1);
