-- AUTO-GENERATED by scripts/generate-kisah-dzulkifli-seed.ts — do not edit by hand.
-- Source content: scripts/content/kisah-dzulkifli.ts (grounded in QS. Al-Anbiya QS. Ta-Ha, Al-Qashash, Al-A'raf, As-Saffat, Maryam, Sad,
-- quran-json CC-BY-4.0). See docs/CONTENT-POLICY.md.
-- Requires quran_seed.sql already applied (resolves related_ayah_id by lookup).
-- No PDFs — read + narrated in-app (TTS), so pdf_ebook_id is NULL.

INSERT OR IGNORE INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Episode 1: Dzulkifli, Termasuk Orang-Orang yang Sabar', 'kisah-dzulkifli-01-termasuk-orang-sabar', 'id', 'kisah-dzulkifli', 1, 1, 'Nabi Dzulkifli termasuk hamba Allah yang namanya diabadikan dalam Al-Qur''an, meski kisah hidupnya tidak diceritakan secara rinci. Ia disebut berdampingan dengan para nabi mulia sebagai teladan kesabaran. Allah berfirman, "Dan (ingatlah kisah) Ismail, Idris, dan Zulkifli. Mereka semua termasuk orang-orang yang sabar. Dan Kami masukkan mereka ke dalam rahmat Kami. Sesungguhnya mereka termasuk orang-orang yang saleh" (QS. Al-Anbiya: 85-86).

Perhatikanlah dua sifat yang Allah sematkan kepadanya dalam ayat singkat ini: "termasuk orang-orang yang sabar" (minas-shabirin) dan "termasuk orang-orang yang saleh" (minas-shalihin). Dua sifat itu sudah cukup menjadi pujian tertinggi bagi seorang hamba — sebab kesabaran adalah pangkal segala keutamaan, dan kesalehan adalah buahnya.

Allah menyandingkan Dzulkifli dengan Ismail dan Idris — dua nabi besar. Penyebutan dalam satu barisan ini menunjukkan kedudukan Dzulkifli yang tinggi di sisi Allah, sekalipun perincian perjuangannya tidak Allah ceritakan kepada kita.

Hikmah: nilai seorang hamba di sisi Allah tidak diukur dari seberapa terkenal kisahnya, melainkan dari kesabaran dan kesalehannya. Banyak orang saleh yang namanya tidak dikenang manusia, tetapi tercatat mulia di sisi Allah.

Sumber & Catatan: episode ini murni bersandar pada Al-Qur''an, QS. Al-Anbiya ayat 85-86 (teks dan terjemahan dari dataset quran-json). Nama "Dzulkifli" hanya disebut dua kali dalam Al-Qur''an (di sini dan QS. Sad: 48), keduanya dalam bentuk pujian ringkas tanpa rincian kisah.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  (SELECT id FROM ayah WHERE surah_id = 21 AND number = 85), NULL, datetime('now');
INSERT OR IGNORE INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Episode 1: Dzulkifli, Among the Patient', 'kisah-dzulkifli-01-termasuk-orang-sabar', 'en', 'kisah-dzulkifli', 1, 1, 'Prophet Dzulkifli (Dhul-Kifl) is among the servants of Allah whose name is immortalized in the Qur''an, even though his life story is not told in detail. He is mentioned alongside noble prophets as a model of patience. Allah said, "And [mention] Isma''il and Idris and Dhul-Kifl; all were of the patient. And We admitted them into Our mercy. Indeed, they were of the righteous" (Qur''an 21:85-86).

Notice the two qualities Allah attaches to him in this brief ayah: "of the patient" (minas-shabirin) and "of the righteous" (minas-shalihin). Those two are already the highest praise for a servant — for patience is the root of every virtue, and righteousness is its fruit.

Allah places Dhul-Kifl beside Isma''il and Idris — two great prophets. Being named in a single line with them shows Dhul-Kifl''s high rank before Allah, even though the details of his struggle were not narrated to us.

Reflection: a servant''s worth before Allah is not measured by how famous his story is, but by his patience and righteousness. Many righteous people are unremembered by men, yet honored before Allah.

Source & Note: this episode rests purely on the Qur''an, 21:85-86 (text and translation from the quran-json dataset). The name "Dhul-Kifl" appears only twice in the Qur''an (here and 38:48), both times as brief praise without any narrative detail.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  (SELECT id FROM ayah WHERE surah_id = 21 AND number = 85), NULL, datetime('now');

INSERT OR IGNORE INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Episode 2: Termasuk Orang-Orang Pilihan, dan Makna Namanya', 'kisah-dzulkifli-02-termasuk-al-akhyar', 'id', 'kisah-dzulkifli', 2, 1, 'Kali kedua Al-Qur''an menyebut Dzulkifli adalah dalam Surah Sad, kembali berdampingan dengan para nabi dan disebut sebagai golongan terpilih. Allah berfirman, "Dan ingatlah Ismail, Ilyasa'', dan Zulkifli. Semuanya termasuk orang-orang yang paling baik" (QS. Sad: 48).

Kata "al-akhyar" berarti orang-orang yang terpilih dan terbaik. Jadi Al-Qur''an memberi Dzulkifli tiga pujian yang berpadu dari dua tempat: ia sabar (Al-Anbiya: 85), ia saleh (Al-Anbiya: 86), dan ia termasuk yang terbaik/terpilih (Sad: 48).

Adapun nama "Dzulkifli" (Dzul-Kifl), para ahli tafsir menjelaskan maknanya secara bahasa. "Al-Kifl" bisa berarti bagian atau nasib (bagian pahala yang berlipat), dan bisa pula berarti tanggungan atau jaminan (kafalah). Sebagian ulama menafsirkan ia dinamai demikian karena sanggup menanggung/menjamin suatu amanah lalu menunaikannya dengan setia. Perlu dijujurkan: Al-Qur''an sendiri tidak menjelaskan sebab penamaan ini, sehingga penafsiran di atas bersifat kebahasaan, bukan kepastian yang qath''i.

Hikmah: gelar "yang terpilih" tidak diberikan cuma-cuma. Ia adalah buah dari kesabaran dan ketaatan yang panjang. Nama yang baik pun sering menyimpan makna keteladanan — dalam hal Dzulkifli, makna kesetiaan menunaikan tanggungan.

Sumber & Catatan: dalil pokok dari Al-Qur''an, QS. Sad: 48 dan QS. Al-Anbiya: 85-86. Penjelasan makna kata "al-kifl" merujuk pada keterangan kebahasaan yang masyhur di kitab-kitab tafsir (mis. Ibnu Katsir, ath-Thabari); karena Al-Qur''an tidak merincinya, ini disampaikan sebagai penafsiran, bukan kepastian.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  (SELECT id FROM ayah WHERE surah_id = 38 AND number = 48), NULL, datetime('now');
INSERT OR IGNORE INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Episode 2: Among the Chosen, and the Meaning of His Name', 'kisah-dzulkifli-02-termasuk-al-akhyar', 'en', 'kisah-dzulkifli', 2, 1, 'The second time the Qur''an mentions Dzulkifli is in Surah Sad, again beside prophets and named among the chosen. Allah said, "And remember Isma''il, Al-Yasa'' (Elisha), and Dhul-Kifl — and all are among the outstanding" (Qur''an 38:48).

The word "al-akhyar" means the chosen and the best. So the Qur''an gives Dhul-Kifl three combined praises from two places: he is patient (21:85), he is righteous (21:86), and he is among the best/chosen (38:48).

As for the name "Dhul-Kifl," the commentators explain its linguistic sense. "Al-Kifl" can mean a share or portion (a multiplied share of reward), and can also mean a responsibility or guarantee (kafalah). Some scholars read it as: he was named so because he took on and guaranteed a trust, then fulfilled it faithfully. In honesty: the Qur''an itself does not explain the reason for the name, so the above is a linguistic interpretation, not a definitive certainty.

Reflection: the title "the chosen" is not given for nothing. It is the fruit of long patience and obedience. A good name, too, often carries a meaning of example — in Dhul-Kifl''s case, the meaning of faithfully discharging a responsibility.

Source & Note: the core evidence is from the Qur''an, 38:48 and 21:85-86. The explanation of "al-kifl" follows the well-known linguistic notes in the tafsir works (e.g. Ibn Kathir, al-Tabari); since the Qur''an does not detail it, this is offered as interpretation, not certainty.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  (SELECT id FROM ayah WHERE surah_id = 38 AND number = 48), NULL, datetime('now');

INSERT OR IGNORE INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Episode 3: Pelajaran Kesabaran dan Menunaikan Amanah', 'kisah-dzulkifli-03-kesabaran-dan-amanah', 'id', 'kisah-dzulkifli', 3, 1, 'Karena Al-Qur''an memuji Dzulkifli terutama dengan kesabaran, di sinilah letak pelajaran utamanya bagi kita. Kesabaran yang Allah puji bukanlah sekadar menahan diri sesaat, melainkan keteguhan yang menetap: sabar dalam ketaatan, sabar menjauhi maksiat, dan sabar menghadapi ujian. Tiga bentuk kesabaran inilah yang mengangkat seorang hamba ke barisan "orang-orang yang saleh" dan "orang-orang yang terpilih".

Makna namanya pun menyimpan pelajaran: seorang yang menanggung amanah (kifl) dan menunaikannya dengan setia. Betapa banyak orang yang menyanggupi sesuatu lalu mengingkarinya; sedangkan hamba pilihan Allah adalah yang menepati apa yang ia tanggung, sekecil apa pun.

Beredar sejumlah riwayat tentang rincian kehidupan Dzulkifli — misalnya bahwa ia menyanggupi kepada seorang nabi sebelumnya untuk berpuasa di siang hari, salat di malam hari, dan menghakimi dengan adil tanpa marah, lalu ia menunaikannya. Namun para ulama menegaskan bahwa riwayat-riwayat semacam ini termasuk Isra''iliyyat (berasal dari sumber Bani Israil) yang tidak dapat dipastikan kebenarannya, dan bukan bagian dari wahyu. Kita menyebutnya sekadar sebagai keterangan tradisi — tidak diyakini pasti benar, tidak pula tergesa didustakan — sembari berpegang pada apa yang jelas dari Al-Qur''an.

Hikmah: kesabaran dan menepati amanah adalah dua kunci yang mengangkat derajat. Dzulkifli mengajarkan bahwa hamba yang paling mulia bukanlah yang paling banyak diceritakan, melainkan yang paling teguh menunaikan tanggung jawabnya kepada Allah dan sesama.

Sumber & Catatan: pujian atas kesabaran dari QS. Al-Anbiya: 85. Riwayat tentang perincian nazar/amal Dzulkifli disebut dalam sejumlah kitab sejarah dan tafsir sebagai Isra''iliyyat; sesuai kaidah, kami sampaikan dengan penanda jelas — tidak dijadikan dalil dan tidak dipastikan benar — karena Al-Qur''an dan Sunnah sahih tidak merincinya. Sebagian ulama juga berbeda pendapat apakah Dzulkifli seorang nabi atau seorang saleh; konteks penyebutannya bersama para nabi menguatkan pandangan bahwa ia seorang nabi.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  (SELECT id FROM ayah WHERE surah_id = 21 AND number = 85), NULL, datetime('now');
INSERT OR IGNORE INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Episode 3: Lessons of Patience and Fulfilling a Trust', 'kisah-dzulkifli-03-kesabaran-dan-amanah', 'en', 'kisah-dzulkifli', 3, 1, 'Because the Qur''an praises Dhul-Kifl above all for patience, that is where his central lesson lies for us. The patience Allah praises is not merely a moment''s restraint, but a settled steadfastness: patience in obedience, patience in avoiding sin, and patience in facing trials. These three forms of patience are what raise a servant into the ranks of "the righteous" and "the chosen."

The meaning of his name, too, holds a lesson: one who takes on a trust (kifl) and discharges it faithfully. How many people promise something and then break it; whereas Allah''s chosen servant is the one who keeps what he has taken on, however small.

A number of reports circulate about the details of Dhul-Kifl''s life — for instance that he pledged to an earlier prophet to fast by day, pray by night, and judge with justice without anger, and then fulfilled it. But the scholars stress that such reports are Isra''iliyyat (originating from the sources of the Children of Israel) whose truth cannot be verified, and are not part of revelation. We mention them merely as tradition — not held to be certainly true, nor hastily denied — while holding fast to what is clear from the Qur''an.

Reflection: patience and keeping a trust are two keys that raise one''s rank. Dhul-Kifl teaches that the noblest servant is not the one whose story is told most, but the one most steadfast in fulfilling his responsibility to Allah and to people.

Source & Note: the praise of patience is from Qur''an 21:85. The reports about the details of Dhul-Kifl''s vow/deeds are recorded in several history and tafsir works as Isra''iliyyat; per the established rule we relay them with a clear marker — not used as evidence and not affirmed as certain — because the Qur''an and authentic Sunnah do not detail them. Scholars also differ on whether Dhul-Kifl was a prophet or a righteous man; the context of his mention among the prophets strengthens the view that he was a prophet.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  (SELECT id FROM ayah WHERE surah_id = 21 AND number = 85), NULL, datetime('now');

