-- Kisah Anak Muslim — 6 short, sequential original stories for children,
-- each teaching one simple Islamic value. Written for ULYAH.COM (not copied
-- from any existing book); no depiction of any living being is used
-- anywhere in the accompanying UI — only decorative geometric/Islamic motifs.

INSERT OR IGNORE INTO kisah_anak (slug, episode_order, title_id, title_en, body_id, body_en, moral_id, moral_en, motif, age_range) VALUES
('bintang-kejujuran', 1, 'Bintang Kejujuran', 'The Star of Honesty',
 'Suatu sore, seorang anak bernama Fatih menemukan uang jajan tergeletak di halaman sekolah. Ia bisa saja mengambilnya diam-diam, tapi hatinya berkata lain. Fatih membawa uang itu ke gurunya dan bercerita jujur di mana ia menemukannya. Ternyata uang itu milik teman sekelasnya yang sedang sedih mencarinya ke mana-mana. Wajah temannya berseri-seri saat uangnya kembali, dan Fatih pulang dengan hati yang tenang — lebih tenang daripada jika ia menyimpannya sendiri.',
 'One afternoon, a boy named Fatih found some pocket money lying in the schoolyard. He could have quietly kept it, but his heart said otherwise. Fatih brought it to his teacher and honestly told her where he found it. It turned out to belong to a classmate who had been sadly searching everywhere. His friend''s face lit up when the money was returned, and Fatih walked home with a calm heart — calmer than if he had kept it for himself.',
 'Kejujuran membuat hati tenang, walau kadang terasa lebih sulit.',
 'Honesty brings peace to the heart, even when it feels harder in the moment.',
 'star', '4-9'),
('lentera-kesabaran', 2, 'Lentera Kesabaran', 'The Lantern of Patience',
 'Aisyah sangat ingin bermain sepeda barunya, tapi hujan turun tiga hari berturut-turut. Ia kesal dan hampir menangis. Neneknya lalu duduk di sampingnya dan berkata, "Setiap hujan pasti berhenti, Nak. Yang sabar menunggu akan lebih bahagia saat waktunya tiba." Aisyah pun menunggu sambil membantu neneknya merapikan mainan dan membaca buku. Ketika hujan akhirnya reda, ia mengayuh sepedanya dengan gembira — dan rasa senangnya terasa berlipat karena sudah lama menanti.',
 'Aisyah really wanted to ride her new bicycle, but it rained for three days straight. She felt upset and almost cried. Her grandmother sat beside her and said, "Every rain stops eventually, dear. Those who wait patiently feel happier when the time comes." So Aisyah waited, helping her grandmother tidy up and reading books. When the rain finally stopped, she rode her bike joyfully — and her happiness felt doubled because she had waited so patiently.',
 'Sabar menunggu membuat kebahagiaan terasa lebih manis.',
 'Waiting patiently makes happiness feel even sweeter.',
 'lantern', '4-9'),
('bulan-sabit-berbagi', 3, 'Bulan Sabit Berbagi', 'The Crescent Moon of Sharing',
 'Rayhan membawa dua potong kue kesukaannya ke sekolah. Saat istirahat, ia melihat temannya, Umar, hanya membawa roti kering tanpa isi. Tanpa berpikir lama, Rayhan membagi satu potong kuenya untuk Umar. "Terima kasih, Rayhan!" kata Umar sambil tersenyum lebar. Sore itu, ibu Rayhan bertanya bagaimana harinya. Rayhan menjawab, "Menyenangkan sekali, Bu! Kue yang kubagi rasanya jadi lebih enak daripada kalau kumakan sendiri."',
 'Rayhan brought two pieces of his favorite cake to school. At recess, he noticed his friend Umar only had plain dry bread. Without hesitating, Rayhan shared one piece of his cake with Umar. "Thank you, Rayhan!" said Umar with a wide smile. That evening, Rayhan''s mother asked about his day. Rayhan replied, "It was wonderful, Mom! The cake I shared tasted even better than if I''d eaten it all myself."',
 'Berbagi membuat rezeki terasa lebih berkah dan manis.',
 'Sharing makes what we have feel even more blessed and sweet.',
 'moon', '4-9'),
('menara-adab', 4, 'Menara Adab', 'The Tower of Good Manners',
 'Setiap kali Zaid masuk rumah, ia selalu mengucap salam dengan suara jelas dan mencium tangan kedua orang tuanya. Suatu hari, sepupunya yang datang berkunjung bertanya, "Kenapa kamu selalu begitu, Zaid?" Zaid menjawab sambil tersenyum, "Karena Rasulullah ﷺ mengajarkan kita untuk selalu menyebarkan salam dan menghormati orang tua. Rasanya rumah jadi lebih hangat kalau begitu." Sepupunya pun ikut mencoba, dan sejak saat itu rumah mereka selalu dipenuhi salam dan senyum setiap kali pintu terbuka.',
 'Every time Zaid entered the house, he always greeted with a clear salam and kissed his parents'' hands. One day, his visiting cousin asked, "Why do you always do that, Zaid?" Zaid smiled and answered, "Because the Prophet ﷺ taught us to always spread salam and honor our parents. It makes the house feel warmer." His cousin tried it too, and from then on their home was always filled with greetings and smiles whenever the door opened.',
 'Adab kecil yang dibiasakan bisa membuat rumah terasa lebih hangat.',
 'Small habits of good manners can make a house feel warmer.',
 'mosque', '4-9'),
('permadani-doa', 5, 'Permadani Doa', 'The Carpet of Du''a',
 'Sebelum tidur, Maryam selalu membaca doa yang diajarkan ibunya. Suatu malam ia bertanya, "Bu, kenapa kita harus berdoa sebelum tidur?" Ibunya menjawab lembut, "Karena tidur itu seperti kematian kecil, Nak. Kita meminta Allah menjaga kita sepanjang malam dan membangunkan kita esok pagi dengan selamat." Maryam mengangguk dan sejak itu ia tidak pernah lupa berdoa — bukan karena diperintah, tapi karena ia merasa lebih tenang dan dijaga saat memejamkan mata.',
 'Before bed, Maryam always recited the du''a her mother had taught her. One night she asked, "Mom, why do we pray before sleeping?" Her mother answered gently, "Because sleep is like a small death, dear. We ask Allah to protect us through the night and wake us safely the next morning." Maryam nodded, and from then on she never forgot to pray — not because she was told to, but because she felt calmer and protected as she closed her eyes.',
 'Doa sebelum tidur membuat hati tenang dan terjaga.',
 'A du''a before sleep brings a calm and protected heart.',
 'star', '4-9'),
('taman-maaf', 6, 'Taman Maaf', 'The Garden of Forgiveness',
 'Bilal marah karena mainan robotnya dipatahkan tak sengaja oleh adiknya, Hana. Ia hampir berteriak, tapi teringat pesan ayahnya: "Memaafkan itu seperti menanam taman di hati — awalnya sulit, tapi lama-lama tumbuh indah." Bilal menarik napas dalam, lalu memeluk Hana yang sudah menangis ketakutan. "Tidak apa-apa, Hana. Kita bisa perbaiki bersama," katanya. Hana tersenyum lega, dan sore itu mereka berdua malah asyik memperbaiki robot itu sambil tertawa.',
 'Bilal was upset because his robot toy was accidentally broken by his little sister, Hana. He almost shouted, but remembered his father''s words: "Forgiving is like planting a garden in your heart — hard at first, but it grows beautiful over time." Bilal took a deep breath, then hugged Hana, who was already crying in fear. "It''s okay, Hana. We can fix it together," he said. Hana smiled with relief, and that evening the two of them ended up happily fixing the robot together, laughing all the while.',
 'Memaafkan menumbuhkan kedamaian yang lebih indah dari amarah.',
 'Forgiveness grows a peace more beautiful than anger.',
 'pattern', '4-9');
