-- AUTO-GENERATED by scripts/generate-kisah-habil-qabil-seed.ts — do not edit by hand.
-- Source content: scripts/content/kisah-habil-qabil.ts (grounded in QS. Al-Qalam
-- 68:17-33, quran-json CC-BY-4.0). See docs/CONTENT-POLICY.md.
-- Requires quran_seed.sql already applied (resolves related_ayah_id by lookup).

INSERT OR IGNORE INTO categories (id, name, slug, parent_id, auto_created) VALUES (5, 'Kisah Islami', 'kisah-islami', NULL, 0);

INSERT INTO ebooks (id, title, author, r2_key, category_id, license_status, license_note) VALUES (1000, 'Episode 1: Dua Kurban dan Benih Kedengkian', 'Tim Editorial ULYAH', 'ebooks/kisah-habil-qabil/id/kisah-habil-qabil-01-dua-kurban-dan-kedengkian.pdf', 5, 'original', 'Ditulis berdasarkan QS. Al-Ma''idah 27-27 (quran-json, CC-BY-4.0). Tidak ada kutipan pihak ketiga berhak cipta.');
INSERT INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Episode 1: Dua Kurban dan Benih Kedengkian', 'kisah-habil-qabil-01-dua-kurban-dan-kedengkian', 'id', 'kisah-habil-qabil', 1, 5, 'Allah menceritakan kisah dua putra Adam dengan sebenarnya sebagai pelajaran tentang bahaya hasad (dengki). Keduanya mempersembahkan kurban kepada Allah; kurban salah seorang diterima, sedangkan yang lain tidak. Allah berfirman, "Dan ceritakanlah (Muhammad) yang sebenarnya kepada mereka tentang kisah kedua putra Adam, ketika keduanya mempersembahkan kurban, maka (kurban) salah seorang dari mereka berdua (Habil) diterima dan dari yang lain (Qabil) tidak diterima. Dia (Qabil) berkata, ‘Sungguh, aku pasti membunuhmu!’ Dia (Habil) berkata, ‘Sesungguhnya Allah hanya menerima (amal) dari orang yang bertakwa’" (QS. Al-Ma''idah: 27).

Diterimanya kurban itu bukan soal besar-kecilnya persembahan, melainkan soal ketakwaan hati yang mempersembahkannya. Alih-alih memperbaiki dirinya agar bertakwa seperti saudaranya, Qabil justru diliputi dengki dan mengancam akan membunuh. Sikap Habil sungguh mulia: ia tidak membalas ancaman dengan ancaman, melainkan meluruskan pangkal masalahnya — bahwa yang menentukan penerimaan amal adalah takwa, bukan kekerasan.

Hikmah: dengki adalah penyakit hati yang membakar amal dan mendorong pada kejahatan. Jika sesuatu tidak diterima, jalan seorang mukmin adalah bermuhasabah dan memperbaiki takwanya, bukan menyalahkan atau membenci orang yang lebih baik amalnya.

Sumber & Catatan: dalil dari Al-Qur''an, QS. Al-Ma''idah: 27 (teks & terjemahan quran-json). Al-Qur''an menyebut keduanya "dua putra Adam" tanpa nama; nama "Habil" dan "Qabil" berasal dari tradisi/tafsir dan tidak dipastikan dari nas.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  (SELECT id FROM ayah WHERE surah_id = 5 AND number = 27), 1000, datetime('now');
INSERT INTO ebooks (id, title, author, r2_key, category_id, license_status, license_note) VALUES (1001, 'Episode 1: Two Sacrifices and the Seed of Envy', 'Tim Editorial ULYAH', 'ebooks/kisah-habil-qabil/en/kisah-habil-qabil-01-dua-kurban-dan-kedengkian.pdf', 5, 'original', 'Ditulis berdasarkan QS. Al-Ma''idah 27-27 (quran-json, CC-BY-4.0). Tidak ada kutipan pihak ketiga berhak cipta.');
INSERT INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Episode 1: Two Sacrifices and the Seed of Envy', 'kisah-habil-qabil-01-dua-kurban-dan-kedengkian', 'en', 'kisah-habil-qabil', 1, 5, 'Allah relates the story of Adam''s two sons in truth as a lesson about the danger of envy (hasad). Both offered a sacrifice to Allah; the sacrifice of one was accepted, but not the other''s. Allah said, "And recite to them the story of Adam''s two sons, in truth, when they both offered a sacrifice, and it was accepted from one of them but was not accepted from the other. Said [the latter], ‘I will surely kill you.’ Said [the former], ‘Indeed, Allah only accepts from the righteous [who fear Him]’" (Qur''an 5:27).

The acceptance of the sacrifice was not about how large the offering was, but about the piety of the heart that offered it. Instead of correcting himself to become God-fearing like his brother, the one whose offering was rejected was consumed with envy and threatened murder. The other brother''s stance was truly noble: he did not answer a threat with a threat, but corrected the root of the matter — that what determines the acceptance of a deed is piety, not violence.

Reflection: envy is a disease of the heart that burns up deeds and drives one to evil. If something is not accepted, the way of a believer is self-examination and improving one''s piety, not blaming or hating the one whose deed was better.

Source & Note: evidence from the Qur''an, 5:27 (text & translation from quran-json). The Qur''an calls them "Adam''s two sons" without names; the names "Habil" (Abel) and "Qabil" (Cain) come from tradition/tafsir and are not certain from the text.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  (SELECT id FROM ayah WHERE surah_id = 5 AND number = 27), 1001, datetime('now');

INSERT INTO ebooks (id, title, author, r2_key, category_id, license_status, license_note) VALUES (1002, 'Episode 2: Tangan yang Menahan Diri karena Takut Allah', 'Tim Editorial ULYAH', 'ebooks/kisah-habil-qabil/id/kisah-habil-qabil-02-tangan-yang-menahan-diri.pdf', 5, 'original', 'Ditulis berdasarkan QS. Al-Ma''idah 28-29 (quran-json, CC-BY-4.0). Tidak ada kutipan pihak ketiga berhak cipta.');
INSERT INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Episode 2: Tangan yang Menahan Diri karena Takut Allah', 'kisah-habil-qabil-02-tangan-yang-menahan-diri', 'id', 'kisah-habil-qabil', 2, 5, 'Menghadapi ancaman pembunuhan, saudara yang beriman itu memilih sikap yang menakjubkan: ia tidak akan menjadi pemulai kejahatan, meski nyawanya terancam. Allah berfirman, "‘Sungguh, jika engkau (Qabil) menggerakkan tanganmu kepadaku untuk membunuhku, aku tidak akan menggerakkan tanganku kepadamu untuk membunuhmu. Aku takut kepada Allah, Tuhan seluruh alam’" (QS. Al-Ma''idah: 28).

Ini bukan kelemahan, melainkan ketakwaan. Ia menahan tangannya bukan karena tak mampu membela diri, tetapi karena takut kepada Allah dan enggan menjadi orang yang memulai penumpahan darah. Lalu ia memperingatkan saudaranya akan akibat perbuatan itu di akhirat, "‘Sesungguhnya aku ingin agar engkau kembali dengan (membawa) dosa (membunuh)ku dan dosamu sendiri, maka engkau akan menjadi penghuni neraka; dan itulah balasan bagi orang yang zalim’" (QS. Al-Ma''idah: 29).

Ia mengingatkan bahwa kezaliman itu pada akhirnya menimpa pelakunya sendiri: si pembunuh akan memikul dosanya sendiri sekaligus dosa dari kezaliman yang ia lakukan, dan tempat kembalinya adalah neraka.

Hikmah: keberanian sejati kadang justru terletak pada menahan diri dari kejahatan, bukan membalasnya dengan kejahatan serupa. Rasa takut kepada Allah adalah rem paling kuat yang menahan tangan manusia dari menzalimi sesama.

Sumber & Catatan: dalil dari Al-Qur''an, QS. Al-Ma''idah: 28-29. Ucapan menahan diri dan peringatan tentang dosa & neraka adalah nas Al-Qur''an, bukan tambahan.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  (SELECT id FROM ayah WHERE surah_id = 5 AND number = 28), 1002, datetime('now');
INSERT INTO ebooks (id, title, author, r2_key, category_id, license_status, license_note) VALUES (1003, 'Episode 2: The Hand That Held Back out of Fear of Allah', 'Tim Editorial ULYAH', 'ebooks/kisah-habil-qabil/en/kisah-habil-qabil-02-tangan-yang-menahan-diri.pdf', 5, 'original', 'Ditulis berdasarkan QS. Al-Ma''idah 28-29 (quran-json, CC-BY-4.0). Tidak ada kutipan pihak ketiga berhak cipta.');
INSERT INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Episode 2: The Hand That Held Back out of Fear of Allah', 'kisah-habil-qabil-02-tangan-yang-menahan-diri', 'en', 'kisah-habil-qabil', 2, 5, 'Facing a death threat, the believing brother chose an astonishing stance: he would not be the initiator of evil, even though his life was in danger. Allah said, "‘If you should raise your hand against me to kill me — I shall not raise my hand against you to kill you. Indeed, I fear Allah, Lord of the worlds’" (Qur''an 5:28).

This was not weakness, but piety. He held back his hand not because he was unable to defend himself, but because he feared Allah and refused to be the one to begin the shedding of blood. Then he warned his brother of the consequence of the deed in the Hereafter: "‘Indeed, I want you to obtain [thereby] my sin and your sin so you will be among the companions of the Fire. And that is the recompense of wrongdoers’" (Qur''an 5:29).

He reminded him that wrongdoing ultimately falls back on the one who commits it: the murderer would carry his own sin along with the sin of the injustice he committed, and his destination would be the Fire.

Reflection: true courage sometimes lies precisely in holding back from evil, not answering it with the same evil. Fear of Allah is the strongest brake that restrains a person''s hand from wronging others.

Source & Note: evidence from the Qur''an, 5:28-29. The words of restraint and the warning about sin and the Fire are the Qur''an''s own text, not additions.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  (SELECT id FROM ayah WHERE surah_id = 5 AND number = 28), 1003, datetime('now');

INSERT INTO ebooks (id, title, author, r2_key, category_id, license_status, license_note) VALUES (1004, 'Episode 3: Burung Gagak, Penyesalan, dan Kemuliaan Satu Nyawa', 'Tim Editorial ULYAH', 'ebooks/kisah-habil-qabil/id/kisah-habil-qabil-03-burung-gagak-dan-penyesalan.pdf', 5, 'original', 'Ditulis berdasarkan QS. Al-Ma''idah 30-32 (quran-json, CC-BY-4.0). Tidak ada kutipan pihak ketiga berhak cipta.');
INSERT INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Episode 3: Burung Gagak, Penyesalan, dan Kemuliaan Satu Nyawa', 'kisah-habil-qabil-03-burung-gagak-dan-penyesalan', 'id', 'kisah-habil-qabil', 3, 5, 'Nafsu dan dengki akhirnya mengalahkan si pelaku. Ia benar-benar membunuh saudaranya sendiri — pembunuhan pertama dalam sejarah manusia. Allah berfirman, "Maka nafsu (Qabil) mendorongnya untuk membunuh saudaranya, kemudian dia pun (benar-benar) membunuhnya, maka jadilah dia termasuk orang yang rugi" (QS. Al-Ma''idah: 30).

Setelah membunuh, ia kebingungan hendak diapakan jasad saudaranya. Maka Allah mengajarinya melalui seekor burung gagak. Allah berfirman, "Kemudian Allah mengutus seekor burung gagak menggali tanah untuk memperlihatkan kepadanya (Qabil) bagaimana dia seharusnya menguburkan mayat saudaranya. Qabil berkata, ‘Oh, celaka aku! Mengapa aku tidak mampu berbuat seperti burung gagak ini, sehingga aku dapat menguburkan mayat saudaraku ini?’ Maka jadilah dia termasuk orang yang menyesal" (QS. Al-Ma''idah: 31).

Penyesalannya datang terlambat — setelah nyawa terenggut. Dari peristiwa inilah Allah menegaskan betapa mahal dan mulianya satu nyawa manusia. Allah berfirman, "Oleh karena itu Kami tetapkan (suatu hukum) bagi Bani Israil, bahwa barangsiapa membunuh seseorang, bukan karena orang itu membunuh orang lain, atau bukan karena berbuat kerusakan di bumi, maka seakan-akan dia telah membunuh semua manusia. Barangsiapa memelihara kehidupan seorang manusia, maka seakan-akan dia telah memelihara kehidupan semua manusia" (QS. Al-Ma''idah: 32).

Hikmah: satu tindak kezaliman yang dibiarkan tumbuh dari hati bisa berakhir pada dosa besar dan penyesalan tak berujung. Islam meletakkan nilai yang sangat tinggi pada nyawa manusia — membunuh satu jiwa tanpa hak disamakan dengan membunuh seluruh manusia, dan menyelamatkan satu jiwa disamakan dengan menyelamatkan semuanya.

Sumber & Catatan: dalil dari Al-Qur''an, QS. Al-Ma''idah: 30-32. Kisah burung gagak dan kaidah kemuliaan satu nyawa adalah nas Al-Qur''an. Rincian di luar itu (mis. sebab persaingan) yang beredar dalam sebagian tafsir tidak dipastikan dan tidak dimuat di sini.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  (SELECT id FROM ayah WHERE surah_id = 5 AND number = 30), 1004, datetime('now');
INSERT INTO ebooks (id, title, author, r2_key, category_id, license_status, license_note) VALUES (1005, 'Episode 3: The Crow, Regret, and the Sanctity of a Single Soul', 'Tim Editorial ULYAH', 'ebooks/kisah-habil-qabil/en/kisah-habil-qabil-03-burung-gagak-dan-penyesalan.pdf', 5, 'original', 'Ditulis berdasarkan QS. Al-Ma''idah 30-32 (quran-json, CC-BY-4.0). Tidak ada kutipan pihak ketiga berhak cipta.');
INSERT INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Episode 3: The Crow, Regret, and the Sanctity of a Single Soul', 'kisah-habil-qabil-03-burung-gagak-dan-penyesalan', 'en', 'kisah-habil-qabil', 3, 5, 'Desire and envy finally overcame the wrongdoer. He truly killed his own brother — the first murder in human history. Allah said, "And his soul permitted to him the murder of his brother, so he killed him and became among the losers" (Qur''an 5:30).

After the killing, he was at a loss for what to do with his brother''s body. So Allah taught him through a crow. Allah said, "Then Allah sent a crow searching in the ground to show him how to hide the disgrace of his brother. He said, ‘O woe to me! Have I failed to be like this crow and hide the body of my brother?’ And he became of the regretful" (Qur''an 5:31).

His regret came too late — after a life had been taken. From this very event Allah affirmed how precious and sacred a single human life is. Allah said, "Because of that, We decreed upon the Children of Israel that whoever kills a soul, unless for a soul or for corruption [done] in the land — it is as if he had slain mankind entirely. And whoever saves one — it is as if he had saved mankind entirely" (Qur''an 5:32).

Reflection: a single act of injustice, if allowed to grow from the heart, can end in a grave sin and endless regret. Islam places the highest value on human life — killing one soul unjustly is likened to killing all of humanity, and saving one soul is likened to saving them all.

Source & Note: evidence from the Qur''an, 5:30-32. The account of the crow and the principle of the sanctity of a single soul are the Qur''an''s own text. Details beyond that (e.g. a rivalry as the cause) circulating in some tafsir are not certain and are not included here.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  (SELECT id FROM ayah WHERE surah_id = 5 AND number = 30), 1005, datetime('now');

