-- Kisah Nabi — EKSPANSI berjilid/berbab (owner: "bikin setiap kisah nabi
-- berjilid-jilid, berbab, dari lahir sampai meninggal, sepanjang mungkin,
-- cantumkan dalil Qur'an, hadits, dan kitab").
--
-- Menyambung kisah_nabi_full.sql: setiap nabi utama diperdalam dengan bab-bab
-- lanjutan (section_order melanjutkan nomor yang sudah ada), mengikuti alur
-- Al-Qur'an dan kerangka Qashash al-Anbiya (Ibnu Katsir) serta Tarikh
-- ath-Thabari, dengan sandaran ayat/hadits pada kolom quran_refs.
-- Idempoten: INSERT OR IGNORE + UNIQUE(person_slug, section_order).

-- ═══════════════════════ NABI YUSUF عليه السلام ═══════════════════════
-- Surah Yusuf disebut Allah "ahsanal-qashash" (kisah terbaik) — dikisahkan
-- utuh dari mimpi hingga pertemuan kembali. Bab 1–6 sudah ada; berikut
-- kelanjutannya bab demi bab.
INSERT OR IGNORE INTO kisah_person_section (person_slug, section_order, heading_id, body_id, quran_refs) VALUES
('yusuf', 7, 'Mimpi Sebelas Bintang', 'Yusuf kecil bermimpi melihat sebelas bintang, matahari, dan bulan bersujud kepadanya. Ayahnya, Nabi Ya''qub, memahami bahwa mimpi itu isyarat kenabian dan kemuliaan, lalu berpesan, "Wahai anakku, janganlah kauceritakan mimpimu kepada saudara-saudaramu, nanti mereka membuat tipu daya untuk membinasakanmu; sesungguhnya setan adalah musuh yang nyata bagi manusia." Ya''qub tahu betapa besar kasih sayangnya kepada Yusuf akan menimbulkan kedengkian.', 'QS Yusuf: 4–6'),
('yusuf', 8, 'Dibuang ke Dasar Sumur', 'Saudara-saudara Yusuf bersepakat menyingkirkannya karena iri atas kasih sayang ayah mereka. Dengan dalih mengajaknya bermain, mereka membawanya pergi, lalu mencampakkannya ke dasar sumur. Malam harinya mereka pulang menangis dan berkata bahwa Yusuf dimakan serigala, seraya membawa baju gamisnya yang dilumuri darah palsu. Ya''qub tidak percaya dan berkata, "Maka kesabaran yang baik itulah (kesabaranku); dan hanya kepada Allah aku memohon pertolongan atas apa yang kalian ceritakan."', 'QS Yusuf: 8–18'),
('yusuf', 9, 'Dijual sebagai Budak di Mesir', 'Sebuah kafilah lewat dan menurunkan timba; betapa gembiranya mereka menemukan seorang anak di dalam sumur. Yusuf dijadikan barang dagangan dan dijual dengan harga murah, beberapa keping dirham. Ia dibeli seorang pembesar Mesir (Al-''Aziz) yang berpesan kepada istrinya agar memuliakan tempat tinggalnya. Demikianlah Allah meneguhkan kedudukan Yusuf di bumi dan mengajarkannya takwil mimpi — "dan Allah berkuasa terhadap urusan-Nya, tetapi kebanyakan manusia tidak mengetahui."', 'QS Yusuf: 19–21'),
('yusuf', 10, 'Godaan dan Gamis yang Robek di Belakang', 'Setelah Yusuf dewasa, istri Al-''Aziz menggodanya dan mengunci semua pintu. Yusuf menolak, "Aku berlindung kepada Allah." Keduanya berlomba menuju pintu dan robeklah gamis Yusuf dari belakang. Seorang saksi dari keluarga wanita itu menimbang bukti: jika gamis robek di depan, Yusuf bersalah; jika robek di belakang, wanita itulah yang berdusta. Ternyata robek di belakang — maka nyatalah bahwa Yusuf yang benar. Inilah bukti bahwa Allah memalingkan keburukan dari hamba-Nya yang ikhlas.', 'QS Yusuf: 23–29'),
('yusuf', 11, 'Para Wanita yang Mengiris Jari', 'Berita itu tersebar; para wanita kota mencela istri Al-''Aziz. Ia lalu mengundang mereka, memberi masing-masing sebuah pisau, dan menyuruh Yusuf keluar. Ketika mereka melihatnya, mereka terpukau hingga mengiris jari mereka sendiri tanpa sadar dan berkata, "Maha sempurna Allah, ini bukanlah manusia; ini benar-benar malaikat yang mulia." Yusuf memilih penjara daripada memenuhi ajakan mereka, "Wahai Tuhanku, penjara lebih aku sukai daripada memenuhi ajakan mereka."', 'QS Yusuf: 30–34'),
('yusuf', 12, 'Dakwah Tauhid di Dalam Penjara', 'Di penjara, dua pemuda meminta Yusuf menakwilkan mimpi mereka. Sebelum menjawab, ia berdakwah: "Apakah tuhan-tuhan yang bermacam-macam itu lebih baik, ataukah Allah Yang Maha Esa lagi Maha Perkasa? Kalian tidak menyembah selain Dia melainkan nama-nama yang kalian buat sendiri." Ia menakwilkan bahwa yang satu akan menuang khamar untuk tuannya dan yang lain akan disalib. Peristiwa itu terjadi persis seperti takwilnya.', 'QS Yusuf: 36–42'),
('yusuf', 13, 'Takwil Mimpi Raja dan Tujuh Tahun Paceklik', 'Raja bermimpi tujuh sapi gemuk dimakan tujuh sapi kurus, dan tujuh bulir hijau serta tujuh bulir kering. Tak seorang pun mampu menakwilkannya kecuali Yusuf: tujuh tahun subur diikuti tujuh tahun paceklik, maka hendaklah mereka menyimpan gandum pada masa subur. Yusuf tidak mau keluar sebelum namanya dibersihkan; para wanita mengakui, "Sekarang jelaslah kebenaran itu, akulah yang menggodanya, dan sesungguhnya dia termasuk orang-orang yang benar."', 'QS Yusuf: 43–53'),
('yusuf', 14, 'Diangkat Menjadi Bendahara Mesir', 'Raja memanggil Yusuf dan menjadikannya orang kepercayaan. Yusuf berkata, "Jadikanlah aku bendaharawan negeri; sesungguhnya aku adalah orang yang pandai menjaga lagi berpengetahuan." Demikianlah Allah memberi kedudukan kepada Yusuf di negeri Mesir, ia berkuasa penuh di mana saja ia kehendaki — "Kami melimpahkan rahmat Kami kepada siapa yang Kami kehendaki, dan Kami tidak menyia-nyiakan pahala orang-orang yang berbuat baik."', 'QS Yusuf: 54–57'),
('yusuf', 15, 'Saudara-Saudara Datang Meminta Gandum', 'Ketika paceklik melanda, saudara-saudara Yusuf datang ke Mesir membeli bahan makanan. Yusuf mengenali mereka, tetapi mereka tidak mengenalinya. Ia memerintahkan agar barang penukar mereka diam-diam dikembalikan ke dalam karung, dan meminta mereka membawa saudara seayah (Bunyamin) pada kedatangan berikutnya. Ya''qub melepas Bunyamin setelah mereka bersumpah, seraya berpesan agar masuk kota dari pintu-pintu yang berbeda.', 'QS Yusuf: 58–68'),
('yusuf', 16, 'Piala Raja dan Pengakuan Jati Diri', 'Yusuf menempatkan piala raja di karung Bunyamin lalu "menemukannya" agar dapat menahan adiknya dengan cara yang Allah izinkan. Ketika para saudara memohon, Yusuf akhirnya membuka jati dirinya, "Akulah Yusuf, dan ini saudaraku; sungguh Allah telah melimpahkan karunia kepada kami. Barangsiapa bertakwa dan bersabar, Allah tidak menyia-nyiakan pahala orang yang berbuat baik." Ia berkata tanpa dendam, "Tidak ada cercaan atas kalian hari ini; mudah-mudahan Allah mengampuni kalian."', 'QS Yusuf: 69–92'),
('yusuf', 17, 'Gamis Yusuf yang Mengembalikan Penglihatan Ya''qub', 'Yusuf mengirimkan gamisnya agar diusapkan ke wajah ayahnya yang telah buta karena tangis dan rindu bertahun-tahun. Ketika kafilah belum tiba, Ya''qub berkata, "Sesungguhnya aku mencium bau Yusuf." Begitu gamis itu diusapkan, penglihatannya kembali. Seluruh keluarga berhijrah ke Mesir; kedua orang tua diangkat ke singgasana, dan sebelas saudara bersujud hormat kepada Yusuf — terwujudlah mimpi masa kecilnya.', 'QS Yusuf: 93–100'),
('yusuf', 18, 'Ibrah Kisah Nabi Yusuf', 'Kisah Yusuf adalah puncak kesabaran atas kezaliman keluarga, godaan, fitnah, dan penjara — yang seluruhnya berujung kemuliaan karena takwa. Ia menutup kisahnya dengan doa yang mengajarkan tauhid hingga akhir, "Ya Tuhanku, Engkau telah menganugerahkan kepadaku sebagian kekuasaan dan mengajarkanku takwil mimpi... wafatkanlah aku dalam keadaan Islam dan gabungkanlah aku dengan orang-orang saleh." Pelajarannya: makar manusia tak mengalahkan takdir Allah, dan pemaaf terhadap yang menzalimi adalah akhlak para nabi.', 'QS Yusuf: 100–101 · QS Yusuf: 111');

-- ═══════════════════════ NABI MUSA عليه السلام ═══════════════════════
-- Nabi yang paling banyak dikisahkan dalam Al-Qur'an. Bab 1–8 sudah ada;
-- berikut kelanjutan alur besarnya hingga wafat.
INSERT OR IGNORE INTO kisah_person_section (person_slug, section_order, heading_id, body_id, quran_refs) VALUES
('musa', 9, 'Bayi dalam Peti di Sungai Nil', 'Fir''aun berlaku sewenang-wenang dan menyembelih setiap bayi laki-laki Bani Israil. Ketika Musa lahir, Allah mengilhamkan ibunya untuk menyusui lalu menghanyutkannya di sungai dalam sebuah peti bila khawatir — "dan janganlah takut dan bersedih, sesungguhnya Kami akan mengembalikannya kepadamu dan menjadikannya salah seorang rasul." Peti itu justru dipungut keluarga Fir''aun, dan atas kehendak Allah Musa dikembalikan menyusu kepada ibunya sendiri, agar hati ibunya tenang.', 'QS Al-Qashash: 3–13 · QS Thaha: 38–40'),
('musa', 10, 'Membela yang Terzalimi dan Lari ke Madyan', 'Setelah dewasa dan diberi hikmah, Musa memasuki kota dan mendapati dua orang berkelahi — seorang dari kaumnya dan seorang dari musuhnya. Ia meninju pembela musuh itu hingga tewas tanpa sengaja, lalu menyesal dan beristighfar, "Ya Tuhanku, sesungguhnya aku telah menzalimi diriku, maka ampunilah aku." Ketika para pembesar berencana membunuhnya, ia lari ke Madyan, menolong dua wanita memberi minum ternak, lalu dinikahkan dengan salah satunya oleh seorang syaikh tua (disebut sebagian ulama sebagai Nabi Syu''aib) dengan mahar bekerja delapan hingga sepuluh tahun.', 'QS Al-Qashash: 14–28'),
('musa', 11, 'Api di Lembah Suci Thuwa dan Dua Mukjizat', 'Dalam perjalanan pulang, Musa melihat api di lereng gunung Thur. Di lembah suci Thuwa, Allah berbicara langsung kepadanya, "Sesungguhnya Aku inilah Allah, tidak ada tuhan selain Aku, maka sembahlah Aku dan dirikanlah salat untuk mengingat-Ku." Diberikan dua tanda: tongkat yang berubah menjadi ular, dan tangan yang bercahaya putih tanpa cacat. Musa diutus kepada Fir''aun yang telah melampaui batas, dan memohon agar saudaranya Harun diangkat menjadi penolongnya.', 'QS Thaha: 9–36 · QS An-Naml: 7–12 · QS Al-Qashash: 29–35'),
('musa', 12, 'Dialog dengan Fir''aun dan Kekalahan Para Penyihir', 'Musa dan Harun menyampaikan kebenaran dengan kata-kata lembut, namun Fir''aun mengaku sebagai tuhan tertinggi. Ia mengumpulkan para penyihir pada hari raya. Mereka melemparkan tali dan tongkat yang tampak merayap; Musa melemparkan tongkatnya dan seketika menelan seluruh sihir mereka. Para penyihir langsung tersungkur sujud, "Kami beriman kepada Tuhan semesta alam, Tuhan Musa dan Harun." Fir''aun mengancam menyalib mereka, tetapi iman telah menghunjam di hati mereka.', 'QS Al-A''raf: 103–126 · QS Thaha: 56–73 · QS Asy-Syu''ara: 10–51'),
('musa', 13, 'Azab Beruntun dan Keluarnya Bani Israil', 'Allah menimpakan tanda-tanda kepada kaum Fir''aun: kemarau, kekurangan buah, topan, belalang, kutu, katak, dan darah — namun mereka tetap ingkar. Akhirnya Allah memerintahkan Musa membawa Bani Israil keluar pada malam hari. Fir''aun dan bala tentaranya mengejar hingga terjepit di tepi laut. Ketika Bani Israil cemas, Musa berkata dengan yakin, "Sekali-kali tidak akan tersusul; sesungguhnya Tuhanku bersamaku, Dia akan memberi petunjuk kepadaku."', 'QS Al-A''raf: 130–137 · QS Asy-Syu''ara: 52–68'),
('musa', 14, 'Terbelahnya Laut dan Tenggelamnya Fir''aun', 'Allah mewahyukan agar Musa memukul laut dengan tongkatnya; laut pun terbelah menjadi jalan kering, setiap belahan seperti gunung besar. Bani Israil menyeberang selamat, sedangkan Fir''aun dan tentaranya tenggelam ketika air kembali menyatu. Di detik ajalnya Fir''aun berkata beriman, tetapi terlambat: "Apakah sekarang, padahal engkau telah durhaka sejak dahulu?" Jasadnya diselamatkan Allah menjadi pelajaran bagi generasi sesudahnya.', 'QS Asy-Syu''ara: 63–66 · QS Yunus: 90–92 · QS Thaha: 77–79'),
('musa', 15, 'Munajat di Bukit Thur dan Lauh-Lauh Taurat', 'Musa diseru bermunajat empat puluh malam. Ia memohon dapat melihat Allah, "Ya Tuhanku, tampakkanlah diri-Mu kepadaku." Allah menjawab, "Engkau tidak akan sanggup melihat-Ku, tetapi lihatlah ke gunung itu." Ketika Allah menampakkan keagungan-Nya kepada gunung, gunung itu hancur luluh dan Musa jatuh pingsan. Ia diberi lauh-lauh (Taurat) berisi pengajaran dan perincian segala sesuatu, serta perintah agar kaumnya berpegang dengan sekuat-kuatnya.', 'QS Al-A''raf: 142–145 · QS Al-Baqarah: 51'),
('musa', 16, 'Fitnah Anak Sapi Emas', 'Selama kepergian Musa, Samiri membuat patung anak sapi dari perhiasan emas yang dapat bersuara, lalu Bani Israil menyembahnya. Harun telah memperingatkan, tetapi mereka tak mengindahkannya. Musa kembali dengan marah dan sedih, menegur Harun lalu menghukum Samiri. Kaum itu diperintahkan bertaubat dengan sungguh-sungguh. Peristiwa ini menunjukkan betapa cepatnya hati berpaling bila ditinggal bimbingan, dan betapa Harun menjaga persatuan umat.', 'QS Thaha: 83–98 · QS Al-A''raf: 148–155'),
('musa', 17, 'Berguru kepada Khidhir', 'Musa diperlihatkan bahwa di atas ilmunya ada ilmu yang Allah ajarkan kepada hamba lain. Ia menempuh perjalanan mencari Khidhir di pertemuan dua laut. Khidhir melubangi perahu, membunuh seorang anak, dan menegakkan dinding tanpa upah — perbuatan yang tampak ganjil, hingga akhirnya ditakwilkan: semuanya adalah rahmat tersembunyi. Kisah ini mengajarkan kerendahan hati bahkan bagi seorang rasul ulul azmi, dan bahwa hikmah Allah kerap tak segera terlihat.', 'QS Al-Kahfi: 60–82'),
('musa', 18, 'Ibrah Kisah Nabi Musa', 'Musa adalah Kalimullah, yang berbicara langsung dengan Allah, pemimpin perjuangan tauhid melawan tiran terbesar. Kisahnya mengajarkan keberanian menegakkan kebenaran di hadapan kekuasaan, kesabaran menghadapi kaum yang keras kepala, dan bahwa pertolongan Allah datang justru ketika jalan tampak buntu. Allah memuji kedudukannya, "Dan Aku telah memilihmu untuk diri-Ku."', 'QS Thaha: 41 · QS An-Nisa: 164 · QS Al-Ahzab: 69'),
('musa', 19, 'Wafatnya Musa', 'Diriwayatkan dalam hadits sahih bahwa malaikat maut datang kepada Musa, lalu Musa memohon kepada Allah agar didekatkan ke tanah suci sejarak lemparan batu. Rasulullah ﷺ bersabda, seandainya beliau di sana, niscaya akan beliau tunjukkan makam Musa di sisi jalan dekat bukit pasir merah. Musa wafat setelah menuntaskan risalahnya, meninggalkan Taurat dan kepemimpinan yang kemudian diteruskan Yusya'' bin Nun.', 'HR Bukhari no. 1339 · HR Muslim no. 2372');

-- ═══════════════════════ NABI IBRAHIM عليه السلام ═══════════════════════
INSERT OR IGNORE INTO kisah_person_section (person_slug, section_order, heading_id, body_id, quran_refs) VALUES
('ibrahim', 7, 'Berdebat dengan Ayah demi Tauhid', 'Dengan santun Ibrahim mengajak ayahnya, Azar, meninggalkan penyembahan berhala, "Wahai ayahku, mengapa engkau menyembah sesuatu yang tidak mendengar, tidak melihat, dan tidak dapat menolongmu sedikit pun? Ikutilah aku, aku akan menunjukkan jalan yang lurus." Ayahnya justru mengancam merajamnya. Ibrahim menjawab dengan lembut, "Semoga keselamatan atasmu, aku akan memohonkan ampun bagimu kepada Tuhanku." Ia berlepas diri hanya setelah jelas ayahnya musuh Allah.', 'QS Maryam: 41–48 · QS At-Taubah: 114'),
('ibrahim', 8, 'Meminta Diperlihatkan Cara Menghidupkan yang Mati', 'Ibrahim memohon agar hatinya makin mantap, "Ya Tuhanku, perlihatkanlah kepadaku bagaimana Engkau menghidupkan yang mati." Allah bertanya, "Belumkah engkau percaya?" Ia menjawab, "Aku telah percaya, tetapi agar hatiku tenang." Maka ia diperintahkan mengambil empat ekor burung, memotongnya, dan meletakkan bagiannya di beberapa bukit, lalu memanggilnya — burung-burung itu datang dengan segera. Inilah pelajaran bahwa keimanan yang benar tidak menolak dalil, bahkan mencarinya untuk ketenangan.', 'QS Al-Baqarah: 260'),
('ibrahim', 9, 'Tamu Para Malaikat dan Kabar Ishaq', 'Para malaikat singgah dalam rupa tamu dan Ibrahim segera menyuguhkan anak sapi panggang. Ketika mereka tidak menyentuhnya, ia merasa takut, tetapi mereka menenangkan dan menyampaikan kabar gembira kelahiran Ishaq, seorang anak yang alim. Istrinya yang telah tua tertawa heran. Mereka juga mengabarkan bahwa mereka diutus membinasakan kaum Luth, dan Ibrahim sempat berbantah memohonkan keselamatan kaum itu karena sifat penyantunnya.', 'QS Hud: 69–76 · QS Adz-Dzariyat: 24–34'),
('ibrahim', 10, 'Wafat dalam Keadaan Hanif', 'Ibrahim menutup hidupnya sebagai imam yang lurus, bukan Yahudi maupun Nasrani, melainkan seorang muslim yang hanif. Allah abadikan wasiat tauhidnya kepada anak-anaknya, "Wahai anak-anakku, sesungguhnya Allah telah memilih agama ini untukmu, maka janganlah kalian mati kecuali dalam keadaan muslim." Ia disebut khalilullah — kekasih Allah — dan namanya diabadikan dalam shalawat setiap salat umat Muhammad ﷺ.', 'QS Al-Baqarah: 130–132 · QS An-Nisa: 125 · QS Ali ''Imran: 67');

-- ═══════════════════════ NABI ISA عليه السلام ═══════════════════════
INSERT OR IGNORE INTO kisah_person_section (person_slug, section_order, heading_id, body_id, quran_refs) VALUES
('isa', 6, 'Berbicara di Buaian', 'Ketika Maryam membawa bayinya dan kaumnya menuduh dengan keji, ia menunjuk kepada sang bayi. Dengan izin Allah, Isa berbicara di buaian, "Sesungguhnya aku hamba Allah, Dia memberiku Al-Kitab dan menjadikanku seorang nabi, dan menjadikan aku diberkati di mana saja aku berada, serta memerintahkan salat dan zakat selama aku hidup." Mukjizat pertama ini sekaligus membersihkan kehormatan ibunya dari tuduhan.', 'QS Maryam: 27–34'),
('isa', 7, 'Mukjizat dengan Izin Allah', 'Isa diberi mukjizat yang nyata: membentuk burung dari tanah lalu meniupnya sehingga hidup dengan izin Allah, menyembuhkan orang buta sejak lahir dan penderita kusta, menghidupkan orang mati, dan mengabarkan apa yang dimakan dan disimpan di rumah — semuanya "dengan izin Allah". Penegasan "bi idznillah" berulang kali menutup pintu pengultusan: mukjizat itu tanda kenabian, bukan ketuhanan.', 'QS Ali ''Imran: 49 · QS Al-Ma''idah: 110'),
('isa', 8, 'Para Hawari dan Hidangan dari Langit', 'Ketika Isa merasakan keingkaran Bani Israil, ia bertanya siapa penolongnya di jalan Allah. Para hawari menjawab, "Kamilah penolong-penolong Allah, kami beriman kepada Allah dan saksikanlah bahwa kami orang-orang muslim." Mereka meminta hidangan dari langit sebagai peneguh hati; Allah mengabulkan dengan peringatan keras bagi yang ingkar sesudahnya. Inti ajaran Isa tetap tauhid, "Sesungguhnya Allah Tuhanku dan Tuhanmu, maka sembahlah Dia; inilah jalan yang lurus."', 'QS Ali ''Imran: 52–53 · QS Al-Ma''idah: 111–115 · QS Maryam: 36'),
('isa', 9, 'Diangkat ke Langit, Tidak Disalib', 'Ketika kaum yang ingkar bersekongkol membunuhnya, Allah menyelamatkannya, "Padahal mereka tidak membunuhnya dan tidak pula menyalibnya, tetapi disamarkan bagi mereka." Allah mengangkat Isa kepada-Nya; ia tidak mati disalib sebagaimana disangka. Al-Qur''an menutup tegas kekeliruan tentang penyaliban dan ketuhanannya, memuliakannya sebagai "Al-Masih Isa putra Maryam, utusan Allah dan kalimat-Nya."', 'QS An-Nisa: 157–159 · QS Ali ''Imran: 55'),
('isa', 10, 'Kabar Kedatangan Ahmad dan Turun di Akhir Zaman', 'Isa menyampaikan kabar gembira tentang seorang rasul sesudahnya yang bernama Ahmad. Dalam hadits sahih, Rasulullah ﷺ mengabarkan bahwa Isa akan turun kembali di akhir zaman sebagai hakim yang adil, mematahkan salib, dan menegakkan keadilan di bawah syariat Islam. Ia adalah tanda dekatnya hari kiamat.', 'QS Ash-Shaff: 6 · HR Bukhari no. 3448 · QS Az-Zukhruf: 61'),
('isa', 11, 'Ibrah Kisah Nabi Isa', 'Kisah Isa menegakkan tauhid di tengah umat yang cenderung mengultuskan: seorang nabi mulia, lahir tanpa ayah sebagai tanda kekuasaan Allah, namun tetap hamba yang beribadah. Pelajarannya, kemuliaan bukan alasan untuk disembah; setinggi apa pun derajat seorang hamba, ia tetaplah hamba.', 'QS An-Nisa: 171–172 · QS Al-Ma''idah: 116–117');

-- ═══════════════════════ NABI SULAIMAN عليه السلام ═══════════════════════
INSERT OR IGNORE INTO kisah_person_section (person_slug, section_order, heading_id, body_id, quran_refs) VALUES
('sulaiman', 6, 'Kerajaan yang Tiada Bandingnya', 'Sulaiman mewarisi kenabian dan kerajaan dari ayahnya Daud, lalu memohon kerajaan yang tak dimiliki siapa pun sesudahnya. Allah menundukkan angin yang berhembus atas perintahnya, membuat tembaga mengalir, serta memerintah jin yang membangun dan menyelam. Ia diajari "bahasa" burung dan diberi segala sesuatu — namun kemuliaannya tidak membuatnya lupa bersyukur, "Ini termasuk karunia Tuhanku untuk mengujiku, apakah aku bersyukur atau kufur."', 'QS Shad: 35–40 · QS An-Naml: 15–16 · QS Al-Anbiya: 81–82'),
('sulaiman', 7, 'Semut dan Barisan Pasukan', 'Ketika pasukan Sulaiman dari jin, manusia, dan burung berbaris, mereka melewati sebuah lembah semut. Seekor semut berkata, "Wahai para semut, masuklah ke sarang kalian agar tidak diinjak Sulaiman dan tentaranya tanpa mereka sadari." Sulaiman tersenyum mendengarnya lalu berdoa, "Ya Tuhanku, berilah aku ilham untuk tetap mensyukuri nikmat-Mu dan agar aku berbuat kebajikan yang Engkau ridhai." Kekuasaannya justru menambah kerendahan hatinya.', 'QS An-Naml: 17–19'),
('sulaiman', 8, 'Burung Hud-Hud dan Ratu Saba', 'Hud-hud membawa kabar tentang kaum Saba yang menyembah matahari di bawah seorang ratu (Bilqis). Sulaiman mengirim surat mengajak kepada tauhid. Setelah pertukaran hadiah dan pemindahan singgasana ratu dalam sekejap oleh seorang yang berilmu dari Kitab, Bilqis datang. Ia menyangka lantai istana dari kaca adalah air lalu menyingkap kakinya, dan akhirnya sadar serta beriman, "Aku berserah diri bersama Sulaiman kepada Allah, Tuhan semesta alam."', 'QS An-Naml: 20–44'),
('sulaiman', 9, 'Wafat sambil Bersandar pada Tongkat', 'Sulaiman wafat dalam keadaan berdiri bersandar pada tongkatnya, sementara para jin tetap bekerja karena mengira ia masih hidup. Barulah ketika rayap memakan tongkatnya dan jasadnya rebah, jin menyadari kematiannya — bukti bahwa jin tidak mengetahui yang gaib. Peristiwa ini menutup kisah raja-nabi yang paling agung kekuasaannya, namun tetap tunduk kepada Allah hingga saat wafatnya.', 'QS Saba: 14'),
('sulaiman', 10, 'Ibrah Kisah Nabi Sulaiman', 'Sulaiman membuktikan bahwa kekuasaan, kekayaan, dan mukjizat terbesar sekalipun tidak memalingkan seorang hamba yang bersyukur dari Tuhannya. Kisahnya mengajarkan bahwa jabatan adalah amanah dan ujian, dan bahwa keadilan serta dakwah tauhid lebih mulia daripada sekadar kemegahan.', 'QS An-Naml: 19 · QS Shad: 30');

-- ═══════════════════════ NABI AYYUB عليه السلام ═══════════════════════
INSERT OR IGNORE INTO kisah_person_section (person_slug, section_order, heading_id, body_id, quran_refs) VALUES
('ayyub', 5, 'Ujian Kehilangan Harta dan Kesehatan', 'Ayyub adalah hamba yang kaya, sehat, dan banyak keturunan, namun Allah mengujinya dengan menghabiskan harta, wafatnya anak-anak, dan penyakit yang menahun di sekujur tubuh. Bertahun-tahun ia menanggung derita tanpa sedikit pun mengeluh kepada selain Allah, tetap berdzikir dan bersabar, hingga menjadi lambang kesabaran sepanjang zaman.', 'QS Al-Anbiya: 83 · QS Shad: 41'),
('ayyub', 6, 'Doa Lembut dan Kesembuhan', 'Ayyub berdoa dengan adab yang tinggi, tidak menuntut, "Sesungguhnya aku telah ditimpa penyakit, dan Engkau Tuhan Yang Maha Penyayang di antara para penyayang." Allah menjawab, "Hantamkanlah kakimu; inilah air yang sejuk untuk mandi dan minum." Penyakitnya sembuh, hartanya dan keluarganya dikembalikan berlipat sebagai rahmat dan peringatan bagi ahli ibadah. Ia diperintah menunaikan sumpahnya dengan cara yang meringankan — "dan Kami dapati dia seorang yang sabar; sebaik-baik hamba, sungguh dia sangat taat."', 'QS Shad: 41–44 · QS Al-Anbiya: 84'),
('ayyub', 7, 'Ibrah Kisah Nabi Ayyub', 'Ayyub mengajarkan bahwa sabar bukan berarti diam tanpa berdoa, melainkan tetap berhusnuzhan kepada Allah di puncak penderitaan, mengadu hanya kepada-Nya dengan adab. Ujian adalah tanda cinta Allah kepada hamba pilihan, dan akhir yang baik selalu menyertai kesabaran.', 'QS Shad: 44');

-- ═══════════════════════ NABI YUNUS عليه السلام ═══════════════════════
INSERT OR IGNORE INTO kisah_person_section (person_slug, section_order, heading_id, body_id, quran_refs) VALUES
('yunus', 5, 'Meninggalkan Kaum Sebelum Izin Allah', 'Yunus diutus kepada penduduk Ninawa, tetapi karena kaumnya lama mengingkari, ia pergi dalam keadaan marah sebelum ada izin dari Allah, menyangka Allah tidak akan menyempitkan keadaannya. Ia naik ke sebuah kapal yang penuh muatan; ketika kapal nyaris tenggelam, diadakan undian dan namanya keluar, lalu ia dilemparkan ke laut.', 'QS Al-Anbiya: 87 · QS Ash-Shaffat: 139–141'),
('yunus', 6, 'Doa dalam Perut Ikan', 'Seekor ikan besar menelannya. Dalam kegelapan yang berlapis — gelap malam, gelap laut, dan gelap perut ikan — Yunus menyeru, "La ilaha illa Anta, Maha Suci Engkau, sesungguhnya aku termasuk orang-orang yang zalim." Allah menyelamatkannya dan mengeluarkannya ke pantai dalam keadaan sakit, lalu menumbuhkan pohon dari jenis labu untuk menaunginya. Rasulullah ﷺ mengabarkan doa Dzun-Nun ini tidaklah dibaca seorang muslim dalam kesulitan melainkan Allah mengabulkannya.', 'QS Al-Anbiya: 87–88 · QS Ash-Shaffat: 142–146 · HR Tirmidzi no. 3505'),
('yunus', 7, 'Kaum yang Beriman Seluruhnya', 'Setelah kepergian Yunus, kaumnya melihat tanda-tanda azab dan bertaubat dengan tulus, maka Allah mengangkat siksa dari mereka — satu-satunya negeri yang seluruh penduduknya beriman lalu diselamatkan setelah nyaris ditimpa azab. Yunus kembali dan mendapati kaumnya telah beriman; ia diutus kepada seratus ribu orang atau lebih. Kisahnya mengajarkan agar seorang dai tidak tergesa dan tetap sabar, dan bahwa pintu taubat terbuka selama azab belum benar-benar turun.', 'QS Yunus: 98 · QS Ash-Shaffat: 147–148 · QS Al-Qalam: 48–50');

-- ═══════════════════════ NABI NUH عليه السلام ═══════════════════════
INSERT OR IGNORE INTO kisah_person_section (person_slug, section_order, heading_id, body_id, quran_refs) VALUES
('nuh', 7, 'Bumi yang Dibersihkan dan Perjanjian Baru', 'Setelah air surut, Allah memerintahkan, "Wahai Nuh, turunlah dengan selamat dan penuh keberkahan dari Kami atasmu dan atas umat-umat yang bersamamu." Bumi dimulai kembali dari orang-orang beriman; Nuh disebut sebagai bapak kedua umat manusia karena dari keturunannyalah manusia berkembang biak. Allah menjadikan kisahnya buah tutur yang baik bagi generasi setelahnya, "Kesejahteraan dilimpahkan atas Nuh di seluruh alam."', 'QS Hud: 48 · QS Ash-Shaffat: 75–79 · QS Al-Isra: 3'),
('nuh', 8, 'Wafat setelah Umur yang Panjang', 'Nuh hidup dalam usia yang sangat panjang; Al-Qur''an menyebut ia berdakwah saja selama sembilan ratus lima puluh tahun. Ketika ajal tiba, ia meninggalkan warisan tauhid dan teladan kesabaran terpanjang. Dalam hadits disebutkan bahwa pada hari kiamat Nuh akan ditanya tentang penyampaian risalah, dan umatnya akan bersaksi bahwa ia telah menyampaikannya — umat Muhammad ﷺ menjadi saksi atas kejujuran para rasul.', 'QS Al-Ankabut: 14 · HR Bukhari no. 3339');

-- ═══════════════════════ NABI ADAM عليه السلام ═══════════════════════
INSERT OR IGNORE INTO kisah_person_section (person_slug, section_order, heading_id, body_id, quran_refs) VALUES
('adam', 7, 'Perjanjian dan Wasiat kepada Anak Cucunya', 'Allah mengambil perjanjian dari punggung anak-anak Adam sebelum mereka lahir, "Bukankah Aku ini Tuhanmu?" Mereka menjawab, "Benar, kami bersaksi." Inilah fitrah tauhid yang tertanam pada setiap manusia. Adam, sebagai nabi pertama, menuntun keturunannya di atas fitrah itu dan mengajarkan bahwa keselamatan hanya dengan mengingat perjanjian tersebut dan tidak menyekutukan Allah.', 'QS Al-A''raf: 172–173'),
('adam', 8, 'Wafatnya Manusia Pertama', 'Adam hidup memakmurkan bumi dan mendidik keturunannya di atas tauhid hingga wafat. Dalam riwayat, umat Islam meyakini Adam sebagai nabi yang diberi wahyu, bukan sekadar manusia pertama. Rasulullah ﷺ menyebutnya "Abul Basyar" — bapak manusia — dan pada hari kiamat seluruh manusia mendatanginya memohon syafaat sebelum akhirnya menuju Nabi Muhammad ﷺ. Kisah Adam ditutup dengan pelajaran abadi: setiap anak cucunya akan kembali kepada Allah sebagaimana ia berasal dari-Nya.', 'QS Thaha: 55 · HR Bukhari no. 3340');
