-- AUTO-GENERATED by scripts/generate-kisah-ashabul-qaryah-seed.ts — do not edit by hand.
-- Source content: scripts/content/kisah-ashabul-qaryah.ts (grounded in QS. Ya-Sin
-- 36:13-29, quran-json CC-BY-4.0). See docs/CONTENT-POLICY.md.
-- Requires quran_seed.sql already applied (resolves related_ayah_id by lookup).

INSERT OR IGNORE INTO categories (id, name, slug, parent_id, auto_created) VALUES (5, 'Kisah Islami', 'kisah-islami', NULL, 0);

INSERT INTO ebooks (id, title, author, r2_key, category_id, license_status, license_note) VALUES (800, 'Episode 1: Tiga Utusan ke Suatu Negeri', 'Tim Editorial ULYAH', 'ebooks/kisah-ashabul-qaryah/id/kisah-ashabul-qaryah-01-tiga-utusan-didustakan.pdf', 5, 'original', 'Ditulis berdasarkan QS. Ya-Sin 13-17 (quran-json, CC-BY-4.0). Tidak ada kutipan pihak ketiga berhak cipta.');
INSERT INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Episode 1: Tiga Utusan ke Suatu Negeri', 'kisah-ashabul-qaryah-01-tiga-utusan-didustakan', 'id', 'kisah-ashabul-qaryah', 1, 5, 'Allah menyebutkan sebuah perumpamaan tentang penduduk suatu negeri yang didatangi para utusan untuk menyeru mereka kepada tauhid. Allah berfirman, "Dan buatlah suatu perumpamaan bagi mereka, yaitu penduduk suatu negeri, ketika para utusan datang kepada mereka. (Yaitu) ketika Kami mengutus kepada mereka dua orang utusan, lalu mereka mendustakan keduanya, kemudian Kami kuatkan dengan (utusan) yang ketiga, maka ketiga (utusan) itu berkata, ‘Sesungguhnya kami adalah orang-orang yang diutus kepadamu’" (QS. Ya-Sin: 13-14).

Mulanya Allah mengutus dua orang, tetapi mereka didustakan; lalu Allah menguatkan dengan utusan ketiga. Namun penduduk negeri itu menolak dengan alasan yang sama seperti kaum-kaum pendusta lainnya. "Mereka menjawab, ‘Kamu hanyalah manusia seperti kami, dan (Allah) Yang Maha Pengasih tidak menurunkan sesuatu apa pun; kamu hanyalah pendusta belaka’" (QS. Ya-Sin: 15).

Para utusan pun menegaskan kejujuran mereka dan tugas mereka yang murni menyampaikan, "Mereka berkata, ‘Tuhan kami mengetahui bahwa kami benar-benar utusan (yang diutus) kepadamu. Dan kewajiban kami hanyalah menyampaikan (perintah Allah) dengan jelas’" (QS. Ya-Sin: 16-17).

Hikmah: penolakan terhadap kebenaran sering berulang dengan alasan yang sama sepanjang zaman — meremehkan utusan karena ia "manusia biasa". Namun tugas seorang penyeru bukanlah memaksa hidayah, melainkan menyampaikan dengan jelas; hidayah sepenuhnya di tangan Allah.

Sumber & Catatan: dalil dari Al-Qur''an, QS. Ya-Sin: 13-17 (teks & terjemahan quran-json). Al-Qur''an tidak menyebut nama negeri maupun nama para utusannya; keterangan yang beredar (mis. negeri Antakiyah) berasal dari tafsir/tradisi dan tidak dipastikan.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  (SELECT id FROM ayah WHERE surah_id = 36 AND number = 13), 800, datetime('now');
INSERT INTO ebooks (id, title, author, r2_key, category_id, license_status, license_note) VALUES (801, 'Episode 1: Three Messengers to a Town', 'Tim Editorial ULYAH', 'ebooks/kisah-ashabul-qaryah/en/kisah-ashabul-qaryah-01-tiga-utusan-didustakan.pdf', 5, 'original', 'Ditulis berdasarkan QS. Ya-Sin 13-17 (quran-json, CC-BY-4.0). Tidak ada kutipan pihak ketiga berhak cipta.');
INSERT INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Episode 1: Three Messengers to a Town', 'kisah-ashabul-qaryah-01-tiga-utusan-didustakan', 'en', 'kisah-ashabul-qaryah', 1, 5, 'Allah gives a parable about the people of a town to whom messengers came calling them to tawhid. Allah said, "And present to them an example: the companions of the town, when the messengers came to it. When We sent to them two but they denied them, so We strengthened them with a third, and they said, ''Indeed, we are messengers to you''" (Qur''an 36:13-14).

At first Allah sent two, but they were denied; then Allah strengthened them with a third messenger. Yet the townspeople refused with the same excuse as other denying nations. "They said, ''You are not but human beings like us, and the Most Merciful has not revealed a thing. You are only telling lies''" (Qur''an 36:15).

The messengers then affirmed their truthfulness and their pure task of conveying: "They said, ''Our Lord knows that we are messengers to you, and we are not responsible except for clear notification''" (Qur''an 36:16-17).

Reflection: rejection of the truth often repeats with the same excuse through all ages — belittling a messenger because he is "just a human." But a caller''s task is not to force guidance, only to convey clearly; guidance is entirely in Allah''s hands.

Source & Note: evidence from the Qur''an, 36:13-17 (text & translation from quran-json). The Qur''an does not name the town or the messengers; accounts that circulate (e.g. the city of Antioch) come from tafsir/tradition and are not certain.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  (SELECT id FROM ayah WHERE surah_id = 36 AND number = 13), 801, datetime('now');

INSERT INTO ebooks (id, title, author, r2_key, category_id, license_status, license_note) VALUES (802, 'Episode 2: Ancaman Kaum dan Jawaban Para Utusan', 'Tim Editorial ULYAH', 'ebooks/kisah-ashabul-qaryah/id/kisah-ashabul-qaryah-02-ancaman-dan-jawaban.pdf', 5, 'original', 'Ditulis berdasarkan QS. Ya-Sin 18-19 (quran-json, CC-BY-4.0). Tidak ada kutipan pihak ketiga berhak cipta.');
INSERT INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Episode 2: Ancaman Kaum dan Jawaban Para Utusan', 'kisah-ashabul-qaryah-02-ancaman-dan-jawaban', 'id', 'kisah-ashabul-qaryah', 2, 5, 'Penduduk negeri itu bukan hanya mendustakan, tetapi juga mengancam para utusan dengan sikap yang buruk. Mereka bahkan menganggap kedatangan para utusan sebagai pembawa kesialan. Allah berfirman, "Mereka menjawab, ‘Sesungguhnya kami bernasib malang karena kamu. Sungguh, jika kamu tidak berhenti (menyeru kami), niscaya kami rajam kamu dan kamu pasti akan merasakan siksaan yang pedih dari kami’" (QS. Ya-Sin: 18).

Anggapan sial (tathayyur) adalah keyakinan jahiliah yang mengaitkan nasib buruk dengan sesuatu yang tak berdaya. Para utusan pun meluruskannya, "Mereka (utusan) berkata, ‘Kemalangan kamu itu adalah karena kamu sendiri. Apakah karena kamu diberi peringatan? Sebenarnya kamu adalah kaum yang melampaui batas’" (QS. Ya-Sin: 19).

Para utusan menegaskan bahwa "kesialan" mereka sesungguhnya bersumber dari diri mereka sendiri — dari kekufuran dan pelampauan batas mereka, bukan dari peringatan yang membawa kebaikan. Menolak nasihat lalu menyalahkan si pemberi nasihat adalah tanda hati yang telah menyimpang.

Hikmah: keyakinan pada "sial" dan "keberuntungan" pada makhluk adalah bentuk syirik kecil yang melemahkan tauhid. Segala yang menimpa manusia adalah buah perbuatan dan ketetapan Allah, bukan karena benda atau peristiwa yang dianggap membawa sial.

Sumber & Catatan: dalil dari Al-Qur''an, QS. Ya-Sin: 18-19. Konsep "tathayyur" (menganggap sial) yang ditolak dalam ayat ini adalah nas Al-Qur''an; sikap ini juga ditegaskan larangannya dalam banyak riwayat sahih.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  (SELECT id FROM ayah WHERE surah_id = 36 AND number = 18), 802, datetime('now');
INSERT INTO ebooks (id, title, author, r2_key, category_id, license_status, license_note) VALUES (803, 'Episode 2: The People''s Threat and the Messengers'' Reply', 'Tim Editorial ULYAH', 'ebooks/kisah-ashabul-qaryah/en/kisah-ashabul-qaryah-02-ancaman-dan-jawaban.pdf', 5, 'original', 'Ditulis berdasarkan QS. Ya-Sin 18-19 (quran-json, CC-BY-4.0). Tidak ada kutipan pihak ketiga berhak cipta.');
INSERT INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Episode 2: The People''s Threat and the Messengers'' Reply', 'kisah-ashabul-qaryah-02-ancaman-dan-jawaban', 'en', 'kisah-ashabul-qaryah', 2, 5, 'The townspeople did not only deny; they also threatened the messengers with an ugly stance. They even considered the messengers'' coming a bad omen. Allah said, "They said, ''Indeed, we consider you a bad omen. If you do not desist, we will surely stone you, and there will surely touch you, from us, a painful punishment''" (Qur''an 36:18).

Taking things as omens (tathayyur) is a belief of ignorance that ties misfortune to something powerless. The messengers set it straight: "They said, ''Your omen is with yourselves. Is it because you were reminded? Rather, you are a transgressing people''" (Qur''an 36:19).

The messengers affirmed that their "bad luck" in fact came from themselves — from their disbelief and transgression, not from a reminder that brings good. To reject counsel and then blame the counselor is a sign of a heart gone astray.

Reflection: believing in "bad luck" and "fortune" in created things is a form of minor shirk that weakens tawhid. All that befalls a person is the fruit of deeds and the decree of Allah, not because of an object or event thought to bring bad luck.

Source & Note: evidence from the Qur''an, 36:18-19. The concept of "tathayyur" (taking omens) rejected in this verse is the Qur''an''s own text; its prohibition is also affirmed in many authentic narrations.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  (SELECT id FROM ayah WHERE surah_id = 36 AND number = 18), 803, datetime('now');

INSERT INTO ebooks (id, title, author, r2_key, category_id, license_status, license_note) VALUES (804, 'Episode 3: Seorang Mukmin Datang dari Ujung Kota', 'Tim Editorial ULYAH', 'ebooks/kisah-ashabul-qaryah/id/kisah-ashabul-qaryah-03-mukmin-dari-ujung-kota.pdf', 5, 'original', 'Ditulis berdasarkan QS. Ya-Sin 20-25 (quran-json, CC-BY-4.0). Tidak ada kutipan pihak ketiga berhak cipta.');
INSERT INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Episode 3: Seorang Mukmin Datang dari Ujung Kota', 'kisah-ashabul-qaryah-03-mukmin-dari-ujung-kota', 'id', 'kisah-ashabul-qaryah', 3, 5, 'Di tengah penolakan kaumnya, muncul seorang lelaki beriman yang datang bergegas dari ujung kota untuk membela para utusan dan menyeru kaumnya kepada kebenaran. Allah berfirman, "Dan datanglah dari ujung kota, seorang laki-laki dengan bergegas, dia berkata, ‘Wahai kaumku! Ikutilah utusan-utusan itu. Ikutilah orang yang tidak meminta imbalan kepadamu, dan mereka adalah orang-orang yang mendapat petunjuk’" (QS. Ya-Sin: 20-21).

Lelaki itu berhujjah dengan akal yang jernih dan hati yang tulus. Ia bertanya mengapa ia tidak menyembah Allah yang telah menciptakannya, "Dan mengapa aku tidak menyembah (Allah) yang telah menciptakanku dan hanya kepada-Nyalah kamu akan dikembalikan? Mengapa aku akan menyembah tuhan-tuhan selain-Nya? Jika (Allah) Yang Maha Pengasih menghendaki bencana terhadapku, pasti pertolongan mereka tidak berguna sama sekali bagi diriku dan mereka (juga) tidak dapat menyelamatkanku. Sesungguhnya jika demikian, aku pasti berada dalam kesesatan yang nyata" (QS. Ya-Sin: 22-24).

Lalu ia mengumumkan keimanannya dengan berani di hadapan kaumnya, "Sesungguhnya aku telah beriman kepada Tuhanmu; maka dengarkanlah (pengakuan keimanan)ku" (QS. Ya-Sin: 25).

Hikmah: satu orang beriman yang berani menyuarakan kebenaran lebih berharga daripada kerumunan yang diam dalam kebatilan. Ia menyeru dengan hujjah, bukan paksaan, dan menegaskan keikhlasan para utusan yang "tidak meminta imbalan" — ciri para pembawa kebenaran sejati.

Sumber & Catatan: dalil dari Al-Qur''an, QS. Ya-Sin: 20-25. Al-Qur''an menyebutnya "seorang laki-laki" tanpa nama; sebagian mufasir menyebutnya "Habib an-Najjar" — nama ini berasal dari tradisi/tafsir, bukan dari nas, sehingga tidak dipastikan.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  (SELECT id FROM ayah WHERE surah_id = 36 AND number = 20), 804, datetime('now');
INSERT INTO ebooks (id, title, author, r2_key, category_id, license_status, license_note) VALUES (805, 'Episode 3: A Believer Comes Running from the Edge of the City', 'Tim Editorial ULYAH', 'ebooks/kisah-ashabul-qaryah/en/kisah-ashabul-qaryah-03-mukmin-dari-ujung-kota.pdf', 5, 'original', 'Ditulis berdasarkan QS. Ya-Sin 20-25 (quran-json, CC-BY-4.0). Tidak ada kutipan pihak ketiga berhak cipta.');
INSERT INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Episode 3: A Believer Comes Running from the Edge of the City', 'kisah-ashabul-qaryah-03-mukmin-dari-ujung-kota', 'en', 'kisah-ashabul-qaryah', 3, 5, 'Amid his people''s rejection, a believing man came hurrying from the far end of the city to defend the messengers and call his people to the truth. Allah said, "And there came from the farthest end of the city a man, running. He said, ''O my people, follow the messengers. Follow those who do not ask of you [any] payment, and they are [rightly] guided''" (Qur''an 36:20-21).

The man argued with clear reason and a sincere heart. He asked why he should not worship the Allah who created him: "And why should I not worship He who created me and to whom you will be returned? Should I take other than Him [false] deities [while], if the Most Merciful intends for me some adversity, their intercession will not avail me at all, nor can they save me? Indeed, I would then be in manifest error" (Qur''an 36:22-24).

Then he announced his faith courageously before his people: "Indeed, I have believed in your Lord, so listen to me" (Qur''an 36:25).

Reflection: one believer who dares to voice the truth is worth more than a crowd silent in falsehood. He called with argument, not compulsion, and stressed the sincerity of the messengers who "ask no payment" — the mark of the true bearers of truth.

Source & Note: evidence from the Qur''an, 36:20-25. The Qur''an calls him "a man" without a name; some commentators call him "Habib an-Najjar" — this name comes from tradition/tafsir, not from the text, so it is not certain.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  (SELECT id FROM ayah WHERE surah_id = 36 AND number = 20), 805, datetime('now');

INSERT INTO ebooks (id, title, author, r2_key, category_id, license_status, license_note) VALUES (806, 'Episode 4: Ia Masuk Surga, Kaumnya Dibinasakan', 'Tim Editorial ULYAH', 'ebooks/kisah-ashabul-qaryah/id/kisah-ashabul-qaryah-04-masuk-surga-dan-kaumnya-binasa.pdf', 5, 'original', 'Ditulis berdasarkan QS. Ya-Sin 26-29 (quran-json, CC-BY-4.0). Tidak ada kutipan pihak ketiga berhak cipta.');
INSERT INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Episode 4: Ia Masuk Surga, Kaumnya Dibinasakan', 'kisah-ashabul-qaryah-04-masuk-surga-dan-kaumnya-binasa', 'id', 'kisah-ashabul-qaryah', 4, 5, 'Lelaki beriman itu tampaknya dibunuh oleh kaumnya karena keimanannya, lalu Allah memuliakannya dengan surga. Yang menakjubkan, di dalam surga pun hatinya masih memikirkan kaumnya, berharap mereka mengetahui balasan iman. Allah berfirman, "Dikatakan (kepadanya), ‘Masuklah ke surga.’ Dia (laki-laki itu) berkata, ‘Alangkah baiknya sekiranya kaumku mengetahui, apa yang menyebabkan Tuhanku memberi ampun kepadaku dan menjadikan aku termasuk orang-orang yang dimuliakan’" (QS. Ya-Sin: 26-27).

Meskipun kaumnya menzaliminya, ia tidak mendendam; ia justru berharap mereka mendapat hidayah seperti dirinya. Inilah puncak kelapangan hati seorang mukmin.

Adapun kaum yang zalim itu, Allah membinasakan mereka dengan satu bentakan suara saja — tanpa perlu pasukan dari langit. Allah berfirman, "Dan setelah dia (meninggal), Kami tidak menurunkan suatu pasukan pun dari langit kepada kaumnya, dan Kami tidak perlu menurunkannya. Tidak ada siksaan atas mereka melainkan dengan satu teriakan saja; maka seketika itu mereka mati" (QS. Ya-Sin: 28-29).

Hikmah: kematian di jalan iman bukanlah kekalahan, melainkan pintu menuju surga dan kemuliaan. Sebaliknya, kekuatan orang zalim tak berarti apa-apa di hadapan Allah — cukup satu teriakan untuk membinasakan mereka. Dan hati seorang mukmin sejati dipenuhi kasih, bahkan mendoakan kebaikan bagi orang yang pernah menzaliminya.

Sumber & Catatan: dalil dari Al-Qur''an, QS. Ya-Sin: 26-29. Bahwa lelaki itu dibunuh kaumnya dipahami dari konteks ayat (langsung "masuklah ke surga"); rincian cara kematiannya di sebagian tafsir berasal dari riwayat dan tidak dipastikan. "Satu teriakan" (shaihah) yang membinasakan kaumnya adalah nas Al-Qur''an.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  (SELECT id FROM ayah WHERE surah_id = 36 AND number = 26), 806, datetime('now');
INSERT INTO ebooks (id, title, author, r2_key, category_id, license_status, license_note) VALUES (807, 'Episode 4: He Enters Paradise, His People Are Destroyed', 'Tim Editorial ULYAH', 'ebooks/kisah-ashabul-qaryah/en/kisah-ashabul-qaryah-04-masuk-surga-dan-kaumnya-binasa.pdf', 5, 'original', 'Ditulis berdasarkan QS. Ya-Sin 26-29 (quran-json, CC-BY-4.0). Tidak ada kutipan pihak ketiga berhak cipta.');
INSERT INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Episode 4: He Enters Paradise, His People Are Destroyed', 'kisah-ashabul-qaryah-04-masuk-surga-dan-kaumnya-binasa', 'en', 'kisah-ashabul-qaryah', 4, 5, 'The believing man was apparently killed by his people for his faith, and then Allah honored him with Paradise. Astonishingly, even in Paradise his heart still thought of his people, wishing they knew the reward of faith. Allah said, "It was said, ''Enter Paradise.'' He said, ''I wish my people could know of how my Lord has forgiven me and placed me among the honored''" (Qur''an 36:26-27).

Though his people wronged him, he held no grudge; rather he wished them guidance like his own. This is the summit of a believer''s magnanimity.

As for the wrongdoing people, Allah destroyed them with a single shout — with no need for an army from the sky. Allah said, "And We did not send down upon his people after him any soldiers from the heaven, nor would We have done so. It was not but one shout, and immediately they were extinguished" (Qur''an 36:28-29).

Reflection: death on the path of faith is not defeat, but a door to Paradise and honor. Conversely, the strength of the wrongdoers means nothing before Allah — one shout is enough to destroy them. And the heart of a true believer is filled with compassion, even wishing good for those who once wronged him.

Source & Note: evidence from the Qur''an, 36:26-29. That the man was killed by his people is understood from the context of the verses (the immediate "Enter Paradise"); details of how he died in some tafsir come from reports and are not certain. The "one shout" (sayhah) that destroyed his people is the Qur''an''s own text.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  (SELECT id FROM ayah WHERE surah_id = 36 AND number = 26), 807, datetime('now');

