-- AUTO-GENERATED by scripts/generate-kisah-hud-seed.ts — do not edit by hand.
-- Source content: scripts/content/kisah-hud.ts (grounded in QS. Al-A'raf, Hud, Asy-Syu'ara, Al-Ahqaf, Al-Haqqah,
-- quran-json CC-BY-4.0). See docs/CONTENT-POLICY.md.
-- Requires quran_seed.sql already applied (resolves related_ayah_id by lookup).
-- No PDFs — read + narrated in-app (TTS), so pdf_ebook_id is NULL.

INSERT OR IGNORE INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Episode 1: Kaum ''Ad dan Seruan Tauhid', 'kisah-hud-01-kaum-ad-dan-seruan-tauhid', 'id', 'kisah-hud', 1, 1, 'Setelah kaum Nabi Nuh binasa, Allah menjadikan kaum ''Ad sebagai pengganti di bumi — sebuah kaum yang kuat, besar postur tubuhnya, dan makmur. Namun kemakmuran itu membuat mereka lupa kepada Sang Pemberi nikmat. Maka Allah mengutus kepada mereka seorang dari kalangan mereka sendiri.

Allah berfirman, "Dan kepada kaum ''Ad (Kami utus) saudara mereka, Hud. Dia berkata, ‘Wahai kaumku! Sembahlah Allah! Tidak ada tuhan (sesembahan) bagimu selain Dia. Maka mengapa kamu tidak bertakwa?’" (QS. Al-A''raf: 65). Satu seruan yang sederhana namun mendasar: sembahlah hanya Allah.

Dalam Surah Asy-Syu''ara, seruan Hud ditegaskan dengan kelembutan seorang saudara, "Ketika saudara mereka Hud berkata kepada mereka, ‘Mengapa kamu tidak bertakwa? Sesungguhnya aku ini seorang rasul kepercayaan (yang diutus) kepadamu, maka bertakwalah kepada Allah dan taatlah kepadaku’" (QS. Asy-Syu''ara: 124-126).

Hikmah: setiap nabi memulai dari titik yang sama — mengajak manusia mengesakan Allah. Kekuatan, kekayaan, dan kejayaan sebuah kaum tidak ada artinya bila mereka melupakan Tuhan yang memberi semua itu.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  (SELECT id FROM ayah WHERE surah_id = 7 AND number = 65), NULL, datetime('now');
INSERT OR IGNORE INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Episode 1: The People of ''Ad and the Call to Tawhid', 'kisah-hud-01-kaum-ad-dan-seruan-tauhid', 'en', 'kisah-hud', 1, 1, 'After the people of Prophet Noah perished, Allah made the people of ''Ad successors on the earth — a people strong, great in stature, and prosperous. Yet that prosperity made them forget the Giver of blessings. So Allah sent to them a man from among themselves.

Allah said, "And to ''Ad [We sent] their brother Hud. He said, ''O my people, worship Allah; you have no deity other than Him. Will you not then fear Him?''" (Qur''an 7:65). A simple yet foundational call: worship Allah alone.

In Surah Asy-Syu''ara, Hud''s call is affirmed with the gentleness of a brother, "When their brother Hud said to them, ''Will you not fear Allah? Indeed, I am to you a trustworthy messenger. So fear Allah and obey me''" (26:124-126).

Reflection: every prophet begins from the same point — calling people to the oneness of Allah. The strength, wealth, and glory of a people count for nothing if they forget the Lord who gave them all of it.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  (SELECT id FROM ayah WHERE surah_id = 7 AND number = 65), NULL, datetime('now');

INSERT OR IGNORE INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Episode 2: Tuduhan Kaum dan Jawaban Hud', 'kisah-hud-02-tuduhan-dan-jawaban-hud', 'id', 'kisah-hud', 2, 1, 'Seruan Hud tidak disambut, melainkan dicemooh oleh para pembesar kaumnya. Allah berfirman, "Pemuka-pemuka yang kafir dari kaumnya berkata, ‘Sesungguhnya kami memandang kamu benar-benar kurang waras, dan kami kira kamu termasuk orang-orang yang berdusta’" (QS. Al-A''raf: 66). Tuduhan bodoh dan pendusta — dua tuduhan yang kerap dilemparkan kepada para nabi.

Hud menjawab bukan dengan amarah, melainkan dengan ketenangan seorang yang yakin akan tugasnya, "Wahai kaumku! Bukan aku kurang waras, tetapi aku ini adalah utusan dari Tuhan seluruh alam. Aku menyampaikan kepadamu amanat Tuhanku, dan aku hanyalah pemberi nasihat yang terpercaya bagimu" (QS. Al-A''raf: 67-68).

Ia menyebut dirinya "pemberi nasihat yang terpercaya" — menegaskan bahwa dakwahnya lahir dari kasih sayang, bukan kepentingan pribadi. Dalam Surah Asy-Syu''ara ia bahkan menegaskan tidak meminta upah apa pun, "Aku tidak meminta imbalan kepadamu atas ajakan itu; imbalanku hanyalah dari Tuhan seluruh alam" (QS. Asy-Syu''ara: 127).

Hikmah: menghadapi hinaan dengan kelembutan adalah akhlak para nabi. Kebenaran tidak perlu dibela dengan kemarahan, cukup dengan kejelasan dan keteguhan hati.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  (SELECT id FROM ayah WHERE surah_id = 7 AND number = 66), NULL, datetime('now');
INSERT OR IGNORE INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Episode 2: The People''s Accusation and Hud''s Reply', 'kisah-hud-02-tuduhan-dan-jawaban-hud', 'en', 'kisah-hud', 2, 1, 'Hud''s call was met not with welcome, but with ridicule from the chiefs of his people. Allah said, "The eminent ones who disbelieved among his people said, ''Indeed, we see you in foolishness, and indeed, we think you are of the liars''" (Qur''an 7:66). Foolishness and lying — two accusations often hurled at the prophets.

Hud answered not with anger, but with the calm of one certain of his task, "O my people, there is no foolishness in me, but I am a messenger from the Lord of the worlds. I convey to you the messages of my Lord, and I am to you a trustworthy adviser" (7:67-68).

He called himself "a trustworthy adviser" — affirming that his call sprang from compassion, not personal gain. In Surah Asy-Syu''ara he even affirmed he sought no reward at all, "And I do not ask you for it any payment; my payment is only from the Lord of the worlds" (26:127).

Reflection: to meet insult with gentleness is the character of the prophets. Truth need not be defended with rage — only with clarity and steadfastness of heart.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  (SELECT id FROM ayah WHERE surah_id = 7 AND number = 66), NULL, datetime('now');

INSERT OR IGNORE INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Episode 3: Peringatan agar Mengingat Nikmat', 'kisah-hud-03-ingat-nikmat-dan-jangan-sombong', 'id', 'kisah-hud', 3, 1, 'Hud mengingatkan kaumnya akan anugerah besar yang telah Allah limpahkan kepada mereka — agar rasa syukur menuntun mereka kembali. Allah berfirman, "Apakah kamu heran bahwa datang kepadamu peringatan dari Tuhanmu melalui seorang laki-laki dari kalanganmu sendiri, untuk memberi peringatan kepadamu? Ingatlah ketika Dia menjadikan kamu sebagai khalifah (penguasa) setelah kaum Nuh, dan Dia lebihkan kamu dalam kekuatan tubuh dan perawakan. Maka ingatlah akan nikmat-nikmat Allah agar kamu beruntung" (QS. Al-A''raf: 69).

Namun ''Ad justru menyalahgunakan kekuatan itu untuk kesombongan. Dalam Surah Asy-Syu''ara, Hud menegur kebiasaan mereka membangun tanda kemegahan di setiap tempat tinggi, "Apakah kamu mendirikan bangunan megah pada setiap tempat yang tinggi untuk bermain-main? Dan kamu membuat benteng-benteng dengan harapan agar kamu hidup kekal? Dan apabila kamu menghukum, kamu menghukum dengan kejam dan bengis" (QS. Asy-Syu''ara: 128-130).

Maka Hud menutup nasihatnya, "Maka bertakwalah kepada Allah dan taatlah kepadaku. Dan bertakwalah kepada Allah yang telah menganugerahkan kepadamu apa yang kamu ketahui — ternak dan anak-anak, kebun-kebun dan mata air" (QS. Asy-Syu''ara: 131-134).

Hikmah: nikmat yang tidak disyukuri berubah menjadi ujian. Kekuatan yang seharusnya menuntun pada rasa syukur, bila disertai kesombongan, justru menjadi jalan menuju kebinasaan.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  (SELECT id FROM ayah WHERE surah_id = 7 AND number = 69), NULL, datetime('now');
INSERT OR IGNORE INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Episode 3: A Reminder to Remember the Blessings', 'kisah-hud-03-ingat-nikmat-dan-jangan-sombong', 'en', 'kisah-hud', 3, 1, 'Hud reminded his people of the great favor Allah had poured upon them — that gratitude might lead them back. Allah said, "Do you wonder that there has come to you a reminder from your Lord through a man from among you, that he may warn you? And remember when He made you successors after the people of Noah and increased you in stature extensively. So remember the favors of Allah, that you might succeed" (Qur''an 7:69).

Yet ''Ad turned that strength into arrogance. In Surah Asy-Syu''ara, Hud rebuked their habit of building monuments of grandeur on every height, "Do you construct on every elevation a sign, amusing yourselves, and take for yourselves strongholds that you might abide eternally? And when you strike, you strike as tyrants" (26:128-130).

So Hud closed his counsel, "So fear Allah and obey me. And fear He who provided you with that which you know — He provided you with grazing livestock and children, and gardens and springs" (26:131-134).

Reflection: a blessing not met with gratitude turns into a trial. Strength that should have led to thankfulness becomes, when paired with arrogance, a road to ruin.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  (SELECT id FROM ayah WHERE surah_id = 7 AND number = 69), NULL, datetime('now');

INSERT OR IGNORE INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Episode 4: Keteguhan Hud dan Tawakal kepada Allah', 'kisah-hud-04-keteguhan-dan-tawakal', 'id', 'kisah-hud', 4, 1, 'Kaum ''Ad tetap keras menolak. Mereka berkata, "Wahai Hud! Engkau tidak mendatangkan suatu bukti yang nyata kepada kami, dan kami tidak akan meninggalkan sesembahan kami karena perkataanmu, dan kami tidak akan mempercayaimu. Kami hanya mengatakan bahwa sebagian sesembahan kami telah menimpakan penyakit gila atas dirimu" (QS. Hud: 53-54).

Menghadapi tuduhan sekeras itu, Hud menjawab dengan tawakal yang menggetarkan. Ia berkata, "Sesungguhnya aku bersaksi kepada Allah dan saksikanlah bahwa aku berlepas diri dari apa yang kamu persekutukan selain Dia. Maka jalankanlah tipu daya kamu semua terhadapku dan jangan kamu tunda-tunda lagi" (QS. Hud: 54-55).

Lalu ia menyandarkan seluruh urusannya kepada Allah, "Sesungguhnya aku bertawakal kepada Allah, Tuhanku dan Tuhanmu. Tidak ada satu makhluk melata pun melainkan Dialah yang memegang ubun-ubunnya (menguasainya). Sungguh, Tuhanku di jalan yang lurus" (QS. Hud: 56).

Hikmah: seorang yang benar-benar bertawakal tidak takut kepada ancaman, karena ia tahu tidak ada satu makhluk pun yang lepas dari genggaman Allah. Keberanian Hud bukan lahir dari kekuatan dirinya, melainkan dari keyakinannya kepada kekuasaan Tuhannya.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  (SELECT id FROM ayah WHERE surah_id = 11 AND number = 53), NULL, datetime('now');
INSERT OR IGNORE INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Episode 4: Hud''s Steadfastness and Reliance on Allah', 'kisah-hud-04-keteguhan-dan-tawakal', 'en', 'kisah-hud', 4, 1, 'The people of ''Ad remained firm in refusal. They said, "O Hud, you have not brought us clear evidence, and we will not leave our gods on your word, and we are not believers in you. We only say that some of our gods have afflicted you with evil (madness)" (Qur''an 11:53-54).

Facing so harsh an accusation, Hud answered with a stirring reliance on Allah. He said, "Indeed, I call Allah to witness, and bear you witness, that I am free from whatever you associate with Allah besides Him. So plot against me all together, then give me no respite" (11:54-55).

Then he entrusted his entire affair to Allah, "Indeed, I have relied upon Allah, my Lord and your Lord. There is no creature but that He holds it by its forelock (has full power over it). Indeed, my Lord is upon a straight path" (11:56).

Reflection: one who truly relies upon Allah does not fear threats, for he knows that not a single creature escapes Allah''s grasp. Hud''s courage was born not of his own strength, but of his certainty in the power of his Lord.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  (SELECT id FROM ayah WHERE surah_id = 11 AND number = 53), NULL, datetime('now');

INSERT OR IGNORE INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Episode 5: Azab Angin yang Membinasakan', 'kisah-hud-05-azab-angin-yang-membinasakan', 'id', 'kisah-hud', 5, 1, 'Karena kesombongan mereka tidak juga surut, datanglah ketetapan Allah. Mulanya kaum ''Ad menyangka azab itu adalah awan pembawa hujan yang mereka nanti-nantikan. Allah berfirman, "Maka ketika mereka melihat azab itu berupa awan yang menuju ke lembah-lembah mereka, mereka berkata, ‘Inilah awan yang akan menurunkan hujan kepada kami.’ (Bukan!) Tetapi itulah azab yang kamu minta agar disegerakan, yaitu angin yang mengandung azab yang pedih, yang menghancurkan segala sesuatu dengan perintah Tuhannya" (QS. Al-Ahqaf: 24-25).

Angin itu bukan angin biasa. Allah berfirman, "Adapun kaum ''Ad, mereka telah dibinasakan dengan angin yang sangat dingin lagi kencang, yang Allah timpakan kepada mereka selama tujuh malam dan delapan hari terus-menerus; maka kamu melihat kaum ''Ad pada waktu itu bergelimpangan seakan-akan mereka tunggul-tunggul pohon kurma yang telah kosong (lapuk). Maka adakah kamu melihat seorang pun yang masih tersisa di antara mereka?" (QS. Al-Haqqah: 6-8).

Dalam Surah Al-Qamar, kedahsyatannya dilukiskan, "Sesungguhnya Kami telah menghembuskan kepada mereka angin yang sangat kencang pada hari nahas yang terus-menerus, yang menggulung manusia seakan-akan mereka pokok-pokok kurma yang tumbang" (QS. Al-Qamar: 19-20).

Hikmah: azab Allah datang dengan cara yang paling tak disangka — bahkan lewat sesuatu yang semula dikira rahmat. Kekuatan tubuh ''Ad yang mereka banggakan tidak berdaya sedikit pun di hadapan satu perintah Tuhan.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  (SELECT id FROM ayah WHERE surah_id = 69 AND number = 6), NULL, datetime('now');
INSERT OR IGNORE INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Episode 5: The Wind That Destroyed', 'kisah-hud-05-azab-angin-yang-membinasakan', 'en', 'kisah-hud', 5, 1, 'Because their arrogance would not subside, the decree of Allah came. At first the people of ''Ad thought the punishment was the rain cloud they had been awaiting. Allah said, "Then when they saw it as a cloud approaching their valleys, they said, ''This is a cloud bringing us rain!'' Rather, it is that for which you were impatient: a wind, within it a painful punishment, destroying everything by the command of its Lord" (Qur''an 46:24-25).

That wind was no ordinary wind. Allah said, "And as for ''Ad, they were destroyed by a screaming, violent wind which He imposed upon them for seven nights and eight days in succession, so you would see the people therein fallen as if they were hollow trunks of palm trees. Then do you see of them any remains?" (69:6-8).

In Surah Al-Qamar its severity is portrayed, "Indeed, We sent upon them a screaming wind on a day of continuous misfortune, extracting the people as if they were trunks of palm trees uprooted" (54:19-20).

Reflection: the punishment of Allah arrives in the most unexpected way — even through something first mistaken for mercy. The bodily strength ''Ad so prided themselves on was utterly powerless before a single command of their Lord.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  (SELECT id FROM ayah WHERE surah_id = 69 AND number = 6), NULL, datetime('now');

INSERT OR IGNORE INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Episode 6: Keselamatan Orang Beriman dan Akhir ''Ad', 'kisah-hud-06-keselamatan-orang-beriman', 'id', 'kisah-hud', 6, 1, 'Di tengah kebinasaan yang menyeluruh, Allah tetap menyelamatkan hamba-hamba-Nya yang beriman. Allah berfirman, "Dan ketika keputusan Kami datang, Kami selamatkan Hud dan orang-orang yang beriman bersama dia dengan rahmat Kami. Kami selamatkan (pula) mereka dari azab yang berat" (QS. Hud: 58). Rahmat selalu menyertai keimanan, bahkan pada saat azab menimpa.

Adapun kaum ''Ad yang mendustakan, Allah menutup kisah mereka dengan peringatan keras, "Dan itulah (kisah) kaum ''Ad yang mengingkari tanda-tanda (kekuasaan) Tuhan mereka, dan mendurhakai rasul-rasul-Nya, dan mereka menuruti perintah setiap penguasa yang sewenang-wenang lagi keras kepala" (QS. Hud: 59).

Mereka pun mendapat laknat di dunia dan akhirat. "Ketahuilah, kaum ''Ad itu mengingkari Tuhan mereka. Ingatlah, kebinasaanlah bagi kaum ''Ad, kaum Hud itu" (QS. Hud: 60). Dalam Surah Al-A''raf ditegaskan, "Maka Kami selamatkan Hud beserta orang-orang yang bersamanya dengan rahmat dari Kami, dan Kami tumpas orang-orang yang mendustakan ayat-ayat Kami; dan mereka bukanlah orang-orang yang beriman" (QS. Al-A''raf: 72).

Hikmah: akhir dari setiap kesombongan adalah kehinaan, dan akhir dari setiap keimanan yang sabar adalah keselamatan. Kisah Hud dan ''Ad menegaskan hukum yang tetap: kebenaran akan menang, dan orang yang bertakwa tidak akan pernah dibiarkan Allah sendirian.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  (SELECT id FROM ayah WHERE surah_id = 11 AND number = 58), NULL, datetime('now');
INSERT OR IGNORE INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Episode 6: The Salvation of the Believers and the End of ''Ad', 'kisah-hud-06-keselamatan-orang-beriman', 'en', 'kisah-hud', 6, 1, 'Amid the total destruction, Allah still saved His believing servants. Allah said, "And when Our command came, We saved Hud and those who believed with him, by mercy from Us; and We saved them from a harsh punishment" (Qur''an 11:58). Mercy always accompanies faith, even at the moment punishment strikes.

As for the people of ''Ad who denied, Allah closed their story with a stern warning, "And that was ''Ad, who rejected the signs of their Lord and disobeyed His messengers and followed the order of every obstinate tyrant" (11:59).

So they were followed by a curse in this world and the Hereafter. "Unquestionably, ''Ad denied their Lord; then away with ''Ad, the people of Hud" (11:60). In Surah Al-A''raf it is affirmed, "So We saved him and those with him by mercy from Us. And We eliminated those who denied Our signs, and they were not believers" (7:72).

Reflection: the end of every arrogance is disgrace, and the end of every patient faith is salvation. The story of Hud and ''Ad affirms a constant law: truth will prevail, and the God-conscious will never be left alone by Allah.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  (SELECT id FROM ayah WHERE surah_id = 11 AND number = 58), NULL, datetime('now');

