-- AUTO-GENERATED by scripts/generate-kisah-ishaq-seed.ts — do not edit by hand.
-- Source content: scripts/content/kisah-ishaq.ts (grounded in QS. Al-A'raf, Hud, Asy-Syu'ara, Al-Ahqaf, Al-Haqqah,
-- quran-json CC-BY-4.0). See docs/CONTENT-POLICY.md.
-- Requires quran_seed.sql already applied (resolves related_ayah_id by lookup).
-- No PDFs — read + narrated in-app (TTS), so pdf_ebook_id is NULL.

INSERT OR IGNORE INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Episode 1: Kabar Gembira Kelahiran Ishaq di Usia Senja', 'kisah-ishaq-01-kabar-gembira-di-usia-senja', 'id', 'kisah-ishaq', 1, 1, 'Nabi Ishaq adalah putra Nabi Ibrahim yang kelahirannya sendiri merupakan sebuah mukjizat. Ia lahir ketika Ibrahim dan istrinya telah lanjut usia. Kabar gembira itu dibawa oleh para malaikat yang datang sebagai tamu. Allah berfirman, "Dan para utusan Kami (para malaikat) telah datang kepada Ibrahim dengan membawa kabar gembira... Dan istrinya berdiri (di sampingnya) lalu dia tersenyum. Maka Kami sampaikan kepadanya kabar gembira tentang (kelahiran) Ishaq, dan setelah Ishaq (akan lahir pula) Ya''qub" (QS. Hud: 69-71).

Istri Ibrahim terheran-heran, sebab ia sudah tua. Ia berkata, "Sungguh ajaib, mungkinkah aku akan melahirkan anak padahal aku sudah tua, dan suamiku ini pun sudah sangat tua? Ini benar-benar sesuatu yang sangat aneh" (QS. Hud: 72).

Para malaikat menjawab dengan menegaskan bahwa tidak ada yang mustahil bagi Allah, "Mengapa engkau merasa heran tentang ketetapan Allah? (Itu adalah) rahmat dan berkah Allah, dicurahkan kepada kamu, wahai ahlulbait! Sesungguhnya Allah Maha Terpuji lagi Maha Pengasih" (QS. Hud: 73).

Hikmah: tidak ada yang mustahil bagi Allah. Kelahiran Ishaq dari pasangan yang telah lanjut usia adalah bukti bahwa ketetapan Allah tidak dibatasi oleh hukum sebab-akibat yang biasa dijangkau manusia. Rahmat-Nya datang di waktu dan cara yang Dia kehendaki.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  (SELECT id FROM ayah WHERE surah_id = 11 AND number = 69), NULL, datetime('now');
INSERT OR IGNORE INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Episode 1: Glad Tidings of Ishaq in Old Age', 'kisah-ishaq-01-kabar-gembira-di-usia-senja', 'en', 'kisah-ishaq', 1, 1, 'Prophet Ishaq was the son of Prophet Ibrahim whose very birth was a miracle. He was born when Ibrahim and his wife had grown old. The glad tidings were carried by the angels who came as guests. Allah said, "And certainly did Our messengers (the angels) come to Abraham with good tidings... And his wife was standing, and she smiled. Then We gave her good tidings of Ishaq and, after Ishaq, Ya''qub" (Qur''an 11:69-71).

Ibrahim''s wife was astonished, for she was old. She said, "Woe to me! Shall I give birth while I am an old woman and this, my husband, is an old man? Indeed, this is an amazing thing!" (11:72).

The angels answered, affirming that nothing is impossible for Allah, "Are you amazed at the decree of Allah? May the mercy of Allah and His blessings be upon you, people of the house. Indeed, He is Praiseworthy and Honorable" (11:73).

Reflection: nothing is impossible for Allah. The birth of Ishaq to an aged couple is proof that Allah''s decree is not bound by the ordinary laws of cause and effect that people reach. His mercy comes at the time and in the manner He wills.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  (SELECT id FROM ayah WHERE surah_id = 11 AND number = 69), NULL, datetime('now');

INSERT OR IGNORE INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Episode 2: Ishaq, Nabi yang Diberkahi', 'kisah-ishaq-02-nabi-yang-diberkahi', 'id', 'kisah-ishaq', 2, 1, 'Ishaq tumbuh menjadi seorang nabi, dan Allah menyebutnya sebagai kabar gembira yang membawa keberkahan. Allah berfirman, "Dan Kami beri dia kabar gembira dengan (kelahiran) Ishaq, seorang nabi yang termasuk orang-orang saleh" (QS. As-Saffat: 112).

Keberkahan itu tidak berhenti pada Ishaq, melainkan mengalir kepada keturunannya. Allah berfirman, "Dan Kami limpahkan keberkahan kepadanya (Ibrahim) dan kepada Ishaq. Dan di antara keturunan keduanya ada yang berbuat baik dan ada (pula) yang terang-terangan berbuat zalim terhadap dirinya sendiri" (QS. As-Saffat: 113).

Ayat ini menyimpan pelajaran penting: keberkahan silsilah tidak menjamin setiap keturunan menjadi baik. Setiap orang tetap bertanggung jawab atas pilihannya sendiri — sebagian menjadi orang yang berbuat baik, dan sebagian menzalimi diri dengan kekufuran.

Hikmah: menjadi keturunan orang saleh adalah anugerah, tetapi bukan jaminan keselamatan. Keberkahan sejati harus diraih dengan iman dan amal masing-masing, bukan sekadar diwarisi dari nama besar leluhur.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  (SELECT id FROM ayah WHERE surah_id = 37 AND number = 112), NULL, datetime('now');
INSERT OR IGNORE INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Episode 2: Ishaq, a Blessed Prophet', 'kisah-ishaq-02-nabi-yang-diberkahi', 'en', 'kisah-ishaq', 2, 1, 'Ishaq grew into a prophet, and Allah mentioned him as glad tidings that carried blessing. Allah said, "And We gave him good tidings of Ishaq, a prophet from among the righteous" (Qur''an 37:112).

That blessing did not stop at Ishaq, but flowed to his descendants. Allah said, "And We blessed him and Ishaq. But among their descendants is the doer of good and the clearly unjust to himself" (37:113).

This verse holds an important lesson: the blessing of a lineage does not guarantee that every descendant will be good. Each person remains responsible for his own choices — some become doers of good, and some wrong themselves through disbelief.

Reflection: to be the descendant of the righteous is a gift, but not a guarantee of salvation. True blessing must be attained through each person''s own faith and deeds, not merely inherited from an ancestor''s great name.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  (SELECT id FROM ayah WHERE surah_id = 37 AND number = 112), NULL, datetime('now');

INSERT OR IGNORE INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Episode 3: Hamba Pilihan yang Teguh dan Berpandangan', 'kisah-ishaq-03-hamba-pilihan-yang-teguh', 'id', 'kisah-ishaq', 3, 1, 'Allah menyebut Ishaq bersama ayahnya Ibrahim dan putranya Ya''qub sebagai teladan hamba yang kuat dalam ketaatan dan tajam dalam pandangan agama. Allah berfirman, "Dan ingatlah hamba-hamba Kami: Ibrahim, Ishaq, dan Ya''qub, yang mempunyai kekuatan-kekuatan yang besar dan ilmu-ilmu (yang tinggi)" (QS. Sad: 45).

Allah lalu menyebutkan keistimewaan yang menjadikan mereka pilihan, "Sungguh, Kami telah menyucikan mereka dengan (menganugerahkan kepada mereka) akhlak yang tinggi, yaitu selalu mengingat negeri akhirat" (QS. Sad: 46). Inilah rahasia keteguhan mereka: hati yang selalu terpaut pada kehidupan akhirat, bukan pada gemerlap dunia.

Maka Allah menutup pujian itu, "Dan sesungguhnya di sisi Kami mereka termasuk orang-orang pilihan yang terbaik" (QS. Sad: 47).

Hikmah: kekuatan sejati bukan pada tubuh atau harta, melainkan pada keteguhan iman dan kejernihan pandangan tentang akhirat. Orang yang selalu mengingat negeri akhirat akan terjaga dari tipu daya dunia, dan itulah yang menjadikan Ishaq dan para nabi sebagai hamba-hamba pilihan Allah.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  (SELECT id FROM ayah WHERE surah_id = 38 AND number = 45), NULL, datetime('now');
INSERT OR IGNORE INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Episode 3: A Chosen Servant of Strength and Vision', 'kisah-ishaq-03-hamba-pilihan-yang-teguh', 'en', 'kisah-ishaq', 3, 1, 'Allah mentioned Ishaq together with his father Ibrahim and his son Ya''qub as examples of servants strong in obedience and sharp in religious insight. Allah said, "And remember Our servants, Ibrahim, Ishaq and Ya''qub — those of strength and [religious] vision" (Qur''an 38:45).

Allah then mentioned the special quality that made them chosen, "Indeed, We chose them for an exclusive quality: remembrance of the home [of the Hereafter]" (38:46). This was the secret of their steadfastness: hearts always attached to the life to come, not to the glitter of this world.

So Allah closed that praise, "And indeed they are, to Us, among the chosen and outstanding" (38:47).

Reflection: true strength is not in body or wealth, but in firmness of faith and clarity of vision about the Hereafter. One who always remembers the home of the Hereafter is guarded from the deception of this world — and that is what made Ishaq and the prophets among Allah''s chosen servants.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  (SELECT id FROM ayah WHERE surah_id = 38 AND number = 45), NULL, datetime('now');

INSERT OR IGNORE INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Episode 4: Ishaq, Mata Rantai Silsilah Tauhid', 'kisah-ishaq-04-mata-rantai-tauhid', 'id', 'kisah-ishaq', 4, 1, 'Kehadiran Ishaq menjadi bagian dari silsilah kenabian yang menjaga ajaran tauhid dari generasi ke generasi. Allah berfirman, "Maka ketika dia (Ibrahim) telah menjauhkan diri dari mereka dan dari apa yang mereka sembah selain Allah, Kami anugerahkan kepadanya Ishaq dan Ya''qub. Dan masing-masing Kami angkat menjadi nabi" (QS. Maryam: 49).

Ishaq disebut pula dalam wasiat tauhid yang diwariskan turun-temurun. Ketika Ya''qub hendak wafat, anak-anaknya berikrar, "Kami akan menyembah Tuhanmu dan Tuhan nenek moyangmu, yaitu Ibrahim, Isma''il, dan Ishaq, (yaitu) Tuhan Yang Maha Esa dan kami (hanya) berserah diri kepada-Nya" (QS. Al-Baqarah: 133).

Allah pun menegaskan bahwa Ishaq termasuk para nabi yang diberi petunjuk, "Dan Kami telah menganugerahkan Ishaq dan Ya''qub kepadanya. Kepada masing-masing telah Kami beri petunjuk; dan sebelum itu Kami telah memberi petunjuk kepada Nuh" (QS. Al-An''am: 84).

Hikmah: tauhid adalah warisan paling berharga yang diwariskan para nabi. Ishaq bukan sekadar penerus keturunan Ibrahim, melainkan penjaga ajaran mengesakan Allah — sebuah mata rantai yang menyambungkan generasi demi generasi dalam iman yang satu.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  (SELECT id FROM ayah WHERE surah_id = 19 AND number = 49), NULL, datetime('now');
INSERT OR IGNORE INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Episode 4: Ishaq, a Link in the Chain of Tawhid', 'kisah-ishaq-04-mata-rantai-tauhid', 'en', 'kisah-ishaq', 4, 1, 'Ishaq''s presence became part of the prophetic line that preserved the teaching of tawhid from generation to generation. Allah said, "So when he (Ibrahim) had left them and those they worshipped other than Allah, We gave him Ishaq and Ya''qub, and each [of them] We made a prophet" (Qur''an 19:49).

Ishaq is also mentioned in the testament of tawhid handed down through the generations. When Ya''qub was about to die, his sons pledged, "We will worship your God and the God of your fathers, Ibrahim, Isma''il and Ishaq — one God. And we are Muslims [in submission] to Him" (2:133).

Allah affirmed that Ishaq was among the guided prophets, "And We gave to him Ishaq and Ya''qub — all [of them] We guided. And Noah, We guided before" (6:84).

Reflection: tawhid is the most precious inheritance the prophets passed on. Ishaq was not merely a continuation of Ibrahim''s line, but a guardian of the teaching of Allah''s oneness — a link joining generation to generation in one single faith.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  (SELECT id FROM ayah WHERE surah_id = 19 AND number = 49), NULL, datetime('now');

