-- AUTO-GENERATED by scripts/generate-kisah-sulaiman-seed.ts — do not edit by hand.
-- Source content: scripts/content/kisah-sulaiman.ts (grounded in QS. An-Naml 27:15-44,
-- quran-json CC-BY-4.0). See docs/CONTENT-POLICY.md.
-- Requires quran_seed.sql already applied (resolves related_ayah_id by lookup).
-- No PDFs — read + narrated in-app (TTS), so pdf_ebook_id is NULL.

INSERT INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Episode 1: Ilmu dan Warisan Kenabian', 'kisah-sulaiman-01-ilmu-dan-warisan', 'id', 'kisah-sulaiman', 1, 1, 'Allah menceritakan bahwa Dia telah memberikan ilmu kepada Dawud dan Sulaiman AS, dan keduanya berkata, "Segala puji bagi Allah yang telah melebihkan kami atas kebanyakan hamba-hamba-Nya yang beriman" (QS. An-Naml: 15). Perhatikanlah, tanggapan pertama dua nabi atas anugerah ilmu bukanlah kesombongan, melainkan syukur.

Kemudian Sulaiman mewarisi (kenabian dan kerajaan) Dawud. Ia berkata, "Wahai manusia, kami telah diberi pengertian tentang suara burung, dan kami dianugerahi segala sesuatu. Sungguh, ini benar-benar suatu karunia yang nyata" (QS. An-Naml: 16).

Sulaiman menyebut nikmat itu bukan untuk membanggakan diri, melainkan sebagai pengakuan terbuka bahwa segala kelebihannya adalah pemberian Allah semata.

Hikmah: ilmu dan kekuasaan adalah ujian sekaligus amanah. Yang membedakan hamba yang mulia adalah kesyukurannya, bukan sekadar besarnya karunia yang ia terima.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  (SELECT id FROM ayah WHERE surah_id = 27 AND number = 15), NULL, datetime('now');
INSERT INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Episode 1: Knowledge and a Prophetic Inheritance', 'kisah-sulaiman-01-ilmu-dan-warisan', 'en', 'kisah-sulaiman', 1, 1, 'Allah relates that He gave knowledge to Dawud (David) and Sulaiman (Solomon), and both said, "Praise be to Allah, who has favored us over many of His believing servants" (Qur''an 27:15). Notice: the first response of two prophets to the gift of knowledge was not pride, but gratitude.

Then Sulaiman inherited [prophethood and kingship] from Dawud. He said, "O people, we have been taught the language of birds, and we have been given of all things. Indeed, this is a clear favor" (27:16).

Sulaiman named this blessing not to boast, but as an open acknowledgment that every advantage he held was purely a gift from Allah.

Reflection: knowledge and power are at once a test and a trust. What sets a noble servant apart is gratitude, not merely the size of the favor received.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  (SELECT id FROM ayah WHERE surah_id = 27 AND number = 15), NULL, datetime('now');

INSERT INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Episode 2: Lembah Para Semut', 'kisah-sulaiman-02-lembah-semut', 'id', 'kisah-sulaiman', 2, 1, 'Dan dihimpunkanlah untuk Sulaiman bala tentaranya dari kalangan jin, manusia, dan burung, lalu mereka diatur dengan tertib dalam barisan (QS. An-Naml: 17). Sebuah pasukan yang menggambarkan betapa luas kekuasaan yang Allah berikan kepadanya.

Hingga ketika mereka sampai di lembah semut, seekor semut berkata, "Wahai para semut, masuklah ke dalam sarang-sarangmu, agar kamu tidak diinjak oleh Sulaiman dan bala tentaranya, sedangkan mereka tidak menyadarinya" (QS. An-Naml: 18). Perhatikan keadilan dalam ucapan semut itu: ia menegaskan bahwa Sulaiman dan pasukannya "tidak menyadari" — tidak menuduh mereka sengaja berbuat zalim.

Maka Sulaiman tersenyum, tertawa karena mendengar perkataan semut itu, lalu ia berdoa, "Ya Tuhanku, anugerahkanlah aku ilham untuk tetap mensyukuri nikmat-Mu yang telah Engkau anugerahkan kepadaku dan kepada kedua orang tuaku, dan agar aku mengerjakan amal saleh yang Engkau ridhai; dan masukkanlah aku dengan rahmat-Mu ke dalam golongan hamba-hamba-Mu yang saleh" (QS. An-Naml: 19).

Hikmah: puncak kekuasaan Sulaiman justru mengembalikannya kepada kerendahan hati — ia meminta agar dijadikan hamba yang bersyukur dan saleh, bukan agar ditambah kekuasaannya.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  (SELECT id FROM ayah WHERE surah_id = 27 AND number = 17), NULL, datetime('now');
INSERT INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Episode 2: The Valley of the Ants', 'kisah-sulaiman-02-lembah-semut', 'en', 'kisah-sulaiman', 2, 1, 'Gathered for Sulaiman were his hosts of jinn, men, and birds, and they were marshaled in ordered ranks (27:17) — an army that shows how vast a dominion Allah had granted him.

Until, when they reached the valley of the ants, an ant said, "O ants, enter your dwellings so that Sulaiman and his hosts do not crush you while they are unaware" (27:18). Note the fairness in the ant''s words: it stressed that Sulaiman and his army were "unaware" — it did not accuse them of deliberate wrong.

So Sulaiman smiled, amused at its words, and prayed, "My Lord, inspire me to be grateful for Your favor which You have bestowed upon me and upon my parents, and to do righteous deeds that please You; and admit me, by Your mercy, among Your righteous servants" (27:19).

Reflection: the height of Sulaiman''s power returned him to humility — he asked to be made a grateful, righteous servant, not to be given still more power.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  (SELECT id FROM ayah WHERE surah_id = 27 AND number = 17), NULL, datetime('now');

INSERT INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Episode 3: Burung Hud-hud dan Kabar dari Saba''', 'kisah-sulaiman-03-hudhud-dan-saba', 'id', 'kisah-sulaiman', 3, 1, 'Suatu ketika Sulaiman memeriksa barisan burung, lalu ia berkata, "Mengapa aku tidak melihat Hud-hud? Apakah ia termasuk yang tidak hadir? Sungguh, aku benar-benar akan mengazabnya dengan azab yang keras, atau menyembelihnya, kecuali jika ia datang kepadaku dengan alasan yang jelas" (QS. An-Naml: 20-21).

Tidak lama kemudian datanglah Hud-hud, dan ia berkata, "Aku telah mengetahui sesuatu yang belum engkau ketahui. Aku datang kepadamu dari negeri Saba'' dengan membawa berita yang meyakinkan" (QS. An-Naml: 22). Hud-hud mengabarkan bahwa di sana ada seorang perempuan yang memerintah, yang dianugerahi segala sesuatu, dan memiliki singgasana yang besar (QS. An-Naml: 23).

Namun, kata Hud-hud, "Aku mendapati dia dan kaumnya menyembah matahari, bukan menyembah Allah; dan setan telah menjadikan terasa indah bagi mereka perbuatan-perbuatan mereka, lalu menghalangi mereka dari jalan Allah, sehingga mereka tidak mendapat petunjuk — agar mereka tidak menyembah Allah, Yang mengeluarkan apa yang tersembunyi di langit dan di bumi... Allah, tidak ada tuhan selain Dia, Tuhan pemilik ‘Arsy yang agung" (QS. An-Naml: 24-26).

Hikmah: seekor burung kecil pun bisa menjadi pembawa kebenaran. Yang paling menggusarkan Hud-hud bukanlah kekayaan negeri Saba'', melainkan bahwa mereka menyembah selain Allah.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  (SELECT id FROM ayah WHERE surah_id = 27 AND number = 20), NULL, datetime('now');
INSERT INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Episode 3: The Hoopoe and the News of Sheba', 'kisah-sulaiman-03-hudhud-dan-saba', 'en', 'kisah-sulaiman', 3, 1, 'One day Sulaiman inspected the ranks of birds and said, "Why do I not see the hoopoe? Or is it among the absent? I will surely punish it with a severe punishment, or slaughter it, unless it brings me a clear reason" (27:20-21).

Before long the hoopoe came and said, "I have grasped what you have not grasped, and I have come to you from Sheba with certain news" (27:22). The hoopoe reported that there a woman ruled, given of all things, with a magnificent throne (27:23).

But, said the hoopoe, "I found her and her people prostrating to the sun instead of Allah; and Satan has made their deeds pleasing to them and barred them from the path, so they are not guided — [prevented] from prostrating to Allah, who brings forth what is hidden in the heavens and the earth... Allah, there is no deity except Him, Lord of the Great Throne" (27:24-26).

Reflection: even a small bird can carry the truth. What most troubled the hoopoe was not Sheba''s wealth, but that its people worshipped other than Allah.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  (SELECT id FROM ayah WHERE surah_id = 27 AND number = 20), NULL, datetime('now');

INSERT INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Episode 4: Surat untuk Sang Ratu', 'kisah-sulaiman-04-surat-untuk-ratu', 'id', 'kisah-sulaiman', 4, 1, 'Sulaiman berkata, "Akan kami lihat, apakah engkau benar, atau termasuk yang berdusta. Pergilah dengan membawa suratku ini, lalu jatuhkanlah kepada mereka, kemudian berpalinglah dari mereka, lalu perhatikanlah apa yang mereka bicarakan" (QS. An-Naml: 27-28). Sulaiman tidak langsung menghukum atau menyerang; ia lebih dahulu mencari kebenaran dan menyampaikan dakwah.

Sang Ratu lalu berkata kepada para pembesarnya, "Wahai para pembesar, sungguh telah disampaikan kepadaku sebuah surat yang mulia. Sesungguhnya surat itu dari Sulaiman, dan sesungguhnya isinya: Dengan nama Allah Yang Maha Pengasih lagi Maha Penyayang" (QS. An-Naml: 29-30).

Isi surat itu, "Janganlah kamu berlaku sombong terhadapku dan datanglah kepadaku sebagai orang-orang yang berserah diri" (QS. An-Naml: 31). Sebuah seruan tauhid yang singkat, tegas, namun penuh kelembutan — diawali dengan menyebut nama Allah Yang Maha Pengasih.

Hikmah: Sulaiman mengutamakan penyampaian kebenaran sebelum kekuatan. Suratnya mengajarkan bahwa dakwah yang benar dibuka dengan nama Allah dan mengajak, bukan memaksa dengan ancaman terlebih dahulu.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  (SELECT id FROM ayah WHERE surah_id = 27 AND number = 27), NULL, datetime('now');
INSERT INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Episode 4: A Letter to the Queen', 'kisah-sulaiman-04-surat-untuk-ratu', 'en', 'kisah-sulaiman', 4, 1, 'Sulaiman said, "We will see whether you told the truth or were among the liars. Go with this letter of mine and deliver it to them, then withdraw from them and see what they say in return" (27:27-28). Sulaiman did not rush to punish or attack; first he sought the truth and conveyed the call.

The Queen then said to her nobles, "O chiefs, indeed a noble letter has been delivered to me. It is from Sulaiman, and it reads: In the name of Allah, the Most Merciful, the Most Compassionate" (27:29-30).

The letter said, "Do not be arrogant with me, but come to me in submission [to Allah]" (27:31). A call to the oneness of Allah — brief, firm, yet gentle — opening with the name of Allah the Most Merciful.

Reflection: Sulaiman put the conveying of truth before the use of force. His letter teaches that a sound call begins with the name of Allah and an invitation, not with threats.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  (SELECT id FROM ayah WHERE surah_id = 27 AND number = 27), NULL, datetime('now');

INSERT INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Episode 5: Musyawarah Ratu dan Ujian Hadiah', 'kisah-sulaiman-05-musyawarah-dan-hadiah', 'id', 'kisah-sulaiman', 5, 1, 'Sang Ratu berkata, "Wahai para pembesar, berilah aku pertimbangan dalam urusanku ini. Aku tidak pernah memutuskan suatu persoalan sebelum kamu hadir memberikan pendapat" (QS. An-Naml: 32). Ia seorang pemimpin yang bijak, yang tidak memutuskan perkara besar seorang diri.

Para pembesar menjawab, "Kita memiliki kekuatan dan keberanian yang hebat (untuk berperang), tetapi keputusan berada di tanganmu; maka pertimbangkanlah apa yang akan engkau perintahkan" (QS. An-Naml: 33). Sang Ratu justru memilih jalan yang lebih bijaksana. Ia berkata, "Sesungguhnya raja-raja apabila memasuki suatu negeri, mereka membinasakannya, dan menjadikan penduduknya yang mulia menjadi hina; demikianlah yang akan mereka perbuat" (QS. An-Naml: 34).

"Dan sungguh aku akan mengirim utusan kepada mereka dengan membawa hadiah, lalu aku akan menunggu apa yang akan dibawa kembali oleh para utusan itu" (QS. An-Naml: 35). Namun ketika hadiah itu sampai kepada Sulaiman, ia berkata, "Apakah kamu hendak menolongku dengan harta? Padahal apa yang Allah berikan kepadaku lebih baik daripada apa yang Allah berikan kepadamu; tetapi kamulah yang merasa bangga dengan hadiahmu" (QS. An-Naml: 36-37).

Hikmah: Ratu Saba'' menghindari peperangan dengan diplomasi, sebuah tanda kebijaksanaan. Dan Sulaiman menolak hadiah itu untuk menegaskan bahwa tujuannya bukan harta, melainkan agar mereka beriman kepada Allah.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  (SELECT id FROM ayah WHERE surah_id = 27 AND number = 32), NULL, datetime('now');
INSERT INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Episode 5: The Queen''s Council and the Test of a Gift', 'kisah-sulaiman-05-musyawarah-dan-hadiah', 'en', 'kisah-sulaiman', 5, 1, 'The Queen said, "O chiefs, advise me in my affair; I never decide a matter until you are present to counsel me" (27:32). She was a wise ruler who did not settle grave matters alone.

The nobles answered, "We possess strength and great might [for war], but the command is yours; so consider what you will order" (27:33). Yet the Queen chose the wiser path. She said, "Indeed kings, when they enter a town, ruin it and humble its noblest people; that is how they behave" (27:34).

"And I will send them a gift and see with what the envoys return" (27:35). But when the gift reached Sulaiman, he said, "Do you seek to aid me with wealth? What Allah has given me is better than what He has given you; rather, it is you who rejoice in your gift" (27:36-37).

Reflection: the Queen of Sheba avoided war through diplomacy — a mark of wisdom. And Sulaiman refused the gift to make clear that his aim was not wealth, but that they believe in Allah.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  (SELECT id FROM ayah WHERE surah_id = 27 AND number = 32), NULL, datetime('now');

INSERT INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Episode 6: Singgasana yang Dipindah dalam Sekejap', 'kisah-sulaiman-06-singgasana-sekejap', 'id', 'kisah-sulaiman', 6, 1, 'Sulaiman berkata, "Wahai para pembesar, siapakah di antara kamu yang sanggup membawa singgasananya kepadaku sebelum mereka datang kepadaku menyerahkan diri?" (QS. An-Naml: 38). Sebuah jin ifrit berkata, "Aku akan membawanya kepadamu sebelum engkau berdiri dari tempat dudukmu; sungguh aku benar-benar kuat dan dapat dipercaya untuk itu" (QS. An-Naml: 39).

Namun seorang yang mempunyai ilmu dari Kitab berkata, "Aku akan membawa singgasana itu kepadamu sebelum matamu berkedip." Maka ketika Sulaiman melihat singgasana itu telah ada di hadapannya, ia berkata, "Ini adalah sebagian dari karunia Tuhanku, untuk mengujiku apakah aku bersyukur atau kufur (mengingkari nikmat)" (QS. An-Naml: 40).

Ia melanjutkan, "Barangsiapa bersyukur, maka sesungguhnya ia bersyukur untuk kebaikan dirinya sendiri; dan barangsiapa kufur, maka sesungguhnya Tuhanku Maha Kaya lagi Maha Mulia" (QS. An-Naml: 40).

Hikmah: mukjizat sebesar apa pun, oleh Sulaiman, dibaca sebagai ujian — bukan alat kesombongan. Ia langsung bertanya pada dirinya sendiri: apakah aku bersyukur atau kufur?', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  (SELECT id FROM ayah WHERE surah_id = 27 AND number = 38), NULL, datetime('now');
INSERT INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Episode 6: The Throne Brought in the Blink of an Eye', 'kisah-sulaiman-06-singgasana-sekejap', 'en', 'kisah-sulaiman', 6, 1, 'Sulaiman said, "O chiefs, which of you can bring me her throne before they come to me in submission?" (27:38). An ifrit of the jinn said, "I will bring it to you before you rise from your place; indeed I am strong and trustworthy for it" (27:39).

But one who had knowledge of the Scripture said, "I will bring it to you before your glance returns to you." So when Sulaiman saw the throne set before him, he said, "This is from the favor of my Lord, to test me whether I am grateful or ungrateful" (27:40).

He continued, "Whoever is grateful, his gratitude is only for [the good of] himself; and whoever is ungrateful — then indeed my Lord is Free of need and Generous" (27:40).

Reflection: however great the miracle, Sulaiman read it as a test — never as a means of pride. He immediately asked himself: am I grateful, or ungrateful?', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  (SELECT id FROM ayah WHERE surah_id = 27 AND number = 38), NULL, datetime('now');

INSERT INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Episode 7: Istana Kaca dan Keislaman Sang Ratu', 'kisah-sulaiman-07-istana-kaca', 'id', 'kisah-sulaiman', 7, 1, 'Sulaiman berkata, "Ubahlah untuknya singgasananya, kita akan melihat apakah ia mengenalinya atau termasuk orang yang tidak mengenalinya" (QS. An-Naml: 41). Maka ketika Ratu Saba'' datang, ditanyakan kepadanya, "Serupa inikah singgasanamu?" Ia menjawab dengan cerdas, "Seakan-akan itulah dia." Dan (Sulaiman berkata), "Kami telah diberi ilmu sebelumnya, dan kami adalah orang-orang yang berserah diri" (QS. An-Naml: 42).

Apa yang selama ini disembahnya selain Allah telah mencegahnya (dari beriman); sungguh ia dahulu termasuk kaum yang kafir (QS. An-Naml: 43). Lalu dikatakan kepadanya, "Masuklah ke dalam istana." Ketika ia melihat lantai istana itu, ia mengiranya kolam air yang besar, dan ia menyingkapkan (pakaian menutupi) kedua betisnya. Sulaiman berkata, "Sesungguhnya itu adalah istana licin yang terbuat dari kaca" (QS. An-Naml: 44).

Pada saat itulah kebenaran menjadi jelas baginya. Ia berkata, "Ya Tuhanku, sesungguhnya aku telah menzalimi diriku sendiri, dan aku berserah diri bersama Sulaiman kepada Allah, Tuhan seluruh alam" (QS. An-Naml: 44).

Hikmah: kisah ini berakhir bukan dengan penaklukan negeri, melainkan dengan hidayah satu jiwa. Tujuan seluruh perjalanan Sulaiman adalah agar Ratu Saba'' mengenal dan berserah diri kepada Allah, Tuhan semesta alam.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  (SELECT id FROM ayah WHERE surah_id = 27 AND number = 41), NULL, datetime('now');
INSERT INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Episode 7: The Glass Palace and the Queen''s Submission', 'kisah-sulaiman-07-istana-kaca', 'en', 'kisah-sulaiman', 7, 1, 'Sulaiman said, "Disguise her throne for her; we will see whether she recognizes it or is among those who do not" (27:41). So when the Queen of Sheba came, she was asked, "Is your throne like this?" She answered shrewdly, "It is as though it were the very one." And [Sulaiman said], "We were given knowledge before her, and we have been in submission [to Allah]" (27:42).

What she used to worship besides Allah had held her back; indeed she had been among a disbelieving people (27:43). Then it was said to her, "Enter the palace." When she saw its floor, she supposed it a pool of water and uncovered her shins. Sulaiman said, "It is a palace [floored] smooth with glass" (27:44).

At that moment the truth became clear to her. She said, "My Lord, indeed I have wronged myself, and I submit with Sulaiman to Allah, Lord of the worlds" (27:44).

Reflection: the story ends not with the conquest of a land, but with the guidance of a single soul. The aim of Sulaiman''s whole endeavor was that the Queen of Sheba come to know and submit to Allah, Lord of all the worlds.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  (SELECT id FROM ayah WHERE surah_id = 27 AND number = 41), NULL, datetime('now');

