-- AUTO-GENERATED by scripts/generate-kisah-ashabul-fil-seed.ts — do not edit by hand.
-- Source content: scripts/content/kisah-ashabul-fil.ts (grounded in QS. Al-Fil
-- 105:1-5, quran-json CC-BY-4.0). See docs/CONTENT-POLICY.md.
-- Requires quran_seed.sql already applied (resolves related_ayah_id by lookup).

INSERT OR IGNORE INTO categories (id, name, slug, parent_id, auto_created) VALUES (5, 'Kisah Islami', 'kisah-islami', NULL, 0);

INSERT INTO ebooks (id, title, author, r2_key, category_id, license_status, license_note) VALUES (700, 'Episode 1: Pasukan Bergajah Hendak Menghancurkan Ka''bah', 'Tim Editorial ULYAH', 'ebooks/kisah-ashabul-fil/id/kisah-ashabul-fil-01-pasukan-bergajah.pdf', 5, 'original', 'Ditulis berdasarkan QS. Al-Fil 1-2 (quran-json, CC-BY-4.0). Tidak ada kutipan pihak ketiga berhak cipta.');
INSERT INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Episode 1: Pasukan Bergajah Hendak Menghancurkan Ka''bah', 'kisah-ashabul-fil-01-pasukan-bergajah', 'id', 'kisah-ashabul-fil', 1, 5, 'Al-Qur''an mengingatkan sebuah peristiwa besar yang terjadi menjelang kelahiran Nabi Muhammad ﷺ, yang dikenal sebagai Tahun Gajah. Sebuah pasukan besar datang dengan gajah untuk menghancurkan Ka''bah, rumah Allah di Makkah. Namun Allah menggagalkan seluruh rencana mereka. Allah berfirman, "Tidakkah engkau (Muhammad) perhatikan bagaimana Tuhanmu telah bertindak terhadap pasukan bergajah? Bukankah Dia telah menjadikan tipu daya mereka itu sia-sia?" (QS. Al-Fil: 1-2).

Ayat ini mengajak kita merenungkan kekuasaan Allah. Pasukan itu datang dengan kekuatan yang tampak tak terkalahkan — dilengkapi gajah yang belum pernah dikenal bangsa Arab dalam peperangan. Secara logika manusia, tidak ada yang mampu menghadang mereka. Namun di hadapan kehendak Allah, seluruh kekuatan itu menjadi "sia-sia" (tadlil) — hilang dan tak berarti.

Allah menyebut rencana mereka sebagai "kaid" (tipu daya) yang Dia gagalkan. Ini menegaskan bahwa siapa pun yang berniat jahat terhadap rumah Allah dan agama-Nya, Allah sendiri yang akan menghadapinya, betapapun besar kekuatannya.

Hikmah: tidak ada kekuatan yang mampu menandingi kehendak Allah. Ketika manusia merasa paling perkasa, Allah bisa menjadikan seluruh kekuatan itu tak berdaya dalam sekejap. Perlindungan atas rumah-Nya adalah bukti bahwa Dia Maha Kuasa atas segala sesuatu.

Sumber & Catatan: dalil dari Al-Qur''an, QS. Al-Fil: 1-2 (teks & terjemahan quran-json). Rincian bahwa pasukan itu dipimpin Abrahah, gubernur dari Yaman, yang membawa gajah bernama Mahmud yang enggan melangkah menuju Ka''bah, bersumber dari sirah dan tafsir yang masyhur (mis. Sirah Ibnu Hisyam); disampaikan sebagai catatan sejarah, bukan bagian dari nas ayat.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  (SELECT id FROM ayah WHERE surah_id = 105 AND number = 1), 700, datetime('now');
INSERT INTO ebooks (id, title, author, r2_key, category_id, license_status, license_note) VALUES (701, 'Episode 1: The Army of the Elephant Marches on the Ka''bah', 'Tim Editorial ULYAH', 'ebooks/kisah-ashabul-fil/en/kisah-ashabul-fil-01-pasukan-bergajah.pdf', 5, 'original', 'Ditulis berdasarkan QS. Al-Fil 1-2 (quran-json, CC-BY-4.0). Tidak ada kutipan pihak ketiga berhak cipta.');
INSERT INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Episode 1: The Army of the Elephant Marches on the Ka''bah', 'kisah-ashabul-fil-01-pasukan-bergajah', 'en', 'kisah-ashabul-fil', 1, 5, 'The Qur''an recalls a great event that took place just before the birth of Prophet Muhammad ﷺ, known as the Year of the Elephant. A large army came with an elephant to destroy the Ka''bah, the House of Allah in Makkah. But Allah brought all their plans to nothing. Allah said, "Have you not considered, [O Muhammad], how your Lord dealt with the companions of the elephant? Did He not make their plan into misguidance?" (Qur''an 105:1-2).

This verse invites us to reflect on the power of Allah. That army came with strength that seemed invincible — equipped with an elephant the Arabs had never known in war. By human logic, nothing could stop them. Yet before the will of Allah, all that power became "misguidance" (tadlil) — lost and worthless.

Allah calls their plan "kaid" (a scheme) that He frustrated. This affirms that whoever intends evil against the House of Allah and His religion, Allah Himself will confront him, however great his power.

Reflection: no power can match the will of Allah. When people feel mightiest, Allah can render all that power helpless in an instant. His protection of His House is proof that He is All-Powerful over all things.

Source & Note: evidence from the Qur''an, 105:1-2 (text & translation from quran-json). The details that the army was led by Abrahah, a governor from Yemen, who brought an elephant named Mahmud that refused to advance toward the Ka''bah, come from the well-known sirah and tafsir (e.g. Sirat Ibn Hisham); related as history, not as part of the text of the ayat.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  (SELECT id FROM ayah WHERE surah_id = 105 AND number = 1), 701, datetime('now');

INSERT INTO ebooks (id, title, author, r2_key, category_id, license_status, license_note) VALUES (702, 'Episode 2: Burung Ababil dan Kehancuran Pasukan Gajah', 'Tim Editorial ULYAH', 'ebooks/kisah-ashabul-fil/id/kisah-ashabul-fil-02-burung-ababil.pdf', 5, 'original', 'Ditulis berdasarkan QS. Al-Fil 3-5 (quran-json, CC-BY-4.0). Tidak ada kutipan pihak ketiga berhak cipta.');
INSERT INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Episode 2: Burung Ababil dan Kehancuran Pasukan Gajah', 'kisah-ashabul-fil-02-burung-ababil', 'id', 'kisah-ashabul-fil', 2, 5, 'Cara Allah menghancurkan pasukan yang perkasa itu sungguh menakjubkan: bukan dengan tentara besar, melainkan dengan makhluk yang kecil dan lemah — kawanan burung. Allah berfirman, "dan Dia mengirimkan kepada mereka burung yang berbondong-bondong, yang melempari mereka dengan batu dari tanah liat yang dibakar, sehingga mereka dijadikan-Nya seperti daun-daun yang dimakan (ulat)" (QS. Al-Fil: 3-5).

Burung-burung itu datang berbondong-bondong (ababil), masing-masing membawa batu kecil dari tanah liat yang mengeras (sijjil). Batu-batu itu dijatuhkan kepada pasukan Abrahah, dan seketika mereka binasa — hancur berkeping seperti daun kering yang telah dimakan dan tersisa serpihannya. Kekuatan besar mereka luluh oleh sarana yang tampak sederhana di mata manusia.

Peristiwa ini menjadi tanda kebesaran Allah yang menjaga Baitullah, sekaligus pendahuluan bagi kemuliaan yang akan datang: di tahun itulah lahir Nabi Muhammad ﷺ, yang kelak menyeru manusia kepada Tuhan pemilik Ka''bah itu.

Hikmah: Allah tidak butuh sarana yang besar untuk mengalahkan yang perkasa. Dengan burung kecil dan batu tanah liat, Dia meruntuhkan pasukan bergajah. Ini menanamkan keyakinan bahwa pertolongan Allah bisa datang dari arah dan cara yang tak terduga — cukuplah kita bertawakal kepada-Nya.

Sumber & Catatan: dalil dari Al-Qur''an, QS. Al-Fil: 3-5. Kata "ababil" (berbondong-bondong) dan "sijjil" (tanah liat yang dibakar/mengeras) adalah nas Al-Qur''an. Peristiwa ini terjadi pada "Tahun Gajah", yang menurut sirah masyhur bertepatan dengan tahun kelahiran Nabi Muhammad ﷺ — keterangan penanggalan ini berasal dari sirah, disampaikan sebagai catatan sejarah.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  (SELECT id FROM ayah WHERE surah_id = 105 AND number = 3), 702, datetime('now');
INSERT INTO ebooks (id, title, author, r2_key, category_id, license_status, license_note) VALUES (703, 'Episode 2: The Flocks of Birds and the Ruin of the Elephant Army', 'Tim Editorial ULYAH', 'ebooks/kisah-ashabul-fil/en/kisah-ashabul-fil-02-burung-ababil.pdf', 5, 'original', 'Ditulis berdasarkan QS. Al-Fil 3-5 (quran-json, CC-BY-4.0). Tidak ada kutipan pihak ketiga berhak cipta.');
INSERT INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Episode 2: The Flocks of Birds and the Ruin of the Elephant Army', 'kisah-ashabul-fil-02-burung-ababil', 'en', 'kisah-ashabul-fil', 2, 5, 'The way Allah destroyed that mighty army was truly astonishing: not with a great host, but with small, weak creatures — flocks of birds. Allah said, "And He sent against them birds in flocks, striking them with stones of hard baked clay, and He made them like eaten straw" (Qur''an 105:3-5).

The birds came in flocks (ababil), each carrying small stones of hardened clay (sijjil). Those stones were dropped upon Abrahah''s army, and at once they perished — shattered to pieces like dry leaves eaten away and left only as fragments. Their great strength dissolved before a means that seemed simple in human eyes.

This event became a sign of Allah''s greatness in guarding His Sacred House, and also a prelude to the honor to come: in that very year Prophet Muhammad ﷺ was born, who would later call people to the Lord who owns that Ka''bah.

Reflection: Allah does not need great means to defeat the mighty. With small birds and stones of clay, He brought down an army of elephants. This instills the certainty that Allah''s help can come from unexpected directions and ways — it is enough that we rely upon Him.

Source & Note: evidence from the Qur''an, 105:3-5. The words "ababil" (in flocks) and "sijjil" (baked/hardened clay) are the Qur''an''s own text. This event took place in the "Year of the Elephant," which according to the well-known sirah coincided with the year of the birth of Prophet Muhammad ﷺ — this dating comes from the sirah, related as history.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  (SELECT id FROM ayah WHERE surah_id = 105 AND number = 3), 703, datetime('now');

