-- AUTO-GENERATED by scripts/generate-kisah-kaum-saba-seed.ts — do not edit by hand.
-- Source content: scripts/content/kisah-kaum-saba.ts (grounded in QS. Al-Qalam
-- 68:17-33, quran-json CC-BY-4.0). See docs/CONTENT-POLICY.md.
-- Requires quran_seed.sql already applied (resolves related_ayah_id by lookup).

INSERT OR IGNORE INTO categories (id, name, slug, parent_id, auto_created) VALUES (5, 'Kisah Islami', 'kisah-islami', NULL, 0);

INSERT INTO ebooks (id, title, author, r2_key, category_id, license_status, license_note) VALUES (1100, 'Episode 1: Dua Kebun dan Perintah Bersyukur', 'Tim Editorial ULYAH', 'ebooks/kisah-kaum-saba/id/kisah-kaum-saba-01-dua-kebun-dan-perintah-syukur.pdf', 5, 'original', 'Ditulis berdasarkan QS. Saba'' 15-15 (quran-json, CC-BY-4.0). Tidak ada kutipan pihak ketiga berhak cipta.');
INSERT INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Episode 1: Dua Kebun dan Perintah Bersyukur', 'kisah-kaum-saba-01-dua-kebun-dan-perintah-syukur', 'id', 'kisah-kaum-saba', 1, 5, 'Kaum Saba'' adalah bangsa yang Allah anugerahi negeri yang subur dan makmur — dua hamparan kebun yang membentang di kanan dan kiri, dengan hasil yang melimpah. Allah berfirman, "Sungguh, bagi kaum Saba'' ada tanda (kebesaran Allah) di tempat kediaman mereka, yaitu dua buah kebun di sebelah kanan dan di sebelah kiri. (Kepada mereka dikatakan), ‘Makanlah olehmu dari rezeki yang (dianugerahkan) Tuhanmu dan bersyukurlah kepada-Nya. (Negerimu) adalah negeri yang baik (nyaman), sedangkan (Tuhanmu) adalah Tuhan Yang Maha Pengampun’" (QS. Saba'': 15).

Allah tidak sekadar memberi mereka nikmat, tetapi juga menunjukkan jalan untuk melanggengkannya: makan dari rezeki-Nya lalu bersyukur. Frasa "baldatun tayyibatun wa rabbun ghafūr" — negeri yang baik dan Tuhan Yang Maha Pengampun — melukiskan betapa sempurnanya keadaan mereka: tanah yang subur, hidup yang nyaman, dan Tuhan yang siap mengampuni bila mereka kembali kepada-Nya.

Hikmah: nikmat yang besar adalah amanah sekaligus ujian. Kunci agar nikmat bertahan dan bertambah adalah syukur — mengakui bahwa semua itu dari Allah, menggunakannya di jalan yang diridhai, dan tidak menyombongkan diri.

Sumber & Catatan: dalil dari Al-Qur''an, QS. Saba'': 15 (teks & terjemahan quran-json). Kisah ini adalah tentang negeri Saba'' dan bendungannya, berbeda dari kisah Ratu Saba'' (Bilqis) bersama Nabi Sulaiman yang ada di Surah An-Naml.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  (SELECT id FROM ayah WHERE surah_id = 34 AND number = 15), 1100, datetime('now');
INSERT INTO ebooks (id, title, author, r2_key, category_id, license_status, license_note) VALUES (1101, 'Episode 1: Two Gardens and the Command to Give Thanks', 'Tim Editorial ULYAH', 'ebooks/kisah-kaum-saba/en/kisah-kaum-saba-01-dua-kebun-dan-perintah-syukur.pdf', 5, 'original', 'Ditulis berdasarkan QS. Saba'' 15-15 (quran-json, CC-BY-4.0). Tidak ada kutipan pihak ketiga berhak cipta.');
INSERT INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Episode 1: Two Gardens and the Command to Give Thanks', 'kisah-kaum-saba-01-dua-kebun-dan-perintah-syukur', 'en', 'kisah-kaum-saba', 1, 5, 'The people of Sheba (Saba'') were a nation Allah blessed with a fertile, prosperous land — two spreading gardens on the right and the left, with abundant yield. Allah said, "There was for [the tribe of] Saba'' in their dwelling place a sign: two [fields of] gardens on the right and on the left. [They were told], ‘Eat from the provisions of your Lord and be grateful to Him. A good land [have you], and a forgiving Lord’" (Qur''an 34:15).

Allah did not merely give them blessings; He also showed them the way to make them last: eat of His provision and give thanks. The phrase "baldatun tayyibatun wa rabbun ghafūr" — a good land and a forgiving Lord — paints how complete their state was: fertile soil, a comfortable life, and a Lord ready to forgive if they returned to Him.

Reflection: a great blessing is both a trust and a test. The key to a blessing lasting and increasing is gratitude — acknowledging it is all from Allah, using it in a way that pleases Him, and not growing arrogant.

Source & Note: evidence from the Qur''an, 34:15 (text & translation from quran-json). This account is about the land of Saba'' and its dam, distinct from the story of the Queen of Sheba (Bilqis) with Prophet Sulaiman in Surah An-Naml.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  (SELECT id FROM ayah WHERE surah_id = 34 AND number = 15), 1101, datetime('now');

INSERT INTO ebooks (id, title, author, r2_key, category_id, license_status, license_note) VALUES (1102, 'Episode 2: Berpaling dari Syukur dan Banjir Besar', 'Tim Editorial ULYAH', 'ebooks/kisah-kaum-saba/id/kisah-kaum-saba-02-berpaling-dan-banjir-bendungan.pdf', 5, 'original', 'Ditulis berdasarkan QS. Saba'' 16-17 (quran-json, CC-BY-4.0). Tidak ada kutipan pihak ketiga berhak cipta.');
INSERT INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Episode 2: Berpaling dari Syukur dan Banjir Besar', 'kisah-kaum-saba-02-berpaling-dan-banjir-bendungan', 'id', 'kisah-kaum-saba', 2, 5, 'Alih-alih bersyukur, kaum Saba'' justru berpaling dari Allah dan mengingkari nikmat-Nya. Maka Allah menarik kembali kenikmatan itu dengan cara yang mengubah negeri makmur menjadi tandus. Allah berfirman, "Tetapi mereka berpaling, maka Kami kirim kepada mereka banjir yang besar dan Kami ganti kedua kebun mereka dengan dua kebun yang ditumbuhi (pohon-pohon) yang berbuah pahit, pohon Asl dan sedikit pohon Sidr" (QS. Saba'': 16).

Banjir besar itu — dikenal sebagai "sailul ''arim", jebolnya bendungan yang selama ini mengairi kebun mereka — meluluhlantakkan negeri yang subur. Kebun buah yang manis berganti menjadi tanaman berbuah pahit, pohon asl (sejenis cemara/tamariska) yang tak berguna, dan hanya sedikit pohon bidara. Allah menegaskan sebab dari semua ini, "Demikianlah Kami memberi balasan kepada mereka karena kekafiran mereka. Dan tidaklah Kami menjatuhkan azab (yang demikian itu), melainkan hanya kepada orang-orang yang sangat ingkar" (QS. Saba'': 17).

Hikmah: kufur nikmat — menikmati pemberian Allah sambil berpaling dari-Nya — dapat mencabut keberkahan. Nikmat yang tidak disyukuri bisa berubah menjadi sebab kehancuran. Yang menyelamatkan bukanlah suburnya kebun, melainkan hati yang bersyukur dan taat.

Sumber & Catatan: dalil dari Al-Qur''an, QS. Saba'': 16-17. Istilah "sailul ''arim" (banjir bendungan) adalah nas Al-Qur''an. Rincian sejarah bendungan Ma''rib di sebagian riwayat/sejarah berada di luar nas dan tidak dipastikan di sini.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  (SELECT id FROM ayah WHERE surah_id = 34 AND number = 16), 1102, datetime('now');
INSERT INTO ebooks (id, title, author, r2_key, category_id, license_status, license_note) VALUES (1103, 'Episode 2: Turning Away from Gratitude, and the Great Flood', 'Tim Editorial ULYAH', 'ebooks/kisah-kaum-saba/en/kisah-kaum-saba-02-berpaling-dan-banjir-bendungan.pdf', 5, 'original', 'Ditulis berdasarkan QS. Saba'' 16-17 (quran-json, CC-BY-4.0). Tidak ada kutipan pihak ketiga berhak cipta.');
INSERT INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Episode 2: Turning Away from Gratitude, and the Great Flood', 'kisah-kaum-saba-02-berpaling-dan-banjir-bendungan', 'en', 'kisah-kaum-saba', 2, 5, 'Instead of giving thanks, the people of Sheba turned away from Allah and denied His blessing. So Allah withdrew that comfort in a way that turned a prosperous land into a barren one. Allah said, "But they turned away, so We sent upon them the flood of the dam, and We replaced their two [fields of] gardens with gardens of bitter fruit, tamarisks, and something of sparse lote trees" (Qur''an 34:16).

That great flood — known as "sayl al-''arim," the bursting of the dam that had irrigated their gardens — devastated the fertile land. Gardens of sweet fruit turned into plants of bitter fruit, useless tamarisk (asl) trees, and only a few lote trees. Allah made clear the cause of it all: "That is how We requited them for their disbelief. And do We [thus] requite except the ungrateful?" (Qur''an 34:17).

Reflection: ingratitude for blessings — enjoying Allah''s gifts while turning away from Him — can strip away their blessing. A blessing that is not met with thanks can turn into a cause of ruin. What saves is not the fertility of a garden, but a heart that is grateful and obedient.

Source & Note: evidence from the Qur''an, 34:16-17. The term "sayl al-''arim" (the flood of the dam) is the Qur''an''s own text. Historical details of the Ma''rib dam found in some reports/history are outside the text and are not asserted here.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  (SELECT id FROM ayah WHERE surah_id = 34 AND number = 16), 1103, datetime('now');

INSERT INTO ebooks (id, title, author, r2_key, category_id, license_status, license_note) VALUES (1104, 'Episode 3: Tercerai-Berai Menjadi Buah Bibir', 'Tim Editorial ULYAH', 'ebooks/kisah-kaum-saba/id/kisah-kaum-saba-03-tercerai-berai-jadi-buah-bibir.pdf', 5, 'original', 'Ditulis berdasarkan QS. Saba'' 18-19 (quran-json, CC-BY-4.0). Tidak ada kutipan pihak ketiga berhak cipta.');
INSERT INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Episode 3: Tercerai-Berai Menjadi Buah Bibir', 'kisah-kaum-saba-03-tercerai-berai-jadi-buah-bibir', 'id', 'kisah-kaum-saba', 3, 5, 'Sebelum azab, Allah mengingatkan betapa besar nikmat yang dulu mereka miliki: negeri-negeri yang berdekatan dan perjalanan yang aman. Allah berfirman, "Dan Kami jadikan antara mereka dan negeri-negeri yang Kami berkahi (Syam), beberapa negeri yang berdekatan dan Kami tetapkan antara negeri-negeri itu (jarak-jarak) perjalanan. Berjalanlah kamu di negeri-negeri itu pada malam dan siang hari dengan aman" (QS. Saba'': 18).

Namun mereka tidak menghargai kemudahan itu; mereka justru bosan dan meminta agar perjalanan mereka dibuat jauh dan sukar, sembari menzalimi diri sendiri dengan kekufuran. Allah berfirman, "Maka mereka berkata, ‘Ya Tuhan kami, jauhkanlah jarak perjalanan kami,’ dan mereka menzalimi diri mereka sendiri; maka Kami jadikan mereka bahan pembicaraan dan Kami hancurkan mereka sehancur-hancurnya. Sungguh, pada yang demikian itu benar-benar terdapat tanda-tanda (kebesaran Allah) bagi setiap orang yang sabar dan bersyukur" (QS. Saba'': 19).

Maka bangsa yang dahulu makmur dan bersatu itu tercerai-berai ke berbagai penjuru, hingga kisah mereka hanya tinggal menjadi buah bibir dan pelajaran bagi generasi sesudahnya. Ayat ditutup dengan kunci keselamatan: tanda-tanda ini hanya dipetik oleh "orang yang sabar dan bersyukur".

Hikmah: kesombongan dan kufur nikmat menghancurkan persatuan dan kemakmuran. Dua sifat yang menyelamatkan seorang hamba dari nasib seperti kaum Saba'' adalah sabar dalam ketaatan dan syukur atas nikmat.

Sumber & Catatan: dalil dari Al-Qur''an, QS. Saba'': 18-19. Semua unsur kisah — perjalanan yang aman, permintaan menjauhkan perjalanan, dan tercerai-berainya mereka menjadi "buah bibir" — adalah nas Al-Qur''an.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  (SELECT id FROM ayah WHERE surah_id = 34 AND number = 18), 1104, datetime('now');
INSERT INTO ebooks (id, title, author, r2_key, category_id, license_status, license_note) VALUES (1105, 'Episode 3: Scattered until They Became Mere Tales', 'Tim Editorial ULYAH', 'ebooks/kisah-kaum-saba/en/kisah-kaum-saba-03-tercerai-berai-jadi-buah-bibir.pdf', 5, 'original', 'Ditulis berdasarkan QS. Saba'' 18-19 (quran-json, CC-BY-4.0). Tidak ada kutipan pihak ketiga berhak cipta.');
INSERT INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Episode 3: Scattered until They Became Mere Tales', 'kisah-kaum-saba-03-tercerai-berai-jadi-buah-bibir', 'en', 'kisah-kaum-saba', 3, 5, 'Before the punishment, Allah reminded them how great the blessing they once had was: neighbouring towns and safe travel. Allah said, "And We placed between them and the cities which We had blessed [many] visible cities. And We determined between them the [distances of] journey, [saying], ‘Travel between them by night or day in safety’" (Qur''an 34:18).

Yet they did not value that ease; rather they grew weary and asked that their journeys be made long and hard, while wronging themselves through disbelief. Allah said, "But they said, ‘Our Lord, lengthen the distance between our journeys,’ and wronged themselves, so We made them narrations and dispersed them in total dispersion. Indeed in that are signs for everyone patient and grateful" (Qur''an 34:19).

So the nation that was once prosperous and united was scattered to every direction, until their story remained only as a byword and a lesson for later generations. The verse closes with the key to safety: these signs are grasped only by "everyone patient and grateful."

Reflection: arrogance and ingratitude destroy unity and prosperity. The two traits that save a servant from a fate like that of Sheba are patience in obedience and gratitude for blessings.

Source & Note: evidence from the Qur''an, 34:18-19. Every element of the account — the safe travel, the plea to lengthen the journeys, and their dispersal into mere "tales" — is the Qur''an''s own text.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  (SELECT id FROM ayah WHERE surah_id = 34 AND number = 18), 1105, datetime('now');

