-- Kisah Sahabat (Companions of the Prophet ﷺ) — fills the previously-empty
-- "Kisah Sahabat" category. Four companions, each its own short multi-episode
-- series (same pattern as kisah_nuh.sql / kisah_musa.sql), grounded in
-- well-established sirah accounts and sahih hadith, universally agreed upon
-- across the Muslim community (no sectarian-contested material). No PDF
-- ebook assets exist for these yet, so pdf_ebook_id is left NULL — the
-- audiobook/text reader works regardless. See docs/CONTENT-POLICY.md.
-- category_id resolved by slug lookup (never hardcoded) so this is safe to
-- run regardless of the exact id the "Kisah Sahabat" row was created with.

-- ══ Abu Bakr as-Siddiq ══════════════════════════════════════════════════

INSERT INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, published_at)
SELECT 'Abu Bakr: Yang Pertama Membenarkan', 'kisah-abu-bakr-01-yang-pertama-membenarkan', 'id', 'kisah-abu-bakr', 1, (SELECT id FROM categories WHERE slug = 'kisah-sahabat'), 'Ketika Rasulullah ﷺ menerima wahyu pertama di Gua Hira dan menyampaikannya kepada orang-orang terdekatnya, Abu Bakr adalah orang pertama dari kalangan laki-laki dewasa yang beriman tanpa ragu sedikit pun. Ia tidak meminta bukti, tidak menuntut penjelasan panjang — cukup mendengar bahwa yang mengatakannya adalah Muhammad, seseorang yang telah ia kenal puluhan tahun sebagai pribadi yang jujur dan tak pernah berdusta.

Keteguhan itu diuji lagi pada peristiwa Isra'' Mi''raj. Ketika kaum Quraisy mendengar Rasulullah ﷺ mengabarkan bahwa beliau melakukan perjalanan malam dari Makkah ke Baitul Maqdis lalu naik ke langit dalam satu malam, banyak yang mencibir dan mempertanyakan akal sehat mereka yang baru masuk Islam. Sebagian orang berlari kepada Abu Bakr, mengira kabar itu akan meruntuhkan imannya. Namun Abu Bakr menjawab tegas, "Jika benar beliau yang mengatakannya, maka aku membenarkannya." Dari sinilah gelar As-Siddiq — Sang Pembenar — melekat abadi pada namanya.

Hikmah: Keyakinan Abu Bakr lahir bukan dari melihat sendiri buktinya, melainkan dari mengenal kejujuran pribadi yang mengabarkannya. Ini mengajarkan kita pentingnya husnuzhon (prasangka baik) kepada orang-orang yang telah terbukti amanah, dan bahwa iman sejati tidak selalu menuntut untuk melihat lebih dulu baru percaya.', 0, 'qc_pending', 'ai_original', 'published', 1.0, NULL, datetime('now');

INSERT INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, published_at)
SELECT 'Abu Bakr: The First to Believe', 'kisah-abu-bakr-01-yang-pertama-membenarkan', 'en', 'kisah-abu-bakr', 1, (SELECT id FROM categories WHERE slug = 'kisah-sahabat'), 'When the Messenger of Allah ﷺ received the first revelation in the Cave of Hira and shared it with those closest to him, Abu Bakr was the first adult man to believe without a moment''s hesitation. He asked for no proof, demanded no lengthy explanation — it was enough for him to hear that the one saying it was Muhammad, a man he had known for decades as someone who never once lied.

That steadfastness was tested again at the event of Isra'' and Mi''raj. When the Prophet ﷺ told the Quraysh he had travelled by night from Makkah to Jerusalem and then ascended through the heavens in a single night, many mocked him and doubted the sanity of the recent converts. Some ran straight to Abu Bakr, expecting the news to shatter his faith. Instead he answered firmly, "If he indeed said it, then I believe him." From that moment the title As-Siddiq — the Testifier of Truth — became permanently attached to his name.

Reflection: Abu Bakr''s certainty was born not from seeing the proof himself, but from knowing the personal integrity of the one reporting it. This teaches us the value of husn al-zann (thinking well) toward those whose trustworthiness has already been proven, and that true faith does not always require seeing before believing.', 0, 'qc_pending', 'ai_original', 'published', 1.0, NULL, datetime('now');

INSERT INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, published_at)
SELECT 'Abu Bakr: Di Gua Tsur', 'kisah-abu-bakr-02-di-gua-tsur', 'id', 'kisah-abu-bakr', 2, (SELECT id FROM categories WHERE slug = 'kisah-sahabat'), 'Saat hijrah ke Madinah, Rasulullah ﷺ memilih Abu Bakr sebagai satu-satunya pendamping perjalanan yang penuh bahaya itu. Untuk mengecoh para pengejar dari Quraisy yang telah memasang sayembara besar bagi siapa pun yang menangkap beliau, keduanya justru bersembunyi terlebih dahulu di Gua Tsur, arah berlawanan dari Madinah, selama tiga hari.

Para pengejar sampai berdiri persis di mulut gua. Abu Bakr, yang lebih mencemaskan keselamatan Rasulullah ﷺ ketimbang dirinya sendiri, berbisik cemas, "Wahai Rasulullah, seandainya salah seorang dari mereka menunduk sedikit saja, tentu ia akan melihat kita." Rasulullah ﷺ menjawab dengan tenang, sebagaimana kemudian diabadikan dalam Al-Qur''an: "Janganlah engkau bersedih, sesungguhnya Allah bersama kita." (QS. At-Taubah: 40)

Hikmah: Tawakal yang sejati bukan berarti tidak pernah merasa takut, melainkan meyakini bahwa pertolongan Allah jauh lebih besar daripada rasa takut itu. Kecemasan Abu Bakr murni demi keselamatan Rasulullah ﷺ, bukan dirinya — sebuah teladan persahabatan yang tulus dan pengorbanan tanpa pamrih.', 0, 'qc_pending', 'ai_original', 'published', 1.0, (SELECT id FROM ayah WHERE surah_id = 9 AND number = 40), datetime('now');

INSERT INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, published_at)
SELECT 'Abu Bakr: In the Cave of Thawr', 'kisah-abu-bakr-02-di-gua-tsur', 'en', 'kisah-abu-bakr', 2, (SELECT id FROM categories WHERE slug = 'kisah-sahabat'), 'During the migration to Madinah, the Prophet ﷺ chose Abu Bakr as the sole companion for that perilous journey. To throw off the Quraysh pursuers — who had put a large bounty on his capture — the two first hid in the opposite direction from Madinah, inside the Cave of Thawr, for three nights.

The search party stood right at the mouth of the cave. Abu Bakr, more anxious for the Prophet''s safety than his own, whispered fearfully, "O Messenger of Allah, if just one of them were to look down at his feet, he would see us." The Prophet ﷺ answered calmly, in words later recorded in the Qur''an: "Do not grieve; indeed Allah is with us." (QS. At-Tawbah 9:40)

Reflection: True reliance on Allah (tawakkul) does not mean the absence of fear, but trusting that Allah''s help is far greater than that fear. Abu Bakr''s anxiety was entirely for the Prophet''s safety, not his own — a model of sincere friendship and selfless sacrifice.', 0, 'qc_pending', 'ai_original', 'published', 1.0, (SELECT id FROM ayah WHERE surah_id = 9 AND number = 40), datetime('now');

INSERT INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, published_at)
SELECT 'Abu Bakr: Seluruh Hartaku untuk Rasulullah', 'kisah-abu-bakr-03-seluruh-hartaku', 'id', 'kisah-abu-bakr', 3, (SELECT id FROM categories WHERE slug = 'kisah-sahabat'), 'Menjelang perang Tabuk, Rasulullah ﷺ menyerukan kaum muslimin untuk berinfak membiayai pasukan. Umar bin Khattab datang membawa separuh hartanya, yakin kali ini ia akhirnya bisa mengungguli Abu Bakr dalam kebaikan. Namun Abu Bakr datang membawa seluruh harta yang ia miliki, tanpa sisa.

Rasulullah ﷺ bertanya, "Apa yang engkau sisakan untuk keluargamu, wahai Abu Bakr?" Ia menjawab dengan tenang, "Aku sisakan untuk mereka Allah dan Rasul-Nya." Mendengar jawaban itu, Umar mengakui, "Aku tidak akan pernah bisa mengunggulinya dalam kebaikan selamanya."

Hikmah: Kedermawanan sejati lahir dari keyakinan penuh bahwa Allah-lah yang menjamin rezeki, bukan dari perhitungan berapa yang harus disisakan untuk diri sendiri. Persaingan Abu Bakr dan Umar dalam kebaikan (fastabiqul khairat) ini juga mengajarkan bahwa berlomba dalam ketaatan seharusnya bebas dari rasa iri, semata untuk meraih ridha Allah.', 0, 'qc_pending', 'ai_original', 'published', 1.0, NULL, datetime('now');

INSERT INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, published_at)
SELECT 'Abu Bakr: All My Wealth for the Messenger of Allah', 'kisah-abu-bakr-03-seluruh-hartaku', 'en', 'kisah-abu-bakr', 3, (SELECT id FROM categories WHERE slug = 'kisah-sahabat'), 'Ahead of the Battle of Tabuk, the Prophet ﷺ called on the Muslims to donate toward equipping the army. Umar ibn al-Khattab brought half of his wealth, confident that this time he would finally surpass Abu Bakr in generosity. But Abu Bakr arrived carrying everything he owned, with nothing held back.

The Prophet ﷺ asked, "What have you left for your family, O Abu Bakr?" He replied calmly, "I left for them Allah and His Messenger." Hearing this, Umar admitted, "I will never be able to outdo him in goodness, ever."

Reflection: True generosity is born from complete conviction that Allah alone guarantees provision, not from calculating how much to keep for oneself. The friendly rivalry between Abu Bakr and Umar in good deeds (fastabiqul khairat) also teaches that competing in righteousness should be free of envy, aimed solely at earning Allah''s pleasure.', 0, 'qc_pending', 'ai_original', 'published', 1.0, NULL, datetime('now');

-- ══ Umar bin Khattab ═════════════════════════════════════════════════════

INSERT INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, published_at)
SELECT 'Umar bin Khattab: Pedang yang Berbalik Menjadi Iman', 'kisah-umar-01-pedang-berbalik-iman', 'id', 'kisah-umar-bin-khattab', 1, (SELECT id FROM categories WHERE slug = 'kisah-sahabat'), 'Sebelum memeluk Islam, Umar bin Khattab dikenal sebagai salah satu penentang paling keras dakwah Rasulullah ﷺ. Suatu hari, dengan pedang terhunus, ia bertekad membunuh beliau. Di tengah jalan, seseorang mengabarkan bahwa adik kandungnya sendiri, Fatimah binti Khattab, beserta suaminya telah lebih dulu memeluk Islam secara diam-diam.

Murka, Umar bergegas ke rumah adiknya. Ia mendapati keduanya sedang membaca lembaran ayat-ayat Surah Thaha. Dalam amarahnya ia memukul suami adiknya, lalu adiknya sendiri hingga berdarah. Namun Fatimah, dengan wajah berlumur darah, berkata tegas, "Benar, kami telah masuk Islam dan beriman kepada Allah dan Rasul-Nya. Lakukan sesukamu!" Melihat darah adiknya sendiri demi mempertahankan keyakinannya, hati Umar luluh. Ia meminta untuk membaca lembaran yang tadi dibaca. Setelah bersuci terlebih dahulu — karena merasakan kemuliaan apa yang akan ia baca — ia membaca ayat-ayat Thaha, dan hatinya pun bergetar. Ia bergegas ke rumah Al-Arqam, tempat Rasulullah ﷺ dan para sahabat berkumpul, dan menyatakan keislamannya di hadapan mereka semua.

Hikmah: Hidayah bisa datang secara tiba-tiba dan sepenuhnya merupakan kehendak Allah; keteguhan seorang saudara perempuan yang tetap kokoh meski disakiti menjadi pintu masuknya cahaya ke hati yang paling keras sekalipun. Kisah ini juga menunjukkan bagaimana mendengar dan merenungi Al-Qur''an secara langsung dapat mengubah hati manusia sepenuhnya.', 0, 'qc_pending', 'ai_original', 'published', 1.0, NULL, datetime('now');

INSERT INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, published_at)
SELECT 'Umar ibn al-Khattab: The Sword That Turned Into Faith', 'kisah-umar-01-pedang-berbalik-iman', 'en', 'kisah-umar-bin-khattab', 1, (SELECT id FROM categories WHERE slug = 'kisah-sahabat'), 'Before embracing Islam, Umar ibn al-Khattab was known as one of the fiercest opponents of the Prophet''s ﷺ message. One day, sword drawn, he set out determined to kill him. Along the way, someone told him that his own sister, Fatimah bint al-Khattab, and her husband had already secretly become Muslims.

Enraged, Umar rushed to his sister''s house and found the couple reading pages of Surah Taha. In his fury he struck his brother-in-law, then his own sister, until she bled. Yet Fatimah, her face streaked with blood, said firmly, "Yes, we have become Muslims and believe in Allah and His Messenger. Do as you wish!" Seeing his own sister''s blood spilled in defence of her faith, Umar''s heart softened. He asked to read what she had been reciting. After purifying himself first — sensing the majesty of what he was about to read — he read the verses of Taha, and his heart trembled. He hurried straight to the house of al-Arqam, where the Prophet ﷺ and the companions were gathered, and declared his faith before them all.

Reflection: Guidance can arrive suddenly and is entirely Allah''s to give; a sister''s steadfastness even while being hurt became the door through which light entered even the hardest of hearts. This story also shows how directly hearing and reflecting on the Qur''an can transform a person completely.', 0, 'qc_pending', 'ai_original', 'published', 1.0, NULL, datetime('now');

INSERT INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, published_at)
SELECT 'Umar bin Khattab: Khalifah yang Berpatroli Malam', 'kisah-umar-02-berpatroli-malam', 'id', 'kisah-umar-bin-khattab', 2, (SELECT id FROM categories WHERE slug = 'kisah-sahabat'), 'Sebagai Khalifah, Umar bin Khattab terbiasa berkeliling sendirian di malam hari untuk memastikan tidak ada rakyatnya yang menderita tanpa sepengetahuannya. Suatu malam bersama pembantunya, Aslam, ia mendengar tangisan anak-anak dari sebuah kemah di pinggir Madinah. Ia mendapati seorang ibu tengah merebus batu di dalam panci, berpura-pura memasak agar anak-anaknya yang kelaparan tertidur karena lelah menunggu.

Umar menangis mendengar penjelasan sang ibu bahwa mereka tidak memiliki apa pun untuk dimakan. Ia segera berlari sendiri ke Baitul Mal (gudang perbendaharaan negara), mengambil karung berisi tepung, minyak samin, dan kurma, lalu memanggulnya sendiri di punggungnya menuju kemah itu — menolak tawaran Aslam untuk membawakannya. "Maukah engkau memikul dosaku di hari kiamat?" katanya. Sesampainya di sana, Umar sendiri yang memasak untuk keluarga itu hingga mereka kenyang dan tertawa gembira, sebelum akhirnya kembali dengan hati tenang.

Hikmah: Kepemimpinan sejati adalah pelayanan; seorang pemimpin bertanggung jawab secara langsung di hadapan Allah atas kesejahteraan setiap orang yang dipimpinnya, bahkan yang tidak pernah ia kenal sekalipun. Kerendahan hati Umar — seorang kepala negara yang mau memanggul karung sendiri — adalah teladan bahwa kedudukan tidak boleh menghalangi seseorang untuk melayani dengan tangannya sendiri.', 0, 'qc_pending', 'ai_original', 'published', 1.0, NULL, datetime('now');

INSERT INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, published_at)
SELECT 'Umar ibn al-Khattab: The Caliph Who Patrolled the Night', 'kisah-umar-02-berpatroli-malam', 'en', 'kisah-umar-bin-khattab', 2, (SELECT id FROM categories WHERE slug = 'kisah-sahabat'), 'As Caliph, Umar ibn al-Khattab would regularly walk alone through Madinah at night to make sure none of his people were suffering without his knowledge. One night, with his servant Aslam, he heard children crying from a tent on the edge of the city. He found a mother boiling stones in a pot, pretending to cook so her hungry children would fall asleep from exhaustion while they waited.

Umar wept on hearing that the family had nothing at all to eat. He rushed to the Bayt al-Mal (the public treasury) himself, took a sack of flour, clarified butter, and dates, and carried it on his own back to the tent — refusing Aslam''s offer to carry it for him. "Will you carry my sins for me on the Day of Judgment?" he said. Once there, Umar himself cooked for the family until the children were full and laughing, before finally returning home at peace.

Reflection: True leadership is service; a leader is directly accountable before Allah for the welfare of every person under his care, even those he has never met. Umar''s humility — a head of state carrying the sack himself — is a lasting example that rank must never excuse anyone from serving with their own hands.', 0, 'qc_pending', 'ai_original', 'published', 1.0, NULL, datetime('now');

-- ══ Bilal bin Rabah ══════════════════════════════════════════════════════

INSERT INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, published_at)
SELECT 'Bilal bin Rabah: Ahad, Ahad', 'kisah-bilal-01-ahad-ahad', 'id', 'kisah-bilal', 1, (SELECT id FROM categories WHERE slug = 'kisah-sahabat'), 'Bilal bin Rabah, seorang budak berkulit hitam asal Habasyah (Ethiopia), termasuk golongan paling awal yang memeluk Islam. Karena keislamannya, majikannya, Umayyah bin Khalaf, menyiksanya secara keji: menyeretnya ke padang pasir yang membara di tengah hari, membaringkannya di atas pasir panas, lalu menindih dadanya dengan batu besar, memaksanya murtad dan menyembah berhala.

Namun di tengah siksaan yang nyaris tak tertahankan itu, Bilal hanya mengulang satu kata: "Ahad, Ahad" — Esa, Esa — menegaskan keyakinannya bahwa Allah Maha Esa, tak tergoyahkan meski nyawa taruhannya. Abu Bakr Ash-Shiddiq yang melintas dan menyaksikan penderitaannya tergerak hatinya. Ia pun membeli Bilal dari Umayyah dengan harga tinggi, lalu segera memerdekakannya karena Allah semata.

Hikmah: Keteguhan (tsabat) dalam iman tidak goyah sekalipun nyawa menjadi taruhannya. Kata "Ahad" yang diucapkan Bilal adalah pengakuan tauhid paling murni di tengah derita. Kisah ini juga menjadi bukti persaudaraan sejati dalam Islam — pertolongan Abu Bakr tidak memandang status sosial maupun ras seorang muslim yang tertindas.', 0, 'qc_pending', 'ai_original', 'published', 1.0, NULL, datetime('now');

INSERT INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, published_at)
SELECT 'Bilal ibn Rabah: One, One', 'kisah-bilal-01-ahad-ahad', 'en', 'kisah-bilal', 1, (SELECT id FROM categories WHERE slug = 'kisah-sahabat'), 'Bilal ibn Rabah, a Black slave from Abyssinia (Ethiopia), was among the very earliest to embrace Islam. Because of his faith, his master Umayyah ibn Khalaf tortured him brutally: dragging him onto the scorching desert sand at midday, laying him down, and pressing a huge rock onto his chest, trying to force him to renounce Islam and worship idols instead.

Yet amid torment nearly beyond endurance, Bilal repeated only one word: "Ahad, Ahad" — One, One — affirming his conviction that Allah is One, unshaken even as his life hung in the balance. Abu Bakr as-Siddiq, passing by and witnessing his suffering, was moved. He bought Bilal from Umayyah at a high price and immediately freed him, for the sake of Allah alone.

Reflection: Steadfastness (thabat) in faith does not waver even when life itself is at stake. The word "Ahad" that Bilal uttered is the purest declaration of Tawhid in the midst of suffering. This story is also living proof of true brotherhood in Islam — Abu Bakr''s rescue paid no regard to the social status or race of an oppressed Muslim.', 0, 'qc_pending', 'ai_original', 'published', 1.0, NULL, datetime('now');

INSERT INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, published_at)
SELECT 'Bilal bin Rabah: Suara Adzan Pertama di Atas Ka''bah', 'kisah-bilal-02-adzan-di-atas-kabah', 'id', 'kisah-bilal', 2, (SELECT id FROM categories WHERE slug = 'kisah-sahabat'), 'Setelah penaklukan Makkah, kota yang dahulu memperbudak dan menyiksanya karena keimanannya, Rasulullah ﷺ memilih Bilal untuk naik ke atas Ka''bah dan mengumandangkan adzan. Suara seorang mantan budak kini menggema dari titik tertinggi kota itu, menyerukan kebesaran Allah kepada seluruh penduduknya.

Beberapa bekas pembesar Quraisy yang berdiri di bawah menggerutu, merasa direndahkan karena dipimpin oleh suara seorang mantan budak. Namun Rasulullah ﷺ menegur keras prasangka semacam itu, menegaskan bahwa kemuliaan di sisi Allah semata-mata diukur dari ketakwaan, sebagaimana firman-Nya, "Sesungguhnya yang paling mulia di antara kalian di sisi Allah ialah yang paling bertakwa." (QS. Al-Hujurat: 13)

Hikmah: Islam tidak mengenal hierarki ras maupun status sosial — kemuliaan di hadapan Allah semata diukur dengan takwa. Perjalanan Bilal dari seorang budak yang disiksa hingga menjadi muadzin di puncak Ka''bah yang telah dibebaskan adalah pelajaran hidup tentang kesetaraan yang diajarkan Islam.', 0, 'qc_pending', 'ai_original', 'published', 1.0, (SELECT id FROM ayah WHERE surah_id = 49 AND number = 13), datetime('now');

INSERT INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, published_at)
SELECT 'Bilal ibn Rabah: The First Call to Prayer Atop the Kaaba', 'kisah-bilal-02-adzan-di-atas-kabah', 'en', 'kisah-bilal', 2, (SELECT id FROM categories WHERE slug = 'kisah-sahabat'), 'After the conquest of Makkah — the very city that had once enslaved and tortured him for his faith — the Prophet ﷺ chose Bilal to climb atop the Kaaba and call the adhan. The voice of a former slave now rang out from the highest point in the city, proclaiming Allah''s greatness to all its people.

Some former Quraysh nobles standing below grumbled, feeling humiliated at being led by a former slave''s voice. But the Prophet ﷺ firmly rebuked such prejudice, affirming that nobility before Allah is measured only by piety, as He says: "Indeed, the most noble of you in the sight of Allah is the most righteous of you." (QS. Al-Hujurat 49:13)

Reflection: Islam recognises no hierarchy of race or social status — nobility before Allah is measured by piety alone. Bilal''s journey from a tortured slave to the muezzin atop the liberated Kaaba is a living lesson in the equality Islam teaches.', 0, 'qc_pending', 'ai_original', 'published', 1.0, (SELECT id FROM ayah WHERE surah_id = 49 AND number = 13), datetime('now');

-- ══ Khadijah binti Khuwailid ═════════════════════════════════════════════

INSERT INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, published_at)
SELECT 'Khadijah: At-Tahirah, Perempuan Suci Quraisy', 'kisah-khadijah-01-at-tahirah', 'id', 'kisah-khadijah', 1, (SELECT id FROM categories WHERE slug = 'kisah-sahabat'), 'Khadijah binti Khuwailid adalah seorang pedagang wanita paling sukses dan terpandang di Makkah, dikenal karena kejujurannya sehingga dijuluki "At-Tahirah" — Sang Suci. Ia pernah menolak banyak lamaran dari para bangsawan Quraisy sebelum akhirnya mempekerjakan seorang pemuda bernama Muhammad — yang saat itu belum diangkat menjadi nabi — untuk membawa dagangannya berniaga ke Syam.

Pembantunya, Maisarah, yang menyertai perjalanan itu, pulang dengan kagum menceritakan kejujuran luar biasa dan tanda-tanda keistimewaan yang ia saksikan pada diri pemuda tersebut sepanjang perjalanan. Tergerak oleh laporan itu dan reputasi akhlak Muhammad yang telah lama ia dengar, Khadijah mengutus perantara untuk melamarnya — sebuah langkah yang tidak biasa bagi wanita terhormat pada masanya.

Hikmah: Akhlak dan kejujuran adalah daya tarik sejati yang melampaui harta dan kedudukan. Kemandirian Khadijah sebagai pengusaha serta ketajamannya dalam memilih pasangan hidup menjadi teladan bagi seorang perempuan yang menggunakan kebijaksanaannya sendiri dalam menentukan jodoh yang saleh.', 0, 'qc_pending', 'ai_original', 'published', 1.0, NULL, datetime('now');

INSERT INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, published_at)
SELECT 'Khadijah: At-Tahirah, the Pure Woman of Quraysh', 'kisah-khadijah-01-at-tahirah', 'en', 'kisah-khadijah', 1, (SELECT id FROM categories WHERE slug = 'kisah-sahabat'), 'Khadijah bint Khuwaylid was the most successful and respected woman merchant in Makkah, known for her honesty and given the title "At-Tahirah" — the Pure One. She had turned down many proposals from Quraysh nobility before eventually hiring a young man named Muhammad — not yet appointed a prophet — to trade her goods in Syria.

Her servant Maysarah, who accompanied the journey, returned full of admiration, describing the young man''s extraordinary honesty and the remarkable signs he had witnessed along the way. Moved by that report and by the reputation for character she had long heard of, Khadijah sent an intermediary to propose marriage to him — an unusual step for a woman of her standing at the time.

Reflection: Character and honesty are a truer attraction than wealth or lineage. Khadijah''s independence as a businesswoman and her discernment in choosing a life partner stand as a model of a woman exercising her own wisdom in selecting a righteous spouse.', 0, 'qc_pending', 'ai_original', 'published', 1.0, NULL, datetime('now');

INSERT INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, published_at)
SELECT 'Khadijah: Penenang Hati Sang Nabi', 'kisah-khadijah-02-penenang-hati-nabi', 'id', 'kisah-khadijah', 2, (SELECT id FROM categories WHERE slug = 'kisah-sahabat'), 'Ketika wahyu pertama turun di Gua Hira dan Rasulullah ﷺ pulang dalam keadaan gemetar seraya berkata, "Selimuti aku, selimuti aku," Khadijah-lah yang pertama menenangkan hatinya. Ia berkata, "Sekali-kali tidak! Demi Allah, Allah tidak akan pernah menghinakanmu. Sesungguhnya engkau selalu menyambung tali silaturahmi, menanggung beban orang yang lemah, mencukupi kebutuhan orang yang tidak punya, memuliakan tamu, dan menolong orang-orang yang ditimpa musibah."

Khadijah kemudian membawanya menemui sepupunya, Waraqah bin Naufal, seorang alim Nasrani, yang mengenali bahwa yang datang kepada Muhammad adalah wahyu yang sama seperti yang pernah turun kepada Musa. Sepanjang hidupnya, Khadijah mengorbankan seluruh hartanya untuk mendukung dakwah Rasulullah ﷺ dan menjadi satu-satunya istri beliau hingga wafatnya. Bertahun-tahun setelah kepergiannya, Rasulullah ﷺ tetap mengenangnya dengan penuh cinta, bahkan malaikat Jibril pernah menyampaikan salam Allah untuknya (HR. Bukhari dan Muslim).

Hikmah: Dukungan emosional dan material seorang pasangan di saat-saat penuh ketakutan dan ketidakpastian adalah ibadah yang sangat besar nilainya. Keimanan Khadijah yang datang lebih dulu dari siapa pun — murni karena mengenal akhlak suaminya — adalah kedudukan tertinggi dari seorang pendamping sejati dalam perjuangan menegakkan kebenaran.', 0, 'qc_pending', 'ai_original', 'published', 1.0, NULL, datetime('now');

INSERT INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, published_at)
SELECT 'Khadijah: Comfort of the Prophet''s Heart', 'kisah-khadijah-02-penenang-hati-nabi', 'en', 'kisah-khadijah', 2, (SELECT id FROM categories WHERE slug = 'kisah-sahabat'), 'When the first revelation came down in the Cave of Hira and the Prophet ﷺ returned home trembling, saying, "Cover me, cover me," it was Khadijah who first calmed his heart. She said, "Never! By Allah, Allah will never disgrace you. You maintain family ties, you bear the burden of the weak, you provide for those who have nothing, you honour guests generously, and you help those struck by calamity."

Khadijah then took him to her cousin, Waraqah ibn Nawfal, a learned Christian scholar, who recognised that what had come to Muhammad was the same revelation once sent down to Moses. Throughout her life, Khadijah spent her entire fortune supporting the Prophet''s ﷺ mission and remained his only wife until her death. Years after she passed, the Prophet ﷺ still remembered her with deep love, and the angel Gabriel once conveyed Allah''s greeting of peace to her (recorded in Sahih al-Bukhari and Sahih Muslim).

Reflection: A spouse''s emotional and material support in moments of fear and uncertainty is an act of worship of immense value. Khadijah''s faith, which came before anyone else''s — purely from knowing her husband''s character — represents the highest station of a true companion in the struggle to uphold truth.', 0, 'qc_pending', 'ai_original', 'published', 1.0, NULL, datetime('now');
