-- Kisah person index — Tabi'in (the generation who learned directly from the
-- Sahabat) and Tabi'in-Tabi'in (the generation after them), same "click a
-- name" pattern. Closes the last empty tiers on /kisah so no category is
-- left showing a "being completed" placeholder. Original profiles written
-- from established, universally-taught Islamic history — not copied from
-- any single book. Figures already covered in Ulama Dunia (Abu Hanifah,
-- Malik) are deliberately not repeated here.

INSERT OR IGNORE INTO kisah_person (slug, category_slug, name_id, name_ar, title_id, summary_id, full_story_slug, sort_order) VALUES
('uwais-al-qarani', 'kisah-tabiin', 'Uwais Al-Qarani', 'أُوَيْس الْقَرَنِيّ رَحِمَهُ اللهُ', 'Tabi''in yang Dicintai Nabi ﷺ Tanpa Pernah Bertemu',
 'Uwais Al-Qarani hidup di Yaman dan tidak pernah sempat bertemu Nabi Muhammad ﷺ secara langsung karena kewajibannya merawat ibunya yang sudah tua dan lumpuh. Nabi ﷺ pernah bersabda kepada para sahabat bahwa kelak akan ada seorang tabi''in bernama Uwais yang doanya sangat mustajab, dan menyuruh Umar bin Khattab RA memintakan doa ampunan darinya bila bertemu — sebuah keutamaan luar biasa bagi seseorang yang bahkan tidak pernah menjadi sahabat Nabi secara langsung. Kisahnya menjadi teladan bahwa kedekatan kepada Allah tidak selalu diukur dari kedekatan fisik, melainkan dari keikhlasan dan bakti.', NULL, 1),
('said-bin-al-musayyib', 'kisah-tabiin', 'Sa''id bin Al-Musayyib', 'سَعِيد بْنُ الْمُسَيَّبِ رَحِمَهُ اللهُ', 'Jurist Tabi''in Terkemuka di Madinah',
 'Sa''id bin Al-Musayyib dikenal sebagai salah satu dari "Tujuh Fuqaha Madinah" (Fuqaha As-Sab''ah), tokoh yang paling dihormati keilmuannya di kalangan tabi''in dalam bidang fikih dan hadits. Ia dikenal sangat berani menyampaikan kebenaran di hadapan penguasa, bahkan pernah dipenjara dan dicambuk karena menolak berbai''at kepada seorang khalifah karena alasan prinsip. Kezuhudannya luar biasa — ia menolak berbagai tawaran kekayaan dan kedudukan demi menjaga independensi keilmuannya.', NULL, 2),
('al-hasan-al-basri', 'kisah-tabiin', 'Al-Hasan Al-Bashri', 'الْحَسَن الْبَصْرِيّ رَحِمَهُ اللهُ', 'Ulama Zuhud & Orator Ternama Basra',
 'Al-Hasan Al-Bashri lahir di Madinah dan tumbuh dekat dengan istri-istri Nabi ﷺ sebelum keluarganya pindah ke Basra, tempat ia kelak menjadi ulama paling berpengaruh di kota itu. Ia terkenal karena nasihat-nasihatnya yang menyentuh hati tentang zuhud, akhirat, dan muhasabah diri, disampaikan dengan kefasihan bahasa yang membuat majelisnya selalu dipadati pendengar dari berbagai kalangan. Banyak ulama tasawuf generasi setelahnya menjadikan wejangan-wejangannya sebagai rujukan utama dalam pembinaan akhlak dan spiritualitas.', NULL, 3),
('muhammad-bin-sirin', 'kisah-tabiin', 'Muhammad bin Sirin', 'مُحَمَّد بْنُ سِيرِينَ رَحِمَهُ اللهُ', 'Ahli Tafsir Mimpi & Hadits Tabi''in',
 'Muhammad bin Sirin dikenal luas sebagai ahli takwil mimpi paling masyhur di kalangan tabi''in, sebuah keahlian yang ia landaskan pada kaidah-kaidah ilmiah dan pemahaman mendalam terhadap Al-Qur''an serta hadits, bukan sekadar tebakan. Selain itu ia juga seorang periwayat hadits yang sangat teliti dan dikenal karena kejujuran serta ketelitiannya dalam menyampaikan riwayat — sifat yang membuat para ulama hadits sangat mempercayai jalur periwayatannya.', NULL, 4),
('urwah-bin-az-zubair', 'kisah-tabiin', 'Urwah bin Az-Zubair', 'عُرْوَة بْنُ الزُّبَيْرِ رَحِمَهُ اللهُ', 'Sejarawan Tabi''in, Putra Az-Zubair bin Awwam',
 'Urwah bin Az-Zubair adalah putra sahabat Az-Zubair bin Awwam RA dan keponakan Aisyah RA, yang menjadikannya salah satu sumber riwayat sirah Nabi ﷺ paling awal dan terpercaya karena kedekatannya langsung dengan Ummul Mukminin. Ia dikenal sebagai salah satu perintis penulisan sejarah hidup Nabi ﷺ secara sistematis, meletakkan fondasi bagi karya-karya sirah yang lebih besar di generasi setelahnya.', NULL, 5),
('umar-bin-abdul-aziz', 'kisah-tabiin', 'Umar bin Abdul Aziz', 'عُمَر بْنُ عَبْدِ الْعَزِيزِ رَحِمَهُ اللهُ', 'Khalifah Kelima yang Adil (Khulafaur Rasyidin Kelima)',
 'Umar bin Abdul Aziz, meski berasal dari Bani Umayyah yang saat itu dikenal hidup dalam kemewahan istana, mengubah total gaya hidup dan pemerintahannya begitu diangkat menjadi khalifah — mengembalikan tanah-tanah yang dirampas secara zalim, menghapus pajak yang memberatkan, dan hidup sesederhana rakyat biasa. Keadilannya yang luar biasa membuat banyak ulama menjulukinya sebagai khalifah kelima setelah Khulafaur Rasyidin (Abu Bakar, Umar, Utsman, Ali), meski masa pemerintahannya hanya berlangsung sekitar dua setengah tahun sebelum ia wafat.', NULL, 6),
('ata-bin-abi-rabah', 'kisah-tabiin', 'Atha'' bin Abi Rabah', 'عَطَاء بْنُ أَبِي رَبَاحٍ رَحِمَهُ اللهُ', 'Mufti Makkah di Zamannya',
 'Atha'' bin Abi Rabah, meski lahir sebagai budak berkulit hitam dengan kondisi fisik yang lemah, tumbuh menjadi mufti (pemberi fatwa) paling dipercaya di Makkah pada masanya, dirujuk oleh jamaah haji dari seluruh penjuru dunia Islam. Ia belajar langsung dari ratusan sahabat Nabi ﷺ yang masih hidup di masanya, menjadikan keilmuannya sangat luas dan mendalam meski latar belakangnya sederhana — teladan bahwa kemuliaan ilmu tidak mengenal status sosial.', NULL, 7);

INSERT OR IGNORE INTO kisah_person (slug, category_slug, name_id, name_ar, title_id, summary_id, full_story_slug, sort_order) VALUES
('sufyan-ats-tsauri', 'kisah-tabiin-tabiin', 'Sufyan Ats-Tsauri', 'سُفْيَان الثَّوْرِيّ رَحِمَهُ اللهُ', 'Amirul Mukminin fil Hadits (w. 161 H)',
 'Sufyan Ats-Tsauri digelari "Amirul Mukminin fil Hadits" (pemimpin kaum beriman dalam ilmu hadits) karena kedalaman dan ketelitiannya yang luar biasa dalam periwayatan. Ia hidup sangat zuhud, menolak berbagai jabatan dan kedudukan dari penguasa, bahkan sempat bersembunyi bertahun-tahun untuk menghindari paksaan menjadi hakim. Karyanya dalam bidang fikih dan hadits menjadi rujukan penting generasi ulama setelahnya, meski mazhab fikihnya sendiri tidak bertahan sebagai mazhab besar seperti keempat mazhab utama.', NULL, 1),
('al-laits-bin-sad', 'kisah-tabiin-tabiin', 'Al-Laits bin Sa''d', 'اللَّيْث بْنُ سَعْدٍ رَحِمَهُ اللهُ', 'Imam Fikih Mesir (w. 175 H)',
 'Al-Laits bin Sa''d adalah ulama besar Mesir yang keilmuannya begitu dihormati sehingga Imam Asy-Syafi''i pernah berkomentar bahwa Al-Laits sesungguhnya lebih faqih (paham fikih) daripada Imam Malik, hanya saja murid-muridnya tidak mengembangkan pemikirannya menjadi mazhab tersendiri yang bertahan. Ia juga dikenal sangat dermawan, menyalurkan sebagian besar hartanya untuk membantu para penuntut ilmu dan masyarakat miskin di sekitarnya.', NULL, 2),
('abdullah-bin-al-mubarak', 'kisah-tabiin-tabiin', 'Abdullah bin Al-Mubarak', 'عَبْدُ اللَّهِ بْنُ الْمُبَارَكِ رَحِمَهُ اللهُ', 'Ulama, Mujahid, dan Saudagar Dermawan (w. 181 H)',
 'Abdullah bin Al-Mubarak memadukan empat peran sekaligus dalam hidupnya: ulama hadits yang sangat dipercaya, mujahid yang aktif berjihad di garis depan, saudagar sukses, dan dermawan yang menyalurkan hasil perniagaannya untuk membiayai jihad serta membantu sesama penuntut ilmu. Ia menulis Kitab Az-Zuhd, salah satu karya paling awal dan berpengaruh dalam literatur zuhud dan tasawuf sunni, memadukan kezuhudan dengan kesungguhan beramal, bukan sekadar meninggalkan dunia.', NULL, 3),
('waki-bin-al-jarrah', 'kisah-tabiin-tabiin', 'Waki'' bin Al-Jarrah', 'وَكِيع بْنُ الْجَرَّاحِ رَحِمَهُ اللهُ', 'Guru Imam Ahmad bin Hanbal (w. 197 H)',
 'Waki'' bin Al-Jarrah adalah salah satu guru hadits paling berpengaruh bagi Imam Ahmad bin Hanbal, dikenal karena daya hafalnya yang sangat kuat — konon mampu meriwayatkan ribuan hadits tanpa pernah menuliskannya. Ia sangat berhati-hati dalam menerima dan meriwayatkan hadits, menjadikan jalur periwayatannya salah satu yang paling dipercaya di kalangan ahli hadits generasi setelahnya.', NULL, 4),
('yahya-bin-main', 'kisah-tabiin-tabiin', 'Yahya bin Ma''in', 'يَحْيَى بْنُ مَعِينٍ رَحِمَهُ اللهُ', 'Perintis Ilmu Kritik Perawi Hadits (w. 233 H)',
 'Yahya bin Ma''in dikenal sebagai salah satu perintis utama ilmu al-jarh wat-ta''dil (kritik dan penilaian kredibilitas perawi hadits), sebuah disiplin ilmu yang menjadi fondasi bagi penilaian keshahihan hadits hingga hari ini. Ia dikatakan telah mengevaluasi kredibilitas puluhan ribu perawi sepanjang hidupnya, dengan penilaian yang sangat dihormati dan sering dirujuk oleh Imam Bukhari maupun ulama hadits besar lainnya.', NULL, 5);
