-- Kisah lengkap SAHABAT, TABI'IN, TABI'UT-TABI'IN, dan ULAMA — berbab
-- (owner: "kisah sahabat & ulama masih sedikit/kosong, isi full berjilid
-- berbab dari sumber manapun di dunia"). Sebelumnya 37 tokoh ini hanya punya
-- ringkasan tanpa satu pun bab. Narasi bersandar pada Al-Qur'an (bila ada),
-- hadits sahih (Bukhari/Muslim/Tirmidzi), Siyar A'lam an-Nubala (Adz-Dzahabi),
-- Al-Bidayah wan-Nihayah (Ibnu Katsir), dan Thabaqat Ibnu Sa'd.
-- Idempoten: INSERT OR IGNORE + UNIQUE(person_slug, section_order).

-- ═══════════════════ KHULAFAUR RASYIDIN ═══════════════════
INSERT OR IGNORE INTO kisah_person_section (person_slug, section_order, heading_id, body_id, quran_refs) VALUES
('abu-bakar', 1, 'Nasab dan Pribadi Sebelum Islam', 'Abu Bakar Abdullah bin Abi Quhafah At-Taimi Al-Qurasyi, lahir di Makkah dua tahun beberapa bulan sesudah Tahun Gajah. Ia seorang saudagar yang jujur dan disegani, ahli nasab Quraisy, berakhlak lembut, dan tak pernah menyembah berhala di masa jahiliah. Kedekatannya dengan Nabi ﷺ sudah terjalin sejak muda sebelum kenabian.', 'HR Bukhari no. 3468'),
('abu-bakar', 2, 'Orang Dewasa Pertama yang Beriman', 'Ketika Nabi ﷺ menyampaikan Islam, Abu Bakar langsung membenarkan tanpa ragu — karena itu ia digelari Ash-Shiddiq. Rasulullah ﷺ bersabda, "Tidaklah aku mengajak seorang pun kepada Islam melainkan ia sempat berpikir, kecuali Abu Bakar." Dengan hartanya ia memerdekakan budak-budak yang disiksa karena iman, di antaranya Bilal bin Rabah.', 'QS Al-Lail: 5–7 (ditafsirkan tentang Abu Bakar) · HR Bukhari no. 3661'),
('abu-bakar', 3, 'Sahabat dalam Hijrah dan "Tsani Itsnain"', 'Abu Bakar menemani Nabi ﷺ berhijrah dan bersembunyi di Gua Tsur. Saat kaki para pengejar tepat di atas mereka, ia cemas, namun Nabi ﷺ menenangkan, "Jangan bersedih, sesungguhnya Allah bersama kita." Al-Qur''an mengabadikan peristiwa ini dan menyebut Abu Bakar sebagai "orang kedua dari dua orang" (tsani itsnain).', 'QS At-Taubah: 40'),
('abu-bakar', 4, 'Diangkat Menjadi Khalifah Pertama', 'Menjelang wafat, Nabi ﷺ memerintahkan Abu Bakar mengimami salat kaum muslimin — isyarat kepemimpinan. Setelah wafatnya Rasulullah ﷺ, kaum muslimin membaiat Abu Bakar di Saqifah. Dengan tegas ia menyampaikan, "Barangsiapa menyembah Muhammad, sungguh Muhammad telah wafat; barangsiapa menyembah Allah, sesungguhnya Allah Maha Hidup dan tidak mati," lalu membacakan firman Allah.', 'QS Ali ''Imran: 144 · HR Bukhari no. 1241'),
('abu-bakar', 5, 'Memerangi Nabi Palsu dan Pembangkang Zakat', 'Sepeninggal Nabi ﷺ, banyak kabilah murtad, muncul nabi-nabi palsu (Musailamah), dan sebagian menolak membayar zakat. Abu Bakar bersikap tegas, "Demi Allah, seandainya mereka menahan seutas tali unta yang dahulu mereka tunaikan kepada Rasulullah, niscaya aku perangi mereka." Perang Riddah menyelamatkan kesatuan umat.', 'HR Bukhari no. 1400 · HR Muslim no. 20'),
('abu-bakar', 6, 'Pengumpulan Pertama Mushaf Al-Qur''an', 'Setelah banyak penghafal Al-Qur''an gugur dalam Perang Yamamah, atas usul Umar, Abu Bakar memerintahkan Zaid bin Tsabit menghimpun Al-Qur''an dari hafalan dan tulisan menjadi satu mushaf. Inilah pengumpulan resmi pertama yang menjaga keutuhan Al-Qur''an hingga hari ini.', 'QS Al-Hijr: 9 · HR Bukhari no. 4986'),
('abu-bakar', 7, 'Wafat dan Keutamaannya', 'Abu Bakar memerintah sekitar dua tahun tiga bulan, hidup zuhud meski berkuasa, lalu wafat pada usia 63 tahun dan dimakamkan di sisi Rasulullah ﷺ. Nabi ﷺ bersabda, "Seandainya aku boleh mengambil khalil (kekasih) selain Tuhanku, niscaya Abu Bakar-lah khalil-ku." Ia manusia terbaik umat ini setelah para nabi.', 'HR Bukhari no. 3656 · HR Bukhari no. 3654'),

('umar-bin-khattab', 1, 'Sang Penentang yang Menjadi Pembela', 'Umar bin Khattab Al-Adawi Al-Qurasyi, berperawakan tinggi, kuat, dan disegani. Pada mulanya ia keras menentang Islam, hingga suatu hari berniat membunuh Nabi ﷺ. Di jalan ia mendengar adiknya membaca surah Thaha; hatinya luluh oleh keagungan Al-Qur''an dan ia pun masuk Islam pada tahun keenam kenabian.', 'QS Thaha: 1–8'),
('umar-bin-khattab', 2, 'Islam yang Menguatkan Dakwah', 'Dengan masuknya Umar, kaum muslimin berani salat terang-terangan di sekitar Ka''bah untuk pertama kalinya. Nabi ﷺ pernah berdoa, "Ya Allah, muliakanlah Islam dengan salah satu dari dua Umar," dan Allah mengabulkannya melalui Umar bin Khattab. Ia digelari Al-Faruq — pembeda antara yang haq dan batil.', 'HR Tirmidzi no. 3681'),
('umar-bin-khattab', 3, 'Pendapat-Pendapat yang Dibenarkan Wahyu', 'Beberapa kali pandangan Umar kemudian dikuatkan oleh turunnya ayat — tentang maqam Ibrahim sebagai tempat salat, hijab bagi istri-istri Nabi, dan sikap terhadap tawanan Badar. Nabi ﷺ bersabda, "Sungguh pada umat sebelum kalian ada orang-orang yang diberi ilham; jika ada pada umatku, dialah Umar."', 'QS Al-Baqarah: 125 · QS Al-Ahzab: 53 · HR Bukhari no. 3689'),
('umar-bin-khattab', 4, 'Khalifah yang Adil dan Penakluk', 'Sebagai khalifah kedua, Umar memperluas Islam ke Syam, Mesir, Irak, dan Persia, namun tetap hidup sederhana dengan baju bertambal. Ia menegakkan keadilan tanpa pandang bulu, meletakkan dasar administrasi negara, dan berkata, "Seandainya seekor keledai tergelincir di Irak, aku takut Allah menanyaiku mengapa tidak kuratakan jalan untuknya."', 'HR Bukhari no. 3700'),
('umar-bin-khattab', 5, 'Peletak Fondasi Negara Islam', 'Umar merintis penanggalan Hijriah, membentuk diwan (administrasi gaji), mendirikan baitul mal, mengangkat qadhi, menata pasukan dan kota-kota garnisun seperti Kufah dan Bashrah, serta menghidupkan salat tarawih berjamaah. Ijtihad-ijtihadnya menjadi rujukan fiqih kenegaraan.', 'HR Bukhari no. 2010'),
('umar-bin-khattab', 6, 'Syahid di Mihrab dan Keutamaannya', 'Umar ditikam oleh Abu Lu''lu''ah, seorang Majusi, saat mengimami salat Subuh, lalu wafat sebagai syahid pada tahun 23 H dan dimakamkan di sisi Nabi ﷺ dan Abu Bakar. Nabi ﷺ pernah bermimpi melihat istana di surga milik Umar. Ia teladan keadilan dan ketegasan yang berpadu dengan kelembutan hati.', 'HR Bukhari no. 3691 · HR Bukhari no. 3242'),

('utsman-bin-affan', 1, 'Pemilik Dua Cahaya', 'Utsman bin Affan Al-Umawi Al-Qurasyi, saudagar kaya yang dermawan dan sangat pemalu. Ia masuk Islam di masa awal melalui ajakan Abu Bakar. Ia dinikahkan Nabi ﷺ dengan putri beliau, Ruqayyah, dan setelah wafatnya dinikahkan pula dengan Ummu Kultsum — karena itu ia digelari Dzun-Nurain, pemilik dua cahaya.', 'HR Tirmidzi no. 3706'),
('utsman-bin-affan', 2, 'Kedermawanan yang Melegenda', 'Utsman membeli sumur Raumah dari seorang Yahudi lalu mewakafkannya untuk kaum muslimin, dan membiayai sepertiga pasukan pada Perang Tabuk (Jaisyul ''Usrah). Nabi ﷺ bersabda, "Tidaklah membahayakan Utsman apa pun yang ia lakukan setelah hari ini," karena besarnya infaknya di jalan Allah.', 'QS At-Taubah: 100 · HR Tirmidzi no. 3701'),
('utsman-bin-affan', 3, 'Khalifah dan Penyatuan Mushaf', 'Sebagai khalifah ketiga, Utsman menyatukan bacaan Al-Qur''an dalam satu rasm (Mushaf Utsmani) ketika perbedaan qiraat mulai menimbulkan perselisihan, lalu mengirim salinannya ke berbagai negeri. Jasa ini menjaga persatuan umat atas satu mushaf hingga kini.', 'QS Al-Qiyamah: 17–18 · HR Bukhari no. 4987'),
('utsman-bin-affan', 4, 'Fitnah dan Kesabaran', 'Di akhir kekhalifahannya muncul fitnah yang digerakkan para pemberontak. Utsman menolak menumpahkan darah kaum muslimin demi mempertahankan jabatannya, dan bersabar meski rumahnya dikepung. Ia teguh memegang wasiat Nabi ﷺ agar tidak melepas "baju" (amanah) yang Allah pakaikan kepadanya.', 'HR Tirmidzi no. 3705'),
('utsman-bin-affan', 5, 'Syahid dalam Keadaan Berpuasa Membaca Al-Qur''an', 'Para pemberontak menyerbu dan membunuh Utsman saat ia berpuasa dan sedang membaca mushaf, hingga darahnya menetes di atas ayat "Fasayakfikahumullah" (maka Allah akan memelihara engkau dari mereka). Ia wafat sebagai syahid pada tahun 35 H, meninggalkan teladan kesabaran, rasa malu, dan kedermawanan.', 'QS Al-Baqarah: 137'),

('ali-bin-abi-thalib', 1, 'Anak yang Tumbuh di Rumah Kenabian', 'Ali bin Abi Thalib, sepupu Nabi ﷺ, diasuh langsung oleh beliau sejak kecil. Ia adalah anak-anak pertama yang beriman kepada Islam, tumbuh dalam bimbingan wahyu, dan tidak pernah bersujud kepada berhala — karena itu ia dijuluki "karramallahu wajhah".', 'HR Tirmidzi no. 3735'),
('ali-bin-abi-thalib', 2, 'Tidur di Ranjang Nabi pada Malam Hijrah', 'Pada malam kaum musyrik hendak membunuh Nabi ﷺ, Ali rela tidur di ranjang beliau menggantikan posisinya, menanggung risiko demi keselamatan Rasulullah, lalu mengembalikan titipan-titipan orang kepada pemiliknya sebelum menyusul hijrah. Allah memuji jiwa yang menjual dirinya demi ridha-Nya.', 'QS Al-Baqarah: 207'),
('ali-bin-abi-thalib', 3, 'Panji di Khaibar dan Menantu Nabi', 'Nabi ﷺ menikahkan Ali dengan putrinya, Fatimah Az-Zahra, dan dari keduanya lahir Hasan dan Husain. Pada Perang Khaibar, Nabi ﷺ bersabda akan memberikan panji kepada seorang yang mencintai Allah dan Rasul-Nya serta dicintai keduanya, lalu menyerahkannya kepada Ali, dan Allah memenangkan kaum muslimin melalui tangannya.', 'HR Bukhari no. 3701 · HR Muslim no. 2404'),
('ali-bin-abi-thalib', 4, 'Gerbang Ilmu dan Hakim yang Cerdas', 'Nabi ﷺ bersabda, "Aku kota ilmu dan Ali pintunya." Umar sendiri sering berlindung dari perkara sulit tanpa kehadiran Ali. Ia terkenal fasih, dalam ilmunya, tajam dalam memutuskan perkara, dan menjadi rujukan tafsir serta qadha di kalangan sahabat.', 'HR Tirmidzi no. 3723'),
('ali-bin-abi-thalib', 5, 'Khalifah di Tengah Fitnah', 'Ali diangkat menjadi khalifah keempat setelah wafatnya Utsman, di masa penuh fitnah dan perpecahan. Ia berupaya menegakkan keadilan dan mempersatukan umat di tengah Perang Jamal dan Shiffin, tetap menjaga kehormatan para sahabat dan tidak melampaui batas syariat.', 'QS Al-Hujurat: 9–10'),
('ali-bin-abi-thalib', 6, 'Zuhud dan Keadilannya', 'Meski khalifah, Ali hidup sangat sederhana, membagi harta baitul mal secara merata, dan berjalan di pasar tanpa pengawal. Ucapan-ucapan hikmahnya tentang dunia, ilmu, dan akhirat dikumpulkan dan dikaji sepanjang zaman sebagai teladan kezuhudan pemimpin.', 'HR Bukhari no. 3705'),
('ali-bin-abi-thalib', 7, 'Syahid di Kufah', 'Ali ditikam oleh Abdurrahman bin Muljam, seorang Khawarij, saat hendak salat Subuh di masjid Kufah, dan wafat sebagai syahid pada tahun 40 H. Dengan wafatnya berakhir masa Khulafaur Rasyidin yang lurus, yang tentangnya Nabi ﷺ berpesan agar umat berpegang teguh.', 'HR Abu Dawud no. 4607 · HR Tirmidzi no. 2676');

-- ═══════════════════ SAHABAT LAINNYA ═══════════════════
INSERT OR IGNORE INTO kisah_person_section (person_slug, section_order, heading_id, body_id, quran_refs) VALUES
('khalid-bin-walid', 1, 'Pedang Allah yang Terhunus', 'Khalid bin Walid Al-Makhzumi, ahli perang Quraisy yang dahulu menjadi kunci kekalahan kaum muslimin di Uhud, kemudian masuk Islam sebelum Fathu Makkah. Nabi ﷺ menggelarinya Saifullah — Pedang Allah — dan tidak pernah ia kalah dalam satu pertempuran pun yang ia pimpin.', 'HR Bukhari no. 3757'),
('khalid-bin-walid', 2, 'Mu''tah: Panji yang Tak Pernah Jatuh', 'Pada Perang Mu''tah melawan Romawi, tiga panglima gugur berturut-turut; Khalid mengambil panji dan menyelamatkan pasukan yang jauh lebih kecil dari kehancuran. Nabi ﷺ mengabarkan peristiwa itu dari Madinah, menyebut sembilan pedang patah di tangan Khalid hari itu.', 'HR Bukhari no. 4262'),
('khalid-bin-walid', 3, 'Penakluk di Masa Abu Bakar dan Umar', 'Dalam Perang Riddah dan penaklukan Irak serta Syam, Khalid memimpin kemenangan-kemenangan besar termasuk Yarmuk melawan Romawi. Ketika Umar memberhentikannya dari komando agar manusia tidak mengagungkannya berlebihan, Khalid taat tanpa keluh — teladan keikhlasan seorang panglima.', 'QS Ash-Shaff: 4'),
('khalid-bin-walid', 4, 'Wafat di Atas Ranjang', 'Khalid yang mendambakan syahid di medan justru wafat di atas tempat tidurnya di Homs. Ia berkata, "Tidak ada sejengkal pun di tubuhku kecuali ada bekas luka karena Allah," lalu menyesali bahwa ia mati seperti unta mati. Kisahnya mengajarkan bahwa ajal di tangan Allah, dan pahala mengikuti niat.', 'QS Ali ''Imran: 145'),

('bilal-bin-rabah', 1, 'Budak yang Disiksa karena Tauhid', 'Bilal bin Rabah, seorang budak dari Habasyah, termasuk yang pertama beriman. Tuannya, Umayyah bin Khalaf, menyiksanya di terik padang pasir dengan batu besar di dada agar murtad, namun Bilal hanya mengucap, "Ahad, Ahad" (Yang Maha Esa). Abu Bakar lalu membelinya dan memerdekakannya.', 'QS Al-Ikhlas: 1 · QS Al-Lail: 17–21'),
('bilal-bin-rabah', 2, 'Muazin Pertama Islam', 'Karena suaranya yang merdu dan lantang, Bilal dijadikan muazin pertama Rasulullah ﷺ. Ia mengumandangkan azan di Madinah, dan pada Fathu Makkah naik ke atas Ka''bah untuk azan — pemandangan yang meruntuhkan kesombongan jahiliah bahwa seorang bekas budak berkulit hitam memuliakan Rumah Allah.', 'QS Al-Hujurat: 13'),
('bilal-bin-rabah', 3, 'Terompah di Surga', 'Nabi ﷺ mengabarkan bahwa beliau mendengar suara terompah Bilal di surga, karena Bilal senantiasa berwudhu dan salat sunnah dua rakaat setiap kali batal wudhu. Setelah wafat Nabi ﷺ, ia tak sanggup lagi azan karena tangisnya. Kisahnya adalah lambang kemuliaan takwa di atas nasab dan warna kulit.', 'HR Bukhari no. 1149'),

('abu-hurairah', 1, 'Sahabat Perawi Hadits Terbanyak', 'Abu Hurairah Ad-Dausi memeluk Islam pada tahun Khaibar dan menyertai Nabi ﷺ siang malam dengan mengorbankan urusan dunianya demi menghafal hadits. Ia meriwayatkan lebih dari lima ribu hadits — terbanyak di antara para sahabat — sehingga menjadi salah satu tiang periwayatan sunnah.', 'HR Bukhari no. 118'),
('abu-hurairah', 2, 'Doa Nabi agar Kuat Hafalannya', 'Abu Hurairah pernah mengeluh mudah lupa, lalu Nabi ﷺ memerintahkannya membentangkan kain, mendoakannya, dan sejak itu ia tidak pernah lupa apa yang didengarnya. Ia juga terkenal berbakti kepada ibunya dan mendoakannya hingga sang ibu masuk Islam.', 'HR Bukhari no. 119 · HR Muslim no. 2491'),
('abu-hurairah', 3, 'Zuhud dan Wafatnya', 'Meski banyak ilmunya, Abu Hurairah hidup miskin dan zuhud, kerap menahan lapar demi menuntut ilmu. Ia wafat di Madinah sekitar tahun 57 H. Warisannya adalah lautan hadits tentang akidah, ibadah, akhlak, dan hari akhir yang menjadi rujukan umat sepanjang masa.', 'QS Al-Ankabut: 43'),

('salman-al-farisi', 1, 'Pencari Kebenaran dari Persia', 'Salman Al-Farisi berasal dari Persia, semula penyembah api, lalu memeluk Nasrani dan berkelana dari guru ke guru mencari agama yang benar. Guru terakhirnya mengabarkan akan datangnya seorang nabi di tanah Arab dengan tanda-tanda tertentu, maka Salman pun berangkat mencarinya.', 'QS Al-Baqarah: 62'),
('salman-al-farisi', 2, 'Menemukan Nabi yang Dinanti', 'Dalam perjalanannya Salman diperdaya dan dijual sebagai budak hingga sampai ke Madinah. Ketika Nabi ﷺ hijrah, Salman menguji tanda-tanda kenabian: menerima hadiah tetapi tidak makan sedekah, dan adanya cap kenabian di punggung beliau. Semua cocok, dan Salman pun beriman.', 'QS Al-A''raf: 157'),
('salman-al-farisi', 3, 'Ide Parit dalam Perang Khandaq', 'Pada Perang Ahzab, Salman mengusulkan menggali parit (khandaq) mengelilingi Madinah — strategi Persia yang belum dikenal Arab — sehingga pasukan sekutu gagal menembus kota. Kaum Muhajirin dan Anshar sama-sama mengklaimnya, lalu Nabi ﷺ bersabda, "Salman termasuk keluarga kami, ahlul bait."', 'QS Al-Ahzab: 9–11'),
('salman-al-farisi', 4, 'Gubernur yang Hidup Sederhana', 'Salman diangkat menjadi gubernur Mada''in di masa Umar, namun tetap hidup dari hasil kerja tangannya menganyam daun kurma, tidur di emperan, dan membagikan gajinya untuk fakir miskin. Ia teladan bahwa ilmu, hikmah, dan kekuasaan tidak menggoyahkan kezuhudan.', 'QS Al-Hasyr: 9'),

('aisyah-binti-abu-bakar', 1, 'Ummul Mukminin yang Cerdas', 'Aisyah binti Abu Bakar, istri Nabi ﷺ yang paling beliau cintai, dikenal sangat cerdas, kuat hafalannya, dan tajam pemahamannya. Ia tumbuh di rumah iman dan menjadi rujukan utama para sahabat dalam fiqih, tafsir, hadits, faraidh, bahkan syair dan pengobatan.', 'HR Bukhari no. 3775'),
('aisyah-binti-abu-bakar', 2, 'Dibersihkan dari Langit', 'Ketika kaum munafik menyebarkan tuduhan dusta (haditsul ifki) atas Aisyah, ia bersabar dan berserah kepada Allah selama berhari-hari, hingga Allah menurunkan ayat-ayat yang membersihkan namanya dari atas tujuh langit. Peristiwa ini menegaskan kesucian dan kemuliaannya.', 'QS An-Nur: 11–20'),
('aisyah-binti-abu-bakar', 3, 'Guru Para Sahabat dan Tabi''in', 'Aisyah meriwayatkan lebih dari dua ribu hadits dan menjadi guru bagi banyak sahabat dan tabi''in. Urwah bin Az-Zubair berkata ia tak pernah melihat orang yang lebih paham Al-Qur''an, faraidh, halal-haram, syair, dan nasab daripada Aisyah.', 'QS Al-Ahzab: 34'),
('aisyah-binti-abu-bakar', 4, 'Wafat dan Warisan Ilmunya', 'Aisyah wafat pada tahun 58 H dan dimakamkan di Baqi''. Seperempat hukum-hukum syariat, menurut sebagian ulama, sampai kepada umat melalui periwayatannya. Ia teladan wanita berilmu, penyabar, dermawan, dan sangat wara''.', 'QS Al-Ahzab: 33'),

('fatimah-az-zahra', 1, 'Putri Kesayangan Rasulullah', 'Fatimah Az-Zahra, putri bungsu Nabi ﷺ dari Khadijah, sangat mirip dengan ayahnya dalam cara berjalan dan berbicara. Nabi ﷺ mencintainya dengan istimewa; bila ia datang, beliau berdiri menyambut. Ia digelari "penghulu wanita ahli surga".', 'HR Bukhari no. 3623 · HR Tirmidzi no. 3872'),
('fatimah-az-zahra', 2, 'Rumah Tangga yang Penuh Kesabaran', 'Fatimah dinikahi Ali bin Abi Thalib dan hidup sangat sederhana, menggiling gandum sendiri hingga tangannya lecet. Nabi ﷺ mengajarkan keduanya membaca tasbih, tahmid, dan takbir sebelum tidur sebagai ganti pembantu — dzikir yang masyhur sebagai "Tasbih Fatimah".', 'HR Bukhari no. 5361'),
('fatimah-az-zahra', 3, 'Yang Pertama Menyusul Nabi', 'Menjelang wafat, Nabi ﷺ membisikkan bahwa Fatimah adalah keluarga pertama yang akan menyusul beliau, dan bahwa ia penghulu wanita mukminah — maka Fatimah tersenyum. Ia wafat enam bulan setelah ayahnya. Dari keturunannyalah, melalui Hasan dan Husain, berlanjut nasab keturunan Nabi ﷺ.', 'QS Al-Ahzab: 33 · HR Bukhari no. 3624'),

('mushab-bin-umair', 1, 'Pemuda Termanja yang Meninggalkan Dunia', 'Mush''ab bin ''Umair adalah pemuda Makkah paling tampan dan mewah, dimanjakan ibunya dengan pakaian dan wangian termahal. Ketika ia memeluk Islam, ia rela meninggalkan semua kemewahan itu, disiksa dan diusir keluarganya, memilih iman di atas dunia.', 'QS Al-Kahfi: 28'),
('mushab-bin-umair', 2, 'Duta Islam Pertama ke Madinah', 'Nabi ﷺ mengutus Mush''ab sebagai duta dan guru pertama ke Yatsrib (Madinah) untuk mengajarkan Al-Qur''an dan Islam. Melalui hikmah dan kelembutannya, banyak tokoh Aus dan Khazraj masuk Islam, menyiapkan jalan bagi hijrah Nabi ﷺ.', 'QS An-Nahl: 125'),
('mushab-bin-umair', 3, 'Syahid di Uhud dengan Kain yang Tak Cukup', 'Pada Perang Uhud, Mush''ab memegang panji hingga kedua tangannya terputus dan ia gugur sebagai syahid. Ketika hendak dikafani, kainnya tidak cukup menutupi tubuh: bila menutup kepala, kakinya tersingkap. Nabi ﷺ menangis mengenangnya sebagai orang yang menepati janjinya kepada Allah.', 'QS Al-Ahzab: 23');

-- ═══════════════════ IMAM MAZHAB EMPAT ═══════════════════
INSERT OR IGNORE INTO kisah_person_section (person_slug, section_order, heading_id, body_id, quran_refs) VALUES
('imam-abu-hanifah', 1, 'Imam Ahli Ra''yi dari Kufah', 'Nu''man bin Tsabit, dikenal sebagai Imam Abu Hanifah (80–150 H), lahir di Kufah pada masa tabi''in dan sempat berjumpa sebagian sahabat. Semula seorang saudagar kain yang jujur, ia kemudian menekuni ilmu fiqih hingga menjadi imam mazhab pertama dari empat mazhab Ahlussunnah.', 'QS Az-Zumar: 9'),
('imam-abu-hanifah', 2, 'Metode Qiyas dan Istihsan', 'Abu Hanifah masyhur dengan ketajaman analisis dan penggunaan qiyas (analogi) serta istihsan dalam menetapkan hukum atas masalah-masalah baru. Majelisnya berbentuk musyawarah bersama murid-murid seperti Abu Yusuf dan Muhammad bin Al-Hasan, yang kemudian menyebarkan dan membukukan mazhabnya.', 'QS An-Nisa: 59'),
('imam-abu-hanifah', 3, 'Wara'' dan Kedermawanan', 'Ia sangat wara'' dalam harta, memilih berdagang agar tidak bergantung pada pemberian penguasa, dan banyak bersedekah kepada murid dan fakir miskin. Ia terkenal panjang salat malamnya hingga dijuluki "al-watad" (pasak) karena lamanya berdiri beribadah.', 'QS As-Sajdah: 16'),
('imam-abu-hanifah', 4, 'Ujian dari Penguasa', 'Abu Hanifah menolak jabatan qadhi yang ditawarkan penguasa karena khawatir tidak mampu berlaku adil di bawah tekanan, hingga ia dipenjara dan disiksa. Ia lebih memilih derita penjara daripada mengorbankan kejujuran ilmunya.', 'QS Al-Ma''idah: 8'),
('imam-abu-hanifah', 5, 'Wafat dan Warisan Mazhab Hanafi', 'Abu Hanifah wafat di penjara Baghdad tahun 150 H. Mazhabnya menjadi yang paling luas pengikutnya di dunia — dari Turki, Asia Tengah, anak benua India, hingga sebagian besar dunia Islam — dan menjadi rujukan fiqih peradaban besar.', 'QS Al-Kahfi: 30'),

('imam-malik', 1, 'Imam Darul Hijrah', 'Malik bin Anas Al-Ashbahi (93–179 H) lahir dan hidup di Madinah, kota Nabi ﷺ, sehingga digelari Imam Darul Hijrah. Ia menuntut ilmu kepada ratusan guru dari kalangan tabi''in dan sangat mengagungkan hadits serta amal penduduk Madinah.', 'QS At-Taubah: 100'),
('imam-malik', 2, 'Al-Muwaththa'': Kitab Hadits-Fiqih Pertama', 'Karya besarnya, Al-Muwaththa'', adalah salah satu kitab hadits sekaligus fiqih paling awal dan paling sahih, disusun dengan sangat teliti selama bertahun-tahun. Imam Syafi''i berkata, "Tidak ada kitab di muka bumi yang lebih sahih setelah Kitabullah daripada Al-Muwaththa'' Malik" (pada masanya).', 'QS Al-Hijr: 9'),
('imam-malik', 3, 'Pengagungan terhadap Hadits Nabi', 'Malik tidak menyampaikan hadits kecuali dalam keadaan bersuci, berpakaian rapi, dan penuh khusyuk, sebagai bentuk pemuliaan terhadap sabda Rasulullah ﷺ. Ia berhati-hati dalam berfatwa dan sering berkata "la adri" (aku tidak tahu) bila ragu.', 'QS Al-Hujurat: 2'),
('imam-malik', 4, 'Teguh di Bawah Tekanan Penguasa', 'Malik pernah didera karena menyampaikan fatwa yang tidak disukai penguasa, namun ia tetap teguh menyampaikan kebenaran ilmu. Kedudukannya sebagai imam justru semakin diagungkan umat karena keteguhannya.', 'QS Al-Ma''idah: 67'),
('imam-malik', 5, 'Wafat dan Mazhab Maliki', 'Malik wafat di Madinah tahun 179 H. Mazhab Maliki tersebar luas di Afrika Utara, Andalusia dahulu, dan Afrika Barat hingga kini, dengan ciri kuat berpegang pada amal ahli Madinah dan hadits.', 'QS Fathir: 32'),

('imam-syafii', 1, 'Nashirus Sunnah dari Keturunan Quraisy', 'Muhammad bin Idris Asy-Syafi''i (150–204 H) lahir di Gaza dari nasab yang bertemu dengan Nabi ﷺ. Yatim dan miskin sejak kecil, ia menghafal Al-Qur''an pada usia tujuh tahun dan Al-Muwaththa'' pada usia sepuluh tahun, lalu berguru kepada Imam Malik di Madinah.', 'QS Al-Mujadalah: 11'),
('imam-syafii', 2, 'Perumus Ilmu Ushul Fiqih', 'Melalui kitabnya Ar-Risalah, Syafi''i menjadi orang pertama yang menyusun kaidah baku ushul fiqih — cara beristinbath hukum dari Al-Qur''an, Sunnah, ijma'', dan qiyas secara sistematis. Ia menjembatani mazhab ahli hadits dan ahli ra''yi.', 'QS An-Nisa: 59 · QS An-Nisa: 83'),
('imam-syafii', 3, 'Qaul Qadim dan Qaul Jadid', 'Setelah pindah ke Mesir dan menemukan realitas serta hadits baru, Syafi''i meninjau ulang sebagian pendapatnya, sehingga dikenal qaul qadim (pendapat lama di Irak) dan qaul jadid (pendapat baru di Mesir). Ini menunjukkan kejujuran ilmiah dan sikap mengikuti dalil, bukan gengsi.', 'QS Az-Zumar: 18'),
('imam-syafii', 4, 'Kecerdasan, Syair, dan Akhlak', 'Syafi''i seorang yang sangat cerdas, ahli bahasa dan syair, serta berakhlak mulia dan tawadhu. Ia berkata, "Ilmu itu bukan yang dihafal, tetapi yang memberi manfaat," dan menekankan adab di atas ilmu. Bait-bait nasihatnya dikaji hingga kini.', 'QS Fathir: 28'),
('imam-syafii', 5, 'Berpegang pada Hadits Sahih', 'Prinsipnya yang masyhur, "Jika sebuah hadits sahih, maka itulah mazhabku," menegaskan bahwa dalil di atas taklid. Ia mengajarkan umat untuk selalu kembali kepada Al-Qur''an dan Sunnah.', 'QS Al-Ahzab: 36'),
('imam-syafii', 6, 'Wafat dan Mazhab Syafi''i', 'Syafi''i wafat di Mesir tahun 204 H. Mazhabnya menjadi pegangan mayoritas kaum muslimin di Mesir, Syam, Yaman, Asia Tenggara termasuk Nusantara, dan menjadi induk kurikulum fiqih pesantren.', 'QS Al-Anbiya: 7'),

('imam-ahmad-bin-hanbal', 1, 'Imam Ahlussunnah', 'Ahmad bin Hanbal Asy-Syaibani (164–241 H) lahir di Baghdad, yatim sejak kecil, dan menempuh perjalanan panjang menuntut hadits ke Hijaz, Yaman, dan Syam. Ia menghafal ratusan ribu hadits dan menjadi imam ahli hadits sekaligus imam mazhab keempat.', 'QS Al-Fathir: 28'),
('imam-ahmad-bin-hanbal', 2, 'Al-Musnad: Samudra Hadits', 'Karya besarnya, Al-Musnad, menghimpun lebih dari dua puluh tujuh ribu hadits yang ia saring dari ratusan ribu, disusun berdasarkan nama sahabat perawinya. Kitab ini menjadi salah satu rujukan hadits terbesar umat.', 'QS Al-Hijr: 9'),
('imam-ahmad-bin-hanbal', 3, 'Ujian Fitnah Khalqul Qur''an', 'Ketika penguasa memaksakan paham bahwa Al-Qur''an adalah makhluk, Ahmad menolak dengan teguh meski dipenjara dan didera bertahun-tahun. Keteguhannya menyelamatkan akidah umat, hingga ia digelari "Imam Ahlussunnah wal Jama''ah".', 'QS Asy-Syura: 11 · QS Ibrahim: 27'),
('imam-ahmad-bin-hanbal', 4, 'Zuhud yang Sempurna', 'Ahmad menolak hadiah dan pemberian penguasa, hidup miskin dengan penuh qana''ah, dan sangat wara''. Ketika keadaan telah aman dan penguasa memuliakannya, ia justru menjauh dari dunia dan kemasyhuran.', 'QS Al-Qashash: 83'),
('imam-ahmad-bin-hanbal', 5, 'Guru Umat dan Akhlaknya', 'Meski kedudukannya tinggi, Ahmad sangat tawadhu, lembut kepada murid, dan cepat memaafkan orang yang menzaliminya di masa fitnah. Ia berkata, "Aku telah menghalalkan (memaafkan) setiap orang kecuali ahli bid''ah."', 'QS Ali ''Imran: 134'),
('imam-ahmad-bin-hanbal', 6, 'Wafat dan Mazhab Hanbali', 'Ahmad wafat di Baghdad tahun 241 H; ratusan ribu manusia menyalatkannya. Mazhab Hanbali kini menjadi pegangan di Jazirah Arab dan menjadi salah satu pilar fiqih Ahlussunnah.', 'QS An-Nur: 37'),

-- ═══════════════════ IMAM HADITS ═══════════════════
('imam-bukhari', 1, 'Amirul Mukminin dalam Hadits', 'Muhammad bin Isma''il Al-Bukhari (194–256 H) lahir di Bukhara, buta di masa kecil lalu Allah kembalikan penglihatannya berkat doa ibunya. Sejak kecil hafalannya luar biasa; ia menghafal ratusan ribu hadits dengan sanadnya dan digelari "Amirul Mukminin fil Hadits".', 'QS Al-Mujadalah: 11'),
('imam-bukhari', 2, 'Shahih Al-Bukhari: Kitab Tershahih', 'Selama enam belas tahun ia menyaring hadits, menuliskan setiap hadits dalam Shahih-nya hanya setelah mandi dan salat istikharah dua rakaat. Hasilnya, Shahih Al-Bukhari disepakati umat sebagai kitab paling sahih setelah Kitabullah.', 'QS Al-Hijr: 9'),
('imam-bukhari', 3, 'Ketelitian dan Ujian Hafalan', 'Para ulama Baghdad pernah mengujinya dengan seratus hadits yang sanad dan matannya sengaja ditukar; Bukhari mengembalikan seluruhnya ke tempat yang benar tanpa keliru — bukti ketelitian dan kekuatan hafalannya yang menakjubkan.', 'QS Az-Zumar: 9'),
('imam-bukhari', 4, 'Wara'' dan Wafatnya', 'Bukhari sangat wara'', dermawan, dan menjauhi penguasa hingga diusir dari kotanya karena menolak mengajar khusus untuk anak-anak gubernur. Ia wafat di Khartank dekat Samarkand tahun 256 H, meninggalkan warisan ilmu yang menjaga sunnah sepanjang zaman.', 'QS Al-Kahfi: 110'),

('imam-muslim', 1, 'Penyusun Shahih Kedua', 'Muslim bin Al-Hajjaj An-Naisaburi (204–261 H) lahir di Naisabur, mengembara menuntut hadits ke berbagai negeri, dan berguru antara lain kepada Imam Al-Bukhari yang sangat ia muliakan. Ia termasuk imam hadits terbesar sepanjang sejarah.', 'QS At-Taubah: 122'),
('imam-muslim', 2, 'Shahih Muslim dan Metode Penyusunannya', 'Kitab Shahih Muslim disusun dengan metode yang sangat rapi: menghimpun seluruh jalur satu hadits pada satu tempat, memudahkan perbandingan sanad. Bersama Shahih Al-Bukhari, ia dikenal sebagai "Shahihain" — dua kitab paling sahih setelah Al-Qur''an.', 'QS Al-Hijr: 9'),
('imam-muslim', 3, 'Akhlak dan Wafatnya', 'Muslim seorang saudagar yang wara'' dan mandiri, tidak bergantung pada pemberian orang. Ia wafat di Naisabur tahun 261 H. Warisannya menjadi tiang kedua periwayatan hadits sahih yang dikaji di seluruh dunia Islam.', 'QS Al-Baqarah: 197'),

('imam-at-tirmidzi', 1, 'Penyusun Al-Jami'' (Sunan Tirmidzi)', 'Muhammad bin Isa At-Tirmidzi (209–279 H) lahir di Tirmidz, murid Imam Al-Bukhari, dan salah satu penyusun Kutubus Sittah. Kitabnya, Al-Jami'' (Sunan At-Tirmidzi), istimewa karena menerangkan derajat tiap hadits (sahih, hasan, dhaif) dan pendapat para ulama fiqih.', 'QS An-Nahl: 43'),
('imam-at-tirmidzi', 2, 'Perintis Istilah "Hasan"', 'Tirmidzi masyhur memperkenalkan dan memopulerkan istilah hadits "hasan" sebagai derajat antara sahih dan dhaif, memperkaya ilmu mustholah hadits. Ia juga menyusun kitab Asy-Syama''il tentang sifat dan akhlak Rasulullah ﷺ.', 'QS Al-Qalam: 4'),
('imam-at-tirmidzi', 3, 'Kekuatan Hafalan dan Wafatnya', 'Tirmidzi dikenal dengan kekuatan hafalan yang luar biasa dan ketakwaannya; di akhir hayat ia kehilangan penglihatan. Ia wafat di Tirmidz tahun 279 H, meninggalkan kitab yang menjadi rujukan hadits dan fiqih perbandingan.', 'QS Fathir: 28'),

-- ═══════════════════ ULAMA BESAR ═══════════════════
('imam-al-ghazali', 1, 'Hujjatul Islam', 'Abu Hamid Muhammad Al-Ghazali (450–505 H) lahir di Thus, Persia, menjadi ulama ensiklopedis dalam fiqih, ushul, mantiq, filsafat, dan tasawuf. Kecerdasannya mengantarkannya menjadi guru besar di Madrasah Nizhamiyah Baghdad pada usia muda, dan digelari Hujjatul Islam.', 'QS Az-Zumar: 9'),
('imam-al-ghazali', 2, 'Pencarian Jiwa dan Titik Balik', 'Di puncak ketenaran, Al-Ghazali mengalami krisis batin, meninggalkan jabatannya, dan berkhalwat bertahun-tahun mencari ketenangan hati dan keikhlasan. Dari perjalanan ruhani ini lahir pembaruan tasawuf yang berlandaskan syariat.', 'QS Ar-Ra''d: 28'),
('imam-al-ghazali', 3, 'Ihya Ulumuddin', 'Karya besarnya, Ihya Ulumuddin, memadukan fiqih lahir dan tasawuf batin — menghidupkan ilmu agama dengan menekankan keikhlasan, penyucian hati, dan akhlak. Kitab ini menjadi salah satu karya paling berpengaruh dalam sejarah Islam.', 'QS Asy-Syams: 9–10'),
('imam-al-ghazali', 4, 'Warisan dan Wafatnya', 'Al-Ghazali kembali mengajar di akhir hayatnya, membela akidah Ahlussunnah dari penyimpangan filsafat melalui Tahafut al-Falasifah, lalu wafat di Thus tahun 505 H. Pengaruh pemikirannya terasa hingga kini di seluruh dunia Islam.', 'QS Al-Baqarah: 269'),

('imam-an-nawawi', 1, 'Muhyiddin, Penghidup Agama', 'Yahya bin Syaraf An-Nawawi (631–676 H) lahir di Nawa, Syam. Sejak kecil ia lebih memilih menghafal Al-Qur''an daripada bermain. Ia hidup sangat zuhud, membujang demi ilmu, dan menjadi rujukan utama mazhab Syafi''i sepanjang zaman.', 'QS Ali ''Imran: 79'),
('imam-an-nawawi', 2, 'Karya-Karya yang Abadi', 'Meski usianya pendek, Nawawi meninggalkan karya-karya yang dikaji umat hingga kini: Riyadhus Shalihin, Al-Arba''in An-Nawawiyah, Syarah Shahih Muslim, Al-Majmu'', dan Al-Adzkar. Keberkahan ilmunya luar biasa karena keikhlasannya.', 'QS Al-Kahfi: 66'),
('imam-an-nawawi', 3, 'Zuhud, Amar Ma''ruf, dan Wafatnya', 'Nawawi berani menasihati penguasa dengan lembut namun tegas, menolak pemberian mereka, dan hidup hanya dari kiriman sederhana ayahnya. Ia wafat muda di Nawa tahun 676 H, meninggalkan teladan bahwa keberkahan ilmu lahir dari keikhlasan dan wara''.', 'QS Al-Ma''idah: 67'),

('ibnu-taimiyah', 1, 'Syaikhul Islam dari Harran', 'Ahmad bin Abdul Halim Ibnu Taimiyah (661–728 H) lahir di Harran, mengungsi ke Damaskus karena serbuan Mongol. Ia ulama ensiklopedis bermazhab Hanbali dengan hafalan dan penguasaan ilmu yang luar biasa dalam tafsir, hadits, fiqih, dan akidah.', 'QS Al-Mujadalah: 11'),
('ibnu-taimiyah', 2, 'Membela Umat dari Serbuan Mongol', 'Ibnu Taimiyah tidak hanya berjihad dengan pena tetapi juga turun ke medan, membangkitkan semangat kaum muslimin melawan Mongol dalam Perang Syaqhab, dan mendorong para pemimpin untuk berjihad membela negeri Islam.', 'QS Al-Anfal: 60'),
('ibnu-taimiyah', 3, 'Pembaru yang Berpegang pada Dalil', 'Ia menyeru kembali kepada Al-Qur''an dan Sunnah dengan pemahaman salaf, membantah penyimpangan akidah dan bid''ah, serta menulis ratusan jilid karya termasuk Majmu'' al-Fatawa. Pandangannya memengaruhi gerakan pembaruan Islam sesudahnya.', 'QS An-Nisa: 59'),
('ibnu-taimiyah', 4, 'Wafat di Penjara demi Ilmu', 'Karena keteguhan pendapatnya, Ibnu Taimiyah beberapa kali dipenjara, dan di penjara Damaskus ia terus menulis dan beribadah hingga penanya dirampas. Ia wafat di penjara tahun 728 H; jenazahnya diantar puluhan ribu manusia.', 'QS Al-Ankabut: 2'),

('ibnu-katsir', 1, 'Ahli Tafsir dan Sejarah', 'Isma''il bin ''Umar Ibnu Katsir (700–774 H) lahir di Bushra, Syam, murid Ibnu Taimiyah dan Al-Mizzi. Ia menjadi salah satu ahli tafsir, hadits, dan sejarah terbesar dalam Islam, dengan metode yang berpegang kuat pada riwayat.', 'QS An-Nahl: 89'),
('ibnu-katsir', 2, 'Tafsir Al-Qur''an al-Azhim', 'Karyanya, Tafsir Ibnu Katsir, menafsirkan Al-Qur''an dengan Al-Qur''an, lalu dengan hadits, lalu perkataan sahabat dan tabi''in — menjadi tafsir bil-ma''tsur paling masyhur dan terpercaya yang dibaca umat di seluruh dunia hingga kini.', 'QS Al-Qiyamah: 19'),
('ibnu-katsir', 3, 'Al-Bidayah wan-Nihayah dan Wafatnya', 'Dalam sejarah, ia menulis Al-Bidayah wan-Nihayah, dari penciptaan alam, kisah para nabi, sirah, hingga peristiwa akhir zaman — rujukan utama Qashash al-Anbiya. Ia wafat di Damaskus tahun 774 H dalam keadaan kehilangan penglihatan, dimakamkan di sisi gurunya Ibnu Taimiyah.', 'QS Yusuf: 111'),

('syaikh-nawawi-al-bantani', 1, 'Sayyid Ulama Hijaz dari Nusantara', 'Muhammad Nawawi Al-Bantani (1230–1314 H) lahir di Tanara, Banten, lalu bermukim dan mengajar di Makkah hingga digelari "Sayyidu Ulama al-Hijaz". Ia salah satu ulama Nusantara paling berpengaruh, guru banyak pendiri pesantren dan organisasi Islam di tanah air.', 'QS At-Taubah: 122'),
('syaikh-nawawi-al-bantani', 2, 'Penulis Puluhan Kitab yang Mendunia', 'Nawawi Al-Bantani menulis puluhan kitab dalam tafsir, fiqih, tauhid, dan akhlak — seperti Tafsir Marah Labid, Tijan Ad-Darari, Nashaihul ''Ibad, dan Kasyifatus Saja — yang dikaji di pesantren Nusantara dan Timur Tengah hingga kini.', 'QS Al-Alaq: 4–5'),
('syaikh-nawawi-al-bantani', 3, 'Warisan Ilmu bagi Nusantara', 'Melalui murid-muridnya, ilmu Nawawi Al-Bantani menyebar dan membentuk tradisi keilmuan pesantren Nusantara yang moderat dan berpegang pada Ahlussunnah. Ia wafat di Makkah tahun 1314 H dan dimakamkan di Ma''la, dekat makam Sayyidah Khadijah.', 'QS Fathir: 32'),

('al-habib-abdullah-al-haddad', 1, 'Quthub Dakwah dan Irsyad', 'Al-Habib Abdullah bin Alwi Al-Haddad (1044–1132 H) lahir di Tarim, Hadramaut, Yaman. Meski kehilangan penglihatan sejak kecil, Allah menganugerahinya hafalan, ilmu, dan bashirah batin yang luar biasa, hingga menjadi imam dakwah dan tasawuf di zamannya.', 'QS An-Nur: 35'),
('al-habib-abdullah-al-haddad', 2, 'Ratib dan Wirid yang Mendunia', 'Ia menyusun Ratib Al-Haddad, wirid perlindungan dan dzikir yang dibaca jutaan muslim di seluruh dunia hingga kini, serta menulis kitab-kitab nasihat seperti An-Nashaih Ad-Diniyah dan Risalatul Mu''awanah yang melembutkan hati.', 'QS Ar-Ra''d: 28'),
('al-habib-abdullah-al-haddad', 3, 'Dakwah, Akhlak, dan Wafatnya', 'Al-Haddad mengajarkan tasawuf yang berpijak kuat pada syariat, menekankan ikhlas, takwa, dan cinta kepada Allah dan Rasul-Nya. Ia wafat di Tarim tahun 1132 H; ajaran dan wiridnya tetap hidup di majelis-majelis ilmu dan dzikir dunia.', 'QS Yunus: 62');

-- ═══════════════════ TABI'IN & TABI'UT-TABI'IN ═══════════════════
INSERT OR IGNORE INTO kisah_person_section (person_slug, section_order, heading_id, body_id, quran_refs) VALUES
('al-hasan-al-basri', 1, 'Imam Tabi''in dan Ahli Nasihat', 'Al-Hasan bin Abil Hasan Al-Bashri (21–110 H), tabi''in agung yang tumbuh di Madinah dan menetap di Bashrah. Ibunya pelayan Ummu Salamah, istri Nabi ﷺ. Ia menimba ilmu dari banyak sahabat dan menjadi imam dalam ilmu, zuhud, dan nasihat yang menggetarkan hati.', 'QS Adz-Dzariyat: 55'),
('al-hasan-al-basri', 2, 'Zuhud dan Kata-Kata Hikmahnya', 'Nasihat-nasihat Al-Hasan tentang kefanaan dunia dan kesungguhan beramal untuk akhirat dikenang sepanjang zaman. Ia berkata, "Wahai anak Adam, engkau hanyalah kumpulan hari; setiap kali satu hari pergi, pergi pula sebagian dirimu."', 'QS Al-Ashr: 1–3'),
('al-hasan-al-basri', 3, 'Berani Menasihati Penguasa', 'Al-Hasan berani menyampaikan kebenaran kepada penguasa zalim di masanya, menegur kezaliman dengan hikmah tanpa takut. Ia wafat di Bashrah tahun 110 H, meninggalkan teladan ulama yang menyatukan ilmu, amal, dan keberanian.', 'QS Ali ''Imran: 104'),

('umar-bin-abdul-aziz', 1, 'Khalifah Kelima yang Adil', 'Umar bin Abdul Aziz (61–101 H), dari Bani Umayyah, cicit Umar bin Khattab melalui ibunya. Semula hidup dalam kemewahan sebagai gubernur, namun setelah diangkat menjadi khalifah ia berubah total menjadi pemimpin yang zuhud dan adil, hingga disebut khalifah kelima yang lurus.', 'QS An-Nahl: 90'),
('umar-bin-abdul-aziz', 2, 'Mengembalikan Harta dan Menegakkan Keadilan', 'Hari pertama menjabat, ia mengembalikan harta yang diambil zalim, termasuk miliknya sendiri, ke baitul mal, dan menolak fasilitas kekhalifahan. Keadilannya membuat rakyat makmur hingga sulit menemukan orang yang mau menerima zakat.', 'QS Al-Ma''idah: 8'),
('umar-bin-abdul-aziz', 3, 'Pelopor Pembukuan Hadits', 'Ia memerintahkan para ulama, di antaranya Imam Az-Zuhri, untuk membukukan hadits secara resmi agar sunnah tidak hilang seiring wafatnya para penghafal — sebuah kebijakan yang menyelamatkan warisan hadits umat.', 'QS Al-Hijr: 9'),
('umar-bin-abdul-aziz', 4, 'Zuhud dan Wafatnya', 'Umar bin Abdul Aziz hidup sangat sederhana meski menguasai negeri yang luas, dan wafat muda pada tahun 101 H — sebagian riwayat menyebut ia diracun. Masa pemerintahannya yang singkat menjadi teladan abadi keadilan dalam Islam.', 'QS Al-Qashash: 83'),

('uwais-al-qarani', 1, 'Wali yang Tersembunyi', 'Uwais bin Amir Al-Qarani, dari Yaman, seorang tabi''in yang tidak sempat berjumpa Nabi ﷺ karena berbakti merawat ibunya. Meski tak dikenal penduduk bumi, ia masyhur di langit karena ketakwaan dan baktinya.', 'QS Al-Isra: 23'),
('uwais-al-qarani', 2, 'Wasiat Nabi kepada Umar', 'Nabi ﷺ berpesan kepada Umar dan Ali, jika berjumpa Uwais, mintalah ia memohonkan ampun untuk mereka, karena doanya mustajab. Ketika Umar menemuinya, ia meminta Uwais mendoakannya — teladan bahwa kemuliaan di sisi Allah bukan pada popularitas.', 'HR Muslim no. 2542'),
('uwais-al-qarani', 3, 'Bakti kepada Ibu di Atas Segalanya', 'Uwais rela meninggalkan kesempatan berjumpa Rasulullah ﷺ demi berbakti kepada ibunya yang renta — menjadikannya lambang keutamaan birrul walidain. Ia gugur, menurut sebagian riwayat, dalam peperangan bersama Ali.', 'QS Luqman: 14'),

('said-bin-al-musayyib', 1, 'Penghulu Tabi''in di Madinah', 'Sa''id bin Al-Musayyib (15–94 H), imam para tabi''in di Madinah, ahli fiqih dan hadits, menantu Abu Hurairah. Ia dikenal paling tahu tentang keputusan-keputusan Umar bin Khattab, dan menjadi salah satu dari tujuh fuqaha Madinah.', 'QS An-Nahl: 43'),
('said-bin-al-musayyib', 2, 'Teguh Menolak Kezaliman', 'Ia menolak menikahkan putrinya dengan putra khalifah demi menjaga agama, hingga dicambuk, namun tetap teguh. Ia wafat di Madinah tahun 94 H, teladan ulama yang menjaga izzah ilmu dari tekanan kekuasaan.', 'QS Al-Ma''idah: 8'),

('muhammad-bin-sirin', 1, 'Tabi''in Ahli Tafsir Mimpi', 'Muhammad bin Sirin (33–110 H), tabi''in dari Bashrah, putra seorang bekas budak yang dimerdekakan Anas bin Malik. Ia terkenal sangat wara'', jujur, ahli hadits, dan diberi Allah keahlian menakwilkan mimpi yang masyhur sepanjang masa.', 'QS Yusuf: 6'),
('muhammad-bin-sirin', 2, 'Kejujuran dan Kewara''annya', 'Ibnu Sirin sangat berhati-hati dalam periwayatan dan muamalah; ia berkata, "Sesungguhnya ilmu ini adalah agama, maka perhatikanlah dari siapa kalian mengambil agama kalian." Ia wafat di Bashrah tahun 110 H.', 'QS Al-Hujurat: 6'),

('urwah-bin-az-zubair', 1, 'Salah Satu Tujuh Fuqaha Madinah', 'Urwah bin Az-Zubair (23–94 H), putra Az-Zubair bin Awwam dan Asma binti Abu Bakar, keponakan Aisyah. Ia menimba ilmu langsung dari bibinya Aisyah dan menjadi salah satu perawi utama hadits serta perintis penulisan sirah Nabi ﷺ.', 'QS Al-Ahzab: 21'),
('urwah-bin-az-zubair', 2, 'Sabar atas Ujian', 'Urwah kehilangan kakinya karena penyakit dan seorang putranya di hari yang sama, namun ia bersyukur karena Allah menyisakan lebih banyak nikmat daripada yang diambil. Ia wafat tahun 94 H, teladan kesabaran dan syukur.', 'QS Az-Zumar: 10'),

('ata-bin-abi-rabah', 1, 'Mufti Makkah dari Kalangan Mantan Budak', 'Atha'' bin Abi Rabah (27–114 H), tabi''in dari Makkah, berkulit hitam dan bekas budak, namun ilmunya mengangkatnya menjadi mufti Masjidil Haram yang dirujuk para khalifah dan jamaah haji dari seluruh dunia.', 'QS Az-Zumar: 9'),
('ata-bin-abi-rabah', 2, 'Ilmu Mengangkat Derajat', 'Khalifah pun menunggu giliran bertanya kepada Atha''. Kisahnya menegaskan sabda bahwa Allah mengangkat derajat manusia dengan ilmu, bukan nasab atau warna kulit. Ia wafat di Makkah tahun 114 H.', 'QS Al-Mujadalah: 11'),

('sufyan-ats-tsauri', 1, 'Amirul Mukminin dalam Hadits', 'Sufyan bin Sa''id Ats-Tsauri (97–161 H) dari Kufah, tabi''ut-tabi''in, imam dalam hadits, fiqih, dan zuhud, hingga digelari "Amirul Mukminin fil Hadits". Ia sangat wara'' dan menjauhi penguasa demi menjaga kemurnian ilmunya.', 'QS Fathir: 28'),
('sufyan-ats-tsauri', 2, 'Zuhud dan Menghindar dari Kekuasaan', 'Sufyan menolak jabatan dan pemberian penguasa, bahkan bersembunyi agar tidak dipaksa menjadi qadhi. Ia berkata, "Sebaik-baik ilmu adalah yang tampak pada wara''-nya." Ia wafat di Bashrah tahun 161 H.', 'QS Al-Qashash: 83'),

('al-laits-bin-sad', 1, 'Imam Mesir yang Dermawan', 'Al-Laits bin Sa''d (94–175 H), imam ahli fiqih dan hadits Mesir, sezaman dengan Imam Malik. Imam Syafi''i berkata, "Al-Laits lebih faqih daripada Malik, hanya saja murid-muridnya tidak menyebarkan mazhabnya." Ia sangat dermawan hingga penghasilannya yang besar habis untuk sedekah.', 'QS Al-Baqarah: 261'),
('al-laits-bin-sad', 2, 'Ilmu dan Kedermawanan yang Berpadu', 'Al-Laits menafkahkan hartanya untuk para ulama dan fakir miskin tanpa perhitungan, menegakkan kemuliaan ilmu dengan kemurahan tangan. Ia wafat di Mesir tahun 175 H, dikenang sebagai teladan ulama yang kaya namun zuhud.', 'QS Saba: 39'),

('abdullah-bin-al-mubarak', 1, 'Ulama, Mujahid, dan Saudagar', 'Abdullah bin Al-Mubarak (118–181 H) dari Khurasan, ulama hadits dan fiqih yang juga mujahid di perbatasan dan saudagar dermawan. Ia memadukan ilmu, jihad, dan infak dalam satu pribadi yang langka.', 'QS At-Taubah: 20'),
('abdullah-bin-al-mubarak', 2, 'Menghidupkan Ilmu dan Jihad', 'Ia menulis kitab Az-Zuhd dan Al-Jihad, membiayai para penuntut ilmu dan mujahid dari hartanya, serta berkata bahwa ia mengangkat kemuliaan ilmu dengan berdagang agar tidak menengadah kepada manusia.', 'QS Al-Ankabut: 69'),
('abdullah-bin-al-mubarak', 3, 'Keikhlasan dan Wafatnya', 'Ibnul Mubarak masyhur dengan keikhlasan dan tawadhu; ia menyembunyikan sedekahnya kepada orang-orang yang malu meminta. Ia wafat tahun 181 H sepulang dari jihad, teladan ulama yang sempurna sisi ilmu dan amalnya.', 'QS Al-Insan: 9'),

('waki-bin-al-jarrah', 1, 'Guru Besar Imam Syafi''i dan Ahmad', 'Waki'' bin Al-Jarrah (129–197 H) dari Kufah, imam hadits terpercaya dan guru banyak imam besar termasuk Imam Asy-Syafi''i dan Imam Ahmad. Hafalannya kuat dan periwayatannya menjadi rujukan.', 'QS An-Nahl: 43'),
('waki-bin-al-jarrah', 2, 'Ilmu Cahaya yang Butuh Ketakwaan', 'Kepada Waki'' lah Imam Syafi''i mengadukan buruknya hafalannya, lalu Waki'' menasihatinya meninggalkan maksiat, karena "ilmu adalah cahaya, dan cahaya Allah tidak diberikan kepada pelaku maksiat." Ia wafat tahun 197 H.', 'QS An-Nur: 35'),

('yahya-bin-main', 1, 'Imam Al-Jarh wat-Ta''dil', 'Yahya bin Ma''in (158–233 H) dari Baghdad, imam terbesar dalam ilmu kritik perawi (al-jarh wat-ta''dil), sahabat karib Imam Ahmad. Ia menghabiskan hartanya untuk menulis dan meneliti hadits demi memilah yang sahih dari yang palsu.', 'QS Al-Hujurat: 6'),
('yahya-bin-main', 2, 'Penjaga Kemurnian Hadits', 'Dengan ketelitiannya, Yahya bin Ma''in menjadi benteng yang menjaga sunnah dari pemalsuan; para ulama berpegang pada penilaiannya terhadap perawi. Ia wafat di Madinah tahun 233 H saat menunaikan haji, dan dishalatkan di atas keranda Nabi ﷺ.', 'QS Al-Hijr: 9');
