-- AUTO-GENERATED by scripts/generate-kisah-ashabul-ukhdud-seed.ts — do not edit by hand.
-- Source content: scripts/content/kisah-ashabul-ukhdud.ts (grounded in QS. Al-Buruj
-- 85:4-10, quran-json CC-BY-4.0). See docs/CONTENT-POLICY.md.
-- Requires quran_seed.sql already applied (resolves related_ayah_id by lookup).

INSERT OR IGNORE INTO categories (id, name, slug, parent_id, auto_created) VALUES (5, 'Kisah Islami', 'kisah-islami', NULL, 0);

INSERT INTO ebooks (id, title, author, r2_key, category_id, license_status, license_note) VALUES (600, 'Episode 1: Parit Api dan Kekejaman yang Disaksikan', 'Tim Editorial ULYAH', 'ebooks/kisah-ashabul-ukhdud/id/kisah-ashabul-ukhdud-01-parit-api.pdf', 5, 'original', 'Ditulis berdasarkan QS. Al-Buruj 4-7 (quran-json, CC-BY-4.0). Tidak ada kutipan pihak ketiga berhak cipta.');
INSERT INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Episode 1: Parit Api dan Kekejaman yang Disaksikan', 'kisah-ashabul-ukhdud-01-parit-api', 'id', 'kisah-ashabul-ukhdud', 1, 5, 'Al-Qur''an mengabadikan sebuah peristiwa kelam dalam sejarah keimanan: sekelompok penguasa zalim yang membakar orang-orang beriman di dalam parit api karena mempertahankan tauhid. Allah berfirman, "Binasa dan terlaknatlah orang-orang yang membuat parit (yaitu para pembesar Najran di Yaman). (Yang) berapi (dinyalakan dengan) kayu bakar, ketika mereka duduk di sekitarnya, sedang mereka menyaksikan apa yang mereka perbuat terhadap orang-orang mukmin" (QS. Al-Buruj: 4-7).

Gambaran ayat ini sungguh mengerikan: parit-parit digali, diisi kayu bakar, lalu dinyalakan menjadi api yang berkobar. Orang-orang beriman dipaksa memilih — meninggalkan iman mereka atau dilemparkan ke dalam api. Dan para penguasa zalim itu duduk di tepi parit, menyaksikan penyiksaan itu dengan puas, tanpa belas kasihan sedikit pun.

Yang paling menonjol dari kisah ini adalah keteguhan luar biasa dari orang-orang beriman. Mereka lebih memilih tubuhnya terbakar daripada hatinya kehilangan iman. Iman mereka lebih berharga daripada nyawa mereka sendiri.

Hikmah: keimanan sejati diuji pada saat paling berat. Ashabul Ukhdud mengabadikan teladan orang-orang yang mempertahankan tauhid meski nyawa taruhannya — sebuah bukti bahwa kekuatan iman bisa mengalahkan rasa takut kepada kematian.

Sumber & Catatan: dalil dari Al-Qur''an, QS. Al-Buruj: 4-7 (teks & terjemahan quran-json). Al-Qur''an tidak menyebut lokasi atau zaman peristiwa secara tegas; keterangan bahwa mereka adalah penduduk Najran (Yaman) berasal dari riwayat dan tafsir, disampaikan sebagai catatan sejarah, bukan bagian dari nas ayat.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  (SELECT id FROM ayah WHERE surah_id = 85 AND number = 4), 600, datetime('now');
INSERT INTO ebooks (id, title, author, r2_key, category_id, license_status, license_note) VALUES (601, 'Episode 1: The Trench of Fire and the Cruelty Witnessed', 'Tim Editorial ULYAH', 'ebooks/kisah-ashabul-ukhdud/en/kisah-ashabul-ukhdud-01-parit-api.pdf', 5, 'original', 'Ditulis berdasarkan QS. Al-Buruj 4-7 (quran-json, CC-BY-4.0). Tidak ada kutipan pihak ketiga berhak cipta.');
INSERT INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Episode 1: The Trench of Fire and the Cruelty Witnessed', 'kisah-ashabul-ukhdud-01-parit-api', 'en', 'kisah-ashabul-ukhdud', 1, 5, 'The Qur''an immortalizes a dark event in the history of faith: a group of tyrannical rulers who burned believers in a trench of fire for holding to tawhid. Allah said, "Cursed were the companions of the trench, [containing] the fire full of fuel, when they were sitting near it, and they, to what they were doing against the believers, were witnesses" (Qur''an 85:4-7).

The image of these verses is truly horrifying: trenches were dug, filled with firewood, then lit into a blazing fire. The believers were forced to choose — abandon their faith or be thrown into the flames. And those tyrannical rulers sat at the edge of the trench, watching the torture with satisfaction, without the least mercy.

What stands out most in this story is the extraordinary steadfastness of the believers. They chose to have their bodies burned rather than let their hearts lose faith. Their faith was more precious to them than their own lives.

Reflection: true faith is tested at the heaviest moments. Ashabul Ukhdud immortalizes the example of those who held to tawhid though their lives were the price — proof that the strength of faith can overcome the fear of death.

Source & Note: evidence from the Qur''an, 85:4-7 (text & translation from quran-json). The Qur''an does not explicitly name the location or era of the event; the report that they were the people of Najran (Yemen) comes from narrations and tafsir, related as history, not as part of the text of the ayat.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  (SELECT id FROM ayah WHERE surah_id = 85 AND number = 4), 601, datetime('now');

INSERT INTO ebooks (id, title, author, r2_key, category_id, license_status, license_note) VALUES (602, 'Episode 2: Dibenci Hanya Karena Beriman kepada Allah', 'Tim Editorial ULYAH', 'ebooks/kisah-ashabul-ukhdud/id/kisah-ashabul-ukhdud-02-kejahatan-tanpa-alasan-selain-iman.pdf', 5, 'original', 'Ditulis berdasarkan QS. Al-Buruj 8-9 (quran-json, CC-BY-4.0). Tidak ada kutipan pihak ketiga berhak cipta.');
INSERT INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Episode 2: Dibenci Hanya Karena Beriman kepada Allah', 'kisah-ashabul-ukhdud-02-kejahatan-tanpa-alasan-selain-iman', 'id', 'kisah-ashabul-ukhdud', 2, 5, 'Al-Qur''an menjelaskan satu-satunya "kesalahan" orang-orang beriman itu di mata para penyiksanya — dan ternyata itu bukan kesalahan sama sekali, melainkan kemuliaan. Allah berfirman, "Dan mereka menyiksa orang-orang mukmin itu hanya karena (orang-orang mukmin itu) beriman kepada Allah Yang Mahaperkasa, Maha Terpuji, yang memiliki kerajaan langit dan bumi. Dan Allah Maha Menyaksikan segala sesuatu" (QS. Al-Buruj: 8-9).

Perhatikan betapa dalamnya makna ayat ini: satu-satunya sebab kebencian dan penyiksaan itu adalah keimanan kepada Allah. Para mukmin tidak mencuri, tidak berbuat kerusakan, tidak menzalimi siapa pun — mereka hanya beriman kepada Allah Yang Mahaperkasa (Al-''Aziz) lagi Maha Terpuji (Al-Hamid).

Ayat ini juga menegaskan sifat Allah: Dialah pemilik kerajaan langit dan bumi, dan Dia menyaksikan segala sesuatu. Maka meskipun para penyiksa itu duduk menonton dengan bangga, sesungguhnya Allah pun menyaksikan setiap tetes penderitaan hamba-Nya yang beriman — dan tidak akan membiarkannya sia-sia.

Hikmah: kebencian orang zalim kepada orang beriman sering kali bukan karena keburukan, melainkan justru karena kebaikan dan keteguhan iman mereka. Dan setiap kezaliman disaksikan Allah; tidak ada yang luput dari-Nya. Cukuplah Allah sebagai Saksi dan Pembalas.

Sumber & Catatan: dalil dari Al-Qur''an, QS. Al-Buruj: 8-9. Dua nama Allah dalam ayat — Al-''Aziz (Mahaperkasa) dan Al-Hamid (Maha Terpuji) — serta penegasan "Allah Maha Menyaksikan segala sesuatu" adalah nas Al-Qur''an.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  (SELECT id FROM ayah WHERE surah_id = 85 AND number = 8), 602, datetime('now');
INSERT INTO ebooks (id, title, author, r2_key, category_id, license_status, license_note) VALUES (603, 'Episode 2: Hated Only for Believing in Allah', 'Tim Editorial ULYAH', 'ebooks/kisah-ashabul-ukhdud/en/kisah-ashabul-ukhdud-02-kejahatan-tanpa-alasan-selain-iman.pdf', 5, 'original', 'Ditulis berdasarkan QS. Al-Buruj 8-9 (quran-json, CC-BY-4.0). Tidak ada kutipan pihak ketiga berhak cipta.');
INSERT INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Episode 2: Hated Only for Believing in Allah', 'kisah-ashabul-ukhdud-02-kejahatan-tanpa-alasan-selain-iman', 'en', 'kisah-ashabul-ukhdud', 2, 5, 'The Qur''an explains the sole "crime" of those believers in the eyes of their torturers — and it turns out to be no crime at all, but an honor. Allah said, "And they resented them not except because they believed in Allah, the Exalted in Might, the Praiseworthy, to whom belongs the dominion of the heavens and the earth. And Allah, over all things, is Witness" (Qur''an 85:8-9).

Notice how deep the meaning of this verse is: the only cause of that hatred and torture was faith in Allah. The believers did not steal, did not spread corruption, did not wrong anyone — they only believed in Allah, the Exalted in Might (Al-''Aziz), the Praiseworthy (Al-Hamid).

This verse also affirms Allah''s attributes: His is the dominion of the heavens and the earth, and He witnesses all things. So even as those torturers sat watching with pride, Allah too witnessed every drop of the suffering of His believing servants — and He would not let it go in vain.

Reflection: the hatred of the unjust toward the believers is often not because of any evil, but precisely because of the goodness and steadfastness of their faith. And every injustice is witnessed by Allah; nothing escapes Him. Allah suffices as Witness and Requiter.

Source & Note: evidence from the Qur''an, 85:8-9. The two names of Allah in the verse — Al-''Aziz (the Exalted in Might) and Al-Hamid (the Praiseworthy) — and the affirmation "Allah, over all things, is Witness" are the Qur''an''s own text.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  (SELECT id FROM ayah WHERE surah_id = 85 AND number = 8), 603, datetime('now');

INSERT INTO ebooks (id, title, author, r2_key, category_id, license_status, license_note) VALUES (604, 'Episode 3: Balasan bagi Penganiaya dan Kemenangan Iman', 'Tim Editorial ULYAH', 'ebooks/kisah-ashabul-ukhdud/id/kisah-ashabul-ukhdud-03-balasan-dan-keteguhan.pdf', 5, 'original', 'Ditulis berdasarkan QS. Al-Buruj 10-10 (quran-json, CC-BY-4.0). Tidak ada kutipan pihak ketiga berhak cipta.');
INSERT INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Episode 3: Balasan bagi Penganiaya dan Kemenangan Iman', 'kisah-ashabul-ukhdud-03-balasan-dan-keteguhan', 'id', 'kisah-ashabul-ukhdud', 3, 5, 'Al-Qur''an menegaskan balasan yang menanti para penyiksa itu jika mereka tidak bertaubat. Allah berfirman, "Sungguh, orang-orang yang mendatangkan cobaan (bencana, membakar dan menyiksa) kepada orang-orang mukmin laki-laki dan perempuan, kemudian mereka tidak bertaubat, maka mereka akan mendapat azab Jahanam dan mereka akan mendapat azab (neraka) yang membakar" (QS. Al-Buruj: 10).

Ada keadilan yang sempurna di sini: mereka membakar orang beriman dengan api dunia, maka mereka pun diancam dengan api Jahanam di akhirat — kecuali jika mereka bertaubat. Pintu taubat tetap terbuka bahkan bagi pelaku kejahatan sebesar itu, selama mereka mau kembali kepada Allah. Ini menunjukkan luasnya rahmat Allah sekaligus tegasnya keadilan-Nya.

Adapun orang-orang beriman yang gugur dalam api dunia, mereka sesungguhnya adalah para pemenang. Mereka kehilangan tubuh yang fana, tetapi meraih surga yang kekal. Api dunia hanya menyakiti sesaat, sedangkan mereka menukarnya dengan kenikmatan abadi di sisi Allah.

Hikmah: kemenangan sejati tidak selalu tampak di dunia. Kadang orang beriman kalah secara fisik, tetapi menang secara hakiki di sisi Allah. Kisah Ashabul Ukhdud mengajarkan bahwa keteguhan iman, sekalipun berujung syahid, adalah kemenangan yang paling agung.

Sumber & Catatan: dalil dari Al-Qur''an, QS. Al-Buruj: 10. Latar belakang kisah ini masyhur diriwayatkan dalam hadits sahih tentang "kisah seorang anak (ghulam) dan raja" — tentang seorang pemuda beriman yang keteguhannya menyebabkan banyak orang beriman lalu dibakar di parit (HR. Muslim no. 3005). Kami menyebutkannya dengan sumbernya sebagai penjelas latar, sementara pokok pelajaran tetap bersandar pada ayat.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  (SELECT id FROM ayah WHERE surah_id = 85 AND number = 10), 604, datetime('now');
INSERT INTO ebooks (id, title, author, r2_key, category_id, license_status, license_note) VALUES (605, 'Episode 3: The Requital of the Torturers and the Victory of Faith', 'Tim Editorial ULYAH', 'ebooks/kisah-ashabul-ukhdud/en/kisah-ashabul-ukhdud-03-balasan-dan-keteguhan.pdf', 5, 'original', 'Ditulis berdasarkan QS. Al-Buruj 10-10 (quran-json, CC-BY-4.0). Tidak ada kutipan pihak ketiga berhak cipta.');
INSERT INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Episode 3: The Requital of the Torturers and the Victory of Faith', 'kisah-ashabul-ukhdud-03-balasan-dan-keteguhan', 'en', 'kisah-ashabul-ukhdud', 3, 5, 'The Qur''an affirms the requital awaiting those torturers if they do not repent. Allah said, "Indeed, those who have tortured the believing men and believing women and then have not repented will have the punishment of Hell, and they will have the punishment of the Burning Fire" (Qur''an 85:10).

There is perfect justice here: they burned the believers with the fire of this world, so they are threatened with the fire of Hell in the Hereafter — unless they repent. The door of repentance stays open even for the perpetrators of so great a crime, so long as they are willing to return to Allah. This shows the vastness of Allah''s mercy together with the firmness of His justice.

As for the believers who fell in the fire of this world, they are in truth the victors. They lost a perishable body but attained an everlasting Paradise. The fire of this world hurts only for a moment, while they traded it for eternal bliss with Allah.

Reflection: true victory is not always visible in this world. Sometimes the believers lose physically but win in reality before Allah. The story of Ashabul Ukhdud teaches that steadfastness of faith, even if it ends in martyrdom, is the most magnificent victory.

Source & Note: evidence from the Qur''an, 85:10. The background of this story is famously narrated in an authentic hadith about "the boy and the king" — a young believer whose steadfastness led many to believe and were then burned in the trench (Sahih Muslim no. 3005). We mention it with its source as background, while the core lesson rests on the ayat.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  (SELECT id FROM ayah WHERE surah_id = 85 AND number = 10), 605, datetime('now');

