-- AUTO-GENERATED by scripts/generate-kisah-yaqub-seed.ts — do not edit by hand.
-- Source content: scripts/content/kisah-yaqub.ts (grounded in QS. Al-A'raf, Hud, Asy-Syu'ara, Al-Ahqaf, Al-Haqqah,
-- quran-json CC-BY-4.0). See docs/CONTENT-POLICY.md.
-- Requires quran_seed.sql already applied (resolves related_ayah_id by lookup).
-- No PDFs — read + narrated in-app (TTS), so pdf_ebook_id is NULL.

INSERT OR IGNORE INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Episode 1: Ya''qub, Nabi dalam Silsilah Ibrahim', 'kisah-yaqub-01-nabi-dalam-silsilah-ibrahim', 'id', 'kisah-yaqub', 1, 1, 'Nabi Ya''qub adalah putra Nabi Ishaq dan cucu Nabi Ibrahim. Ia dianugerahkan sebagai kelanjutan silsilah kenabian yang menjaga tauhid. Allah berfirman, "Maka ketika dia (Ibrahim) telah menjauhkan diri dari mereka dan dari apa yang mereka sembah selain Allah, Kami anugerahkan kepadanya Ishaq dan Ya''qub. Dan masing-masing Kami angkat menjadi nabi" (QS. Maryam: 49).

Ya''qub disebut Allah sebagai teladan hamba yang kuat dalam ketaatan dan tajam pandangannya, bersama ayah dan kakeknya. "Dan ingatlah hamba-hamba Kami: Ibrahim, Ishaq, dan Ya''qub, yang mempunyai kekuatan-kekuatan yang besar dan ilmu-ilmu (yang tinggi). Sungguh, Kami telah menyucikan mereka dengan (menganugerahkan kepada mereka) akhlak yang tinggi, yaitu selalu mengingat negeri akhirat" (QS. Sad: 45-46).

Dan Allah menegaskan bahwa Ya''qub termasuk para nabi yang diberi petunjuk, "Dan Kami telah menganugerahkan Ishaq dan Ya''qub kepadanya. Kepada masing-masing telah Kami beri petunjuk" (QS. Al-An''am: 84).

Hikmah: kenabian adalah karunia Allah yang menjaga cahaya tauhid dari satu generasi ke generasi berikutnya. Ya''qub mewarisi bukan sekadar nasab mulia, melainkan tanggung jawab menjaga dan meneruskan iman kepada Allah Yang Maha Esa.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  (SELECT id FROM ayah WHERE surah_id = 19 AND number = 49), NULL, datetime('now');
INSERT OR IGNORE INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Episode 1: Ya''qub, a Prophet in the Line of Ibrahim', 'kisah-yaqub-01-nabi-dalam-silsilah-ibrahim', 'en', 'kisah-yaqub', 1, 1, 'Prophet Ya''qub was the son of Prophet Ishaq and the grandson of Prophet Ibrahim. He was granted as a continuation of the prophetic line that preserved tawhid. Allah said, "So when he (Ibrahim) had left them and those they worshipped other than Allah, We gave him Ishaq and Ya''qub, and each [of them] We made a prophet" (Qur''an 19:49).

Allah mentioned Ya''qub as an example of a servant strong in obedience and sharp in vision, together with his father and grandfather. "And remember Our servants, Ibrahim, Ishaq and Ya''qub — those of strength and [religious] vision. Indeed, We chose them for an exclusive quality: remembrance of the home [of the Hereafter]" (38:45-46).

And Allah affirmed that Ya''qub was among the guided prophets, "And We gave to him Ishaq and Ya''qub — all [of them] We guided" (6:84).

Reflection: prophethood is Allah''s gift that preserves the light of tawhid from one generation to the next. Ya''qub inherited not merely a noble lineage, but the responsibility of guarding and passing on faith in Allah, the One.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  (SELECT id FROM ayah WHERE surah_id = 19 AND number = 49), NULL, datetime('now');

INSERT OR IGNORE INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Episode 2: Kesabaran yang Indah atas Kehilangan Yusuf', 'kisah-yaqub-02-kesabaran-yang-indah', 'id', 'kisah-yaqub', 2, 1, 'Ujian terbesar Ya''qub datang lewat anak-anaknya sendiri, ketika Yusuf yang sangat ia cintai dipisahkan darinya. Saat saudara-saudara Yusuf datang membawa kabar dusta dan baju berlumur darah palsu, Ya''qub tidak meratap tanpa kendali. Ia berkata, "...Maka hanya bersabar itulah yang terbaik (bagiku). Dan kepada Allah saja memohon pertolongan-Nya terhadap apa yang kamu ceritakan" (QS. Yusuf: 18).

Bertahun-tahun kemudian, ketika ia kehilangan pula putranya yang lain, kesedihannya memuncak namun kesabarannya tetap terjaga. Allah berfirman, "Ya''qub berkata, ‘...Maka hanya bersabar itulah yang terbaik. Mudah-mudahan Allah mendatangkan mereka semua kepadaku. Sungguh, Dialah Yang Maha Mengetahui, Mahabijaksana’" (QS. Yusuf: 83).

Kesedihannya begitu dalam hingga penglihatannya memutih, "Dan dia berpaling dari mereka (anak-anaknya) seraya berkata, ‘Aduhai, dukacitaku terhadap Yusuf,’ dan kedua matanya menjadi putih karena sedih. Dia diam menahan amarah (terhadap anak-anaknya)" (QS. Yusuf: 84).

Hikmah: "sabar yang indah" (shabrun jamil) adalah kesabaran yang tidak disertai keluh kesah kepada makhluk. Ya''qub menunjukkan bahwa seorang mukmin boleh bersedih dan menangis, tetapi hatinya tetap berbaik sangka dan bersandar penuh kepada Allah.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  (SELECT id FROM ayah WHERE surah_id = 12 AND number = 83), NULL, datetime('now');
INSERT OR IGNORE INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Episode 2: Beautiful Patience over the Loss of Yusuf', 'kisah-yaqub-02-kesabaran-yang-indah', 'en', 'kisah-yaqub', 2, 1, 'Ya''qub''s greatest trial came through his own sons, when Yusuf, whom he loved dearly, was taken from him. When Yusuf''s brothers came with a false story and a shirt stained with false blood, Ya''qub did not wail out of control. He said, "...So patience is most fitting. And Allah is the one sought for help against that which you describe" (Qur''an 12:18).

Years later, when he lost another of his sons as well, his grief reached its peak, yet his patience held firm. Allah said, "Ya''qub said, ''...So patience is most fitting. Perhaps Allah will bring them to me all together. Indeed, it is He who is the Knowing, the Wise''" (12:83).

His grief was so deep that his sight turned white, "And he turned away from them and said, ''Oh, my sorrow over Yusuf,'' and his eyes became white from grief, for he was a suppressor [of his anguish]" (12:84).

Reflection: "beautiful patience" (sabrun jamil) is patience not accompanied by complaint to creation. Ya''qub shows that a believer may grieve and weep, yet his heart still holds good expectation of Allah and leans wholly upon Him.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  (SELECT id FROM ayah WHERE surah_id = 12 AND number = 83), NULL, datetime('now');

INSERT OR IGNORE INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Episode 3: Jangan Berputus Asa dari Rahmat Allah', 'kisah-yaqub-03-jangan-berputus-asa-dari-rahmat-allah', 'id', 'kisah-yaqub', 3, 1, 'Di tengah dukanya yang panjang, Ya''qub tidak pernah mengeluh kepada manusia. Ia menyimpan pengaduannya hanya kepada Allah. Ketika anak-anaknya menegurnya karena terus mengingat Yusuf, ia menjawab, "Sesungguhnya hanya kepada Allah aku mengadukan kesusahan dan kesedihanku, dan aku mengetahui dari Allah apa yang tidak kamu ketahui" (QS. Yusuf: 86).

Keyakinannya kepada rahmat Allah tidak pernah padam, meski bertahun-tahun berlalu. Ia justru mengutus anak-anaknya untuk terus mencari, seraya berpesan, "Wahai anak-anakku! Pergilah kamu, carilah (berita) tentang Yusuf dan saudaranya, dan jangan kamu berputus asa dari rahmat Allah. Sesungguhnya yang berputus asa dari rahmat Allah hanyalah orang-orang yang kafir" (QS. Yusuf: 87).

Kesabaran dan harapan itu akhirnya berbuah. Yusuf ternyata masih hidup, dan ketika baju Yusuf diusapkan ke wajahnya, penglihatan Ya''qub kembali pulih (QS. Yusuf: 96).

Hikmah: berputus asa dari rahmat Allah adalah sifat orang yang tidak mengenal-Nya. Ya''qub mengajarkan bahwa selama seorang hamba masih hidup, pintu harapan tidak pernah tertutup — sebab pertolongan Allah bisa datang di saat yang paling tidak terduga.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  (SELECT id FROM ayah WHERE surah_id = 12 AND number = 86), NULL, datetime('now');
INSERT OR IGNORE INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Episode 3: Never Despair of Allah''s Mercy', 'kisah-yaqub-03-jangan-berputus-asa-dari-rahmat-allah', 'en', 'kisah-yaqub', 3, 1, 'Amid his long grief, Ya''qub never complained to people. He kept his complaint for Allah alone. When his sons rebuked him for continually remembering Yusuf, he answered, "I only complain of my suffering and my grief to Allah, and I know from Allah that which you do not know" (Qur''an 12:86).

His certainty in Allah''s mercy never dimmed, though years had passed. Instead, he sent his sons to keep searching, saying, "O my sons, go and find out about Yusuf and his brother, and despair not of relief from Allah. Indeed, no one despairs of relief from Allah except the disbelieving people" (12:87).

That patience and hope finally bore fruit. Yusuf was still alive, and when Yusuf''s shirt was cast over his face, Ya''qub''s sight returned (12:96).

Reflection: to despair of Allah''s mercy is the trait of one who does not know Him. Ya''qub teaches that as long as a servant still lives, the door of hope is never closed — for the help of Allah can come at the most unexpected moment.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  (SELECT id FROM ayah WHERE surah_id = 12 AND number = 86), NULL, datetime('now');

INSERT OR IGNORE INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Episode 4: Wasiat Tauhid Menjelang Wafat', 'kisah-yaqub-04-wasiat-tauhid-menjelang-wafat', 'id', 'kisah-yaqub', 4, 1, 'Warisan terbesar yang Ya''qub tinggalkan bukanlah harta, melainkan iman. Sebagaimana ayahnya, ia mewasiatkan kepada anak-anaknya agar teguh dalam Islam hingga akhir hayat. Allah berfirman, "Dan Ibrahim mewasiatkan (ucapan) itu kepada anak-anaknya, dan demikian pula Ya''qub. ‘Wahai anak-anakku! Sesungguhnya Allah telah memilih agama ini untukmu, maka janganlah kamu mati kecuali dalam keadaan Muslim (berserah diri kepada Allah)’" (QS. Al-Baqarah: 132).

Al-Qur''an lalu menggambarkan detik-detik terakhir Ya''qub, ketika ia memastikan iman anak-anaknya, "Apakah kamu menjadi saksi ketika maut akan menjemput Ya''qub, ketika dia berkata kepada anak-anaknya, ‘Apa yang kamu sembah sepeninggalku?’ Mereka menjawab, ‘Kami akan menyembah Tuhanmu dan Tuhan nenek moyangmu yaitu Ibrahim, Isma''il, dan Ishaq, (yaitu) Tuhan Yang Maha Esa, dan kami (hanya) berserah diri kepada-Nya’" (QS. Al-Baqarah: 133).

Hikmah: yang paling dikhawatirkan seorang nabi menjelang wafat bukanlah harta yang ditinggalkan, melainkan iman yang diwariskan. Ya''qub mengajarkan bahwa tugas utama orang tua adalah memastikan anak-anaknya tetap berpegang pada tauhid — sebab itulah warisan yang kekal melampaui kematian.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  (SELECT id FROM ayah WHERE surah_id = 2 AND number = 132), NULL, datetime('now');
INSERT OR IGNORE INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Episode 4: The Testament of Tawhid at Death', 'kisah-yaqub-04-wasiat-tauhid-menjelang-wafat', 'en', 'kisah-yaqub', 4, 1, 'The greatest inheritance Ya''qub left was not wealth, but faith. Like his father, he instructed his sons to hold firm to Islam until their last breath. Allah said, "And Ibrahim instructed his sons [to do the same] and [so did] Ya''qub, [saying], ''O my sons, indeed Allah has chosen for you this religion, so do not die except while you are Muslims (in submission to Allah)''" (Qur''an 2:132).

The Qur''an then portrays Ya''qub''s final moments, as he made certain of his sons'' faith, "Or were you witnesses when death approached Ya''qub, when he said to his sons, ''What will you worship after me?'' They said, ''We will worship your God and the God of your fathers, Ibrahim, Isma''il and Ishaq — one God. And we are Muslims [in submission] to Him''" (2:133).

Reflection: what a prophet fears most at death is not the wealth he leaves behind, but the faith he passes on. Ya''qub teaches that a parent''s foremost task is to ensure his children remain firm upon tawhid — for that is the inheritance that endures beyond death.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  (SELECT id FROM ayah WHERE surah_id = 2 AND number = 132), NULL, datetime('now');

