-- AUTO-GENERATED by scripts/generate-kisah-qarun-seed.ts — do not edit by hand.
-- Source content: scripts/content/kisah-qarun.ts (grounded in QS. Al-Qashash
-- 28:76-83, quran-json CC-BY-4.0). See docs/CONTENT-POLICY.md.
-- Requires quran_seed.sql already applied (resolves related_ayah_id by lookup).

INSERT OR IGNORE INTO categories (id, name, slug, parent_id, auto_created) VALUES (5, 'Kisah Islami', 'kisah-islami', NULL, 0);

INSERT INTO ebooks (id, title, author, r2_key, category_id, license_status, license_note) VALUES (500, 'Episode 1: Kekayaan yang Melimpah dan Nasihat Kaumnya', 'Tim Editorial ULYAH', 'ebooks/kisah-qarun/id/kisah-qarun-01-harta-melimpah-dan-nasihat.pdf', 5, 'original', 'Ditulis berdasarkan QS. Al-Qashash 76-77 (quran-json, CC-BY-4.0). Tidak ada kutipan pihak ketiga berhak cipta.');
INSERT INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Episode 1: Kekayaan yang Melimpah dan Nasihat Kaumnya', 'kisah-qarun-01-harta-melimpah-dan-nasihat', 'id', 'kisah-qarun', 1, 5, 'Qarun adalah seorang dari kaum Nabi Musa, namun ia berlaku sewenang-wenang terhadap mereka. Allah menganugerahinya harta yang sangat berlimpah, sampai-sampai kunci-kunci gudang hartanya saja berat dipikul oleh sekelompok orang kuat. Allah berfirman, "Sesungguhnya Qarun termasuk kaum Musa, tetapi dia berlaku zalim terhadap mereka, dan Kami telah menganugerahkan kepadanya perbendaharaan harta yang kunci-kuncinya sungguh berat dipikul oleh sejumlah orang yang kuat-kuat…" (QS. Al-Qashash: 76).

Melihat Qarun mulai terlena, orang-orang saleh di kaumnya menasihatinya dengan bijak, "…(Ingatlah) ketika kaumnya berkata kepadanya, ‘Janganlah engkau terlalu bangga; sungguh, Allah tidak menyukai orang-orang yang membanggakan diri’" (QS. Al-Qashash: 76).

Nasihat itu berlanjut dengan pedoman hidup yang seimbang, "Dan carilah (pahala) negeri akhirat dengan apa yang telah dianugerahkan Allah kepadamu, tetapi janganlah engkau lupakan bagianmu di dunia, dan berbuatbaiklah (kepada orang lain) sebagaimana Allah telah berbuat baik kepadamu, dan janganlah engkau berbuat kerusakan di bumi. Sungguh, Allah tidak menyukai orang yang berbuat kerusakan" (QS. Al-Qashash: 77).

Hikmah: harta adalah anugerah sekaligus ujian. Kaum Qarun mengajarkan keseimbangan Islam yang indah — mengejar akhirat tanpa melupakan dunia, berbuat baik kepada sesama, dan menjauhi kerusakan. Harta yang benar adalah yang mengantar pemiliknya lebih dekat kepada Allah, bukan menjauhkannya.

Sumber & Catatan: seluruh episode ini bersandar pada Al-Qur''an, QS. Al-Qashash: 76-77 (teks & terjemahan quran-json). Al-Qur''an tidak merinci jumlah harta atau silsilah Qarun; keterangan yang beredar di sebagian tafsir berasal dari riwayat dan tidak dipastikan.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  (SELECT id FROM ayah WHERE surah_id = 28 AND number = 76), 500, datetime('now');
INSERT INTO ebooks (id, title, author, r2_key, category_id, license_status, license_note) VALUES (501, 'Episode 1: Overflowing Wealth and His People''s Counsel', 'Tim Editorial ULYAH', 'ebooks/kisah-qarun/en/kisah-qarun-01-harta-melimpah-dan-nasihat.pdf', 5, 'original', 'Ditulis berdasarkan QS. Al-Qashash 76-77 (quran-json, CC-BY-4.0). Tidak ada kutipan pihak ketiga berhak cipta.');
INSERT INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Episode 1: Overflowing Wealth and His People''s Counsel', 'kisah-qarun-01-harta-melimpah-dan-nasihat', 'en', 'kisah-qarun', 1, 5, 'Qarun (Korah) was one of the people of Prophet Musa, yet he acted tyrannically toward them. Allah had granted him immense wealth — so much that the very keys to his treasure vaults were a heavy load for a band of strong men. Allah said, "Indeed, Qarun was from the people of Musa, but he tyrannized them. And We gave him of treasures whose keys would burden a band of strong men…" (Qur''an 28:76).

Seeing Qarun begin to grow heedless, the righteous among his people counseled him with wisdom: "…[Recall] when his people said to him, ''Do not exult. Indeed, Allah does not like the exultant''" (Qur''an 28:76).

That counsel continued with a balanced guide for life: "But seek, through that which Allah has given you, the home of the Hereafter; and [yet] do not forget your share of the world. And do good as Allah has done good to you. And desire not corruption in the land. Indeed, Allah does not like the corrupters" (Qur''an 28:77).

Reflection: wealth is both a gift and a test. The people of Qarun teach the beautiful balance of Islam — to pursue the Hereafter without forgetting the world, to do good to others, and to shun corruption. True wealth is that which brings its owner closer to Allah, not that which distances him.

Source & Note: this entire episode rests on the Qur''an, 28:76-77 (text & translation from quran-json). The Qur''an does not specify the amount of Qarun''s wealth or his lineage; details circulating in some tafsir come from reports and are not certain.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  (SELECT id FROM ayah WHERE surah_id = 28 AND number = 76), 501, datetime('now');

INSERT INTO ebooks (id, title, author, r2_key, category_id, license_status, license_note) VALUES (502, 'Episode 2: Kesombongan — ''Aku Diberi Karena Ilmuku''', 'Tim Editorial ULYAH', 'ebooks/kisah-qarun/id/kisah-qarun-02-kesombongan-karena-ilmu.pdf', 5, 'original', 'Ditulis berdasarkan QS. Al-Qashash 78-78 (quran-json, CC-BY-4.0). Tidak ada kutipan pihak ketiga berhak cipta.');
INSERT INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Episode 2: Kesombongan — ''Aku Diberi Karena Ilmuku''', 'kisah-qarun-02-kesombongan-karena-ilmu', 'id', 'kisah-qarun', 2, 5, 'Alih-alih menerima nasihat, Qarun menolaknya dengan sombong. Ia menganggap kekayaannya murni hasil kepandaian dan usahanya sendiri, bukan pemberian Allah yang harus disyukuri. Allah berfirman, "Dia (Qarun) berkata, ‘Sesungguhnya aku diberi (harta itu), semata-mata karena ilmu yang ada padaku.’…" (QS. Al-Qashash: 78).

Inilah penyakit hati yang berbahaya: merasa bahwa segala nikmat adalah buah kehebatan diri, sehingga lupa kepada Sang Pemberi. Padahal, betapa banyak orang yang lebih kuat dan lebih banyak hartanya telah dibinasakan Allah karena kesombongan serupa. Allah menegur, "…Tidakkah dia tahu, bahwa Allah telah membinasakan umat-umat sebelumnya yang lebih kuat daripadanya, dan lebih banyak mengumpulkan harta? Dan orang-orang yang berdosa itu tidak perlu ditanya tentang dosa-dosa mereka" (QS. Al-Qashash: 78).

Ilmu dan usaha memang sarana, tetapi keberhasilan hakiki tetaplah karunia Allah. Qarun keliru karena menjadikan ilmunya sebagai alasan untuk menyombongkan diri, bukan sebagai jalan bersyukur.

Hikmah: nikmat yang tidak disandarkan kepada Allah akan menumbuhkan kesombongan, dan kesombongan adalah pintu kebinasaan. Seorang mukmin yang cerdas justru semakin rendah hati ketika nikmatnya bertambah, karena ia tahu semua itu titipan yang akan dimintai pertanggungjawaban.

Sumber & Catatan: dalil dari Al-Qur''an, QS. Al-Qashash: 78. Ucapan Qarun "innama utituhu ''ala ''ilmin ''indi" ("aku diberi karena ilmu padaku") adalah nas ayat yang menggambarkan inti kesombongannya.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  (SELECT id FROM ayah WHERE surah_id = 28 AND number = 78), 502, datetime('now');
INSERT INTO ebooks (id, title, author, r2_key, category_id, license_status, license_note) VALUES (503, 'Episode 2: Arrogance — ''I Was Only Given It Because of My Knowledge''', 'Tim Editorial ULYAH', 'ebooks/kisah-qarun/en/kisah-qarun-02-kesombongan-karena-ilmu.pdf', 5, 'original', 'Ditulis berdasarkan QS. Al-Qashash 78-78 (quran-json, CC-BY-4.0). Tidak ada kutipan pihak ketiga berhak cipta.');
INSERT INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Episode 2: Arrogance — ''I Was Only Given It Because of My Knowledge''', 'kisah-qarun-02-kesombongan-karena-ilmu', 'en', 'kisah-qarun', 2, 5, 'Instead of accepting the counsel, Qarun rejected it arrogantly. He regarded his wealth as purely the fruit of his own cleverness and effort, not a gift of Allah to be thanked. Allah said, "He said, ''I was only given it because of knowledge I have.''…" (Qur''an 28:78).

This is a dangerous disease of the heart: to feel that every blessing is the fruit of one''s own brilliance, and so to forget the Giver. Yet how many stronger and wealthier than him Allah had destroyed for the same arrogance. Allah rebuked: "…Did he not know that Allah had destroyed before him of generations those who were greater than him in power and greater in accumulation [of wealth]? But the criminals, about their sins, will not be asked" (Qur''an 28:78).

Knowledge and effort are indeed means, but true success remains a favor of Allah. Qarun erred because he made his knowledge a reason to boast, rather than a path to gratitude.

Reflection: a blessing not attributed to Allah breeds arrogance, and arrogance is the door to ruin. A wise believer grows more humble as his blessings increase, because he knows they are a trust for which he will be held accountable.

Source & Note: evidence from the Qur''an, 28:78. Qarun''s words "innama utituhu ''ala ''ilmin ''indi" ("I was only given it because of knowledge I have") are the verse''s own text depicting the core of his arrogance.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  (SELECT id FROM ayah WHERE surah_id = 28 AND number = 78), 503, datetime('now');

INSERT INTO ebooks (id, title, author, r2_key, category_id, license_status, license_note) VALUES (504, 'Episode 3: Pamer Kemewahan dan Dua Sikap Manusia', 'Tim Editorial ULYAH', 'ebooks/kisah-qarun/id/kisah-qarun-03-pamer-kemewahan-dua-sikap.pdf', 5, 'original', 'Ditulis berdasarkan QS. Al-Qashash 79-80 (quran-json, CC-BY-4.0). Tidak ada kutipan pihak ketiga berhak cipta.');
INSERT INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Episode 3: Pamer Kemewahan dan Dua Sikap Manusia', 'kisah-qarun-03-pamer-kemewahan-dua-sikap', 'id', 'kisah-qarun', 3, 5, 'Suatu hari Qarun keluar di hadapan kaumnya dengan segala kemegahan dan perhiasannya, memamerkan kekayaannya. Peristiwa itu memunculkan dua sikap yang berbeda di tengah manusia. Allah berfirman, "Maka keluarlah dia (Qarun) kepada kaumnya dengan kemegahannya. Orang-orang yang menginginkan kehidupan dunia berkata, ‘Mudah-mudahan kita mempunyai harta kekayaan seperti apa yang telah diberikan kepada Qarun; sesungguhnya dia benar-benar mempunyai keberuntungan yang besar’" (QS. Al-Qashash: 79).

Itulah sikap orang-orang yang tertipu gemerlap dunia; mereka mengukur keberuntungan hanya dari harta. Namun orang-orang yang berilmu dan beriman memberi timbangan yang berbeda, "Tetapi orang-orang yang dianugerahi ilmu berkata, ‘Celakalah kamu! Ketahuilah, pahala Allah lebih baik bagi orang-orang yang beriman dan mengerjakan kebajikan, dan (pahala yang besar) itu hanya diperoleh oleh orang-orang yang sabar’" (QS. Al-Qashash: 80).

Dua kalimat itu mewakili dua cara pandang manusia sepanjang masa: yang menyilaukan mata pada dunia, dan yang menembus pandangannya sampai ke akhirat. Orang berilmu tahu bahwa keberuntungan sejati bukan pada tumpukan harta, melainkan pada pahala Allah yang diraih dengan iman, amal saleh, dan kesabaran.

Hikmah: kemewahan sering menipu orang yang lemah pandangannya. Ilmu yang benar menjaga hati agar tidak silau oleh dunia, dan mengarahkan cita-cita kepada kekayaan yang kekal di sisi Allah.

Sumber & Catatan: dalil dari Al-Qur''an, QS. Al-Qashash: 79-80. Al-Qur''an tidak merinci bentuk "kemegahan" (zinah) Qarun; yang tegas adalah kontras dua sikap manusia — yang mengidamkan dunia dan yang mengutamakan pahala akhirat.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  (SELECT id FROM ayah WHERE surah_id = 28 AND number = 79), 504, datetime('now');
INSERT INTO ebooks (id, title, author, r2_key, category_id, license_status, license_note) VALUES (505, 'Episode 3: Flaunting Luxury and the Two Attitudes of People', 'Tim Editorial ULYAH', 'ebooks/kisah-qarun/en/kisah-qarun-03-pamer-kemewahan-dua-sikap.pdf', 5, 'original', 'Ditulis berdasarkan QS. Al-Qashash 79-80 (quran-json, CC-BY-4.0). Tidak ada kutipan pihak ketiga berhak cipta.');
INSERT INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Episode 3: Flaunting Luxury and the Two Attitudes of People', 'kisah-qarun-03-pamer-kemewahan-dua-sikap', 'en', 'kisah-qarun', 3, 5, 'One day Qarun came out before his people in all his splendor and adornment, showing off his wealth. That event drew out two different attitudes among people. Allah said, "So he came out before his people in his adornment. Those who desired the worldly life said, ''Oh, would that we had like what was given to Qarun. Indeed, he is one of great fortune''" (Qur''an 28:79).

That is the attitude of those deceived by the glitter of this world; they measure fortune only by wealth. But those endowed with knowledge and faith gave a different measure: "But those who had been given knowledge said, ''Woe to you! The reward of Allah is better for one who believes and does righteousness. And none are granted it except the patient''" (Qur''an 28:80).

Those two sayings represent two ways of seeing that people hold in every age: one dazzled by the world, and one whose sight pierces through to the Hereafter. The people of knowledge know that true fortune is not in a pile of wealth, but in the reward of Allah attained by faith, righteous deeds, and patience.

Reflection: luxury often deceives those weak in insight. True knowledge guards the heart from being dazzled by the world and directs one''s aspiration to the everlasting wealth with Allah.

Source & Note: evidence from the Qur''an, 28:79-80. The Qur''an does not detail the form of Qarun''s "adornment" (zinah); what is firm is the contrast of the two human attitudes — those who craved the world and those who prioritized the reward of the Hereafter.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  (SELECT id FROM ayah WHERE surah_id = 28 AND number = 79), 505, datetime('now');

INSERT INTO ebooks (id, title, author, r2_key, category_id, license_status, license_note) VALUES (506, 'Episode 4: Ditelan Bumi dan Pelajaran Abadi', 'Tim Editorial ULYAH', 'ebooks/kisah-qarun/id/kisah-qarun-04-ditelan-bumi-dan-pelajaran.pdf', 5, 'original', 'Ditulis berdasarkan QS. Al-Qashash 81-83 (quran-json, CC-BY-4.0). Tidak ada kutipan pihak ketiga berhak cipta.');
INSERT INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Episode 4: Ditelan Bumi dan Pelajaran Abadi', 'kisah-qarun-04-ditelan-bumi-dan-pelajaran', 'id', 'kisah-qarun', 4, 5, 'Puncak kisah Qarun datang sebagai keputusan Allah yang menggetarkan. Karena kesombongan dan kezalimannya, Allah membenamkan dia beserta seluruh hartanya ke dalam bumi. Allah berfirman, "Maka Kami benamkanlah dia (Qarun) bersama rumahnya ke dalam bumi. Maka tidak ada baginya satu golongan pun yang akan menolongnya selain Allah, dan dia tidak termasuk orang-orang yang dapat membela diri" (QS. Al-Qashash: 81).

Seketika, harta yang dulu dibanggakan tak mampu menyelamatkannya sedikit pun. Orang-orang yang kemarin mengangankan kedudukannya pun tersadar. Allah berfirman, "Dan orang-orang yang kemarin mengangankan kedudukannya (Qarun) itu berkata, ‘Aduhai, benarlah Allah yang melapangkan rezeki bagi siapa yang Dia kehendaki di antara hamba-hamba-Nya dan membatasi (bagi siapa yang Dia kehendaki). Sekiranya Allah tidak melimpahkan karunia-Nya kepada kita, tentu Dia telah membenamkan kita (pula). Aduhai, benarlah, tidak beruntung orang-orang yang mengingkari (nikmat Allah)’" (QS. Al-Qashash: 82).

Al-Qur''an menutup kisah ini dengan pelajaran yang agung, "Negeri akhirat itu Kami jadikan untuk orang-orang yang tidak menyombongkan diri dan tidak berbuat kerusakan di bumi. Dan kesudahan (yang baik) itu bagi orang-orang yang bertakwa" (QS. Al-Qashash: 83).

Hikmah: harta tidak akan menolong pemiliknya di sisi Allah bila diiringi kesombongan dan kezaliman. Kesudahan yang baik hanya milik orang yang rendah hati dan bertakwa. Kisah Qarun adalah peringatan abadi bahwa dunia yang dibanggakan bisa lenyap dalam sekejap, sedangkan yang kekal hanyalah amal dan ketakwaan.

Sumber & Catatan: dalil dari Al-Qur''an, QS. Al-Qashash: 81-83. Peristiwa "dibenamkan ke bumi" (khasf) adalah nas Al-Qur''an. Rincian tambahan yang beredar di sebagian kisah berasal dari riwayat dan tidak diperlukan untuk memahami pelajaran ayat.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  (SELECT id FROM ayah WHERE surah_id = 28 AND number = 81), 506, datetime('now');
INSERT INTO ebooks (id, title, author, r2_key, category_id, license_status, license_note) VALUES (507, 'Episode 4: Swallowed by the Earth and an Everlasting Lesson', 'Tim Editorial ULYAH', 'ebooks/kisah-qarun/en/kisah-qarun-04-ditelan-bumi-dan-pelajaran.pdf', 5, 'original', 'Ditulis berdasarkan QS. Al-Qashash 81-83 (quran-json, CC-BY-4.0). Tidak ada kutipan pihak ketiga berhak cipta.');
INSERT INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Episode 4: Swallowed by the Earth and an Everlasting Lesson', 'kisah-qarun-04-ditelan-bumi-dan-pelajaran', 'en', 'kisah-qarun', 4, 5, 'The climax of Qarun''s story came as an awesome decree of Allah. Because of his arrogance and injustice, Allah caused the earth to swallow him along with all his wealth. Allah said, "And We caused the earth to swallow him and his home. And there was for him no company to aid him other than Allah, nor was he of those who [could] defend themselves" (Qur''an 28:81).

In an instant, the wealth once boasted of could not save him in the least. Those who yesterday had wished for his position came to their senses. Allah said, "And those who had wished for his position the previous day began to say, ''Oh, how Allah extends provision to whom He wills of His servants and restricts it! If not that Allah had conferred favor on us, He would have caused it to swallow us. Oh, how the disbelievers do not succeed!''" (Qur''an 28:82).

The Qur''an closes this story with a mighty lesson: "That home of the Hereafter We assign to those who do not desire exaltedness upon the earth or corruption. And the [best] outcome is for the righteous" (Qur''an 28:83).

Reflection: wealth will not aid its owner before Allah if it is joined with arrogance and injustice. A good ending belongs only to the humble and the God-fearing. The story of Qarun is an everlasting warning that the world one boasts of can vanish in a moment, while only deeds and piety endure.

Source & Note: evidence from the Qur''an, 28:81-83. The event of being "swallowed by the earth" (khasf) is the Qur''an''s own text. Additional details circulating in some retellings come from reports and are not needed to grasp the lesson of the ayat.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  (SELECT id FROM ayah WHERE surah_id = 28 AND number = 81), 507, datetime('now');

