-- Kisah person index — Ulama Dunia (major classical scholars), same
-- "click a name" pattern as Nabi/Sahabat. Original profiles written from
-- established, universally-taught Islamic scholarly history — not copied
-- from any single book.

INSERT OR IGNORE INTO kisah_person (slug, category_slug, name_id, name_ar, title_id, summary_id, full_story_slug, sort_order) VALUES
('imam-abu-hanifah', 'kisah-ulama-dunia', 'Imam Abu Hanifah', 'الإِمَام أَبُو حَنِيفَة رَحِمَهُ اللهُ', 'Pendiri Mazhab Hanafi (w. 150 H)',
 'Nu''man bin Tsabit, dikenal sebagai Abu Hanifah, lahir di Kufah dan menjadi peletak dasar mazhab fikih Hanafi — mazhab dengan pengikut terbanyak di dunia Islam hingga kini, dianut luas di Turki, Asia Selatan, dan Asia Tengah. Ia dikenal karena pendekatan fikihnya yang menekankan qiyas (analogi) dan ra''yu (penalaran) secara sistematis ketika nash langsung tidak ditemukan. Ia sempat ditawari jabatan hakim agung namun menolaknya demi menjaga independensi keilmuannya, bahkan rela dipenjara akibat penolakan tersebut. Muridnya, terutama Abu Yusuf dan Muhammad bin Hasan Asy-Syaibani, kemudian membukukan dan menyebarkan mazhabnya ke seluruh dunia Islam.', NULL, 1),
('imam-malik', 'kisah-ulama-dunia', 'Imam Malik bin Anas', 'الإِمَام مَالِك بْنُ أَنَسٍ رَحِمَهُ اللهُ', 'Pendiri Mazhab Maliki, Penulis Al-Muwatta (w. 179 H)',
 'Malik bin Anas lahir dan hidup sepanjang hayatnya di Madinah, kota Nabi ﷺ, sehingga fikihnya sangat berpegang pada praktik (amal) penduduk Madinah yang dianggapnya mewarisi langsung tradisi generasi sahabat. Karyanya, Al-Muwatta, adalah salah satu kitab hadits dan fikih tertua yang tersusun rapi, memadukan hadits Nabi ﷺ dengan pendapat sahabat dan tabi''in. Mazhab Maliki yang ia rintis kini dianut luas di Afrika Utara dan Afrika Barat. Ia dikenal sangat berhati-hati dalam berfatwa, sering menjawab "saya tidak tahu" ketika belum yakin, sebuah teladan kerendahan hati ilmiah yang jarang ditemukan.', NULL, 2),
('imam-syafii', 'kisah-ulama-dunia', 'Imam Asy-Syafi''i', 'الإِمَام مُحَمَّد بْنُ إِدْرِيسَ الشَّافِعِيّ رَحِمَهُ اللهُ', 'Pendiri Mazhab Syafi''i, Bapak Ushul Fikih (w. 204 H)',
 'Muhammad bin Idris Asy-Syafi''i lahir di Gaza, belajar fikih Maliki di Madinah dari Imam Malik sendiri, lalu memperdalam ilmu di Irak dan Mesir hingga merumuskan metodologinya sendiri. Ia dijuluki "Bapak Ushul Fikih" karena karyanya, Ar-Risalah, adalah kitab pertama yang menyusun secara sistematis kaidah-kaidah pengambilan hukum Islam dari Al-Qur''an, hadits, ijma, dan qiyas. Mazhab Syafi''i yang ia dirikan dianut luas di Indonesia, Malaysia, Mesir bagian selatan, dan Afrika Timur — menjadikannya mazhab paling berpengaruh di dunia pesantren Nusantara, tempat hampir seluruh kitab kuning dasar (Safinah, Fathul Qarib, Minhajut Thalibin) berpijak.', NULL, 3),
('imam-ahmad-bin-hanbal', 'kisah-ulama-dunia', 'Imam Ahmad bin Hanbal', 'الإِمَام أَحْمَد بْنُ حَنْبَلٍ رَحِمَهُ اللهُ', 'Pendiri Mazhab Hanbali, Penulis Musnad Ahmad (w. 241 H)',
 'Ahmad bin Hanbal dikenal sebagai ulama yang paling teguh mempertahankan akidah Ahlussunnah saat menghadapi ujian berat Mihnah — tekanan penguasa Abbasiyah yang memaksa ulama mengakui paham bahwa Al-Qur''an adalah makhluk (diciptakan). Ia dipenjara dan disiksa bertahun-tahun namun tidak pernah goyah, menjadikannya simbol keteguhan akidah yang dihormati lintas mazhab. Karyanya, Musnad Ahmad, memuat lebih dari 27.000 hadits dan menjadi salah satu koleksi hadits terbesar dalam sejarah Islam. Mazhab Hanbali yang berlandaskan ajarannya kini dianut luas di Jazirah Arab.', NULL, 4),
('imam-bukhari', 'kisah-ulama-dunia', 'Imam Al-Bukhari', 'الإِمَام مُحَمَّد بْنُ إِسْمَاعِيل الْبُخَارِيّ رَحِمَهُ اللهُ', 'Penulis Shahih Bukhari, Kitab Tershahih Setelah Al-Qur''an (w. 256 H)',
 'Muhammad bin Ismail Al-Bukhari lahir di Bukhara (kini Uzbekistan) dan sejak kecil memiliki daya hafal luar biasa, telah menghafal ribuan hadits sebelum usia baligh. Ia melakukan perjalanan (rihlah) ke berbagai kota keilmuan Islam untuk mengumpulkan dan menyaring hadits dari ratusan guru, menerapkan standar keshahihan yang sangat ketat. Dari sekitar 600.000 hadits yang ia kumpulkan, hanya sekitar 7.275 (dengan pengulangan) yang ia masukkan ke dalam Shahih Bukhari — kitab yang disepakati umat Islam sebagai kitab paling shahih setelah Al-Qur''an.', 'kisah-nabi-yusuf-01-mimpi', 5),
('imam-muslim', 'kisah-ulama-dunia', 'Imam Muslim', 'الإِمَام مُسْلِم بْنُ الْحَجَّاجِ رَحِمَهُ اللهُ', 'Penulis Shahih Muslim (w. 261 H)',
 'Muslim bin Al-Hajjaj An-Naisaburi adalah murid sekaligus rekan sezaman Imam Bukhari yang menyusun kitab hadits keduanya yang paling shahih, Shahih Muslim. Ia dikenal karena metodologi penyusunan yang sangat sistematis — mengumpulkan seluruh jalur (sanad) suatu hadits dalam satu tempat sehingga memudahkan kajian perbandingan riwayat. Bersama Shahih Bukhari, karyanya membentuk apa yang dikenal umat Islam sebagai "Ash-Shahihain" (dua kitab paling shahih), rujukan utama dalam menetapkan derajat keshahihan sebuah hadits.', NULL, 6),
('imam-al-ghazali', 'kisah-ulama-dunia', 'Imam Al-Ghazali', 'الإِمَام أَبُو حَامِد الْغَزَالِيّ رَحِمَهُ اللهُ', 'Hujjatul Islam, Penulis Ihya Ulumuddin (w. 505 H)',
 'Abu Hamid Al-Ghazali digelari "Hujjatul Islam" (bukti kebenaran Islam) karena kedalaman keilmuannya yang mencakup fikih, filsafat, tasawuf, dan ilmu kalam sekaligus. Setelah mengalami krisis spiritual di puncak kejayaannya sebagai pengajar di Baghdad, ia meninggalkan segala kedudukan duniawi untuk menempuh jalan tasawuf, dan dari perjalanan itu lahir karya monumentalnya, Ihya Ulumuddin — ensiklopedia spiritual Islam yang memadukan fikih lahiriah dengan penyucian batin. Kitabnya, Bidayatul Hidayah, menjadi salah satu kitab akhlak dasar paling banyak diajarkan di pesantren Nusantara.', NULL, 7),
('imam-an-nawawi', 'kisah-ulama-dunia', 'Imam An-Nawawi', 'الإِمَام يَحْيَى بْنُ شَرَفٍ النَّوَوِيّ رَحِمَهُ اللهُ', 'Penulis Riyadhus Shalihin & Arba''in Nawawi (w. 676 H)',
 'Yahya bin Syaraf An-Nawawi hidup relatif singkat namun luar biasa produktif, menghasilkan puluhan karya besar dalam fikih, hadits, dan akhlak dalam waktu kurang dari 45 tahun usianya. Karyanya Al-Arba''in An-Nawawi (empat puluh hadits pilihan) dan Riyadhus Shalihin (taman orang-orang saleh) menjadi dua kitab paling banyak dihafal dan dikaji santri di seluruh dunia hingga kini. Ia juga menulis Minhajut Thalibin, ringkasan fikih Syafi''i yang menjadi rujukan fatwa utama mazhab tersebut selama berabad-abad. Ia dikenal hidup zuhud, menolak segala jabatan dan kemewahan demi mencurahkan waktu sepenuhnya untuk ilmu dan ibadah.', NULL, 8),
('ibnu-taimiyah', 'kisah-ulama-dunia', 'Ibnu Taimiyah', 'شَيْخُ الْإِسْلَام ابْنُ تَيْمِيَّةَ رَحِمَهُ اللهُ', 'Mujaddid Akidah, Ulama Kontroversial nan Berpengaruh (w. 728 H)',
 'Ahmad bin Abdul Halim, dikenal sebagai Ibnu Taimiyah, adalah ulama mazhab Hanbali yang dikenal karena keberaniannya mengkritik praktik-praktik yang ia anggap menyimpang dari pemahaman generasi awal Islam (salaf), termasuk sebagian tradisi tasawuf dan filsafat kalam. Pandangannya yang tegas membuatnya berulang kali dipenjara oleh penguasa pada masanya, namun ia tetap menulis dan berdakwah bahkan dari dalam penjara hingga wafat di sana. Pemikirannya sangat berpengaruh pada gerakan-gerakan pembaruan Islam di masa-masa setelahnya dan tetap menjadi rujukan penting sekaligus bahan perdebatan di kalangan ulama hingga sekarang.', NULL, 9),
('ibnu-katsir', 'kisah-ulama-dunia', 'Ibnu Katsir', 'الْحَافِظ ابْنُ كَثِيرٍ رَحِمَهُ اللهُ', 'Penulis Tafsir Ibnu Katsir & Al-Bidayah wan Nihayah (w. 774 H)',
 'Isma''il bin Umar Ibnu Katsir adalah murid Ibnu Taimiyah yang dikenal luas karena karya tafsirnya, Tafsir Al-Qur''an Al-''Azhim (populer disebut Tafsir Ibnu Katsir) — salah satu tafsir bil ma''tsur (berbasis riwayat) paling dihormati, menafsirkan Al-Qur''an dengan Al-Qur''an sendiri, lalu hadits, lalu pendapat sahabat. Ia juga menulis Al-Bidayah wan Nihayah, sejarah dunia dari penciptaan hingga masanya yang menjadi salah satu rujukan sejarah Islam paling komprehensif. Karya-karyanya menjadi pegangan wajib di hampir setiap pesantren dan lembaga kajian tafsir di seluruh dunia.', NULL, 10),
('imam-at-tirmidzi', 'kisah-ulama-dunia', 'Imam At-Tirmidzi', 'الإِمَام مُحَمَّد بْنُ عِيسَى التِّرْمِذِيّ رَحِمَهُ اللهُ', 'Penulis Jami'' At-Tirmidzi, Perintis Ilmu Derajat Hadits (w. 279 H)',
 'Muhammad bin Isa At-Tirmidzi adalah murid Imam Bukhari yang menyusun salah satu dari enam kitab hadits utama (Kutubus Sittah), Jami'' At-Tirmidzi. Keistimewaan kitabnya terletak pada kebiasaannya mencantumkan penilaian derajat setiap hadits (shahih, hasan, atau dha''if) secara eksplisit disertai penjelasan perbedaan pendapat mazhab fikih terkait hadits tersebut — menjadikannya rujukan penting bagi pelajar yang ingin memahami keterkaitan hadits dengan fikih perbandingan.', NULL, 11),
('syaikh-nawawi-al-bantani', 'kisah-ulama-dunia', 'Syaikh Nawawi Al-Bantani', 'الشَّيْخ نَوَوِي الْبَنْتَنِيّ رَحِمَهُ اللهُ', 'Ulama Nusantara, Guru Para Ulama Besar Indonesia (w. 1314 H)',
 'Nawawi bin Umar Al-Bantani lahir di Tanara, Banten, lalu menempuh pendidikan dan mengajar puluhan tahun di Makkah hingga digelari "Sayyidul Hijaz" oleh ulama Timur Tengah atas keluasan ilmunya. Ia menulis lebih dari 100 kitab dalam berbagai bidang — tafsir, fikih, tauhid, tasawuf — banyak di antaranya menjadi kitab wajib pesantren Nusantara hingga kini, termasuk Tijan Ad-Darari (syarah akidah) dan tafsir Marah Labid. Murid-muridnya di Makkah kelak menjadi pendiri organisasi dan pesantren besar di Indonesia, menjadikannya salah satu mata rantai keilmuan terpenting yang menghubungkan ulama Nusantara dengan Haramain.', NULL, 12),
('al-habib-abdullah-al-haddad', 'kisah-ulama-dunia', 'Al-Habib Abdullah Al-Haddad', 'الْحَبِيب عَبْدُ اللَّهِ بْنُ عَلَوِيٍّ الْحَدَّاد رَحِمَهُ اللهُ', 'Penulis Ratib Al-Haddad, Ulama Tasawuf Hadramaut (w. 1132 H)',
 'Abdullah bin Alwi Al-Haddad adalah ulama sufi dari Hadramaut, Yaman, yang meski kehilangan penglihatannya sejak kecil akibat cacar, tumbuh menjadi salah satu tokoh tasawuf paling berpengaruh di dunia Melayu-Nusantara. Ia menyusun Ratib Al-Haddad, kumpulan zikir yang hingga kini rutin dibaca berjamaah di masjid-masjid dan majelis taklim di Indonesia, Malaysia, dan kawasan sekitarnya. Karya nasihatnya, An-Nashaihud Diniyyah, menjadi salah satu kitab akhlak dan tasawuf yang paling luas dikaji di pesantren-pesantren tarekat.', NULL, 13);
