-- AUTO-GENERATED by scripts/generate-kisah-harun-seed.ts — do not edit by hand.
-- Source content: scripts/content/kisah-harun.ts (grounded in QS. Ta-Ha, Al-Qashash, Al-A'raf, As-Saffat, Maryam,
-- quran-json CC-BY-4.0). See docs/CONTENT-POLICY.md.
-- Requires quran_seed.sql already applied (resolves related_ayah_id by lookup).
-- No PDFs — read + narrated in-app (TTS), so pdf_ebook_id is NULL.

INSERT OR IGNORE INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Episode 1: Musa Memohon Harun sebagai Penolong', 'kisah-harun-01-permohonan-musa', 'id', 'kisah-harun', 1, 1, 'Ketika Allah memilih Musa untuk mengemban tugas besar menghadapi Fir''aun, Musa merasakan beratnya beban itu. Maka ia memohon kepada Tuhannya agar diberi seorang penolong dari keluarganya sendiri — saudaranya, Harun. Allah mengabadikan doanya, "Dan jadikanlah untukku seorang pembantu dari keluargaku, (yaitu) Harun, saudaraku. Teguhkanlah kekuatanku dengan (adanya) dia, dan jadikanlah dia teman dalam urusanku, agar kami banyak bertasbih kepada-Mu, dan banyak mengingat-Mu" (QS. Ta-Ha: 29-34).

Musa tidak meminta harta atau kedudukan, melainkan seorang saudara yang menguatkan langkahnya di jalan Allah dan menemaninya dalam berzikir dan berjuang. Permohonan itu langsung dikabulkan. Allah berfirman, "Sungguh, telah diperkenankan permintaanmu, wahai Musa" (QS. Ta-Ha: 36).

Dalam Surah Al-Qashash, Musa menyebut satu keutamaan Harun yang khusus, "Dan saudaraku Harun, dia lebih fasih lidahnya daripadaku, maka utuslah dia bersamaku sebagai pembantuku untuk membenarkan (perkataan)ku; sesungguhnya aku khawatir mereka akan mendustakanku." Allah menjawab, "Kami akan menguatkan engkau dengan saudaramu, dan Kami berikan kepadamu berdua kekuasaan yang besar…" (QS. Al-Qashash: 34-35).

Hikmah: perjuangan besar tidak dipikul sendirian. Seorang yang kuat imannya pun butuh saudara yang meneguhkan. Allah mengajarkan bahwa saling menolong dalam kebaikan dan mengingat-Nya adalah sunnah para nabi — dan Dia mengabulkan doa yang tujuannya memperbanyak tasbih dan zikir kepada-Nya.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  (SELECT id FROM ayah WHERE surah_id = 20 AND number = 29), NULL, datetime('now');
INSERT OR IGNORE INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Episode 1: Musa Asks for Harun as a Helper', 'kisah-harun-01-permohonan-musa', 'en', 'kisah-harun', 1, 1, 'When Allah chose Musa for the great task of confronting Pharaoh, Musa felt the weight of it. So he asked his Lord for a helper from his own family — his brother, Harun. Allah preserved his supplication: "And appoint for me a minister from my family — Harun, my brother. Increase through him my strength and let him share my task, that we may exalt You much and remember You much" (Qur''an 20:29-34).

Musa asked for neither wealth nor rank, but for a brother to strengthen his steps on the path of Allah and to keep him company in remembrance and struggle. The request was granted at once. Allah said, "You have been granted your request, O Musa" (Qur''an 20:36).

In Surah Al-Qashash, Musa named a special merit of Harun: "And my brother Harun is more fluent than me in tongue, so send him with me as support, verifying me. Indeed, I fear that they will deny me." Allah answered, "We will strengthen your arm through your brother and grant you both authority…" (Qur''an 28:34-35).

Reflection: a great struggle is not carried alone. Even one strong in faith needs a brother who steadies him. Allah teaches that mutual help in goodness and in His remembrance is the way of the prophets — and He answers a prayer whose aim is to multiply glorification and remembrance of Him.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  (SELECT id FROM ayah WHERE surah_id = 20 AND number = 29), NULL, datetime('now');

INSERT OR IGNORE INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Episode 2: Harun Diangkat menjadi Nabi dan Juru Bicara', 'kisah-harun-02-nabi-dan-juru-bicara', 'id', 'kisah-harun', 2, 1, 'Harun bukan sekadar pembantu; Allah mengangkatnya menjadi nabi sebagai wujud rahmat-Nya. Allah berfirman, "Dan Kami telah menganugerahkan sebagian rahmat Kami kepadanya, yaitu (menjadikan) saudaranya, Harun, seorang nabi" (QS. Maryam: 53).

Dengan kefasihan lidahnya, Harun menjadi juru bicara yang membenarkan dan menyampaikan risalah bersama Musa. Keduanya lalu diutus menghadap Fir''aun. Allah membekali mereka dengan pesan tentang cara berdakwah kepada penguasa yang zalim, "Pergilah kamu berdua kepada Fir''aun, sesungguhnya dia telah melampaui batas. Maka berbicaralah kamu berdua kepadanya dengan kata-kata yang lemah lembut, mudah-mudahan dia sadar atau takut" (QS. Ta-Ha: 43-44).

Meski menghadapi tiran yang mengaku tuhan, keduanya diperintahkan berkata lembut. Harun, dengan tabiatnya yang santun dan fasih, sangat sesuai untuk peran ini. Ia mendampingi Musa menyampaikan bukti-bukti kebenaran tanpa gentar.

Hikmah: kenabian adalah anugerah dan rahmat, bukan hasil ambisi. Dan dakwah — bahkan kepada orang yang paling zalim — tetap dimulai dengan kelembutan, karena tujuannya menyadarkan, bukan sekadar menaklukkan. Kefasihan lidah adalah nikmat yang mulia bila dipakai membela kebenaran.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  (SELECT id FROM ayah WHERE surah_id = 19 AND number = 53), NULL, datetime('now');
INSERT OR IGNORE INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Episode 2: Harun Is Made a Prophet and a Spokesman', 'kisah-harun-02-nabi-dan-juru-bicara', 'en', 'kisah-harun', 2, 1, 'Harun was not merely a helper; Allah raised him to prophethood as an expression of His mercy. Allah said, "And We gave him out of Our mercy his brother Harun as a prophet" (Qur''an 19:53).

With the fluency of his tongue, Harun became the spokesman who verified and conveyed the message alongside Musa. The two were then sent to Pharaoh. Allah equipped them with guidance on how to call a tyrannical ruler: "Go, both of you, to Pharaoh. Indeed, he has transgressed. And speak to him with gentle speech that perhaps he may be reminded or fear [Allah]" (Qur''an 20:43-44).

Though facing a tyrant who claimed divinity, the two were commanded to speak gently. Harun, with his courteous and eloquent nature, was well suited to this role. He stood with Musa, conveying the proofs of truth without fear.

Reflection: prophethood is a gift and a mercy, not the fruit of ambition. And da''wah — even to the most tyrannical — still begins with gentleness, for its aim is to awaken, not merely to subdue. Fluency of speech is a noble blessing when used to defend the truth.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  (SELECT id FROM ayah WHERE surah_id = 19 AND number = 53), NULL, datetime('now');

INSERT OR IGNORE INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Episode 3: Harun Dipercaya Memimpin Bani Israil', 'kisah-harun-03-khalifah-atas-bani-israil', 'id', 'kisah-harun', 3, 1, 'Setelah Bani Israil diselamatkan dari Fir''aun, Musa dipanggil Tuhannya untuk bermunajat di Gunung Thur selama waktu yang ditentukan. Sebelum berangkat, Musa menyerahkan kepemimpinan umat kepada Harun. Allah berfirman, "Dan Musa berkata kepada saudaranya, Harun, ‘Gantikanlah aku dalam (memimpin) kaumku, dan perbaikilah (dirimu dan kaummu), dan janganlah engkau mengikuti jalan orang-orang yang berbuat kerusakan’" (QS. Al-A''raf: 142).

Amanah ini menunjukkan betapa besar kepercayaan Musa kepada Harun. Ia dipilih memimpin umat yang berjumlah besar, yang baru saja lepas dari perbudakan dan masih rapuh imannya. Tugas Harun bukan sekadar menjaga ketertiban, melainkan menjaga agama mereka agar tidak menyimpang.

Harun menerima amanah itu dengan penuh tanggung jawab. Ia berdiri di tengah kaum yang mudah goyah, berusaha membimbing mereka tetap di atas tauhid selama saudaranya pergi.

Hikmah: amanah kepemimpinan adalah ujian berat, terutama atas umat yang imannya belum kokoh. Pesan Musa — "perbaikilah, dan jangan ikuti jalan perusak" — adalah pedoman abadi bagi setiap pemimpin: menegakkan perbaikan dan menjauhi segala yang merusak.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  (SELECT id FROM ayah WHERE surah_id = 7 AND number = 142), NULL, datetime('now');
INSERT OR IGNORE INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Episode 3: Harun Is Entrusted to Lead the Children of Israel', 'kisah-harun-03-khalifah-atas-bani-israil', 'en', 'kisah-harun', 3, 1, 'After the Children of Israel were saved from Pharaoh, Musa was called by his Lord to commune at Mount Tur for an appointed term. Before leaving, Musa handed leadership of the people to Harun. Allah said, "And Musa said to his brother Harun, ''Take my place among my people, do right [by them], and do not follow the way of the corrupters''" (Qur''an 7:142).

This trust shows how greatly Musa relied on Harun. He was chosen to lead a vast people, newly freed from slavery and still fragile in faith. Harun''s task was not merely to keep order, but to guard their religion against deviation.

Harun accepted the trust with full responsibility. He stood among a people easily swayed, striving to keep them upon tawhid while his brother was away.

Reflection: the trust of leadership is a heavy trial, especially over a people whose faith is not yet firm. Musa''s charge — "do right, and do not follow the way of the corrupters" — is an eternal guide for every leader: to uphold reform and shun all that corrupts.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  (SELECT id FROM ayah WHERE surah_id = 7 AND number = 142), NULL, datetime('now');

INSERT OR IGNORE INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Episode 4: Menghadapi Fitnah Patung Anak Sapi', 'kisah-harun-04-fitnah-anak-sapi', 'id', 'kisah-harun', 4, 1, 'Selama Musa di Gunung Thur, seorang bernama Samiri menyesatkan Bani Israil. Ia membuat patung anak sapi dari perhiasan emas mereka, yang bisa mengeluarkan suara, lalu mengajak kaum itu menyembahnya. Sebagian besar mereka pun tergoda. Harun segera bangkit memperingatkan mereka. Allah berfirman, "Dan sungguh, sebelumnya Harun telah berkata kepada mereka, ‘Wahai kaumku! Sesungguhnya kamu hanya diberi cobaan dengan (patung anak sapi) itu, dan sesungguhnya Tuhanmu ialah (Tuhan) Yang Maha Pengasih, maka ikutilah aku dan taatilah perintahku’" (QS. Ta-Ha: 90).

Namun kaum yang keras kepala itu menolak nasihatnya. "Mereka menjawab, ‘Kami tidak akan meninggalkan (penyembahan) patung ini, sebelum Musa kembali kepada kami’" (QS. Ta-Ha: 91).

Harun tidak tinggal diam terhadap kemungkaran. Ia memperingatkan dengan tegas bahwa itu hanyalah fitnah (ujian), dan bahwa hanya Allah Yang Maha Pengasih yang layak disembah. Tetapi ia menghadapi mayoritas yang membangkang, bahkan mengancam keselamatannya.

Hikmah: seorang pembimbing yang benar tidak diam melihat penyimpangan, sekecil apa pun kekuatan yang ia miliki. Harun sudah menunaikan tugasnya — memperingatkan dengan jelas. Namun hidayah tetap di tangan Allah; nasihat bisa ditolak oleh hati yang telah dikuasai hawa nafsu.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  (SELECT id FROM ayah WHERE surah_id = 20 AND number = 90), NULL, datetime('now');
INSERT OR IGNORE INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Episode 4: Facing the Fitna of the Golden Calf', 'kisah-harun-04-fitnah-anak-sapi', 'en', 'kisah-harun', 4, 1, 'While Musa was at Mount Tur, a man named the Samiri led the Children of Israel astray. He fashioned a calf from their gold ornaments that made a lowing sound, and called the people to worship it. Most of them were seduced by it. Harun rose at once to warn them. Allah said, "And Harun had already told them before [the return of Musa], ''O my people, you are only being tested by it, and indeed, your Lord is the Most Merciful, so follow me and obey my order''" (Qur''an 20:90).

But the stubborn people rejected his counsel. "They said, ''We will never cease being devoted to it until Musa returns to us''" (Qur''an 20:91).

Harun did not stay silent before the wrong. He warned firmly that it was only a fitna (trial), and that only Allah, the Most Merciful, deserves worship. Yet he faced a defiant majority that even threatened his safety.

Reflection: a true guide does not stay silent before deviation, however little power he holds. Harun fulfilled his duty — warning clearly. But guidance remains with Allah; counsel can be rejected by a heart overtaken by desire.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  (SELECT id FROM ayah WHERE surah_id = 20 AND number = 90), NULL, datetime('now');

INSERT OR IGNORE INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Episode 5: Penjelasan Harun kepada Musa yang Marah', 'kisah-harun-05-penjelasan-kepada-musa', 'id', 'kisah-harun', 5, 1, 'Musa kembali dari Gunung Thur membawa Taurat, dan mendapati kaumnya menyembah anak sapi. Ia sangat marah dan sedih. Dalam luapan cemburu terhadap agama Allah, ia menegur saudaranya. Allah berfirman, "Dan ketika Musa telah kembali kepada kaumnya, dengan marah dan sedih hati, dia berkata, ‘Alangkah buruknya perbuatan yang kamu kerjakan selama kepergianku!…’ Dan dia (Musa) memegang kepala saudaranya (Harun) sambil menarik ke arahnya. (Harun) berkata, ‘Wahai anak ibuku! Kaum ini telah menganggapku lemah dan hampir saja mereka membunuhku, sebab itu janganlah engkau menjadikan musuh-musuh menyoraki melihat kemalanganku, dan janganlah engkau jadikan aku sebagai orang-orang yang zalim’" (QS. Al-A''raf: 150).

Dalam Surah Ta-Ha, Harun menambahkan alasan mengapa ia tidak bertindak lebih keras, "…Sesungguhnya aku khawatir engkau akan berkata, ‘Engkau telah memecah belah antara Bani Israil dan engkau tidak memelihara amanatku’" (QS. Ta-Ha: 94).

Harun ternyata telah bertindak sejauh yang ia mampu, tetapi menahan diri dari tindakan yang bisa memecah belah umat menjadi dua kubu yang saling berperang. Mendengar penjelasan itu, kemarahan Musa reda, dan ia pun berdoa memohon ampun untuk dirinya dan saudaranya.

Hikmah: kadang menjaga persatuan umat menuntut kesabaran yang lebih besar daripada tindakan keras. Harun memilih menjaga jamaah dari perpecahan sambil terus menasihati. Dan seorang yang beriman, meski terzalimi oleh salah paham, tetap menjelaskan dengan lembut, bukan membalas dengan amarah.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  (SELECT id FROM ayah WHERE surah_id = 7 AND number = 150), NULL, datetime('now');
INSERT OR IGNORE INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Episode 5: Harun Explains Himself to an Angry Musa', 'kisah-harun-05-penjelasan-kepada-musa', 'en', 'kisah-harun', 5, 1, 'Musa returned from Mount Tur carrying the Torah and found his people worshipping the calf. He was filled with anger and grief. In his zeal for the religion of Allah, he rebuked his brother. Allah said, "And when Musa returned to his people, angry and grieved, he said, ''How wretched is that by which you have replaced me after [my departure]…'' And he seized his brother by [the hair of] his head, pulling him toward him. [Harun] said, ''O son of my mother, indeed the people overpowered me and were about to kill me, so let not the enemies rejoice over me and do not place me among the wrongdoing people''" (Qur''an 7:150).

In Surah Ta-Ha, Harun added why he had not acted more forcefully: "…Indeed, I feared that you would say, ''You caused division among the Children of Israel and did not observe my word''" (Qur''an 20:94).

Harun had in fact acted to the limit of his ability, but restrained himself from a course that might split the people into two warring camps. On hearing the explanation, Musa''s anger subsided, and he prayed for forgiveness for himself and his brother.

Reflection: at times, preserving the unity of a people demands greater patience than harsh action. Harun chose to guard the community from schism while continuing to counsel. And a believer, though wronged by misunderstanding, still explains gently rather than answering with rage.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  (SELECT id FROM ayah WHERE surah_id = 7 AND number = 150), NULL, datetime('now');

INSERT OR IGNORE INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Episode 6: Keutamaan Harun dan Pujian Allah', 'kisah-harun-06-keutamaan-dan-pujian-allah', 'id', 'kisah-harun', 6, 1, 'Al-Qur''an menutup kisah dua bersaudara ini dengan pujian yang tinggi dan salam sejahtera yang abadi. Allah berfirman, "Dan sungguh, Kami telah melimpahkan nikmat kepada Musa dan Harun. Dan Kami selamatkan keduanya dan kaumnya dari bencana yang besar, dan Kami tolong mereka, sehingga jadilah mereka orang-orang yang menang. Dan Kami berikan kepada keduanya Kitab yang sangat jelas, dan Kami tunjukkan keduanya ke jalan yang lurus. Dan Kami abadikan untuk keduanya (pujian) di kalangan orang-orang yang datang kemudian, ‘Kesejahteraan (dilimpahkan) atas Musa dan Harun.’ Sungguh, demikianlah Kami memberi balasan kepada orang-orang yang berbuat baik. Sesungguhnya keduanya termasuk hamba-hamba Kami yang beriman" (QS. As-Saffat: 114-122).

Nama Harun disebut berdampingan dengan Musa dalam pujian dan keselamatan. Ia bukan hanya penolong, tetapi seorang nabi yang mulia, hamba beriman yang termasuk golongan orang-orang yang berbuat baik (muhsinin).

Harun wafat mendahului Musa, setelah menunaikan tugasnya membimbing Bani Israil dengan sabar dan lembut. Namanya dikenang harum sepanjang zaman sebagai teladan kesetiaan dan kesabaran.

Hikmah: balasan bagi para muhsinin adalah nama yang harum dan salam sejahtera yang abadi. Harun mengajarkan bahwa peran sebagai "penolong kebenaran" — mendukung, menguatkan, dan menjaga persatuan — adalah kedudukan mulia di sisi Allah, sama terhormatnya dengan memimpin di barisan terdepan.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  (SELECT id FROM ayah WHERE surah_id = 37 AND number = 114), NULL, datetime('now');
INSERT OR IGNORE INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Episode 6: The Merit of Harun and Allah''s Praise', 'kisah-harun-06-keutamaan-dan-pujian-allah', 'en', 'kisah-harun', 6, 1, 'The Qur''an closes the story of these two brothers with high praise and an everlasting greeting of peace. Allah said, "And We did certainly confer favor upon Musa and Harun. And We saved them and their people from the great affliction, and We supported them so it was they who overcame. And We gave them the explicit Scripture, and We guided them on the straight path. And We left for them [favorable mention] among later generations: ''Peace upon Musa and Harun.'' Indeed, We thus reward the doers of good. Indeed, they were of Our believing servants" (Qur''an 37:114-122).

Harun''s name is mentioned side by side with Musa in praise and in rescue. He was not only a helper, but a noble prophet, a believing servant among the ranks of those who do good (the muhsinin).

Harun passed away before Musa, after fulfilling his task of guiding the Children of Israel with patience and gentleness. His name is remembered with honor through the ages as a model of loyalty and forbearance.

Reflection: the reward of the doers of good is an honored name and an everlasting greeting of peace. Harun teaches that the role of a "supporter of the truth" — backing, strengthening, and guarding unity — is a noble station before Allah, as honorable as leading in the front rank.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  (SELECT id FROM ayah WHERE surah_id = 37 AND number = 114), NULL, datetime('now');

