-- AUTO-GENERATED by scripts/generate-wali-songo-seed.ts — do not edit by hand.
-- Source content: scripts/content/wali-songo.ts (historical/hagiographic; each
-- episode cites its own sources — documented history vs. tradition/folklore).
-- See docs/CONTENT-POLICY.md. No PDFs — read + narrated in-app (TTS).

-- Own category, created idempotently (slug is UNIQUE) and resolved by slug.
INSERT OR IGNORE INTO categories (name, slug, parent_id, auto_created) VALUES ('Kisah Wali Songo', 'kisah-wali-songo', NULL, 0);

INSERT OR IGNORE INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Pengantar: Siapa Wali Songo dan Dari Mana Kisahnya', 'wali-songo-00-pengantar', 'id', 'wali-songo', 1, (SELECT id FROM categories WHERE slug = 'kisah-wali-songo'), '"Wali Songo" berarti sembilan wali — para penyebar Islam yang paling berpengaruh di tanah Jawa sekitar abad ke-15 hingga ke-16 Masehi. Mereka bukan satu generasi yang persis bersamaan, melainkan sebuah jaringan guru dan murid, ayah dan anak, yang saling menyambung selama beberapa dekade. Sebagian besar bergerak di pesisir utara Jawa (Pasisir), pusat perdagangan yang menghubungkan Nusantara dengan dunia Islam yang lebih luas.

Sembilan nama yang paling umum disebut adalah: Sunan Gresik (Maulana Malik Ibrahim), Sunan Ampel (Raden Rahmat), Sunan Bonang, Sunan Drajat, Sunan Kudus (Ja''far Shadiq), Sunan Giri, Sunan Kalijaga, Sunan Muria, dan Sunan Gunung Jati (Syarif Hidayatullah). Perlu dicatat bahwa daftar ini sedikit berbeda di beberapa sumber — beberapa naskah memasukkan nama seperti Syekh Siti Jenar atau Sunan Bayat, sehingga "songo/sembilan" lebih tepat dipahami sebagai sebutan untuk sebuah dewan atau majelis dakwah, bukan angka yang kaku.

Yang membuat Wali Songo istimewa bukan sekadar bahwa mereka menyebarkan Islam, tetapi CARA mereka melakukannya: dengan lembut, bertahap, dan berakar pada budaya setempat. Mereka berdakwah lewat perdagangan, pendidikan pesantren, kesenian (wayang, gamelan, tembang), tata kota, dan keteladanan akhlak — bukan dengan paksaan. Karena pendekatan inilah Islam di Jawa tumbuh damai dan mengakar kuat.

Sumber & Catatan: kisah Wali Songo berasal dari beberapa jenis sumber yang perlu dibedakan. Yang bersifat sejarah terdokumentasi meliputi makam-makam berangka tahun (misalnya batu nisan Maulana Malik Ibrahim di Gresik bertarikh 1419 M), bangunan yang masih berdiri (Masjid Agung Demak, Menara Kudus), serta catatan berdirinya kesultanan Demak, Cirebon, dan Banten. Sementara itu, banyak rincian pribadi, silsilah, dan kisah karomah (keajaiban) bersumber dari naskah tradisi seperti Babad Tanah Jawi dan Serat Walisana, serta tutur (cerita lisan) yang turun-temurun. Dalam seri ini, kami menyebutkan sumbernya di tiap bagian, dan menandai dengan jelas mana yang catatan sejarah dan mana yang tradisi.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  NULL, NULL, datetime('now');
INSERT OR IGNORE INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Introduction: Who the Wali Songo Were and Where Their Story Comes From', 'wali-songo-00-pengantar', 'en', 'wali-songo', 1, (SELECT id FROM categories WHERE slug = 'kisah-wali-songo'), '"Wali Songo" means the nine saints — the most influential propagators of Islam on the island of Java, roughly between the 15th and 16th centuries CE. They were not a single simultaneous generation but a network of teachers and students, fathers and sons, linked across several decades. Most worked along Java''s northern coast (the Pasisir), the trading belt that connected the archipelago with the wider Muslim world.

The nine most commonly named are: Sunan Gresik (Maulana Malik Ibrahim), Sunan Ampel (Raden Rahmat), Sunan Bonang, Sunan Drajat, Sunan Kudus (Ja''far Shadiq), Sunan Giri, Sunan Kalijaga, Sunan Muria, and Sunan Gunung Jati (Syarif Hidayatullah). Note that this list varies slightly between sources — some manuscripts include figures such as Syekh Siti Jenar or Sunan Bayat — so "songo/nine" is best understood as the name of a council or assembly of preachers rather than a rigid number.

What makes the Wali Songo remarkable is not merely that they spread Islam, but HOW they did it: gently, gradually, and rooted in local culture. They preached through trade, pesantren (Islamic boarding schools) education, the arts (shadow puppetry, gamelan, sung poetry), town-building, and the example of good character — never by force. It is because of this approach that Islam in Java grew peacefully and took deep root.

Sources & Notes: the story of the Wali Songo comes from several kinds of sources that must be distinguished. Documented history includes dated tombs (for example the gravestone of Maulana Malik Ibrahim in Gresik, dated 1419 CE), surviving buildings (the Great Mosque of Demak, the Kudus Minaret), and records of the founding of the Demak, Cirebon, and Banten sultanates. Many personal details, genealogies, and karomah (miracle) stories, however, come from traditional manuscripts such as the Babad Tanah Jawi and Serat Walisana, and from oral tradition (tutur) passed down the generations. In this series we name the source in each chapter and clearly mark what is historical record and what is tradition.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  NULL, NULL, datetime('now');

INSERT OR IGNORE INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Sunan Gresik — Maulana Malik Ibrahim, Sang Perintis', 'wali-songo-01-sunan-gresik', 'id', 'wali-songo', 2, (SELECT id FROM categories WHERE slug = 'kisah-wali-songo'), 'Maulana Malik Ibrahim, yang dikenal sebagai Sunan Gresik, dipandang sebagai perintis dan yang tertua di antara Wali Songo. Ia diperkirakan datang ke Jawa pada awal abad ke-15 dan menetap di Gresik, sebuah kota pelabuhan penting di pesisir utara Jawa Timur.

Pendekatan dakwahnya sangat lembut dan membumi. Ia dikenal sebagai pedagang sekaligus tabib yang menolong siapa saja tanpa membedakan agama, dan mengajarkan cara bertani serta berdagang yang lebih baik kepada penduduk. Dengan melayani kebutuhan nyata masyarakat — kesehatan, ekonomi, keadilan — ia menampilkan Islam sebagai rahmat, bukan ancaman. Banyak orang tertarik memeluk Islam bukan karena dipaksa, melainkan karena tersentuh oleh akhlak dan kebaikannya.

Ia juga meletakkan dasar pendidikan dengan mendirikan tempat belajar (cikal bakal pesantren), sehingga generasi berikutnya memiliki fondasi ilmu untuk melanjutkan dakwah. Dari sinilah estafet Wali Songo dimulai.

Hikmah: dakwah yang paling kuat sering kali dimulai dari pelayanan yang tulus. Maulana Malik Ibrahim mengajarkan bahwa memperbaiki kehidupan orang — memberi obat, ilmu, dan keadilan — adalah pintu hati yang paling lebar.

Sumber & Catatan: keberadaan dan wafatnya Maulana Malik Ibrahim termasuk yang paling kuat secara sejarah, karena batu nisannya di Gresik berangka tahun 822 Hijriah (1419 M) dan masih dapat dilihat hingga kini — sebuah bukti terdokumentasi. Adapun asal-usulnya (ada riwayat menyebut dari Persia/Asia Tengah, ada pula yang menyebut dari wilayah Arab seperti Kashan atau dari Champa) masih diperdebatkan para sejarawan dan berasal dari berbagai naskah tradisi. Rincian tentang profesinya sebagai tabib dan pedagang bersumber dari babad dan tutur setempat.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  NULL, NULL, datetime('now');
INSERT OR IGNORE INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Sunan Gresik — Maulana Malik Ibrahim, the Pioneer', 'wali-songo-01-sunan-gresik', 'en', 'wali-songo', 2, (SELECT id FROM categories WHERE slug = 'kisah-wali-songo'), 'Maulana Malik Ibrahim, known as Sunan Gresik, is regarded as the pioneer and the eldest among the Wali Songo. He is thought to have arrived in Java in the early 15th century and settled in Gresik, an important port town on the northern coast of East Java.

His method of preaching was gentle and down-to-earth. He was known as a trader and a healer who helped everyone regardless of religion, and who taught the people better ways of farming and trading. By serving people''s real needs — health, livelihood, justice — he presented Islam as a mercy rather than a threat. Many were drawn to embrace Islam not through coercion, but because they were moved by his character and kindness.

He also laid the foundations of education by establishing a place of learning (the seed of the pesantren tradition), so that the next generation would have a grounding in knowledge to carry the mission forward. From here the relay of the Wali Songo began.

Reflection: the strongest preaching often begins with sincere service. Maulana Malik Ibrahim teaches that improving people''s lives — giving medicine, knowledge, and justice — is the widest door to the heart.

Sources & Notes: the existence and death of Maulana Malik Ibrahim are among the most historically secure, because his gravestone in Gresik is dated 822 AH (1419 CE) and can still be seen today — documented evidence. His origins (some accounts say Persia/Central Asia, others an Arab region such as Kashan, or Champa) remain debated among historians and derive from various traditional manuscripts. Details of his work as a healer and trader come from local babad and oral tradition.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  NULL, NULL, datetime('now');

INSERT OR IGNORE INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Sunan Ampel — Raden Rahmat dan Ajaran Moh Limo', 'wali-songo-02-sunan-ampel', 'id', 'wali-songo', 3, (SELECT id FROM categories WHERE slug = 'kisah-wali-songo'), 'Sunan Ampel, bernama asli Raden Rahmat, adalah salah satu tokoh pusat Wali Songo. Ia mendirikan pesantren di Ampel Denta, kawasan Surabaya, yang menjadi pusat pendidikan Islam paling berpengaruh pada zamannya. Dari pesantren inilah lahir dan terdidik banyak wali berikutnya.

Ajarannya yang paling terkenal adalah "Moh Limo" — lima hal yang harus ditinggalkan, dirumuskan dalam bahasa Jawa yang mudah diingat rakyat: moh main (tidak berjudi), moh ngombe (tidak mabuk/minum keras), moh maling (tidak mencuri), moh madat (tidak memakai candu/narkoba), dan moh madon (tidak berzina). Dengan lima pesan sederhana ini, Sunan Ampel mengajarkan inti akhlak Islam dalam bentuk yang dekat dengan kehidupan sehari-hari.

Ia juga dikenal sebagai perencana dan penasihat: banyak riwayat menyebut perannya dalam berdirinya Kesultanan Demak, kerajaan Islam pertama di Jawa, dan dalam pembangunan Masjid Agung Demak. Ia menjadi guru dan tokoh yang dihormati, penghubung antara dunia ulama dan dunia kekuasaan.

Hikmah: pesan yang baik akan lebih mudah tertanam bila disampaikan dengan bahasa yang dekat dengan pendengarnya. "Moh Limo" mengajarkan bahwa memperbaiki masyarakat bisa dimulai dari lima larangan yang jelas dan membumi.

Sumber & Catatan: keberadaan pesantren Ampel Denta dan makam Sunan Ampel di Surabaya adalah fakta terdokumentasi dan masih menjadi tempat ziarah hingga kini. Perannya sebagai guru para wali dan penasihat Demak banyak diriwayatkan dalam Babad Tanah Jawi dan tradisi pesantren. Rumusan "Moh Limo" adalah ajaran yang diwariskan secara turun-temurun dalam tutur Jawa; tahun kelahiran dan wafatnya (sekitar 1401–1481 M dalam beberapa riwayat) bervariasi antar sumber.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  NULL, NULL, datetime('now');
INSERT OR IGNORE INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Sunan Ampel — Raden Rahmat and the Teaching of Moh Limo', 'wali-songo-02-sunan-ampel', 'en', 'wali-songo', 3, (SELECT id FROM categories WHERE slug = 'kisah-wali-songo'), 'Sunan Ampel, whose birth name was Raden Rahmat, was one of the central figures of the Wali Songo. He founded a pesantren at Ampel Denta in the Surabaya area, which became the most influential centre of Islamic education of its time. From this school many of the later saints emerged and were trained.

His most famous teaching is "Moh Limo" — five things to abstain from, framed in easily remembered Javanese: moh main (no gambling), moh ngombe (no intoxicants), moh maling (no stealing), moh madat (no opium/drugs), and moh madon (no adultery). With these five simple messages, Sunan Ampel taught the core of Islamic character in a form close to everyday life.

He was also known as a planner and advisor: many accounts describe his role in the founding of the Sultanate of Demak, the first Islamic kingdom in Java, and in the building of its Great Mosque. He became a revered teacher and figure, a bridge between the world of scholars and the world of power.

Reflection: a good message takes root more easily when delivered in language close to its listeners. "Moh Limo" shows that reforming a society can begin with five clear, grounded prohibitions.

Sources & Notes: the existence of the Ampel Denta pesantren and Sunan Ampel''s tomb in Surabaya are documented facts and remain pilgrimage sites today. His role as teacher of the saints and advisor to Demak is widely narrated in the Babad Tanah Jawi and pesantren tradition. The "Moh Limo" formulation is a teaching handed down through Javanese oral tradition; his birth and death years (around 1401–1481 CE in some accounts) vary between sources.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  NULL, NULL, datetime('now');

INSERT OR IGNORE INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Sunan Bonang — Dakwah Lewat Gamelan dan Tembang', 'wali-songo-03-sunan-bonang', 'id', 'wali-songo', 4, (SELECT id FROM categories WHERE slug = 'kisah-wali-songo'), 'Sunan Bonang, bernama Raden Makdum Ibrahim, adalah putra Sunan Ampel. Ia melanjutkan dakwah ayahnya dengan sebuah pendekatan yang khas dan memikat: melalui kesenian, khususnya musik gamelan dan tembang (nyanyian Jawa).

Menurut tradisi, ia menggubah dan memanfaatkan alat musik — nama "Bonang" sendiri dikaitkan dengan salah satu instrumen gamelan — untuk menarik masyarakat berkumpul, lalu menyisipkan pesan tauhid dan akhlak dalam bait-bait tembang. Salah satu karya yang secara tradisi dinisbatkan kepadanya adalah "Tembang Tombo Ati" (Obat Hati), yang berisi lima resep penyembuh hati: membaca Al-Qur''an dan maknanya, mendirikan salat malam, berkumpul dengan orang saleh, memperbanyak puasa, dan berzikir panjang di malam hari.

Dengan cara ini, Sunan Bonang tidak menolak budaya Jawa, melainkan mengarahkannya. Ia mengambil apa yang sudah dicintai masyarakat — seni suara dan musik — lalu mengisinya dengan nilai-nilai Islam, sehingga dakwah terasa akrab, bukan asing.

Hikmah: keindahan bisa menjadi jalan menuju kebenaran. Sunan Bonang mengajarkan bahwa seni yang diarahkan dengan niat baik dapat menjadi sarana menyampaikan pesan yang mulia.

Sumber & Catatan: makam Sunan Bonang di Tuban adalah situs terdokumentasi dan ramai diziarahi. Perannya dalam dakwah lewat kesenian, serta penisbatan "Tombo Ati" kepadanya, berasal dari tradisi lisan dan naskah-naskah Jawa; para peneliti mencatat bahwa penisbatan karya seni kepada tokoh tertentu dalam tradisi Jawa tidak selalu bisa dipastikan secara historis. Tahun hidupnya (sekitar 1465–1525 M) berbeda-beda antar sumber.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  NULL, NULL, datetime('now');
INSERT OR IGNORE INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Sunan Bonang — Preaching Through Gamelan and Song', 'wali-songo-03-sunan-bonang', 'en', 'wali-songo', 4, (SELECT id FROM categories WHERE slug = 'kisah-wali-songo'), 'Sunan Bonang, named Raden Makdum Ibrahim, was the son of Sunan Ampel. He carried on his father''s mission with a distinctive and captivating approach: through the arts, especially gamelan music and tembang (Javanese sung poetry).

According to tradition, he composed and made use of musical instruments — the name "Bonang" itself is linked to one of the gamelan instruments — to draw people together, then wove messages of divine oneness and good character into the verses of song. One work traditionally attributed to him is the "Tembang Tombo Ati" (Medicine of the Heart), which lists five remedies for the heart: reciting the Qur''an with its meaning, praying in the night, keeping the company of the righteous, fasting often, and long remembrance of God at night.

In this way, Sunan Bonang did not reject Javanese culture but redirected it. He took what the people already loved — the art of voice and music — and filled it with Islamic values, so that the message felt familiar rather than foreign.

Reflection: beauty can be a path to truth. Sunan Bonang teaches that art guided by good intention can become a vehicle for a noble message.

Sources & Notes: Sunan Bonang''s tomb in Tuban is a documented, much-visited site. His role in preaching through the arts, and the attribution of "Tombo Ati" to him, come from oral tradition and Javanese manuscripts; researchers note that attributing artistic works to particular figures in Javanese tradition cannot always be historically verified. His life dates (around 1465–1525 CE) differ between sources.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  NULL, NULL, datetime('now');

INSERT OR IGNORE INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Sunan Drajat — Wali Kaum Papa dan Ajaran Berbagi', 'wali-songo-04-sunan-drajat', 'id', 'wali-songo', 5, (SELECT id FROM categories WHERE slug = 'kisah-wali-songo'), 'Sunan Drajat, bernama Raden Qasim, adalah putra Sunan Ampel dan adik Sunan Bonang. Bila saudaranya menonjol lewat kesenian, Sunan Drajat dikenal dengan kepekaan sosialnya yang mendalam — ia menaruh perhatian besar pada kaum miskin, anak yatim, orang sakit, dan mereka yang lemah.

Ajarannya menekankan kedermawanan dan gotong royong. Tradisi mengaitkannya dengan pesan "catur piwulang" — empat nasihat berbagi: memberi makan kepada yang lapar, memberi pakaian kepada yang telanjang, memberi payung (perlindungan) kepada yang kehujanan, dan memberi tongkat (bimbingan) kepada yang buta jalannya. Ini adalah rumusan indah tentang kepedulian sosial dalam Islam.

Ia berdakwah di kawasan Lamongan, dan seperti wali lain, ia pun memanfaatkan tembang (di antaranya tembang Pangkur) untuk menyampaikan nasihat. Namun ciri khasnya tetap: Islam yang hadir sebagai pembela kaum lemah, bukan sekadar ritual.

Hikmah: iman yang benar berbuah kepedulian nyata. Sunan Drajat mengajarkan bahwa mencintai Allah tak terpisahkan dari mengasihi sesama, terutama mereka yang paling membutuhkan.

Sumber & Catatan: makam Sunan Drajat di Lamongan dan museum di sekitarnya adalah situs terdokumentasi. Ajaran "catur piwulang" dan penisbatan tembang kepadanya berasal dari tradisi lisan dan naskah Jawa yang diwariskan turun-temurun. Silsilahnya sebagai putra Sunan Ampel disebutkan dalam berbagai babad, meski rincian tahun bervariasi.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  NULL, NULL, datetime('now');
INSERT OR IGNORE INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Sunan Drajat — Saint of the Poor and the Teaching of Giving', 'wali-songo-04-sunan-drajat', 'en', 'wali-songo', 5, (SELECT id FROM categories WHERE slug = 'kisah-wali-songo'), 'Sunan Drajat, named Raden Qasim, was a son of Sunan Ampel and the younger brother of Sunan Bonang. Where his brother stood out through the arts, Sunan Drajat was known for his deep social conscience — he gave great attention to the poor, orphans, the sick, and the weak.

His teaching stressed generosity and mutual help. Tradition links him with the message of the "catur piwulang" — four counsels of giving: feed the hungry, clothe the naked, shelter (give an umbrella to) those caught in the rain, and give a staff (guidance) to those who have lost their way. It is a beautiful formulation of social compassion in Islam.

He preached in the Lamongan region and, like the other saints, used sung poetry (among them the Pangkur metre) to convey counsel. But his hallmark remained constant: an Islam present as the defender of the weak, not merely as ritual.

Reflection: true faith bears the fruit of real compassion. Sunan Drajat teaches that loving God is inseparable from caring for people, especially those most in need.

Sources & Notes: Sunan Drajat''s tomb in Lamongan and the nearby museum are documented sites. The "catur piwulang" teaching and the songs attributed to him come from oral tradition and Javanese manuscripts handed down over generations. His lineage as a son of Sunan Ampel is stated in various babad, though the dates vary.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  NULL, NULL, datetime('now');

INSERT OR IGNORE INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Sunan Kudus — Ja''far Shadiq dan Kearifan Menara Kudus', 'wali-songo-05-sunan-kudus', 'id', 'wali-songo', 6, (SELECT id FROM categories WHERE slug = 'kisah-wali-songo'), 'Sunan Kudus, bernama Ja''far Shadiq, dikenal sebagai wali yang mendalam ilmunya, terutama dalam bidang fikih, sehingga sering dijuluki "Wali al-''ilmi" (wali ilmu). Ia berdakwah di kawasan yang kemudian bernama Kudus (dari kata Arab "Quds", suci) di Jawa Tengah.

Peninggalannya yang paling terkenal dan masih berdiri adalah Masjid Menara Kudus. Menaranya berbentuk unik menyerupai candi Hindu-Jawa, bukan menara bergaya Timur Tengah. Ini adalah bukti nyata pendekatan akulturatif: alih-alih menghancurkan bentuk budaya lama, Sunan Kudus merangkulnya dan mengisinya dengan fungsi baru. Sebuah prasasti pada masjid ini menyebut tahun 1549 M.

Ia juga terkenal karena kearifan toleransinya. Menghormati masyarakat setempat yang banyak masih beragama Hindu dan memuliakan sapi, Sunan Kudus menganjurkan umat Islam Kudus untuk tidak menyembelih sapi — sebuah tradisi yang bertahan hingga kini. Dengan cara ini ia menjaga kerukunan dan menunjukkan wajah Islam yang penuh hormat.

Hikmah: kearifan sejati tahu membedakan mana yang prinsip dan mana yang bisa diberi kelonggaran demi menjaga hati sesama. Sunan Kudus mengajarkan bahwa menghormati budaya orang lain dapat membuka jalan dakwah yang lebih lapang.

Sumber & Catatan: Masjid Menara Kudus, prasasti tahunnya (1549 M), dan makam Sunan Kudus adalah bukti sejarah yang terdokumentasi kuat dan masih dapat dikunjungi. Tradisi tidak menyembelih sapi di Kudus juga tercatat dan hidup hingga sekarang. Adapun rincian peran militernya sebagai panglima Demak dan sejumlah kisah pribadinya bersumber dari babad dan tradisi yang perlu ditimbang secara kritis.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  NULL, NULL, datetime('now');
INSERT OR IGNORE INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Sunan Kudus — Ja''far Shadiq and the Wisdom of the Kudus Minaret', 'wali-songo-05-sunan-kudus', 'en', 'wali-songo', 6, (SELECT id FROM categories WHERE slug = 'kisah-wali-songo'), 'Sunan Kudus, named Ja''far Shadiq, was known as a saint of deep learning, especially in jurisprudence (fiqh), so much so that he was often called "Wali al-''ilmi" (the saint of knowledge). He preached in the region later named Kudus (from the Arabic "Quds", holy) in Central Java.

His most famous surviving legacy is the Menara Kudus Mosque. Its minaret is uniquely shaped like a Hindu-Javanese temple rather than a Middle Eastern tower. This is concrete evidence of the acculturative approach: rather than destroying old cultural forms, Sunan Kudus embraced them and filled them with a new function. An inscription on the mosque bears the year 1549 CE.

He was also renowned for the wisdom of his tolerance. Out of respect for the local people, many still Hindu and honouring cattle, Sunan Kudus urged the Muslims of Kudus not to slaughter cows — a tradition that survives to this day. In this way he preserved harmony and showed a face of Islam full of respect.

Reflection: true wisdom knows how to tell a matter of principle from a matter where leniency preserves others'' hearts. Sunan Kudus teaches that respecting another''s culture can open a broader road for the message.

Sources & Notes: the Menara Kudus Mosque, its dated inscription (1549 CE), and Sunan Kudus''s tomb are strongly documented historical evidence that can still be visited. The tradition of not slaughtering cows in Kudus is likewise recorded and alive today. Details of his role as a military commander of Demak and several personal stories, however, come from babad and tradition that should be weighed critically.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  NULL, NULL, datetime('now');

INSERT OR IGNORE INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Sunan Giri — Raden Paku dan Pusat Ilmu di Bukit Giri', 'wali-songo-06-sunan-giri', 'id', 'wali-songo', 7, (SELECT id FROM categories WHERE slug = 'kisah-wali-songo'), 'Sunan Giri, yang bernama Raden Paku dan juga dikenal sebagai Ainul Yaqin, mendirikan pusat pendidikan dan pemerintahan keagamaan di perbukitan Giri, dekat Gresik. Pesantren Giri berkembang begitu besar dan berwibawa sehingga menjadi semacam "kerajaan ilmu" — Giri Kedaton — yang pengaruhnya menjangkau jauh, bahkan sampai ke wilayah timur Nusantara seperti Kalimantan, Sulawesi, dan Maluku.

Sunan Giri menekankan pendidikan sebagai jantung dakwah. Dari Giri lahir para dai yang kemudian menyebar ke berbagai penjuru kepulauan. Karena wibawa keilmuannya, ia juga menjadi rujukan dan penasihat bagi para penguasa Islam pada masa itu.

Tradisi juga menisbatkan kepadanya sejumlah permainan dan tembang anak-anak yang mengandung pesan moral — cara halus menanamkan nilai kepada generasi muda sejak dini. Dengan begitu, dakwah tidak hanya menyentuh orang dewasa, tetapi juga membentuk anak-anak lewat budaya bermain.

Hikmah: membangun ilmu dan pendidikan adalah investasi dakwah yang paling tahan lama. Sunan Giri mengajarkan bahwa satu pusat ilmu yang kuat dapat melahirkan ribuan penerus kebaikan.

Sumber & Catatan: keberadaan Giri Kedaton dan makam Sunan Giri di Gresik adalah fakta sejarah yang terdokumentasi; pengaruh politik-keagamaan Giri atas wilayah timur Nusantara juga tercatat dalam sejarah kesultanan-kesultanan setempat. Penisbatan permainan dan tembang anak kepadanya bersumber dari tradisi lisan Jawa dan tidak selalu dapat dipastikan secara historis.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  NULL, NULL, datetime('now');
INSERT OR IGNORE INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Sunan Giri — Raden Paku and the Centre of Learning on the Giri Hills', 'wali-songo-06-sunan-giri', 'en', 'wali-songo', 7, (SELECT id FROM categories WHERE slug = 'kisah-wali-songo'), 'Sunan Giri, named Raden Paku and also known as Ainul Yaqin, founded a centre of education and religious governance on the Giri hills near Gresik. The Giri pesantren grew so large and authoritative that it became a kind of "kingdom of knowledge" — Giri Kedaton — whose influence reached far, even to the eastern parts of the archipelago such as Borneo, Sulawesi, and the Moluccas.

Sunan Giri made education the heart of his mission. From Giri came preachers who then spread to many corners of the islands. Because of the authority of his learning, he also became a reference and advisor to the Muslim rulers of the age.

Tradition also attributes to him a number of children''s games and songs carrying moral messages — a gentle way of instilling values in the young from an early age. In this way the mission touched not only adults but also shaped children through the culture of play.

Reflection: building knowledge and education is the most enduring investment in a mission. Sunan Giri teaches that one strong centre of learning can give rise to thousands who carry the good forward.

Sources & Notes: the existence of Giri Kedaton and Sunan Giri''s tomb in Gresik are documented historical facts; Giri''s religious-political influence over the eastern archipelago is also recorded in the histories of the local sultanates. The attribution of children''s games and songs to him comes from Javanese oral tradition and cannot always be historically verified.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  NULL, NULL, datetime('now');

INSERT OR IGNORE INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Sunan Kalijaga — Raden Said dan Dakwah Lewat Wayang', 'wali-songo-07-sunan-kalijaga', 'id', 'wali-songo', 8, (SELECT id FROM categories WHERE slug = 'kisah-wali-songo'), 'Sunan Kalijaga, bernama Raden Said, adalah wali yang paling lekat dengan budaya Jawa dan mungkin yang paling terkenal di kalangan rakyat. Menurut riwayat, ia adalah putra seorang adipati Tuban. Masa mudanya diwarnai kisah pertobatan: tradisi menuturkan ia pernah menjadi perampok yang mengambil harta orang kaya untuk kaum miskin, sebelum bertaubat di bawah bimbingan Sunan Bonang dan menempuh jalan kewalian.

Ciri khas dakwahnya adalah akulturasi budaya yang mendalam. Ia menggunakan wayang kulit sebagai media dakwah — memasukkan nilai-nilai Islam ke dalam kisah pewayangan, bahkan konon menciptakan lakon dan istilah baru seperti "Jimat Kalimasada" yang mengingatkan pada kalimat syahadat. Ia juga dikaitkan dengan tradisi gamelan Sekaten yang ditabuh menjelang peringatan Maulid Nabi untuk menarik masyarakat ke masjid, serta dengan gubahan suluk dan kidung.

Filosofinya adalah bertahap dan lembut: tidak mencabut budaya secara paksa, melainkan mengisinya perlahan dengan makna baru, seperti air mengubah warna tanpa merusak wadahnya. Pendekatan ini membuat Islam diterima luas oleh masyarakat Jawa pedalaman.

Hikmah: perubahan yang berakar sering kali datang dengan sabar dan bertahap. Sunan Kalijaga mengajarkan bahwa memahami dan menghargai budaya sasaran dakwah adalah kunci agar pesan diterima dengan hati terbuka.

Sumber & Catatan: makam Sunan Kalijaga di Kadilangu, Demak, adalah situs terdokumentasi; perannya dalam pengembangan wayang, gamelan Sekaten, dan seni Islam-Jawa tercermin dalam tradisi kesenian yang hidup hingga kini. Namun banyak rincian biografinya — termasuk kisah masa mudanya sebagai "Lokajaya" dan berbagai karomah — bersumber dari Babad Tanah Jawi dan tutur lisan, sehingga perlu dipahami sebagai tradisi, bukan catatan sejarah yang pasti.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  NULL, NULL, datetime('now');
INSERT OR IGNORE INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Sunan Kalijaga — Raden Said and Preaching Through Shadow Puppetry', 'wali-songo-07-sunan-kalijaga', 'en', 'wali-songo', 8, (SELECT id FROM categories WHERE slug = 'kisah-wali-songo'), 'Sunan Kalijaga, named Raden Said, was the saint most bound up with Javanese culture and perhaps the best known among ordinary people. According to tradition, he was the son of a regent (adipati) of Tuban. His youth was marked by a story of repentance: tradition tells that he was once a robber who took from the rich to give to the poor, before repenting under the guidance of Sunan Bonang and taking the path of sainthood.

The hallmark of his mission was deep cultural acculturation. He used the wayang kulit (shadow puppet theatre) as a medium of preaching — infusing Islamic values into the puppet tales, and reportedly creating new stories and terms such as the "Jimat Kalimasada," which evokes the testimony of faith (shahada). He is also associated with the Sekaten gamelan tradition, played before the celebration of the Prophet''s birthday to draw people to the mosque, and with the composition of suluk and kidung poetry.

His philosophy was gradual and gentle: not uprooting culture by force, but slowly filling it with new meaning, like water changing a colour without breaking its vessel. This approach made Islam broadly accepted among the people of inland Java.

Reflection: change that takes root often comes patiently and step by step. Sunan Kalijaga teaches that understanding and honouring the culture of those you address is the key to a message being received with an open heart.

Sources & Notes: Sunan Kalijaga''s tomb in Kadilangu, Demak, is a documented site; his role in developing wayang, the Sekaten gamelan, and Javanese-Islamic art is reflected in living artistic traditions today. Many biographical details, however — including the story of his youth as "Lokajaya" and various karomah — come from the Babad Tanah Jawi and oral tradition, and should be understood as tradition rather than certain historical record.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  NULL, NULL, datetime('now');

INSERT OR IGNORE INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Sunan Muria — Raden Umar Said, Wali Pegunungan', 'wali-songo-08-sunan-muria', 'id', 'wali-songo', 9, (SELECT id FROM categories WHERE slug = 'kisah-wali-songo'), 'Sunan Muria, bernama Raden Umar Said, berdakwah di lereng Gunung Muria, di utara Jawa Tengah. Menurut tradisi yang umum, ia adalah putra Sunan Kalijaga, dan mewarisi pendekatan ayahnya yang halus dan berbasis budaya.

Yang membedakannya adalah medan dakwahnya: ia memilih masyarakat pedesaan dan pegunungan — para petani, pekebun, dan nelayan yang tinggal jauh dari pusat kota. Kepada mereka ia mengajarkan Islam dengan bahasa dan cara yang sederhana, sabar, dan penuh keteladanan, menyesuaikan diri dengan irama hidup orang desa.

Seperti para wali lain, ia menggunakan tembang sebagai sarana dakwah; tradisi menisbatkan kepadanya tembang Sinom dan Kinanti yang berisi nasihat halus. Ia dikenal menempuh cara "topo ngeli" — mengikuti arus masyarakat sambil perlahan mengarahkannya kepada kebaikan, bukan melawannya secara keras.

Hikmah: dakwah yang baik menjangkau semua lapisan, termasuk mereka yang jauh dari pusat dan sering terlupakan. Sunan Muria mengajarkan kesabaran dan kesederhanaan dalam membimbing masyarakat kecil.

Sumber & Catatan: makam Sunan Muria di puncak perbukitan Muria (Kudus) adalah situs ziarah yang terdokumentasi. Silsilahnya sebagai putra Sunan Kalijaga dan penisbatan tembang kepadanya berasal dari tradisi lisan dan naskah Jawa; sebagian sumber berbeda pendapat mengenai silsilah ini, sehingga sebaiknya dipahami sebagai riwayat tradisi.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  NULL, NULL, datetime('now');
INSERT OR IGNORE INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Sunan Muria — Raden Umar Said, the Mountain Saint', 'wali-songo-08-sunan-muria', 'en', 'wali-songo', 9, (SELECT id FROM categories WHERE slug = 'kisah-wali-songo'), 'Sunan Muria, named Raden Umar Said, preached on the slopes of Mount Muria in northern Central Java. According to the common tradition, he was a son of Sunan Kalijaga and inherited his father''s gentle, culture-based approach.

What set him apart was his field of work: he chose the rural and mountain communities — the farmers, gardeners, and fishermen who lived far from the towns. To them he taught Islam in simple, patient language full of good example, adapting to the rhythm of village life.

Like the other saints, he used sung poetry as a means of preaching; tradition attributes to him the Sinom and Kinanti metres, containing gentle counsel. He was known for the way of "topo ngeli" — flowing along with the current of society while slowly steering it toward good, rather than opposing it harshly.

Reflection: good preaching reaches every layer of society, including those far from the centre who are often forgotten. Sunan Muria teaches patience and simplicity in guiding humble folk.

Sources & Notes: Sunan Muria''s tomb atop the Muria hills (Kudus) is a documented pilgrimage site. His lineage as a son of Sunan Kalijaga and the songs attributed to him come from oral tradition and Javanese manuscripts; some sources differ on this lineage, so it is best understood as traditional account.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  NULL, NULL, datetime('now');

INSERT OR IGNORE INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Sunan Gunung Jati — Syarif Hidayatullah, Wali dan Penguasa', 'wali-songo-09-sunan-gunung-jati', 'id', 'wali-songo', 10, (SELECT id FROM categories WHERE slug = 'kisah-wali-songo'), 'Sunan Gunung Jati, bernama Syarif Hidayatullah, adalah satu-satunya di antara Wali Songo yang sekaligus menjadi seorang penguasa negara. Ia berdakwah di Jawa Barat dan menjadi tokoh kunci dalam berdirinya Kesultanan Cirebon dan Kesultanan Banten — dua kekuatan Islam penting di ujung barat Jawa.

Dengan memadukan peran ulama dan pemimpin, Sunan Gunung Jati mampu menyebarkan Islam secara luas dan menata masyarakat sekaligus. Di bawah pengaruhnya, Islam menggantikan pengaruh kerajaan Hindu Pajajaran di wilayah itu secara bertahap, dan Cirebon tumbuh menjadi pusat keagamaan sekaligus perdagangan.

Meski memegang kekuasaan, tradisi mengenangnya sebagai pemimpin yang tetap menjunjung dakwah dan keadilan. Ia menunjukkan bahwa kekuasaan, bila dipegang oleh orang saleh, dapat menjadi alat untuk melindungi umat dan menegakkan kebaikan, bukan untuk menindas.

Hikmah: amanah kepemimpinan adalah ujian sekaligus peluang. Sunan Gunung Jati mengajarkan bahwa kekuasaan yang dilandasi iman dan keadilan dapat menjadi jalan besar bagi kebaikan bersama.

Sumber & Catatan: peran Syarif Hidayatullah dalam berdirinya Kesultanan Cirebon dan Banten adalah bagian dari sejarah yang terdokumentasi dalam catatan kesultanan dan sumber-sumber sejarah; makamnya di Gunung Sembung, Cirebon, adalah kompleks ziarah yang terkenal. Sebagian rincian silsilahnya (termasuk klaim nasab hingga jalur kenabian) dan kisah-kisah karomahnya bersumber dari babad dan tradisi, dan diriwayatkan beragam antar naskah. Tahun hidupnya diperkirakan sekitar 1448–1568 M dalam sejumlah sumber.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  NULL, NULL, datetime('now');
INSERT OR IGNORE INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Sunan Gunung Jati — Syarif Hidayatullah, Saint and Ruler', 'wali-songo-09-sunan-gunung-jati', 'en', 'wali-songo', 10, (SELECT id FROM categories WHERE slug = 'kisah-wali-songo'), 'Sunan Gunung Jati, named Syarif Hidayatullah, was the only one among the Wali Songo who was also a ruler of a state. He preached in West Java and became a key figure in the founding of the Sultanate of Cirebon and the Sultanate of Banten — two important Islamic powers at the western end of Java.

By combining the roles of scholar and leader, Sunan Gunung Jati was able to spread Islam widely and order society at the same time. Under his influence, Islam gradually replaced the sway of the Hindu kingdom of Pajajaran in the region, and Cirebon grew into a centre of both religion and trade.

Though he held power, tradition remembers him as a leader who still upheld the mission and justice. He showed that power, when held by a righteous person, can be a tool to protect the community and uphold what is good, rather than to oppress.

Reflection: the trust of leadership is both a test and an opportunity. Sunan Gunung Jati teaches that power founded on faith and justice can become a great road for the common good.

Sources & Notes: Syarif Hidayatullah''s role in founding the Cirebon and Banten sultanates is part of history documented in sultanate records and historical sources; his tomb at Gunung Sembung, Cirebon, is a well-known pilgrimage complex. Some details of his genealogy (including claims of descent tracing to the prophetic line) and his karomah stories come from babad and tradition, and are narrated variously between manuscripts. His life is estimated at around 1448–1568 CE in a number of sources.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  NULL, NULL, datetime('now');

INSERT OR IGNORE INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'Warisan Wali Songo — Metode Dakwah yang Abadi', 'wali-songo-10-warisan-dan-metode', 'id', 'wali-songo', 11, (SELECT id FROM categories WHERE slug = 'kisah-wali-songo'), 'Setelah menelusuri kisah sembilan wali, satu benang merah tampak jelas: keberhasilan mereka bukan terletak pada kekuatan atau paksaan, melainkan pada kearifan metode. Wali Songo menyebarkan Islam dengan cara yang bijaksana, sabar, dan berakar pada budaya masyarakat yang mereka dakwahi.

Metode itu bisa dirangkum dalam beberapa prinsip. Pertama, keteladanan akhlak — mereka menampilkan Islam lewat perilaku mulia, kejujuran dalam berdagang, dan pelayanan kepada yang lemah. Kedua, pendidikan — pesantren-pesantren yang mereka dirikan mencetak penerus dakwah untuk generasi-generasi berikutnya. Ketiga, akulturasi budaya — mereka tidak menghancurkan seni dan tradisi Jawa, melainkan mengarahkannya: wayang, gamelan, tembang, bahkan arsitektur, diisi dengan nilai tauhid. Keempat, kelembutan dan bertahap — mereka mengajak, bukan memaksa; menuntun, bukan menghakimi.

Pendekatan inilah yang membuat Islam di Nusantara dikenal sebagai Islam yang ramah dan damai. Prinsip-prinsip Wali Songo tetap relevan hingga hari ini: bahwa cara menyampaikan kebenaran sama pentingnya dengan kebenaran itu sendiri.

Hikmah: dakwah yang paling langgeng adalah yang menyentuh hati, bukan yang menekan. Warisan Wali Songo mengajarkan bahwa hikmah, kesabaran, dan cinta kepada masyarakat adalah kunci menyebarkan kebaikan yang bertahan lintas zaman.

Sumber & Catatan: kesimpulan tentang metode dakwah Wali Songo ini disarikan dari pola yang tampak konsisten di seluruh kisah mereka — sebagian berpijak pada bukti sejarah (pesantren, masjid, kesultanan, kesenian yang masih hidup), sebagian pada tradisi (babad, serat, tutur). Prinsip "keteladanan, pendidikan, akulturasi, dan kelembutan" adalah pembacaan yang banyak disepakati para pengkaji sejarah Islam Nusantara, meski penekanannya dapat berbeda antar penulis.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  NULL, NULL, datetime('now');
INSERT OR IGNORE INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT 'The Legacy of the Wali Songo — an Enduring Method of Preaching', 'wali-songo-10-warisan-dan-metode', 'en', 'wali-songo', 11, (SELECT id FROM categories WHERE slug = 'kisah-wali-songo'), 'After tracing the stories of the nine saints, one common thread stands out clearly: their success lay not in force or coercion, but in the wisdom of their method. The Wali Songo spread Islam in a way that was wise, patient, and rooted in the culture of the people they addressed.

That method can be summed up in a few principles. First, the example of character — they presented Islam through noble conduct, honesty in trade, and service to the weak. Second, education — the pesantren they founded produced successors to carry the mission for generations. Third, cultural acculturation — they did not destroy Javanese arts and traditions but redirected them: wayang, gamelan, sung poetry, even architecture, were filled with the values of divine oneness. Fourth, gentleness and gradualness — they invited rather than forced, guided rather than judged.

It is this approach that made Islam in the archipelago known as a friendly and peaceful Islam. The principles of the Wali Songo remain relevant today: that the way a truth is conveyed is as important as the truth itself.

Reflection: the most lasting mission is the one that touches hearts, not the one that presses upon them. The legacy of the Wali Songo teaches that wisdom, patience, and love for the people are the keys to spreading a good that endures across the ages.

Sources & Notes: this conclusion about the Wali Songo''s method is distilled from the pattern that appears consistently across their stories — partly resting on historical evidence (pesantren, mosques, sultanates, living arts) and partly on tradition (babad, serat, oral tutur). The principles of "example, education, acculturation, and gentleness" are a reading broadly shared by scholars of the history of Islam in the archipelago, though the emphasis may differ between writers.', 0, 'qc_pending', 'ai_original', 'published', 1.0,
  NULL, NULL, datetime('now');

