// AUTO-GENERATED by scripts/generate-locale-readiness.ts — do not edit by hand.
// How complete each language's UI actually is, measured from the dictionaries
// and the generated UI_I18N table. A language is only offered to visitors once
// it reaches 100% (see isLocaleReady in i18n.ts) so nobody lands on a page that
// switches between two languages mid-scroll.
// Re-run after changing dictionaries or UI strings:  pnpm gen:locale-readiness

export interface LocaleReadiness {
  /** Percent of scored UI strings that are genuinely in this language. */
  dict: number;
  /** Percent of the site's own writing translated and cached for this language. */
  content: number;
  /** The lower of the two — a language is only as finished as its weakest half. */
  overall: number;
  /** Up to 40 English strings still showing through, for the admin portal. */
  missing: string[];
}

export const LOCALE_READINESS: Record<string, LocaleReadiness> = {"en":{"dict":100,"content":83,"overall":83,"missing":[]},"ar":{"dict":100,"content":100,"overall":100,"missing":[]},"bn":{"dict":100,"content":7.7,"overall":7.7,"missing":[]},"de":{"dict":100,"content":49.3,"overall":49.3,"missing":[]},"es":{"dict":100,"content":72.1,"overall":72.1,"missing":[]},"fa":{"dict":100,"content":5.9,"overall":5.9,"missing":[]},"fr":{"dict":100,"content":100,"overall":100,"missing":[]},"ha":{"dict":100,"content":3.7,"overall":3.7,"missing":[]},"hi":{"dict":100,"content":70.1,"overall":70.1,"missing":[]},"id":{"dict":100,"content":100,"overall":100,"missing":[]},"it":{"dict":100,"content":4.1,"overall":4.1,"missing":[]},"ja":{"dict":100,"content":19.3,"overall":19.3,"missing":[]},"ko":{"dict":100,"content":4.2,"overall":4.2,"missing":[]},"ms":{"dict":100,"content":4.3,"overall":4.3,"missing":[]},"nl":{"dict":100,"content":4.8,"overall":4.8,"missing":[]},"pl":{"dict":100,"content":4.8,"overall":4.8,"missing":[]},"ps":{"dict":100,"content":6.1,"overall":6.1,"missing":[]},"pt":{"dict":100,"content":4.8,"overall":4.8,"missing":[]},"ru":{"dict":100,"content":6.9,"overall":6.9,"missing":[]},"so":{"dict":100,"content":4.2,"overall":4.2,"missing":[]},"sw":{"dict":100,"content":7.6,"overall":7.6,"missing":[]},"ta":{"dict":100,"content":4.6,"overall":4.6,"missing":[]},"th":{"dict":100,"content":4,"overall":4,"missing":[]},"tr":{"dict":100,"content":4.2,"overall":4.2,"missing":[]},"ur":{"dict":100,"content":4.7,"overall":4.7,"missing":[]},"uz":{"dict":100,"content":7.3,"overall":7.3,"missing":[]},"vi":{"dict":100,"content":4.6,"overall":4.6,"missing":[]},"zh":{"dict":100,"content":6.9,"overall":6.9,"missing":[]}};
