// AUTO-GENERATED by scripts/generate-locale-readiness.ts — do not edit by hand.
// How complete each language's UI actually is, measured from the dictionaries
// and the generated UI_I18N table. A language is only offered to visitors once
// it reaches 100% (see isLocaleReady in i18n.ts) so nobody lands on a page that
// switches between two languages mid-scroll.
// Re-run after changing dictionaries or UI strings:  pnpm gen:locale-readiness

export interface LocaleReadiness {
  /** Percent of scored UI strings that are genuinely in this language. */
  dict: number;
  /** Percent of the site's own writing translated and cached for this language. */
  content: number;
  /** The lower of the two — a language is only as finished as its weakest half. */
  overall: number;
  /** Up to 40 English strings still showing through, for the admin portal. */
  missing: string[];
}

export const LOCALE_READINESS: Record<string, LocaleReadiness> = {"en":{"dict":100,"content":97.7,"overall":97.7,"missing":[]},"ar":{"dict":100,"content":100,"overall":100,"missing":[]},"bn":{"dict":100,"content":1.7,"overall":1.7,"missing":[]},"de":{"dict":100,"content":93.6,"overall":93.6,"missing":[]},"es":{"dict":100,"content":100,"overall":100,"missing":[]},"fa":{"dict":100,"content":1.3,"overall":1.3,"missing":[]},"fr":{"dict":100,"content":95.1,"overall":95.1,"missing":[]},"ha":{"dict":100,"content":0.8,"overall":0.8,"missing":[]},"hi":{"dict":100,"content":18.7,"overall":18.7,"missing":[]},"id":{"dict":100,"content":100,"overall":100,"missing":[]},"it":{"dict":100,"content":0.9,"overall":0.9,"missing":[]},"ja":{"dict":100,"content":4.5,"overall":4.5,"missing":[]},"ko":{"dict":100,"content":0.9,"overall":0.9,"missing":[]},"ms":{"dict":100,"content":1,"overall":1,"missing":[]},"nl":{"dict":100,"content":1.1,"overall":1.1,"missing":[]},"pl":{"dict":100,"content":1.1,"overall":1.1,"missing":[]},"ps":{"dict":100,"content":1.4,"overall":1.4,"missing":[]},"pt":{"dict":100,"content":1.1,"overall":1.1,"missing":[]},"ru":{"dict":100,"content":1.7,"overall":1.7,"missing":[]},"so":{"dict":100,"content":0.9,"overall":0.9,"missing":[]},"sw":{"dict":100,"content":1.7,"overall":1.7,"missing":[]},"ta":{"dict":100,"content":1,"overall":1,"missing":[]},"th":{"dict":100,"content":0.9,"overall":0.9,"missing":[]},"tr":{"dict":100,"content":1,"overall":1,"missing":[]},"ur":{"dict":100,"content":1.1,"overall":1.1,"missing":[]},"uz":{"dict":100,"content":1.6,"overall":1.6,"missing":[]},"vi":{"dict":100,"content":1,"overall":1,"missing":[]},"zh":{"dict":100,"content":1.6,"overall":1.6,"missing":[]}};
