/**
 * Generates packages/db-schema/seed/kisah_ibrahim.sql from
 * scripts/content/kisah-ibrahim.ts. Run:
 *   npx tsx scripts/generate-kisah-ibrahim-seed.ts
 * (after quran_seed.sql has been applied, since related_ayah_id is resolved
 * via a subquery against `ayah`).
 *
 * Unlike the earlier prophet series, this one ships NO PDF/ebook rows — the
 * stories are read from their body text and narrated by the built-in
 * ContinuousStoryReader (TTS), so there is nothing to download and no broken
 * PDF links. pdf_ebook_id is left NULL.
 */
import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { KISAH_IBRAHIM_SERIES } from "./content/kisah-ibrahim.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(__dirname, "..");
const outDir = join(repoRoot, "packages", "db-schema", "seed");

// Ibrahim belongs in "Kisah Para Nabi" (category id=1 from
// 0002_seed_static.sql), the same bucket as the other prophet series.
const CATEGORY_ID = 1;

function esc(s: string): string {
  return `'${s.replace(/'/g, "''")}'`;
}

function main() {
  mkdirSync(outDir, { recursive: true });
  const lines: string[] = [
    "-- AUTO-GENERATED by scripts/generate-kisah-ibrahim-seed.ts — do not edit by hand.",
    "-- Source content: scripts/content/kisah-ibrahim.ts (grounded in the main Ibrahim passages (Al-An'am, Maryam, Al-Anbiya, Al-Baqarah, Hud, As-Saffat),",
    "-- quran-json CC-BY-4.0). See docs/CONTENT-POLICY.md.",
    "-- Requires quran_seed.sql already applied (resolves related_ayah_id by lookup).",
    "-- No PDFs — read + narrated in-app (TTS), so pdf_ebook_id is NULL.",
    "",
  ];

  KISAH_IBRAHIM_SERIES.forEach((ep, i) => {
    for (const lang of ["id", "en"] as const) {
      const content = ep[lang];
      lines.push(
        `INSERT INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT ${esc(content.title)}, ${esc(ep.slug)}, ${esc(lang)}, 'kisah-ibrahim', ${i + 1}, ${CATEGORY_ID}, ${esc(content.body)}, 0, 'qc_pending', 'ai_original', 'published', 1.0,
  (SELECT id FROM ayah WHERE surah_id = ${ep.surahId} AND number = ${ep.ayahStart}), NULL, datetime('now');`
      );
    }
    lines.push("");
  });

  writeFileSync(join(outDir, "kisah_ibrahim.sql"), lines.join("\n") + "\n", "utf-8");
  console.log(
    `Wrote kisah_ibrahim.sql — ${KISAH_IBRAHIM_SERIES.length} episodes x 2 languages = ${KISAH_IBRAHIM_SERIES.length * 2} stories.`
  );
}

main();
