/**
 * Generates packages/db-schema/seed/hadith_ahmad.sql and hadith_darimi.sql
 * from gadingnst/hadith-api (github.com/gadingnst/hadith-api, MIT license) —
 * Musnad Ahmad ibn Hanbal and Sunan ad-Darimi, in Arabic and native
 * Indonesian, matched by hadith number. This is a genuine addition to the
 * library, not a duplicate: neither collection exists among the nine already
 * imported from fawazahmed0/hadith-api (see generate-hadith-seed.ts).
 *
 * Source data is the repo's own bundled JSON dumps (books/ahmad.json,
 * books/darimi.json) — {number, arab, id} per hadith — not a live API call
 * per hadith, so this runs as one bounded fetch per collection.
 *
 * `narrator` is left NULL: like the other bulk-imported collections, the
 * Indonesian text already carries the full isnad chain naturally. `grade`
 * is left NULL — unlike Bukhari/Muslim, inclusion in Musnad Ahmad or Sunan
 * ad-Darimi is not itself a uniform authenticity grade (both contain a mix
 * of hadith gradings), so no grade is asserted without a scholarly source
 * for each individual hadith.
 *
 * Run: npx tsx scripts/generate-hadith-ahmad-darimi-seed.ts
 * (Set HADITH_SOURCE_DIR to a local directory of pre-downloaded ahmad.json /
 * darimi.json to skip the network fetch during iteration.)
 */
import { writeFileSync, mkdirSync, existsSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(__dirname, "..");
const outDir = join(repoRoot, "packages", "db-schema", "seed");
const CACHE_DIR = process.env.HADITH_SOURCE_DIR;

const BASE_URL = "https://raw.githubusercontent.com/gadingnst/hadith-api/master/books";
const MAX_STATEMENT_BYTES = 60_000;

interface GadingRecord {
  number: number;
  arab: string;
  id: string;
}

interface Collection {
  key: string; // hadits.collection slug + output filename
  file: string; // books/<file>.json on gadingnst
  idStart: number;
  nameId: string;
  nameAr: string;
  author: string;
  sortOrder: number;
}

const COLLECTIONS: Collection[] = [
  { key: "ahmad", file: "ahmad.json", idStart: 80001, nameId: "Musnad Ahmad", nameAr: "مسند أحمد", author: "Imam Ahmad bin Hanbal", sortOrder: 10 },
  { key: "darimi", file: "darimi.json", idStart: 90001, nameId: "Sunan Ad-Darimi", nameAr: "سنن الدارمي", author: "Imam Ad-Darimi", sortOrder: 11 },
];

function esc(s: string): string {
  return `'${s.replace(/'/g, "''")}'`;
}

async function loadJson(col: Collection): Promise<GadingRecord[]> {
  if (CACHE_DIR) {
    const p = join(CACHE_DIR, col.file);
    if (existsSync(p)) return JSON.parse(readFileSync(p, "utf-8"));
  }
  const res = await fetch(`${BASE_URL}/${col.file}`);
  if (!res.ok) throw new Error(`Fetch failed for ${col.file}: ${res.status}`);
  return (await res.json()) as GadingRecord[];
}

async function main() {
  mkdirSync(outDir, { recursive: true });

  const catalogLines: string[] = [
    "-- AUTO-GENERATED by scripts/generate-hadith-ahmad-darimi-seed.ts — do not edit by hand.",
    "-- Source: gadingnst/hadith-api (github.com/gadingnst/hadith-api), MIT license.",
    "-- Musnad Ahmad + Sunan ad-Darimi — Arabic + native Indonesian, matched by hadith number.",
    "-- Self-contained catalogue rows (INSERT OR IGNORE) so no separate migration is needed,",
    "-- same pattern as the 'Kisah Islami' category added in kisah_dzulqarnain.sql.",
    "",
  ];
  for (const col of COLLECTIONS) {
    const idEnd = col.idStart + 9998;
    catalogLines.push(
      `INSERT OR IGNORE INTO hadits_collection (slug, name_id, name_ar, author, sort_order, id_start, id_end, has_native_id) VALUES (${esc(col.key)}, ${esc(col.nameId)}, ${esc(col.nameAr)}, ${esc(col.author)}, ${col.sortOrder}, ${col.idStart}, ${idEnd}, 1);`
    );
  }
  writeFileSync(join(outDir, "hadith_ahmad_darimi_catalog.sql"), catalogLines.join("\n") + "\n", "utf-8");

  for (const col of COLLECTIONS) {
    console.log(`Fetching ${col.file}...`);
    const records = await loadJson(col);
    console.log(`  ${records.length} hadith`);

    const lines: string[] = [
      `-- AUTO-GENERATED by scripts/generate-hadith-ahmad-darimi-seed.ts — do not edit by hand.`,
      `-- Source: gadingnst/hadith-api (github.com/gadingnst/hadith-api), MIT license.`,
      `-- ${col.nameId} — ${records.length} hadith, Arabic + Indonesian, matched by number.`,
      "",
    ];

    let stmt = "INSERT OR IGNORE INTO hadits (id, text_ar, text_id, narrator, grade, source, collection, hadith_number) VALUES\n";
    let stmtBytes = new TextEncoder().encode(stmt).length;
    let rowsInStmt = 0;

    // `id` is assigned sequentially by array position, NOT derived from
    // `number` — the classical numbering in Musnad Ahmad in particular is
    // NOT a clean 1..N sequence (it runs past 26,000 for only ~4,300
    // included hadith), so `idStart + number - 1` would overflow this
    // collection's allocated id range and collide with the next one. The
    // real classical number is preserved as `hadith_number` for display —
    // matches the sequential-id / preserved-number pattern already used by
    // generate-hadith-seed.ts for the other nine collections.
    let nextId = col.idStart;
    for (const rec of records) {
      const id = nextId++;
      const row = `  (${id}, ${esc(rec.arab.trim())}, ${esc(rec.id.trim())}, NULL, NULL, ${esc(col.nameId)}, ${esc(col.key)}, ${rec.number})`;
      const rowBytes = new TextEncoder().encode(row).length;
      if (stmtBytes + rowBytes + 2 > MAX_STATEMENT_BYTES && rowsInStmt > 0) {
        lines.push(stmt.replace(/,\n$/, ";\n"));
        stmt = "INSERT OR IGNORE INTO hadits (id, text_ar, text_id, narrator, grade, source, collection, hadith_number) VALUES\n";
        stmtBytes = new TextEncoder().encode(stmt).length;
        rowsInStmt = 0;
      }
      stmt += (rowsInStmt > 0 ? ",\n" : "") + row;
      stmtBytes += rowBytes + 2;
      rowsInStmt++;
    }
    if (rowsInStmt > 0) lines.push(stmt + ";\n");

    writeFileSync(join(outDir, `hadith_${col.key}.sql`), lines.join("\n") + "\n", "utf-8");
    console.log(`  Wrote hadith_${col.key}.sql`);
  }

  console.log("Done.");
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
