/**
 * Generates packages/db-schema/seed/kisah_musa.sql from scripts/content/kisah-musa.ts.
 * Run: npx tsx scripts/generate-kisah-musa-seed.ts (after quran_seed.sql has been
 * applied, since related_ayah_id is resolved via a subquery against `ayah`).
 */
import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { KISAH_MUSA_SERIES } from "./content/kisah-musa.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(__dirname, "..");
const outDir = join(repoRoot, "packages", "db-schema", "seed");

// Yusuf's seed already uses ebook ids 1-12 — start well clear of that range.
const EBOOK_ID_START = 100;

function esc(s: string): string {
  return `'${s.replace(/'/g, "''")}'`;
}

function main() {
  mkdirSync(outDir, { recursive: true });
  const lines: string[] = [
    "-- AUTO-GENERATED by scripts/generate-kisah-musa-seed.ts — do not edit by hand.",
    "-- Source content: scripts/content/kisah-musa.ts (grounded in QS. Al-Qasas 28:3-35",
    "-- and QS. Asy-Syu'ara 26:10-68, quran-json CC-BY-4.0). See docs/CONTENT-POLICY.md.",
    "-- Requires quran_seed.sql already applied (resolves related_ayah_id by lookup).",
    "",
  ];

  let ebookId = EBOOK_ID_START;
  for (const ep of KISAH_MUSA_SERIES) {
    for (const lang of ["id", "en"] as const) {
      const content = ep[lang];
      const pdfKey = `ebooks/kisah-nabi-musa/${lang}/${ep.slug}.pdf`;
      const surahLabel = ep.surahId === 28 ? "Al-Qasas" : ep.surahId === 26 ? "Asy-Syu'ara" : `Surah ${ep.surahId}`;

      lines.push(
        `INSERT INTO ebooks (id, title, author, r2_key, category_id, license_status, license_note) VALUES (${ebookId}, ${esc(content.title)}, ${esc("Tim Editorial ULYAH")}, ${esc(pdfKey)}, 1, 'original', ${esc(`Ditulis berdasarkan QS. ${surahLabel} ${ep.ayahStart}-${ep.ayahEnd} (quran-json, CC-BY-4.0). Tidak ada kutipan pihak ketiga berhak cipta.`)});`
      );

      lines.push(
        `INSERT INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT ${esc(content.title)}, ${esc(ep.slug)}, ${esc(lang)}, 'kisah-nabi-musa', ${KISAH_MUSA_SERIES.indexOf(ep) + 1}, 1, ${esc(content.body)}, 0, 'qc_pending', 'ai_original', 'published', 1.0,
  (SELECT id FROM ayah WHERE surah_id = ${ep.surahId} AND number = ${ep.ayahStart}), ${ebookId}, datetime('now');`
      );

      ebookId++;
    }
    lines.push("");
  }

  writeFileSync(join(outDir, "kisah_musa.sql"), lines.join("\n") + "\n", "utf-8");
  console.log(`Wrote kisah_musa.sql — ${KISAH_MUSA_SERIES.length} episodes x 2 languages = ${KISAH_MUSA_SERIES.length * 2} stories, ${ebookId - EBOOK_ID_START} PDFs.`);
}

main();
