/**
 * Generates packages/db-schema/seed/quran_seed_de.sql — the German Qur'an
 * translation (Abu Rida Muhammad Ibn Ahmad Ibn Rassoul, via Tanzil), sourced
 * from the fawazahmed0/quran-api dataset (Unlicense) that this repo already
 * uses for its hadith imports. quran-json (the source of every other
 * language's seed) ships no German edition, which is why tilawa.de fell back
 * to English ayah translations — a direct violation of the owner rule that
 * every site uses ONLY its domain's native language.
 *
 * Output format matches scripts/generate-quran-seed.ts exactly: sequential
 * ayah ids 1..6236 in (surah asc, ayah asc) order, INSERT batches kept under
 * D1's per-statement size limit.
 *
 * Run: npx tsx scripts/generate-quran-de-seed.ts
 */
import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const outDir = join(__dirname, "..", "packages", "db-schema", "seed");

const SOURCE_URL = "https://raw.githubusercontent.com/fawazahmed0/quran-api/1/editions/deu-aburidamuhammad.min.json";

interface Verse {
  chapter: number;
  verse: number;
  text: string;
}

function esc(s: string): string {
  return `'${s.replace(/'/g, "''")}'`;
}

const MAX_STATEMENT_BYTES = 60_000;

function batchByBytes(rows: string[]): string[][] {
  const out: string[][] = [];
  let current: string[] = [];
  let currentBytes = 0;
  for (const row of rows) {
    const rowBytes = Buffer.byteLength(row, "utf-8") + 2;
    if (current.length > 0 && currentBytes + rowBytes > MAX_STATEMENT_BYTES) {
      out.push(current);
      current = [];
      currentBytes = 0;
    }
    current.push(row);
    currentBytes += rowBytes;
  }
  if (current.length > 0) out.push(current);
  return out;
}

async function main() {
  mkdirSync(outDir, { recursive: true });
  const res = await fetch(SOURCE_URL);
  if (!res.ok) throw new Error(`Fetch failed: ${res.status}`);
  const data = (await res.json()) as { quran: Verse[] };

  const verses = [...data.quran].sort((a, b) => a.chapter - b.chapter || a.verse - b.verse);
  if (verses.length !== 6236) {
    throw new Error(`Expected 6236 verses, got ${verses.length} — refusing to write a partial scripture seed.`);
  }

  const rows: string[] = [];
  let id = 0;
  for (const v of verses) {
    id++;
    rows.push(`(${id}, 'de', ${esc(v.text)}, 'fawazahmed0/quran-api — Abu Rida (Tanzil)')`);
  }

  const lines: string[] = [
    "-- AUTO-GENERATED by scripts/generate-quran-de-seed.ts — translation, lang=de.",
    "-- Source: fawazahmed0/quran-api (Unlicense), edition deu-aburidamuhammad",
    "-- (Abu Rida Muhammad Ibn Ahmad Ibn Rassoul, via tanzil.net).",
    "",
  ];
  for (const b of batchByBytes(rows)) {
    lines.push(`INSERT INTO translation (ayah_id, lang, text, source) VALUES\n${b.join(",\n")};`);
  }
  writeFileSync(join(outDir, "quran_seed_de.sql"), lines.join("\n") + "\n", "utf-8");
  console.log(`Wrote quran_seed_de.sql — ${id} ayah, lang=de.`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
