/**
 * Generates packages/db-schema/seed/kisah_yusuf.sql from scripts/content/kisah-yusuf.ts.
 * Run: npx tsx scripts/generate-kisah-yusuf-seed.ts (after quran_seed.sql has been
 * applied, since related_ayah_id is resolved via a subquery against `ayah`).
 */
import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { KISAH_YUSUF_SERIES } from "./content/kisah-yusuf.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(__dirname, "..");
const outDir = join(repoRoot, "packages", "db-schema", "seed");

function esc(s: string): string {
  return `'${s.replace(/'/g, "''")}'`;
}

function main() {
  mkdirSync(outDir, { recursive: true });
  const lines: string[] = [
    "-- AUTO-GENERATED by scripts/generate-kisah-yusuf-seed.ts — do not edit by hand.",
    "-- Source content: scripts/content/kisah-yusuf.ts (grounded in QS. Yusuf 12:4-101,",
    "-- quran-json CC-BY-4.0). See docs/CONTENT-POLICY.md.",
    "-- Requires quran_seed.sql already applied (resolves related_ayah_id by lookup).",
    "",
  ];

  let ebookId = 1;
  for (const ep of KISAH_YUSUF_SERIES) {
    for (const lang of ["id", "en"] as const) {
      const content = ep[lang];
      const pdfKey = `ebooks/kisah-nabi-yusuf/${lang}/${ep.slug}.pdf`;

      lines.push(
        `INSERT INTO ebooks (id, title, author, r2_key, category_id, license_status, license_note) VALUES (${ebookId}, ${esc(content.title)}, ${esc("Tim Editorial ULYAH")}, ${esc(pdfKey)}, 1, 'original', ${esc(`Ditulis berdasarkan QS. Yusuf ${ep.ayahStart}-${ep.ayahEnd} (quran-json, CC-BY-4.0). Tidak ada kutipan pihak ketiga berhak cipta.`)});`
      );

      lines.push(
        `INSERT INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT ${esc(content.title)}, ${esc(ep.slug)}, ${esc(lang)}, 'kisah-nabi-yusuf', ${KISAH_YUSUF_SERIES.indexOf(ep) + 1}, 1, ${esc(content.body)}, 0, 'qc_pending', 'ai_original', 'published', 1.0,
  (SELECT id FROM ayah WHERE surah_id = 12 AND number = ${ep.ayahStart}), ${ebookId}, datetime('now');`
      );

      ebookId++;
    }
    lines.push("");
  }

  writeFileSync(join(outDir, "kisah_yusuf.sql"), lines.join("\n") + "\n", "utf-8");
  console.log(`Wrote kisah_yusuf.sql — ${KISAH_YUSUF_SERIES.length} episodes x 2 languages = ${KISAH_YUSUF_SERIES.length * 2} stories, ${ebookId - 1} PDFs.`);
}

main();
