/**
 * Generates packages/db-schema/seed/ulama_nusantara.sql from
 * scripts/content/ulama-nusantara.ts. Run:
 *   npx tsx scripts/generate-ulama-nusantara-seed.ts
 *
 * These are historical/hagiographic stories (Wali Songo), NOT tied to a single
 * ayah, so related_ayah_id is NULL. They live in their own category, "Kisah
 * Wali Songo", which the seed creates idempotently (INSERT OR IGNORE — slug is
 * UNIQUE) and then resolves by slug so we never hard-code a fragile numeric id.
 * Like the prophet series they ship NO PDFs — read + narrated in-app by the
 * ContinuousStoryReader (TTS), so pdf_ebook_id is NULL.
 */
import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { ULAMA_NUSANTARA_SERIES } from "./content/ulama-nusantara.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(__dirname, "..");
const outDir = join(repoRoot, "packages", "db-schema", "seed");

const CAT_NAME = "Kisah Ulama Nusantara";
const CAT_SLUG = "kisah-ulama-nusantara";
const CAT_SUBQUERY = `(SELECT id FROM categories WHERE slug = '${CAT_SLUG}')`;

function esc(s: string): string {
  return `'${s.replace(/'/g, "''")}'`;
}

function main() {
  mkdirSync(outDir, { recursive: true });
  const lines: string[] = [
    "-- AUTO-GENERATED by scripts/generate-ulama-nusantara-seed.ts — do not edit by hand.",
    "-- Source content: scripts/content/ulama-nusantara.ts (historical/hagiographic; each",
    "-- episode cites its own sources — documented history vs. tradition/folklore).",
    "-- See docs/CONTENT-POLICY.md. No PDFs — read + narrated in-app (TTS).",
    "",
    "-- Own category, created idempotently (slug is UNIQUE) and resolved by slug.",
    `INSERT OR IGNORE INTO categories (name, slug, parent_id, auto_created) VALUES (${esc(CAT_NAME)}, '${CAT_SLUG}', NULL, 0);`,
    "",
  ];

  ULAMA_NUSANTARA_SERIES.forEach((ep, i) => {
    for (const lang of ["id", "en"] as const) {
      const content = ep[lang];
      lines.push(
        `INSERT OR IGNORE INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT ${esc(content.title)}, ${esc(ep.slug)}, ${esc(lang)}, 'ulama-nusantara', ${i + 1}, ${CAT_SUBQUERY}, ${esc(content.body)}, 0, 'qc_pending', 'ai_original', 'published', 1.0,
  NULL, NULL, datetime('now');`
      );
    }
    lines.push("");
  });

  writeFileSync(join(outDir, "ulama_nusantara.sql"), lines.join("\n") + "\n", "utf-8");
  console.log(
    `Wrote ulama_nusantara.sql — ${ULAMA_NUSANTARA_SERIES.length} chapters x 2 languages = ${ULAMA_NUSANTARA_SERIES.length * 2} stories.`
  );
}

main();
