/**
 * Generates packages/db-schema/seed/kisah_ashabul_qaryah.sql from
 * scripts/content/kisah-ashabul-qaryah.ts. Run:
 *   npx tsx scripts/generate-kisah-ashabul-qaryah-seed.ts
 * (after quran_seed.sql has been applied, since related_ayah_id is resolved
 * via a subquery against `ayah`).
 */
import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { KISAH_ASHABUL_QARYAH_SERIES } from "./content/kisah-ashabul-qaryah.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(__dirname, "..");
const outDir = join(repoRoot, "packages", "db-schema", "seed");

// Yusuf 1-12, Musa 100-111, Dzulqarnain 200-207 — start clear of all.
const EBOOK_ID_START = 800;
// The People of the Cave were righteous youths, not prophets, so they
// belong in the general "Kisah Islami" category, not "Kisah Para Nabi".
// Created here with INSERT OR IGNORE so the seed is self-contained.
const CATEGORY_ID = 5;

function esc(s: string): string {
  return `'${s.replace(/'/g, "''")}'`;
}

function main() {
  mkdirSync(outDir, { recursive: true });
  const lines: string[] = [
    "-- AUTO-GENERATED by scripts/generate-kisah-ashabul-qaryah-seed.ts — do not edit by hand.",
    "-- Source content: scripts/content/kisah-ashabul-qaryah.ts (grounded in QS. Ya-Sin",
    "-- 36:13-29, quran-json CC-BY-4.0). See docs/CONTENT-POLICY.md.",
    "-- Requires quran_seed.sql already applied (resolves related_ayah_id by lookup).",
    "",
    "INSERT OR IGNORE INTO categories (id, name, slug, parent_id, auto_created) VALUES (5, 'Kisah Islami', 'kisah-islami', NULL, 0);",
    "",
  ];

  let ebookId = EBOOK_ID_START;
  for (const ep of KISAH_ASHABUL_QARYAH_SERIES) {
    for (const lang of ["id", "en"] as const) {
      const content = ep[lang];
      const pdfKey = `ebooks/kisah-ashabul-qaryah/${lang}/${ep.slug}.pdf`;
      const surahLabel = "Ya-Sin";

      lines.push(
        `INSERT INTO ebooks (id, title, author, r2_key, category_id, license_status, license_note) VALUES (${ebookId}, ${esc(content.title)}, ${esc("Tim Editorial ULYAH")}, ${esc(pdfKey)}, ${CATEGORY_ID}, 'original', ${esc(`Ditulis berdasarkan QS. ${surahLabel} ${ep.ayahStart}-${ep.ayahEnd} (quran-json, CC-BY-4.0). Tidak ada kutipan pihak ketiga berhak cipta.`)});`
      );

      lines.push(
        `INSERT INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT ${esc(content.title)}, ${esc(ep.slug)}, ${esc(lang)}, 'kisah-ashabul-qaryah', ${KISAH_ASHABUL_QARYAH_SERIES.indexOf(ep) + 1}, ${CATEGORY_ID}, ${esc(content.body)}, 0, 'qc_pending', 'ai_original', 'published', 1.0,
  (SELECT id FROM ayah WHERE surah_id = ${ep.surahId} AND number = ${ep.ayahStart}), ${ebookId}, datetime('now');`
      );

      ebookId++;
    }
    lines.push("");
  }

  writeFileSync(join(outDir, "kisah_ashabul_qaryah.sql"), lines.join("\n") + "\n", "utf-8");
  console.log(
    `Wrote kisah_ashabul_qaryah.sql — ${KISAH_ASHABUL_QARYAH_SERIES.length} episodes x 2 languages = ${KISAH_ASHABUL_QARYAH_SERIES.length * 2} stories, ${ebookId - EBOOK_ID_START} PDFs.`
  );
}

main();
