/**
 * Generates packages/db-schema/seed/kisah_ayyub.sql from
 * scripts/content/kisah-ayyub.ts. Run:
 *   npx tsx scripts/generate-kisah-ayyub-seed.ts
 * (after quran_seed.sql has been applied, since related_ayah_id is resolved
 * via a subquery against `ayah`). No PDFs — read + narrated in-app (TTS), so
 * pdf_ebook_id is NULL. INSERT OR IGNORE so re-applying is safe/idempotent.
 */
import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { KISAH_AYYUB_SERIES } from "./content/kisah-ayyub.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(__dirname, "..");
const outDir = join(repoRoot, "packages", "db-schema", "seed");

// "Kisah Para Nabi" (category id=1 from 0002_seed_static.sql).
const CATEGORY_ID = 1;

function esc(s: string): string {
  return `'${s.replace(/'/g, "''")}'`;
}

function main() {
  mkdirSync(outDir, { recursive: true });
  const lines: string[] = [
    "-- AUTO-GENERATED by scripts/generate-kisah-ayyub-seed.ts — do not edit by hand.",
    "-- Source content: scripts/content/kisah-ayyub.ts (grounded in QS. Al-A'raf, Hud, Asy-Syu'ara, Al-Ahqaf, Al-Haqqah,",
    "-- quran-json CC-BY-4.0). See docs/CONTENT-POLICY.md.",
    "-- Requires quran_seed.sql already applied (resolves related_ayah_id by lookup).",
    "-- No PDFs — read + narrated in-app (TTS), so pdf_ebook_id is NULL.",
    "",
  ];

  KISAH_AYYUB_SERIES.forEach((ep, i) => {
    for (const lang of ["id", "en"] as const) {
      const content = ep[lang];
      lines.push(
        `INSERT OR IGNORE INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT ${esc(content.title)}, ${esc(ep.slug)}, ${esc(lang)}, 'kisah-ayyub', ${i + 1}, ${CATEGORY_ID}, ${esc(content.body)}, 0, 'qc_pending', 'ai_original', 'published', 1.0,
  (SELECT id FROM ayah WHERE surah_id = ${ep.surahId} AND number = ${ep.ayahStart}), NULL, datetime('now');`
      );
    }
    lines.push("");
  });

  writeFileSync(join(outDir, "kisah_ayyub.sql"), lines.join("\n") + "\n", "utf-8");
  console.log(
    `Wrote kisah_ayyub.sql — ${KISAH_AYYUB_SERIES.length} episodes x 2 languages = ${KISAH_AYYUB_SERIES.length * 2} stories.`
  );
}

main();
