/**
 * Generates packages/db-schema/seed/kisah_nuh.sql from
 * scripts/content/kisah-nuh.ts. Run:
 *   npx tsx scripts/generate-kisah-nuh-seed.ts
 * (after quran_seed.sql has been applied, since related_ayah_id is resolved
 * via a subquery against `ayah`).
 */
import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { KISAH_NUH_SERIES } from "./content/kisah-nuh.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(__dirname, "..");
const outDir = join(repoRoot, "packages", "db-schema", "seed");

// Yusuf 1-12, Musa 100-111, Dzulqarnain 200-207, Ashabul Kahfi 300-307 —
// start clear of all.
const EBOOK_ID_START = 400;
// Nuh is one of the 25 prophets, so this belongs in "Kisah Para Nabi"
// (id=1 from 0002_seed_static.sql), not the general "Kisah Islami" bucket
// used for Dzulqarnain/Ashabul Kahfi.
const CATEGORY_ID = 1;

function esc(s: string): string {
  return `'${s.replace(/'/g, "''")}'`;
}

function main() {
  mkdirSync(outDir, { recursive: true });
  const lines: string[] = [
    "-- AUTO-GENERATED by scripts/generate-kisah-nuh-seed.ts — do not edit by hand.",
    "-- Source content: scripts/content/kisah-nuh.ts (grounded in QS. Hud 11:25-49",
    "-- and QS. Nuh 71:1-28, quran-json CC-BY-4.0). See docs/CONTENT-POLICY.md.",
    "-- Requires quran_seed.sql already applied (resolves related_ayah_id by lookup).",
    "",
  ];

  let ebookId = EBOOK_ID_START;
  for (const ep of KISAH_NUH_SERIES) {
    for (const lang of ["id", "en"] as const) {
      const content = ep[lang];
      const pdfKey = `ebooks/kisah-nuh/${lang}/${ep.slug}.pdf`;
      const surahLabel = ep.surahId === 11 ? "Hud" : "Nuh";

      lines.push(
        `INSERT INTO ebooks (id, title, author, r2_key, category_id, license_status, license_note) VALUES (${ebookId}, ${esc(content.title)}, ${esc("Tim Editorial ULYAH")}, ${esc(pdfKey)}, ${CATEGORY_ID}, 'original', ${esc(`Ditulis berdasarkan QS. ${surahLabel} ${ep.ayahStart}-${ep.ayahEnd} (quran-json, CC-BY-4.0). Tidak ada kutipan pihak ketiga berhak cipta.`)});`
      );

      lines.push(
        `INSERT INTO stories (title, slug, lang, series_key, episode_number, category_id, body, ai_generated, qc_status, source_format, status, confidence_score, related_ayah_id, pdf_ebook_id, published_at)
SELECT ${esc(content.title)}, ${esc(ep.slug)}, ${esc(lang)}, 'kisah-nuh', ${KISAH_NUH_SERIES.indexOf(ep) + 1}, ${CATEGORY_ID}, ${esc(content.body)}, 0, 'qc_pending', 'ai_original', 'published', 1.0,
  (SELECT id FROM ayah WHERE surah_id = ${ep.surahId} AND number = ${ep.ayahStart}), ${ebookId}, datetime('now');`
      );

      ebookId++;
    }
    lines.push("");
  }

  writeFileSync(join(outDir, "kisah_nuh.sql"), lines.join("\n") + "\n", "utf-8");
  console.log(
    `Wrote kisah_nuh.sql — ${KISAH_NUH_SERIES.length} episodes x 2 languages = ${KISAH_NUH_SERIES.length * 2} stories, ${ebookId - EBOOK_ID_START} PDFs.`
  );
}

main();
