/**
 * Generates packages/db-schema/seed/*.sql from the `quran-json` npm package
 * (CC-BY-4.0, github.com/risan/quran-json) — full Arabic text + translation +
 * transliteration for all 114 surah / 6,236 ayah, in every language the
 * dataset ships with a licensed translation for.
 *
 * quran_seed.sql          -> surah + ayah (Arabic) + Indonesian translation (required)
 * quran_seed_<lang>.sql   -> translation-only, one file per additional language
 *
 * Multi-language requirement: the site must switch 100% consistently when a
 * visitor changes language — UI chrome AND Qur'an translation text. German
 * and Japanese have no licensed Qur'an translation source available here, so
 * they intentionally fall back to English content (with a visible notice in
 * the UI) while every other part of the site (nav, player, admin, donation,
 * TTS voice) still switches fully — see docs/SETUP.md "Bahasa & Lokalisasi".
 *
 * Run: pnpm db:generate-seed  (from repo root, after `pnpm install`)
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { createRequire } from "node:module";

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(__dirname, "..");
const require = createRequire(import.meta.url);
const quranJsonPkg = require.resolve("quran-json/package.json", {
  paths: [join(repoRoot, "packages", "db-schema")],
});
const pkgRoot = join(dirname(quranJsonPkg), "dist");
const outDir = join(repoRoot, "packages", "db-schema", "seed");

interface ArabicChapter {
  id: number;
  name: string;
  transliteration: string;
  type: "meccan" | "medinan";
  total_verses: number;
  verses: { id: number; text: string }[];
}

interface LangChapter {
  verses: { id: number; text: string; translation: string; transliteration: string }[];
}

// Every language quran-json ships a chapters/<lang>/*.json translation for.
// 'id' is baked into the base file; the rest get their own seed file.
const EXTRA_LANGUAGES = ["en", "ru", "fr", "zh", "es", "bn", "sv", "tr", "ur"] as const;

function esc(s: string | null | undefined): string {
  if (s === null || s === undefined) return "NULL";
  return `'${s.replace(/'/g, "''")}'`;
}

/**
 * Groups value tuples so each INSERT statement stays under D1's hard
 * 100KB-per-statement limit (SQLITE_TOOBIG otherwise — long ayat like
 * Al-Baqarah 282 blow past it quickly with fixed row-count batching).
 */
const MAX_STATEMENT_BYTES = 60_000;

function batchByBytes(rows: string[]): string[][] {
  const out: string[][] = [];
  let current: string[] = [];
  let currentBytes = 0;
  for (const row of rows) {
    const rowBytes = Buffer.byteLength(row, "utf-8") + 2;
    if (current.length > 0 && currentBytes + rowBytes > MAX_STATEMENT_BYTES) {
      out.push(current);
      current = [];
      currentBytes = 0;
    }
    current.push(row);
    currentBytes += rowBytes;
  }
  if (current.length > 0) out.push(current);
  return out;
}

function main() {
  mkdirSync(outDir, { recursive: true });
  const arabic: ArabicChapter[] = JSON.parse(readFileSync(join(pkgRoot, "quran.json"), "utf-8"));

  // Pass 1: surah + ayah + Indonesian translation, with deterministic
  // sequential ayah ids (1..6236) that every other language file reuses.
  const surahValues: string[] = [];
  const ayahRows: string[] = [];
  const idTranslationRows: string[] = [];
  let ayahId = 0;

  for (const ch of arabic) {
    surahValues.push(
      `(${ch.id}, ${esc(ch.name)}, ${esc(ch.transliteration)}, ${esc(ch.transliteration)}, ${esc(ch.type)}, ${ch.total_verses})`
    );
    const idChapter: LangChapter = JSON.parse(
      readFileSync(join(pkgRoot, "chapters", "id", `${ch.id}.json`), "utf-8")
    );
    for (let i = 0; i < ch.verses.length; i++) {
      ayahId++;
      const v = ch.verses[i]!;
      const idVerse = idChapter.verses[i]!;
      ayahRows.push(`(${ayahId}, ${ch.id}, ${v.id}, ${esc(v.text)}, ${esc(idVerse.transliteration ?? null)})`);
      idTranslationRows.push(`(${ayahId}, 'id', ${esc(idVerse.translation)}, 'quran-json (CC-BY-4.0)')`);
    }
  }

  const baseLines: string[] = [
    "-- AUTO-GENERATED by scripts/generate-quran-seed.ts — do not edit by hand.",
    "-- Source: quran-json v3.1.2 (CC-BY-4.0) https://github.com/risan/quran-json",
    `-- 114 surah, ${ayahId} ayah, Arabic text + Indonesian translation + transliteration.`,
    "",
    "-- ── surah ──",
    `INSERT INTO surah (id, name_ar, name_id, name_transliteration, revelation_place, ayah_count) VALUES\n${surahValues.join(",\n")};`,
    "",
    "-- ── ayah (explicit sequential ids, 1..N, stable across all language files) ──",
  ];
  for (const b of batchByBytes(ayahRows)) {
    baseLines.push(`INSERT INTO ayah (id, surah_id, number, text_ar, text_translit) VALUES\n${b.join(",\n")};`);
  }
  baseLines.push("", "-- ── translation (Indonesian, lang='id') ──");
  for (const b of batchByBytes(idTranslationRows)) {
    baseLines.push(`INSERT INTO translation (ayah_id, lang, text, source) VALUES\n${b.join(",\n")};`);
  }
  writeFileSync(join(outDir, "quran_seed.sql"), baseLines.join("\n") + "\n", "utf-8");
  console.log(`Wrote quran_seed.sql — ${arabic.length} surah, ${ayahId} ayah, lang=id.`);

  // Pass 2: one translation-only seed file per extra language, reusing the
  // exact same sequential ayah id scheme (verse order is identical across
  // every chapters/<lang>/<n>.json in this dataset).
  for (const lang of EXTRA_LANGUAGES) {
    const rows: string[] = [];
    let id = 0;
    for (const ch of arabic) {
      const chapter: LangChapter = JSON.parse(
        readFileSync(join(pkgRoot, "chapters", lang, `${ch.id}.json`), "utf-8")
      );
      for (const v of chapter.verses) {
        id++;
        rows.push(`(${id}, '${lang}', ${esc(v.translation)}, 'quran-json (CC-BY-4.0)')`);
      }
    }
    const lines = [
      `-- AUTO-GENERATED by scripts/generate-quran-seed.ts — translation, lang=${lang}.`,
      "-- Source: quran-json v3.1.2 (CC-BY-4.0) https://github.com/risan/quran-json",
      "",
    ];
    for (const b of batchByBytes(rows)) {
      lines.push(`INSERT INTO translation (ayah_id, lang, text, source) VALUES\n${b.join(",\n")};`);
    }
    writeFileSync(join(outDir, `quran_seed_${lang}.sql`), lines.join("\n") + "\n", "utf-8");
    console.log(`Wrote quran_seed_${lang}.sql — ${id} rows.`);
  }
}

main();
